### ISSUE TITLE
Unable to use `vim.encryption.CryptoManagerKmip.GenerateKey()` with native key provider!

### ISSUE THREAD

**Issue by reubenur-rahman** [vmware/pyvmomi#1007]
### Describe the bug

The vSphere SDK documentation doesn't mention whether the `GenerateKey()` function is supported for the native key provider or not. Invoking this function for the native key provider raises the following fault. 

Is there a way to achieve it using pyvmomi or the REST API? PowerCLI can encrypt a VM using the native key provider but doesn't know how it generates the key and unfortunately can't use PowerShell for the project.

Appreciate any help or pointers!

![image](https://user-images.githubusercontent.com/6652363/220906959-ad3cbec5-bfc0-46eb-a9fd-ddbdd56729ab.png)

### Reproduction steps

 `vim.encryption.CryptoManagerKmip.GenerateKey()`

### Expected behavior

Uniform key generation for native and standard providers.

**Comment by reubenur-rahman** [comment]
@DanielDraganov @michaelrice @lamw appreciate any pointers.

**Comment by DanielDraganov** [comment]
Hello Reuben. This VMODL1 API is part of vSphere 8.0.1.0 which is not yet released.
