### ISSUE TITLE
Support new 'data sets' APIs

### ISSUE THREAD

**Issue by NVShawn** [vmware/pyvmomi#1011]
### Is your feature request related to a problem? Please describe.

We'd like to start to use the new VMWare DataSets feature to pass data back and forth with our VMs. Seems the proper tool for the job.

### Describe the solution you'd like

Something similar to how 'custom attributes' are treated

**Comment by prziborowski** [comment]
I believe this feature exists in a different API set: https://github.com/vmware/vsphere-automation-sdk-python. And you should bug that repository to add a sample for it so you have an idea of how to use the API.

There aren't bindings for it in pyVmomi, which are based on the SOAP/webservice APIs.

**Comment by NVShawn** [comment]
Gotcha. Will go fishing over in that pond. Thanks!
