### ISSUE TITLE
I've been unable to pull the license information of of the ESXi hosts..

### ISSUE THREAD

**Issue by bostonmacosx** [vmware/pyvmomi#1013]
### Is your feature request related to a problem? Please describe.

It isn't a problem necessarily but I can't find supporting infromation on how to pull license information from the pyvmomi package for Hosts. Below is sample code I've been trying to play with. 

def get_obj(si, root, vim_type):
    container = si.content.viewManager.CreateContainerView(root, vim_type,True)
    view = container.view
    #print(container.view)
    obj = [ret for ret in container.view]
    container.Destroy()
    return obj

lm = content.licenseManager.licenseAssignmentManager

DCS = get_obj(c, c.content.rootFolder, [vim.Datacenter])
print(DCS)
print(len(DCS))
for dc in DCS:
    print("DATACENTEER --"+dc.name)
    HOSTS = get_obj(c,dc,[vim.HostSystem])
    for host in HOSTS:
        print("HOST -- "+str(host.config.host))
        print(host.hardware.systemInfo.uuid)
        #entity_id = host.hardware.systemInfo.uuid
        print(lm.QueryAssignedLicenses(str(host.config.host)))
        #print(host.config)
        #print(host.configManager)
        #sys.exit()

### Describe the solution you'd like

A way to see what licenses are on what hosts.

### Describe alternatives you've considered

Old Perl SDK from VMWares

**Comment by prziborowski** [comment]
I think you are mostly there.
According to https://developer.vmware.com/apis/358/vsphere/doc/vim.LicenseAssignmentManager.html#queryAssignedLicenses you should use the ID, which I think will be the moId.

```
print(lm.QueryAssignedLicenses(host._moId))
```

**Comment by bostonmacosx** [comment]
@prziborowski Appreciated.. there was 9 hours out of my day circling the answer ;P
Thanks AGain
