### ISSUE TITLE
Syntax error in vim/__init__pyi

### ISSUE THREAD

**Issue by IvarVirusiim** [vmware/pyvmomi#1015]
### Describe the bug

`pyvmomi = "8.0.1.0"`

File: `pyVmomi/vim/__init__.pyi:1117`
```
class HostSystem(ManagedEntity):
...

    class StandbyMode(Enum):
        entering = "entering"
        exiting = "exiting"
        in = "in" # <--- "in" is a reserved keyword
        none = "none"
```

### Reproduction steps

1. Install version "8.0.1.0" 
2. Import in file: `from pyVmomi import vim`
3. Run `mypy` to check for type hints 

### Expected behavior

No syntax error detected

**Comment by intgr** [comment]
Also `pyVmomi/vim/event/__init__.pyi` lines 75 and 155 contain `def from(self) -> str:` which is invalid syntax. `from` is a reserved keyword in Python.
