### ISSUE TITLE
Get the tag field of a cluster via API

### ISSUE THREAD

**Issue by wevernek** [vmware/pyvmomi#1024]
### Is your feature request related to a problem? Please describe.

Hey guys!

My team needs to get the tag of a cluster through the tool, and we would like to know at what level this information is found in the API.

Today we have a script built in Python to get information from the VMs in our datacenter and, through the documentation, we can't find the tag.

Our team has added this information in the following field within the vSphere Client:

![Captura de Tela 2023-06-06 às 11 06 56](https://github.com/vmware/pyvmomi/assets/18062168/c890faee-5dd0-4e78-9983-faae46a10d09)

### Describe the solution you'd like

If you can show us where to get this field through the API, or send us a useful link, we appreciate it!

**Comment by wevernek** [comment]
@FelipeLepore for your information 🚩

**Comment by karaatanassov** [comment]
You need to use the auotmation API of vSphere for this task.

See this API 
https://developer.vmware.com/apis/vsphere-automation/latest/cis/api/cis/tagging/tag-associationactionlist-attached-tags/post/

It is also avaialbe as Python binding in the [vSphere Automation SDK](https://github.com/vmware/vsphere-automation-sdk-python)

You can see the python doc here https://vmware.github.io/vsphere-automation-sdk-python/vsphere/8.0.2.0/com.vmware.cis.html#com.vmware.cis.tagging_client.TagAssociation.list_attached_tags
