### ISSUE TITLE
Type warnings

### ISSUE THREAD

**Issue by IvarVirusiim** [vmware/pyvmomi#1026]
### Describe the bug

When using PyCharm and type hinting, there are warnings like those:

![image](https://github.com/vmware/pyvmomi/assets/38400710/1a3f7237-8b64-459c-a8c8-98ce2ddcf782)

![image](https://github.com/vmware/pyvmomi/assets/38400710/7ae03993-ceba-4a3c-b11a-737fe475338a)

![image](https://github.com/vmware/pyvmomi/assets/38400710/ecba406c-49b5-43fb-bbeb-c5e9d338e500)

### Reproduction steps

1. Add a type hint using full path, for example: `vim.vm.device.VirtualEthernetCard`
2. Look at warning that says: `Cannot find reference 'vm' in '__init__.pyi' `:
![image](https://github.com/vmware/pyvmomi/assets/38400710/a25d1004-3004-4bea-8b5c-62a325c1b5d5)

### Expected behavior

No warnings

### Additional context

For this example (`vim.vm.device.VirtualEthernetCard`) using re-exports should fix them:

https://typing.readthedocs.io/en/latest/source/stubs.html#imports

For example `vim.__init__.pyi` :
`from . import vim as vim`

and in `vm.__init__.pyi`:
`from . import device as device`

**Comment by DanielDraganov** [comment]
Thanks for reporting this. There is discrepancy between PyCharm and Visual Studio Code because the latter did not have issues with the imports and did not show warnings. Nevertheless, the imports are modified to comply with the "from Y import X as X" rule.

**Comment by nofacer** [comment]
Hi @DanielDraganov , I think this issue still exists.
![image](https://github.com/vmware/pyvmomi/assets/8757916/98c71334-7c89-46c2-b859-05d342250578)
