### ISSUE TITLE
[stubs] HttpNfcLease is missing State inner enum type

### ISSUE THREAD

**Issue by streambinder** [vmware/pyvmomi#1028]
### Describe the bug

Current shipped stubs do not include `State` enum within `HttpNfcLease`.

### Reproduction steps

No need.

### Expected behavior

Including a `State` enum would simplify handling and better type-check code which interacts with `HttpNfcLease` state.

**Comment by streambinder** [comment]
Hey @DanielDraganov, any update on this?

**Comment by DanielDraganov** [comment]
Hello. The latest major release refactored the type stubs and this issue is fixed: https://github.com/vmware/pyvmomi/commit/f544b14b22cac8383de16e75887447e80b097391
