### ISSUE TITLE
[stubs] SecurityError not recognized as Exception

### ISSUE THREAD

**Issue by streambinder** [vmware/pyvmomi#1030]
### Describe the bug

Cannot raise `NoPermission` instance as: 
> Expression `e` has type `vim.fault.NoPermission` but must extend BaseException.

Reference code:

```python
def f() -> None:
    ...
    try:
        return partial(vim.ServiceInstance, ...)()
    except vim.fault.NoPermission as e:
        ...
        raise e
```

### Reproduction steps

1. write a function which: `raise vim.fault.NoPermission()`
2. run `mypy`/`pyre` against it

### Expected behavior

I'd expect `raise vim.fault.NoPermission()` to not be linted as an error.

**Comment by DanielDraganov** [comment]
Fixed in https://github.com/vmware/pyvmomi/commit/4e387cc3d2754eaa48716d59aa2f34a0027deec3
