### ISSUE TITLE
Unable to remove an advanced setting for a VM

### ISSUE THREAD

**Issue by madhanse** [vmware/pyvmomi#1040]
### Describe the bug

I tried to use ReconfigVM_Task() function to update vm.config.extraConfig by creating a list excluding this setting. No change in the advanced settings in the vSphere Client.

### Reproduction steps

1. Create a list excluding the setting to remove
2. Create a vim.vm.ConfigSpec object and add the updated list
3. Call the ReconfigureVM_Task() to execute the task
...

### Expected behavior

Setting removed for the VM

**Comment by prziborowski** [comment]
In order to remove a setting, you provide the setting you wish to remove with a blank value.
It is mentioned at https://developer.vmware.com/apis/358/vsphere/doc/vim.vm.ConfigSpec.html#extraConfig
```
Keys with empty values will be removed.
```

**Comment by madhanse** [comment]
Got it thanks.
