### ISSUE TITLE
Unable to get recent tasks list against ESXi host

### ISSUE THREAD

**Issue by IonutDanNica** [vmware/pyvmomi#1044]
### Describe the bug

When trying to get recent tasks against an ESXi host we get this error message:

Can't load class 'vslmCatalogChangeResult'

### Reproduction steps

1. connect to ESXi,  get recent tasks list

2.
        c = SmartConnect(host=ip, user=user, pwd=pwd, disableSslCertValidation=True)
        current_session_key = c.content.sessionManager.currentSession.key
        # Path for tasks
        tasks_list = c.content.taskManager.recentTask
3. Observe error message

Can't load class 'vslmCatalogChangeResult'

### Expected behavior

I would expect to get the recent task list object.

### Additional context

This error does not show if we run the same code against VCSA, only via ESXi, and with ESXi it is a bit intermittent, we can't seem to pinpoint a pattern to the intermittence

Running script in Windows with these versions installed
PyvMomi 8.0.1.0.2
Pyvim 3.0.3
Python version 3.10

**Comment by DanielDraganov** [comment]
Hi @IonutDanNica 
This issue duplicates https://github.com/vmware/pyvmomi/issues/1016
This is an internal issues that is yet to be fixed.
