### ISSUE TITLE
Incorrect typing in PortConnection

### ISSUE THREAD

**Issue by IvarVirusiim** [vmware/pyvmomi#1056]
### Describe the bug

According to the documentation, the fields in `dvs\__init__.pyi` `PortConnection` should be optional (except `switchUuid`).

https://vdc-repo.vmware.com/vmwb-repository/dcr-public/184bb3ba-6fa8-4574-a767-d0c96e2a38f4/ba9422ef-405c-47dd-8553-e11b619185b2/SDK/vsphere-ws/docs/ReferenceGuide/vim.dvs.PortConnection.html

### Reproduction steps

```
from pyVmomi import vim
port_connection = vim.dvs.PortConnection()
port_connection.portKey = None
````

Run `mypy` and get `Incompatible types in assignment`

### Expected behavior

`None` should be an accepted value.

**Comment by karaatanassov** [comment]
Duplicate of https://github.com/vmware/pyvmomi/issues/1048

**Comment by DanielDraganov** [comment]
Fixed in https://github.com/vmware/pyvmomi/commit/f544b14b22cac8383de16e75887447e80b097391
