### ISSUE TITLE
Python 3.12 issue with wrap_socket (deprecated in 3.7)

### ISSUE THREAD

**Issue by ekrichbaum** [vmware/pyvmomi#1057]
### Describe the bug

Remove the ssl.wrap_socket() function, deprecated in Python 3.7: instead, create a [ssl.SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) object and call its [ssl.SSLContext.wrap_socket](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.wrap_socket) method. Any package that still uses ssl.wrap_socket() is broken and insecure. The function neither sends a SNI TLS extension nor validates server hostname. Code is subject to [CWE-295](https://cwe.mitre.org/data/definitions/295.html): Improper Certificate Validation. (Contributed by Victor Stinner in [gh-94199](https://github.com/python/cpython/issues/94199).)

around line 1002:
```
   # Function used to wrap sockets with SSL
   contextInstance                 = ssl.SSLContext();
   contextInstance.verify_mode     = ssl.CERT_REQUIRED;
   contextInstance.load_verify_locations(cafile=os.path.relpath(certifi.where()),
       capath=None, cadata=None);
   socketInstance = socket.socket();
   _SocketWrapper = contextInstance.wrap_socket(socketInstance);
   #_SocketWrapper = ssl.wrap_socket
```

### Reproduction steps

1. Python 3.12
...

### Expected behavior

Follow >3.7 python guidelines. Do not break in 3.12.

**Comment by ekrichbaum** [comment]
forgot to add:
```
import certifi
```

**Comment by samweisgamdschie** [comment]
Same problem here. And please add fix to versions <8.0 as well, if possible :angel:

**Comment by gquittet** [comment]
Same issue here

**Comment by gquittet** [comment]
I tried to update the code base to make it compatible with Python 3.12, but after a clean installation of the project, the tests are failing.
Do I miss something?

I want to be sure that I'm not breaking anything with the update.

**Comment by ekrichbaum** [comment]
It's been a while so I'm not sure where this even was in context. I see that I referenced around line 1002 but I wasn't specific enough even for myself there. 

I see the wrap_socket function used in the SoapAdapter.py file (but not around that line) and will try to recreate this to see where it was that I adjusted it.
