### ISSUE TITLE
Dead documentation link

### ISSUE THREAD

**Issue by CameronWThomas** [vmware/pyvmomi#1076]
### Describe the bug

The link to the vsphere web services api, found [here](https://github.com/vmware/pyvmomi?tab=readme-ov-file#documentation) points to a [dead link](https://code.vmware.com/apis/1720/vsphere).

### Reproduction steps

Follow [dead link](https://code.vmware.com/apis/1720/vsphere).
No documentation found

### Expected behavior

It looks as though the new api is located [here](https://developer.broadcom.com/xapis/vsphere-web-services-api/8.0/)

**Comment by DanielDraganov** [comment]
Thank you for reporting this. The link was updated in https://github.com/vmware/pyvmomi/commit/32b5cfe79de263fa1c070660cdd6083a6e1a9e55
