### ISSUE TITLE
How do I resize a Virtual Disk?

### ISSUE THREAD

**Issue by unclethan** [vmware/pyvmomi#119]
I have created a VM from a Template, and wish to change the size of the disk. I am guessing the VirtualDiskManager is involved, but I am unsure of how to proceed. Are there any examples out there, I was unable to find any when I googled.
Thanks

**Comment by avinash321** [comment]
yes , it is not working

**Comment by Jamie-** [comment]
While I presume the snippet above works, I already have the vim.VirtualMachine object of the virtual machine I want to resize the disk on. I came up with the following snippet, adding here as https://github.com/vmware/pyvmomi-community-samples/issues/16 is locked and I think it will be useful to others in future.

This snippet assumes the VM only has one disk and therefore only works on the first disk it finds.

```python
from pyVmomi import vim
from pyVim.task import WaitForTask

...

# vm: vim.VirtualMachine instance already obtained
vdisk = None
for device in vm.config.hardware.device:
    if isinstance(device, vim.vm.device.VirtualDisk):
        vdisk = device
        break
if not vdisk:
    raise Exception("Failed to find VM virtual disk for resizing!")
cspec = vim.vm.ConfigSpec()
vdisk.capacityInKB = 100 * 1024**2  # 100GB
vdisk_spec = vim.vm.device.VirtualDeviceSpec(
    device=vdisk,
    operation=vim.vm.device.VirtualDeviceSpec.Operation.edit,
)
cspec.deviceChange = [vdisk_spec]
WaitForTask(vm.Reconfigure(cspec))
```

**Comment by MashotoMolefe** [comment]
Only works when I increase the size but fails when I shrink vm size. How can i solve this.

> While I presume the snippet above works, I already have the vim.VirtualMachine object of the virtual machine I want to resize the disk on. I came up with the following snippet, adding here as [vmware/pyvmomi-community-samples#16](https://github.com/vmware/pyvmomi-community-samples/issues/16) is locked and I think it will be useful to others in future.
> 
> This snippet assumes the VM only has one disk and therefore only works on the first disk it finds.
> 
> ```python
> from pyVmomi import vim
> from pyVim.task import WaitForTask
> 
> ...
> 
> # vm: vim.VirtualMachine instance already obtained
> vdisk = None
> for device in vm.config.hardware.device:
>     if isinstance(device, vim.vm.device.VirtualDisk):
>         vdisk = device
>         break
> if not vdisk:
>     raise Exception("Failed to find VM virtual disk for resizing!")
> cspec = vim.vm.ConfigSpec()
> vdisk.capacityInKB = 100 * 1024**2  # 100GB
> vdisk_spec = vim.vm.device.VirtualDeviceSpec(
>     device=vdisk,
>     operation=vim.vm.device.VirtualDeviceSpec.Operation.edit,
> )
> cspec.deviceChange = [vdisk_spec]
> WaitForTask(vm.Reconfigure(cspec))
> ```

**Comment by Jamie-** [comment]
Shrinking is not as easy as enlarging as it is more involved - I'm not sure if it's automatable. See this KB article as a starting point https://kb.vmware.com/s/article/1002019
