### ISSUE TITLE
pyVim/connect.py - import httplib

### ISSUE THREAD

**Issue by hartsock** [vmware/pyvmomi#140]
Use of `httplib` in the method `OpenPathWithStub` may  cause problems for users on Python 3.x. Refactor this method to use `requests` and write tests for this method.

**Comment by khayamgondal** [comment]
@hartsock is this issue still open? If so I can work on it.

**Comment by prziborowski** [comment]
This is no longer an issue. httplib is not being used (rather six.moves.http_client is).
Was done: https://github.com/vmware/pyvmomi/commit/cd533499cb625181b159e6f67c295c40d2fdd1c4#diff-f27d9cf5aae6795e868fe6b3804107e2
