### ISSUE TITLE
pyVim/connect.py - use of file builtin method

### ISSUE THREAD

**Issue by hartsock** [vmware/pyvmomi#141]
The use of the `file` built in method means that the method `GetLocalTicket` will be broken for Python 3.x users. Write tests for this method and rewrite using `six` lib compatible calls.

See: [connect.py GetLocalTicket](https://github.com/vmware/pyvmomi/blob/master/pyVim/connect.py#L262)

**Comment by khayamgondal** [comment]
@hartsock is it still open? If is it, I can take it.

**Comment by DanielDraganov** [comment]
This is almost a 10 year old improvement suggestion which is outdated.
GetLocalTicket() was updated two years later: https://github.com/vmware/pyvmomi/commit/bab12c6061b0dbd9d5d93fa4a7ae7202935fb468
