### ISSUE TITLE
pyVmomi/SoapAdapter - SoapStubAdapter init method may use urlparse

### ISSUE THREAD

**Issue by hartsock** [vmware/pyvmomi#142]
The `SoapStubAdapter` class' `__init__` method makes a call `urlparse.urlparse(url)[:3]` if the constructor for the object is passed an optional `url` string. This path of execution in the constructor does not appear to be used in any known use cases. That means that the offending code may not even be reachable.

Paths to resolution of this issue:
- Refactor the `__init__` method to never use `urlparse`
- Refactor use of `urlparse` to use a `six` library compatible call.
- Rewrite the `__init__` method to eliminate _dead_ code (if you can identify this code as uncallable).

Note: write tests to cover any changes.

**Comment by khayamgondal** [comment]
@hartsock is it still pending? I can work on it.

**Comment by hartsock** [comment]
@khayamgondal it's actually @pgbidkar who's running the project now. I think this may have already been covered during a previous upgrade to Python3 compatible libraries.

**Comment by hartsock** [comment]
@pgbidkar this appears to be the code I was talking about

https://github.com/vmware/pyvmomi/blob/master/pyVmomi/SoapAdapter.py#L1218

If I remember correctly I wasn't able to reach these blocks from inside the debugger.

**Comment by khayamgondal** [comment]
It should be closed than.

**Comment by DanielDraganov** [comment]
`urlparse` is already using `six`. Closing the issue.
