### ISSUE TITLE
Unable to Fetch FileSize, modifled and owner information of files in datastore

### ISSUE THREAD

**Issue by vnbang2003** [vmware/pyvmomi#178]
Am trying to fetch filename, filesize and owner information of each file in datastore.
Below is the code i use for fetching 

<>
search = vim.HostDatastoreBrowserSearchSpec()
    search.matchPattern = "*.vmx"
    searchDS = dsbrowser.SearchDatastoreSubFolders_Task(dsname, search)
    while searchDS.info.state != "success":
        pass
    results = searchDS.info.result
    #print results
    for rs in searchDS.info.result:
        dsfolder = rs.folderPath
        for f in rs.file:
             dsfile = f.path
             filesize = f.fileSize
             owner = f..owner
             print dsfile, filesize, owner

<>
Example /Op i guess 
Auto-Dev VC_Win2K8.vmx None None
Auto-Dev workbench 3.0.vmx None None

I am able to get filename but filesize and owner information is always None.

**Comment by DanielDraganov** [comment]
This is quite old and after so many years  guess the is no longer relevant. Closing it.
If further assistance is required please use the Discussions section.
