### ISSUE TITLE
InsecureRequestWarning message when connecting on vcenter

### ISSUE THREAD

**Issue by sebbrochet** [vmware/pyvmomi#179]
Hello,

Using pyvmomi==5.5.0.2014.1.1, **urllib3** reports a warning message when connecting to a vcenter host, possibly because the HTTPS connection is made with `verified=false` (see: https://github.com/kennethreitz/requests/issues/2214)

Warning message doesn't seem to be displayed when using pyvmomi==5.5.0    

 Full error:   

```
.../lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
```

Sample code to reproduce error:

```
from pyVim import connect
connect.SmartConnect(host=args.target,
                     user=args.user,
                     pwd=args.password,
                     port=int(args.port))
```

As a workaround, warning message can be disabled with:    

```
import requests
requests.packages.urllib3.disable_warnings()
```

**Comment by hartsock** [comment]
@michaelrice I'm in agreement here. We could entertain a feature that made this *easy* to do with a flag to smart connect but, I think it is best to leave the warnings. 

My concerns:
* we do **not** want to make it *too* easy to form insecure HTTPS connections
* we do want to encourage people to understand what's happening when they use `verified=false`
* we do **not** want to introduce a blocker, objection, or non-sensical work-around for down-stream projects such as SaltStack, OpenStack, or Ansible

**TODO**: weigh the possibility of a flag `warnings=False` in a future release.

I'm leaving this open to remind myself to come back to this later.

**Comment by joshk0** [comment]
+1, might hack on this soon. (Hey! I'm alive!)

**Comment by joshk0** [comment]
@hartsock, would it be appropriate to plumb the setting to enable SSL verification in SmartConnect, and then let the warnings continue to show if you pass false?

**Comment by amitdash** [comment]
I have used below code just above pyVmomi import

import requests
requests.packages.urllib3.disable_warnings()
import ssl
try:
	_create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

**Comment by hartsock** [comment]
@amitdash this is the approach I'm going to combine with @joshk0's suggestion. The result will be pushed up for review shortly.

**Comment by joshk0** [comment]
Feel free to assign me on the PR. I can look it, just haven't had time to dig in on code.

**Comment by spicyramen** [comment]
I modified Line 339 "verify" variable to to False in /usr/local/lib/python2.7/dist-packages/requests/adapters.py
self.cert_verify(conn, request.url, False, cert)

**Comment by DanielDraganov** [comment]
After so many years this issue is no longer relevant. Closing it.
