### ISSUE TITLE
Possible versionId mismatch MMESoapStubAdapter

### ISSUE THREAD

**Issue by grzn** [vmware/pyvmomi#180]
Consider the following scenario:
- Using pyVmomi with vCenter 5.5, which manages ESXi 5.1

In this case, MMESoapStubAdapter sets versionId to _urn:vim25/5.5", but the ESXi is 5.1, and later the ESX returns InvalidProperty exceptions:

``` python
/opt/infinidat/host-power-tools-for-vmware/eggs/pyvmomi-5.5.0.1-py2.7.egg/pyVmomi/ManagedMethodExecutorHelper.pyc in InvokeMethod(self, mo, info, args)
     75                                     version=version,
     76                                     method=methodName,
---> 77                                     argument=methodArgs)
     78       return self._DeserializeExecutorResult(result, info.result)
     79

/opt/infinidat/host-power-tools-for-vmware/eggs/pyvmomi-5.5.0.1-py2.7.egg/pyVmomi/VmomiSupport.pyc in <lambda>(*args, **kwargs)
    567          # curried methods will receive 'self' *after* any fixed arguments
    568          return lambda *args, **kwargs: \
--> 569                            self.f(*(self.args + (obj,) + args), **kwargs)
    570       return self
    571

/opt/infinidat/host-power-tools-for-vmware/eggs/pyvmomi-5.5.0.1-py2.7.egg/pyVmomi/VmomiSupport.pyc in _InvokeMethod(info, self, *posargs, **kwargs)
    376             args[idx] = v
    377       map(CheckField, info.params, args)
--> 378       return self._stub.InvokeMethod(self, info, args)
    379    _InvokeMethod = staticmethod(_InvokeMethod)
    380

/opt/infinidat/host-power-tools-for-vmware/eggs/pyvmomi-5.5.0.1-py2.7.egg/pyVmomi/SoapAdapter.pyc in InvokeMethod(self, mo, info, args, outerStub)
   1299             return obj
   1300          else:
-> 1301             raise obj # pylint: disable-msg=E0702
   1302       else:
   1303          conn.close()

vmodl.fault.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct. \nversion',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'version'
}}
```

Note that v5.5.0.1 here is https://github.com/Infinidat/pyvmomi/commit/ba5b8d21d2d9754e6a47db1ce80a82dd5b6f3cd4, and the changes we added to our fork are not related to this problem.

**Comment by shbalu07** [comment]
I have borh VC and ESXI at 5.5, but hitting the below issue while doing migration of vm from Host A to Host B.

Caught vmodl fault: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct. \n',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = <unset>
}

Code:
import atexit
import argparse
import time

from pyVmomi import vim, vmodl
from pyVim import connect
from pyVim.connect import Disconnect

inputs = {'vcenter_ip': '72.20.100.9',
          'vcenter_password': 'pwd123!',
          'vcenter_user': 'administrator@vsphere.local',
          'vm_name': 'Comp1_Automation1_test',
          'destination_host': '72.20.100.21'
          }

def get_obj(content, vimtype, name):
    """
     Get the vsphere object associated with a given text name
    """
    obj = None
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if c.name == name:
            obj = c
            break
    return obj


def wait_for_task(task, actionName='job', hideResult=False):
    """
    Waits and provides updates on a vSphere task
    """

    while task.info.state == vim.TaskInfo.State.running:
        time.sleep(2)
        print(task.info.state)
    if task.info.state == vim.TaskInfo.State.success:
        if task.info.result is not None and not hideResult:
            out = '%s completed successfully, result: %s' % (actionName, task.info.result)
            print out
        else:
            out = '%s completed successfully.' % actionName
            print out
    else:
        out = '%s did not complete successfully: %s' % (actionName, task.info.error)
        raise task.info.error
        print out
    return task.info.result

def dump(obj):
  for attr in dir(obj):
    print "obj.%s = %s" % (attr, getattr(obj, attr))

def main():

    try:
        si = None
        try:
            print "Trying to connect to VCENTER SERVER . . ."
            si = connect.Connect(inputs['vcenter_ip'], 443, inputs['vcenter_user'], inputs['vcenter_password'], service="hostd")
        except IOError, e:
            pass
            atexit.register(Disconnect, si)

        print "Connected to VCENTER SERVER !"

        content = si.RetrieveContent()

        vm = get_obj(content, [vim.VirtualMachine], inputs['vm_name'])
        dump(vm)
        destination_host = get_obj(content, [vim.HostSystem], inputs['destination_host'])
        resource_pool = vm.resourcePool
        if vm.runtime.powerState != 'poweredOn':
            print "WARNING:: Migration is only for Powered On VMs"
            sys.exit()

        migrate_priority = vim.VirtualMachine.MovePriority.defaultPriority

        msg = "Migrating %s to destination host %s" % (inputs['vm_name'], inputs['destination_host'])
        print msg

        #Live Migration :: Change host only
        print "resource_pool:",resource_pool
        print "destination_host:",destination_host
        #Live Migration :: Change both host and datastore
        vm_relocate_spec = vim.vm.RelocateSpec()
        vm_relocate_spec.host = destination_host
        vm_relocate_spec.pool = resource_pool
        datastores = destination_host.datastore
        print "Datastore:",datastores
        #Assuming Migrating between local datastores
        for datastore in datastores:
            print "datastore.summary.type: --->", datastore.summary.type
            if datastore.summary.type == 'VMFS':
                vm_relocate_spec.datastore = datastore
                dump(datastore)
                break
        dump(vm_relocate_spec)
        print "vm_relocate_spec.host: ",vm_relocate_spec.host,"vm_relocate_spec.pool: ", vm_relocate_spec.pool,\
                                "vm_relocate_spec.datastore: ", vm_relocate_spec.datastore
        task = vm.Relocate(spec=vm_relocate_spec)

        # Wait for Migrate to complete
        wait_for_task(task, si)

    except vmodl.MethodFault, e:
        print(dir(e))
        print "Caught vmodl fault: %s" % e
        return 1
    except Exception, e:
        print "Caught exception: %s" % str(e)
        return 1
# Start program
if __name__ == "__main__":
    main()

**Comment by DanielDraganov** [comment]
After so many years this issue is no longer relevant. 5.5 has reached end of life. Closing it.
