### ISSUE TITLE
RegisterVM method on vim.folder doesn't exist

### ISSUE THREAD

**Issue by sebbrochet** [vmware/pyvmomi#181]
Hi,

Contrary to documentation on this page (https://github.com/vmware/pyvmomi/blob/master/docs/vim/Folder.rst), the `RegisterVM` method on a `vim.folder` object doesn't exist.

After some digging, seems like corresponding method is named: `RegisterVM_Task`

Tested on pyvmomi==5.5.0.2014.1.1 against vCenter 5.5.0

**Comment by hartsock** [comment]
This appears to be a documentation issue. The name `RegisterVM_Task` seems to appear.
