### ISSUE TITLE
Search by VM_UUID not returning VM

### ISSUE THREAD

**Issue by zukeru** [vmware/pyvmomi#186]
I have a program that searchs a db continusously for commands to send to a vcenter for various reasons mainly because out customer portal is in a different security zone than vcenter so inorder to protect our vcenter we use a db as a mediator for commands. I'm writing the script to get the vm by its uuid, however it is returning a none type for the vm when I know it exist because im getting the uuid from vcenter directly and then saving to db. Then when my command section is running it gets that vm uuid from the db with the command and trys to find the vm by the uuid. However, the uuid doesnt return a vm just a null value.

		#!/usr/bin/python

		import atexit
		import calendar
		import cx_Oracle
		from datetime import datetime
		from metering import *
		import os
		import psycopg2
		from pyVim.connect import SmartConnect, Disconnect
		from pyVmomi import vim
		import sys
		import time
		import threading
		import pchelper
		import requests
		from multiprocessing import Process
		from Crypto.Cipher import XOR
		import base64

		def encrypt(key, plaintext):
		  cipher = XOR.new(key)
		  return base64.b64encode(cipher.encrypt(plaintext))

		def keep_vc_alive(vcenter,hostname,username, password,suicide, pause_thread):
		   '''
		   Paramaters
		   vcenter:       the vcenter connection handle
		   credentials:   vcenter connection credentials
		   suicide:       used to terminate the thread when the main function hits the main exception block
		   pause_thread:  the event that lets the thread know not to step on the other process
		   '''
		   while not suicide.is_set():
		      if not pause_thread.is_set():
			 try:
			    logging.info('staying connected' % str(hostname))
			    vcenter.CurrentTime()
			 except:
			    logging.info('unable to call current time of vcenter %s attempting to reconnect.' % str(hostname))
			    try:
			       vcenter = None
			       vcenter = SmartConnect(host=hostname,user=username,pwd=password)
			    except ApplicationError:   
			       break
			 suicide.wait(timeout=60*28)  # sleep for 28 minutes
		   raise ApplicationError

		def status_worker():
		   list_of_vc_connections = {}
		   config_values_vc = metering_config('VSphereManager',['vcenter-ip','username','password','api-version'])
		   for k in xrange(0, len(config_values_vc['username'])):   # Loop through each vcenter server
			 password = config_values_vc['password'][k]
			 hostname = config_values_vc['vcenter-ip'][k]
			 username = config_values_vc['username'][k]
			 vcenter_connection = SmartConnect(host=hostname,user=username,pwd=password)
			 atexit.register(Disconnect, vcenter_connection)
			 content = vcenter_connection.RetrieveContent()
			 
			 if not vcenter_connection:
			    logging.error("Could not connect to vcenter-ip %s" % (str(hostname)))
			    continue
			 uuid_dict[config_values_vc['vcenter-ip'][k]] = content.about.instanceUuid
			 list_of_vc_connections[config_values_vc['vcenter-ip'][k]] = vcenter_connection
			 vc_thread[config_values_vc['vcenter-ip'][k]] = threading.Thread(target=keep_vc_alive, args=(list_of_vc_connections[config_values_vc['vcenter-ip'][k]],config_values_vc['vcenter-ip'][k], username, password, suicide, pause_thread))
			 vc_thread[config_values_vc['vcenter-ip'][k]].start()  
			 
		   postgres = psycopg2.connect()
		   pg_cursor = postgres.cursor()
		   oracle,data_dict = db_init()    # Open the connection to the DB 
		   oracle_cursor = oracle.cursor()
				     
		   while True:
			 t0_clock = time.clock()
			 t0_time = time.time()
			 pg_cursor.execute('SET SESSION TIMEZONE TO MST7MDT')
			 postgres.commit()
			 
			 for vcenter in list_of_vc_connections:
			    vm_properties = ["name","runtime.powerState"]         
			    root_folder = list_of_vc_connections[vcenter].content.rootFolder
			    view = pchelper.get_container_view(list_of_vc_connections[vcenter], obj_type=[vim.VirtualMachine])
			    vm_data = pchelper.collect_properties(list_of_vc_connections[vcenter], view_ref=view, obj_type=vim.VirtualMachine, path_set=vm_properties, include_mors=True)
			    for virtual_machine in vm_data:
			       vm_mor = str(virtual_machine['obj']).split(':')[1]
			       vm_mor = vm_mor.replace("'","")
			       power_state = virtual_machine['runtime.powerState']   
			       vm_name = virtual_machine['name']
			       oracle_cursor.execute('''select c.vm_id, a.customer_id from customers a, vm_groups b, vms c where a.customer_id = b.customer_id and b.vm_group_id = c.vm_group_id and c.vm_mor = '%s' ''' % vm_mor)
			       returned_row = oracle_cursor.fetchone()
			       
			       if returned_row:
				  pg_cursor.execute('''select * from portal_command_center where vm_id = %s ''' % returned_row[0])
				  check_exist = pg_cursor.fetchone()
				  if not check_exist:
				     pg_cursor.execute('''insert into portal_command_center(vm_id, vm_uuid, power_state, vm_name, customer_id) 
								values(%s,'%s', '%s', '%s', %s)''' % (returned_row[0],virtual_machine['obj'].config.uuid, power_state, vm_name, returned_row[1]))
				  else:
				     pg_cursor.execute('''update portal_command_center set power_state='%s' where vm_id = %s ''' % (power_state, returned_row[0]))
			 postgres.commit()                             
			 runtime = time.time() - t0_time 
		      
		def vm_command_center():
		      list_of_vc_connections = {}
		      config_values_vc = metering_config('VSphereManager',['vcenter-ip','username','password','api-version'])
		      for k in xrange(0, len(config_values_vc['username'])):   # Loop through each vcenter server
			    password = config_values_vc['password'][k]
			    hostname = config_values_vc['vcenter-ip'][k]
			    username = config_values_vc['username'][k]
			    vcenter_connection = SmartConnect(host=hostname,user=username,pwd=password)
			    atexit.register(Disconnect, vcenter_connection)
			    content = vcenter_connection.RetrieveContent()
			    
			    if not vcenter_connection:
			       logging.error("Could not connect to vcenter-ip %s" % (str(hostname)))
			       continue
			    uuid_dict[config_values_vc['vcenter-ip'][k]] = content.about.instanceUuid
			    list_of_vc_connections[config_values_vc['vcenter-ip'][k]] = vcenter_connection
			    vc_thread[config_values_vc['vcenter-ip'][k]] = threading.Thread(target=keep_vc_alive, args=(list_of_vc_connections[config_values_vc['vcenter-ip'][k]],config_values_vc['vcenter-ip'][k], username, password, suicide, pause_thread))
			    vc_thread[config_values_vc['vcenter-ip'][k]].start()  
		      
		      command_dict = {}      
		      postgres = psycopg2.connect()
		      pg_cursor = postgres.cursor()
		      command_cursor = postgres.cursor()
		      check_command_cursor = postgres.cursor()
		      queue_cursor = postgres.cursor()
		      oracle,data_dict = db_init()    # Open the connection to the DB 
		      oracle_cursor = oracle.cursor()   
			  
		      while True:
			 command_cursor.execute('''select vm_id, vm_name, vm_uuid, customer_id, power_state, command_state, username, ip_address, command_issued_time, command_completed_time from portal_command_center where command_state != '' ''')
			 for row in command_cursor:
			    vm_id=row[0]
			    vm_name=row[1]
			    vm_uuid=row[2]
			    customer_id=row[3]
			    power_state=row[4]
			    command_state=row[5]
			    username=row[6]
			    ip_address=row[7]
			    command_issued_time=row[8]
			    command_completed_time=row[9]
			    
			    token_to_generate = username + ip_address
			    token=encrypt('', token_to_generate) 
			    pg_cursor.execute('''select customer_id, token from command_token where token = '%s' ''' % token)
			    row = pg_cursor.fetchone()
			    ''' 
			     this if statement triggers when the command token saved in the db, matches the one from the user who sent the command.
			     Then the command dictonary is built, and it checks to see if the command is already in the command_queue table,
			     if the command is in the command_queue table it will not re-insert the command. Thus, whe we display the command to customers
			     command_queue will only have active commands. Then it will be deleted from command_queue upon completion
			    '''
			     
			    if row:
			       if vm_id not in command_dict:
				  command_dict[vm_id] = {'vm_id':vm_id, 'vm_uuid':vm_uuid, 'vm_name':vm_name, 'customer_id':customer_id,'power_state':power_state, 'command':command_state, 'username':username, 'ip_address':ip_address, 'command_issued_time': command_issued_time, 'command_completed_time':command_completed_time }
				  check_command_cursor.execute('''select * from command_queue where vm_id = %s and command_issued_time = '%s' ''' %(vm_id, command_issued_time))
				  row = check_command_cursor.fetchone()
				  if row:
				     pass
				  else:
				     queue_cursor.execute('''insert into command_queue (vm_id, vm_name, customer_id, power_state, command, username, ip_address, command_issued_time) values(%s, '%s', %s, '%s', '%s', '%s', '%s', '%s')''' % (vm_id, vm_name, customer_id, power_state, command_state, username, ip_address, command_issued_time))
			 
			 for command in command_dict:
			    for vcenter in list_of_vc_connections:
			       vm_uuid = command_dict[command]['vm_uuid']
			       search_index = list_of_vc_connections[vcenter].content.searchIndex
			       vm = search_index.FindByUuid(None, vm_uuid, True, True)
			       print 'execute command'
				  
		suicide = threading.Event()
		pause_thread = threading.Event()  
		number_of_connections = 0
		vc_thread = {}
		uuid_dict = {}
		vm_dict = {}
		requests.packages.urllib3.disable_warnings()

		status_worker = Process(target=status_worker, args=())
		command_worker = Process(target=vm_command_center, args=())
		status_worker.start()
		command_worker.start()

		while True:
		   print 'working'
		   time.sleep(1000)

**Comment by hartsock** [comment]
I'm sure I'm not giving this justice, my eyes are glazing over at the size of this post. So, I'll at least give you some troubleshooting advice first before we dig too deep.

* According to [official docs](http://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html#findByUuid) those two flags on the end of `search_index.FindByUuid(None, vm_uuid, True, True)` that you set to `True` are `vmSearch` and `instanceUuid` which means you're looking by the vCenter Instance UUID. The value `vm_uuid` is `row[2]` which may or may not contain the instanceUUID assuming the query you built is correct and *I'm not sure* if that's how you're *intended* to get the vm_uuid. You may be looking at the BIOS UUID which is the UUID the guest knows about itself and not the vCenter UUID.

* You're break point shows a `vcenter_uuid` that does not equal the `vm_uuid` yet your search `FindByUuid(None, vm_uuid, True, True)` is looking for the vcenter ID not the BIOS ID which I presume is what you're locally calling the `vm_uuid`. 

Based on your break point and my analysis of the call you made this is *actually* correct behavior. If you wanted to search and find `vm_uuid` you should *probably* call `FindByUuid(None, vm_uuid, True,` **False**`)` instead!

Feel free to re-open if this doesn't resolve your issue.
