### ISSUE TITLE
Please continue support of VC 4.0

### ISSUE THREAD

**Issue by MchaelBoyar** [vmware/pyvmomi#187]
Please relax your policy of supporting last 4 versions of VC.
The current policy is too restrictive, specifically pyVmomi 5.1.0 is last to support VC 4.0.
I'm a pyVmomi user, I still have some VC 4.0 left; I'm forced to stick with pyVmomi 5.1.0

Michael Boyar
Configuration Management
JP Morgan Chase
VMWare Agreement #: 00101692

**Comment by DanielDraganov** [comment]
This one is quite old. Based on the age and https://github.com/vmware/pyvmomi#compatibility-policy I'm closing the issue.
