### ISSUE TITLE
Can’t retrieve licensableResource property of HostSystem

### ISSUE THREAD

**Issue by MchaelBoyar** [vmware/pyvmomi#188]
I can't retrieve licensableResource property of HostSystem.
For example, using MOB in VC 5.1 the property is visible, yet in pyVmomi it generates this stack trace:

> > > h.licensableResource
> > >                 Traceback (most recent call last):
> > >                 File "<stdin>", line 1, in <module>
> > >                 File "pyVmomi\VmomiSupport.py", line 560, in **call**
> > >                 return self.f(_args, *_kwargs)
> > >                 File "pyVmomi\VmomiSupport.py", line 383, in _InvokeAccessor
> > >                 return self._stub.InvokeAccessor(self, info)
> > >                 File "pyVmomi\StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
> > >                 options=self._pcType.RetrieveOptions(maxObjects=1))
> > >                 File "pyVmomi\VmomiSupport.py", line 566, in <lambda>
> > >                 self.f(_(self.args + (obj,) + args), *_kwargs)
> > >                 File "pyVmomi\VmomiSupport.py", line 375, in _InvokeMethod
> > >                 return self._stub.InvokeMethod(self, info, args)
> > >                 File "pyVmomi\SoapAdapter.py", line 1301, in InvokeMethod
> > >                 raise obj # pylint: disable-msg=E0702
> > >                 pyVmomi.VmomiSupport.InvalidProperty: (vmodl.query.InvalidProperty) {
> > >                                 dynamicType = <unset>,
> > >                                 dynamicProperty = (vmodl.DynamicProperty) [],
> > >                                 msg = '',
> > >                                 faultCause = <unset>,
> > >                                 faultMessage = (vmodl.LocalizableMessage) [],
> > >                                 name = u'licensableResource'
> > >                 }

Michael Boyar
Configuration Management
JP Morgan Chase
VMWare Agreement #:  00101692

**Comment by DanielDraganov** [comment]
This one is quite old. Based on the age and https://github.com/vmware/pyvmomi#compatibility-policy I'm closing the issue.
