### ISSUE TITLE
pyVmomi makes mistakes in differentiating between 4.0, 4.1 and 5.x VC targets

### ISSUE THREAD

**Issue by MchaelBoyar** [vmware/pyvmomi#189]
pyVmomi makes mistakes in differentiating between 4.0, 4.1 and 5.x VC targets and tries to get 5.x properties from 4.x targets.
Examples:
Unexpected error:  <class 'pyVmomi.VmomiSupport.vmodl.query.InvalidProperty'>
Unexpected error:  <class 'pyVmomi.VmomiSupport.vmodl.fault.SystemError'>

Michael Boyar
Configuration Management
JP Morgan Chase
VMWare Agreement #:  00101692

**Comment by DanielDraganov** [comment]
This one is quite old. Based on the age and https://github.com/vmware/pyvmomi#compatibility-policy I'm closing the issue.
