### ISSUE TITLE
Parse Error when trying to access description attribute of EventManager

### ISSUE THREAD

**Issue by sujeetk** [vmware/pyvmomi#190]
I am trying to obtain eventInfo object associated with an event manager in the following manner:

```
from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim

import ConfigParser

config = ConfigParser.ConfigParser()
config.readfp(open('params.conf'))

VC_HOST = config.get('vcenter', 'host')
VC_PORT = config.get('vcenter', 'port')
VC_USERNAME = config.get('vcenter', 'username')
VC_PASSWORD = config.get('vcenter', 'password')

service_instance = connect.SmartConnect(host=VC_HOST, user=VC_USERNAME,     pwd=VC_PASSWORD, port=int(VC_PORT))

event_manager = service_instance.content.eventManager
event_description = event_manager.description
event_details = event_description.eventInfo

print type(event_details)
```

I get an exception with the following trace:

http://pastebin.com/znVDTaPR

**Comment by hartsock** [comment]
@michaelrice thanks for the recording

@sujeetk the giant xml dump is supposed to help us figure out where the parser died. Using @michaelrice 's recording I may hopefully be able to identify the XML line and position where the XML parser fails and then fix it.

Things that are nice to know:
* What version of vSphere are you using?
* What version of Python?

I'll place this in the back log for sooner rather than later.

**Comment by hartsock** [comment]
Note: anyone can build a unit test and/or fix using @michaelrice 's recording. I'll remove the 'help wanted' tag the day I start work on this bug.

**Comment by sujeetk** [comment]
I am using vSphere 5.5 and Python 2.7.

**Comment by joshw** [comment]
I have just encountered the same issue..  On a VMware ESXi 5.5.0 build-1331820 target, I am encountering this error:

```
>>> len(si.content.eventManager.description.eventInfo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/Library/Python/2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Library/Python/2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Library/Python/2.7/site-packages/pyVmomi/SoapAdapter.py", line 1357, in InvokeMethod
    raise exc
pyVmomi.SoapAdapter.ParserError: 'xml document: <httplib.HTTPResponse instance at 0x108c6da28> parse error at: line:7, col:73574'
```

After some digging, I have found that it is the 'key' field in the EventDescriptionEventDetail.. it refers to a type (the event type in this case), and if that type is unknown to pyVmomi, it throws an error in the EndElementHandler, when GuessWsdlType causes a KeyError.

The workaround is to add the missing event classes as follows:

```
>>> from pyVmomi.VmomiSupport import CreateDataType
>>> CreateDataType("vim.event.HostDVPortEvent", "HostDVPortEvent", "vim.event.Event", "vim.version.version1", None)
>>> CreateDataType("vim.event.VmDVPortEvent", "VmDVPortEvent", "vim.event.Event", "vim.version.version1", None)
>>> CreateDataType("vim.event.ChangeOwnerOfFileEvent", "ChangeOwnerOfFileEvent", "vim.event.Event", "vim.version.version1", None)
>>> CreateDataType("vim.event.ChangeOwnerOfFileFailedEvent", "ChangeOwnerOfFileFailedEvent", "vim.event.Event", "vim.version.version1", None)
>>>
>>>
>>> len(si.content.eventManager.description.eventInfo)
439
```

I am not confident that this is an ideal fix, however- it still seems possible that some more event types may exist in the world which are not included in the pyvmomi library, and this error message is particularly unhelpful.. If nothing else, it should identify what unrecognized class was encountered.  

But it's also possible that in some situations (like this), it should be more accepting of unrecognized classes.

**Comment by prziborowski** [comment]
I agree that it should be more accepting of unrecognized classes. There is another issue around for a similar problem when calling EnvironmentBrowser.QueryConfigOptions (typically against a newer Host/vCenter with older pyvmomi).

Typically pyvmomi is generated with all the known types for the latest version, so unknown types are not an issue (unless using older pyvmomi with newer hosts).

I think think in this case, it is an issue of the host leaking events that were never released. I don't see them subclassed from [Event](https://code.vmware.com/apis/196/vsphere#/doc/vim.event.Event.html).
So pyvmomi would do well to handle that more gracefully.

**Comment by folti** [comment]
Hello,

We encountered with these problem since our  VCenter 6.5.0 build-5973321 started to return HostSubSpecificationUpdateEvent events, which, along with HostSubSpecificationDeleteEvent are not declared in ServerObjects.py.

pyVmomi version is 6.7.0.2018.9.

**Comment by DanielDraganov** [comment]
HostSubSpecificationUpdateEvent is now available in pyVmomi.
As for unknown types, this is an internal issues that is yet to be fixed. -> https://github.com/vmware/pyvmomi/issues/1016#issuecomment-1562455349
This issue duplicates https://github.com/vmware/pyvmomi/issues/1016
