### ISSUE TITLE
Sometimes the API will return no data for specific properties even though it should

### ISSUE THREAD

**Issue by embodyhumility** [vmware/pyvmomi#20]
I wrote a python program to query the vm.guest.net property so I could get all of the MAC addresses for all VM's.  Most of the time, the program will return the correct results, however, sometimes the program will return nothing for vm.guest.net, yet the VM has not changed in any way.  If I restart vCenter, the program will again return all of the correct data.

I have seen this same behavior with other properties but vm.guest.net seems to be the most prone to failure.

To test this, you can write a program to record all of the MAC's for each VM in the infrastructure and you will find over the course of a month one or more of those calls will return nothing.

Thanks, I hope this was clear and you can fix the bug.

Best,

Dave

**Comment by srazin** [comment]
Hello!
2 years later but we also running into a similar issue with yavijava (java library) which confirms that it is not py issue (assuming we looking at the same problem which sounds like we do).
After the restart of vCenter everything comes to normal. Also if you connect another system...different IP, it also seem to work (not sure if vCenter in some way also holds the session identity based on the connected MAC...).
Anyone seen this again? Any KB articles @ VMware?
