### ISSUE TITLE
Allow client to force non-compressed HTTP sessions.

### ISSUE THREAD

**Issue by gxben** [vmware/pyvmomi#202]
I had an issue with pyvmomi SDK where certain objects can't be accessed (SOAP Exception from HTTP request).
It appears to be due to the fact that pyvmomi adds gzip,deflate header to request and, under special circumstances, server responds with transfert-encoding being chunked.

SoapAdapter class doesn't seems to handle HTTP chunked data at all, going through exception.

Attached is a small patch that simply extends SmartConnect method to determine whether or not we want to propagate Accept-Encoding header in request, hence enabling or disabling any form of compression (until HTTP chunked data is properly handled).
It updates API but default behavior is kept unchanged unless parameter is being specified.

See http://pastebin.com/af0ZHHX3

**Comment by hartsock** [comment]
I think this is a reasonable change request and I'm surprised it hasn't come up before. Please note that there are [standards for contribution](https://github.com/vmware/pyvmomi/wiki/Contributions). In some cases where it's clear testing is not feasible and that the code is non-intrusive based on human inspection I may grant an exception. I would prefer avoiding exceptions like that and prefer clever testing and test tooling instead.

*Yes, I'm holding these contributions to a much higher standard.*

**Comment by khayamgondal** [comment]
Does someone working on it?

**Comment by prziborowski** [comment]
According to the source, this has been completed: https://github.com/vmware/pyvmomi/blob/master/pyVim/connect.py#L735

**Comment by khayamgondal** [comment]
It should be closed than.

**Comment by hartsock** [comment]
Okee dokee. Closing this ... @pgbidkar reopen if needed.
