### ISSUE TITLE
[Question] How to identify a management dvswitch/portgroup

### ISSUE THREAD

**Issue by rreubenur** [vmware/pyvmomi#206]
Is there an easy way to identify a management dvswitch/portgroup ?  What I know is to identify it from  host level that is ```host.configManager.virtualNicManager.info.netConfig.nicType```  . Is it possible to identify them from dvswitch object or is there any shortest method ?

**Comment by hartsock** [comment]
Okay, this is a *good* question. I'll actually have to do some research to figure this out.

**Comment by rreubenur** [comment]
Okay I think there is no way you can find a mgmt dvs from dvs properties.  The only way to find that is HostConfigManager which I have explained in my question.

Closing this issue.
