### ISSUE TITLE
can connect.Connect() use loginBySSPI

### ISSUE THREAD

**Issue by troob** [vmware/pyvmomi#208]
Is it possible to use loginBySSPI with connect.Connect() ?

**Comment by hartsock** [comment]
While there *are* stubs for this behavior in the `pyVmomi` code as it ships now, the *backing* logic has not been approved for release under an Open Source license. I am hopeful that we will get donations from someone who is willing to create these function in some future release. I'm not able to quote a time line on when that might be just now.

* I would encourage you to open a feature request ticket or find one and comment `+1` or a similar comment of support
* I do show these to folks as part of my discussions about what should be Open Source
* Logging your use-case as a feature request also helps us build a better client library product
** be specific... outline what you're doing, what you can't do, and what you want to do
** pseudo code helps communicate these ideas when English fails us

All the best.
