### ISSUE TITLE
Create VM by using StorageDRS

### ISSUE THREAD

**Issue by jm66** [vmware/pyvmomi#213]
Hi guys,

I've been trying to create a VM using Storage DRS, and while I don't get the VM created, vCenter crashes. I'm currently analyzing the vC logs but wanted to ask you guys if I'm doing it right. Here's what I've done so far assuming the following:
- A full VM config Spec tested with vim.Folder.CreateVM_Task. This means that the config spec object is working and there are no errors.
- A valid datastore cluster name and the function get_dscluster gets the corresponding object for the datastore cluster
- A valid target folder (vim.Folder) object
- A valid resource pool object (vim.ClusterComputeResource.resourcePool)

``` python
def create_vm_sdrs(content, si, dsc_name, folder, vm_config_spec, resource_pool):

    # make an empty pod selection spec, then customize it
    podsel = vim.storageDrs.PodSelectionSpec()
    pod = get_dscluster(content, dsc_name)
    podsel.storagePod = pod

    # make an empty storage placement spec, then customize it
    storagespec = vim.storageDrs.StoragePlacementSpec()
    storagespec.podSelectionSpec = podsel
    storagespec.type = 'create'
    storagespec.folder = folder
    storagespec.resourcePool = resource_pool
    storagespec.configSpec = vm_config_spec

    # recommended datastores
    rec = content.storageResourceManager.RecommendDatastores(storageSpec=storagespec)

    # recommendation key
    rec_key = rec.recommendations[0].key

    task = content.storageResourceManager.ApplyStorageDrsRecommendation_Task(rec_key)
    tasks.wait_for_tasks(si, [task])
```
Any help on this is greatly appreciated.

Thanks,
JM

**Comment by hartsock** [comment]
So, the closest thing we have is [William Lam](https://twitter.com/lamw)'s blog post [VM Provisioning on Datastore Clusters in vSphere 5](http://www.virtuallyghetto.com/2012/03/vm-provisioning-on-datastore-clusters.html). Hopefully, you can use this post to work out a solution for yourself. I would greatly appreciate a [sample](https://github.com/vmware/pyvmomi-community-samples) should you work something out that might fit. I don't think we have any samples that come close (on *any* of our API).

Let me know if this helps. (And, thanks to William for having a post on the topic.)

**Comment by hartsock** [comment]
I've looked this over again... and something *jumps* out at me...
` rec = content.storageResourceManager.RecommendDatastores(storageSpec=storagespec)`

You are trying to build a `RecommendDatastores` object with the `storageSpec` set  to `storagespec` if I'm right and you output the variable `rec` as a string or examine it in the debugger you'll notice that `storageSpec` is never set to the value `storagespec` ... that's because *pyVmomi initializers don't work that way*.

You have to write instead:
```
rec = content.storageResourceManager.RecommendDatastores()
rec.storageSpec=storagespec
```

This little bit of confusion happens quite a few times on pyVmomi and I think I would like to see a feature enhancement to handle this use-case. I'll open a separate ticket and put it in the *wishlist* and refer to this and any other tickets I can find with this issue.

**Comment by jm66** [comment]
hey @hartsock, thanks for your response. I wrote the code based on William Lam's post and it was very useful. I will review it once more and see if I'm missing something.

With respect to the initializers, I followed your recommendation:
``` python
    rec = content.storageResourceManager.RecommendDatastores()
    rec.storageSpec = storagespec
```
But got the following:
```
    rec = content.storageResourceManager.RecommendDatastores()
  File "build/bdist.macosx-10.9-x86_64/egg/pyVmomi/VmomiSupport.py", line 566, in <lambda>
  File "build/bdist.macosx-10.9-x86_64/egg/pyVmomi/VmomiSupport.py", line 374, in _InvokeMethod
  File "build/bdist.macosx-10.9-x86_64/egg/pyVmomi/VmomiSupport.py", line 892, in CheckField
TypeError: Required field "storageSpec" not provided (not @optional)
```
Looking at https://github.com/vmware/pyvmomi/blob/master/docs/vim/StorageResourceManager.rst it seems that it ```RecommendDatastores``` needs to be initialized with ```storageSpec``` set to ```storagespec``` in my case.

**Comment by hartsock** [comment]
@jm66 it appears I may be just plain wrong about the builder thing.

**Comment by hartsock** [comment]
This is odd ... according to [official documentation](http://pubs.vmware.com/vsphere-55/index.jsp#com.vmware.wssdk.apiref.doc/vim.StorageResourceManager.html#recommendDatastores) ... `RecommendDatastores` is a **method** call.

Okay, so that means ...

`rec = content.storageResourceManager.RecommendDatastores(storagespec)`

... should work and if it does then I'm guilty of *over thinking* things.

**Comment by jm66** [comment]
No worries - I'll keep digging. For now, I've found a workaround which is not elegant but at least solves the problem. I can get the recommended datastore object from ```rec``` provided by ```storageResourceManager.RecommendDatastores(storagespec) ``` so I can use it to create the vm using ```vim.Folder.CreateVM_Task```. 

Yeah, I know, it's not an elegant solution and will keep investigating.

**Comment by hartsock** [comment]
@jm66 if you do find something nice (or even if you don't) I'm serious about the sample. I would like to float up some of these to possibly help with future API designs for whomever is doing that on the release for vSphere after this one.

**Comment by jm66** [comment]
Sure @hartsock , will share it. Good new (I think): I've analyzed many logs and found something quite interesting. I have the feeling the problem is related to vCenter:
```
mem> 2015-02-10T14:31:59.045-05:00 [00824 verbose 'Default' opID=31b2d03d] [VpxVmomi] Invoking [applyRecommendation] on [vim.StorageResourceManager:StorageResourceManager] session [c80cde73-1930-8549-e443-343dd5418235(52dc70dc-d131-761a-2a9c-7e88c627d28c)]
mem> 2015-02-10T14:34:52.766-05:00 [00824 panic 'Default' opID=31b2d03d] (Log recursion level 2) Win32 exception: Access Violation (0xc0000005)
mem> -->    Read (0) at address 0000000000000028
mem> -->    rip: 0000000140e5cd77 rsp: 0000000018d0e850 rbp: 0000000000000028
mem> -->    rax: 000000004fa09320 rbx: 000000004f9fd230 rcx: 000000004fa04af0
mem> -->    rdx: ffffffffffffc2b0 rdi: 000000004fa09320 rsi: 0000000018d0e950
mem> -->    r8:  0000000000000000 r9:  0000000000000000 r10: 0000000002a07fd0
mem> -->    r11: 000000004fa04af0 r12: 000000003f11bec0 r13: 000000005301a6b0
mem> -->    r14: 000000004be06290 r15: 000000003f8918a0
mem> --> 

------ In-memory logs end   --------
2015-02-10T14:34:52.766-05:00 [00824 panic 'Default' opID=31b2d03d] Section for VMware VirtualCenter, pid=4308, version=5.5.0, build=2183111, option=Release
--> 
2015-02-10T14:34:52.772-05:00 [00824 info 'vpxdvpxdSupportManager' opID=31b2d03d] Wrote uptime information
```

Opening a support case now.

**Comment by fpaillot** [comment]
Hi,
I have so code that works well with create.

Be careful, StoragePlacementSpec, need a host object...

storageSpec = vim.storageDrs.StoragePlacementSpec(type='create',
                                                    configSpec = config_sdrs,
                                                    resourcePool = resource_pool,
                                                    host = target_host,
                                                    podSelectionSpec = podSpec,
                                                    folder = vm_folder)

result = content.storageResourceManager.RecommendDatastores(storageSpec=storageSpec)
result_key = result.recommendations[0].key

task =content.storageResourceManager.ApplyStorageDrsRecommendation_Task(result_key)
tasks.wait_for_tasks(service_instance, [task])

**Comment by lingfish** [comment]
It would be nice if a complete example was contributed for this - I'm struggling to get my head around it too.
