### ISSUE TITLE
[Feature Request] Implement loginBySSPI for SAML PKI authentication

### ISSUE THREAD

**Issue by kellerkind** [vmware/pyvmomi#214]
It would be great to implement this in pyvmomi. There's a python module at [GitHub](https://github.com/onelogin/python-saml) which would help accomplishing this task!

**Comment by michaelrice** [comment]
I can see one issue with that module if its dependencies section is correct. It says 2.7, and right now we have to maintain 2.6, 2.7, and various version of 3.x support. This is a good place to start though, if it doesnt support all of those versions maybe it wouldnt take too much to add support for them..

**Comment by DanielDraganov** [comment]
SAML token authentication is added in https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1
