### ISSUE TITLE
will VAIO be part of the pyVmomi 6.0 release?

### ISSUE THREAD

**Issue by strongliang** [vmware/pyvmomi#216]
It's probably a yes but I'd just like to confirm it

**Comment by hartsock** [comment]
I won't likely have it in the public version for [2015.1](https://github.com/vmware/pyvmomi/milestones/pyVmomi%202015.1) but we *might* have it by [2015.2](https://github.com/vmware/pyvmomi/milestones/pyVmomi%202015.2) this project is asynchronous of the main vCenter release schedule which normally means we probably lag by about 6 months. Also, remember this is a [fling](https://labs.vmware.com/about) so we aren't under the official support umbrella.

That's about as precise an answer as I can give at this time. We'll get more solid on plans as we get deeper into 2015. I hope to cut more than 2 releases this year and try and make the differences between releases smaller.

**Comment by hartsock** [comment]
NOTE: There is a private licensed version of pyVmomi that you can obtain and that one has a different feature set from this one.

**Comment by hartsock** [comment]
@strongliang it will be inside your vCenter appliance or server. You will have to discuss that with your partner developer channels as that's a wholly different license.
