### ISSUE TITLE
VirtualDisk's capacityInKB attribute is deprecated in vSphere API 5.5 but is a required field in pyVmomi

### ISSUE THREAD

**Issue by synthead** [vmware/pyvmomi#218]
In the [VMware vSphere API 5.5 spec for VirtualDisk](http://pubs.vmware.com/vsphere-55/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.device.VirtualDisk.html), it states:

> Deprecated. As of vSphere API 5.5, use capacityInBytes.
> Capacity of this virtual disk in kilobytes. Information might be lost when actual disk size is rounded off to kilobytes.

Currently, I have this bit of code in a script:

    disk = pyVmomi.vim.vm.device.VirtualDisk()
    ...
    disk.capacityInKB = int(1048576 * size)  # 1 GiB == 1048576 KiB.

But when I replace `.capacityInKB` with `.capacityInBytes`, like so...

    disk = pyVmomi.vim.vm.device.VirtualDisk()
    ...
    disk.capacityInBytes = int(1073741824 * size)  # 1 GiB == 1073741824 B.

... the vSphere Web Client's Task Console reports a bit of an ambiguous error (device 0 being my disk):

> Invalid configuration for device '0'.

In poking around, I saw that when I create a VirtualDisk object using `.capacityInKB`, the object looks like this:

    (vim.vm.device.VirtualDisk) {
       ...
       capacityInKB = 1048576,
       capacityInBytes = <unset>,
    },

...and in creating a VirtualDisk object using `.capacityInBytes`, the object looks like this:

    (vim.vm.device.VirtualDisk) {
       ...
       capacityInKB = 0,
       capacityInBytes = 1073741824,
    },

In an attempt to create a workaround, I tried to set `.capacityInKB` to `None`, and this traceback appeared:

    ...
    /usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py in __setattr__(self, name, val)
        521 
        522    def __setattr__(self, name, val):
    --> 523       CheckField(self._GetPropertyInfo(name), val)
        524       SetAttr(self, name, val)
        525 
    
    /usr/lib/python3.4/site-packages/pyVmomi/VmomiSupport.py in CheckField(info, val)
        890          # unset items
        891          if not (info.flags & F_OPTIONAL) and info.type is not object:
    --> 892             raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
        893          return
        894       elif info.type is object:
    
    TypeError: Required field "capacityInKB" not provided (not @optional)

**Comment by jeffhu** [comment]
The capacityInKB field is marked deprecated but it is also required which means that a None value cannot be passed for the value.  For now, I suggest continuing to pass a value for capacityInKB which is the value you would pass in capacityInBytes / 1024.

This does seem to make it impractical to actually deprecate the capacityInKB field, but it appears to be a limitation of pyvmomi and how the SOAP API is implemented.
