### ISSUE TITLE
Get Folder in which VM resides

### ISSUE THREAD

**Issue by retooth** [vmware/pyvmomi#221]
Hi,

i'm looking for a way to find the folder in which a VM resides. Something like:

``` python
virtual_machine = si.content.searchIndex.FindByUuid(None, "uuid-string", True, True)
folder = virtual_machine.ParentFolder
```

Does pyVmomi offer a method like this?

**Comment by michaelrice** [comment]
That's less a limitation of pyvmomi and more that of the web services API
that pyvmomi wraps.

I think what you will have to do is something like:

    parent = vm.parent
    Until parent is instance of Folder:
        Parent = parent.parent

Sorry for sloppy pseudo code I'm on my phone right now.

There may be a better way to solve this but that's all that is coming to
mind right now.

**Comment by retooth** [comment]
It states [here](https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.VirtualMachine.html):

> The parent of a virtual machine must be a folder, and a virtual machine has no children.

So

````python
vm.parent
````

will give me the folder?

**Comment by jm66** [comment]
@michaelrice totally right.
```python
vm_obj.parent
'vim.Folder:group-v4705'

vm_obj.parent.name
'foldername'
```

**Comment by retooth** [comment]
great! thanks, guys

**Comment by michaelrice** [comment]
I was thinking that if the VM was part of a Vapp the parent would be the
Vapp. You might check that just to be sure.
