### ISSUE TITLE
Why there is no attribute for UplinkPortOrderPolicy to select unused uplink ? 

### ISSUE THREAD

**Issue by reubenur-rahman** [vmware/pyvmomi#222]
Why there is no attribute to select unused uplink ? When we can do the same from client ! Is it by, design or is there any other way to do that ?

The documented API only supports active & standby.

https://github.com/vmware/pyvmomi/blob/f7f7484198ebd96fdad0416fb1aff990ccff99ea/docs/vim/dvs/VmwareDistributedVirtualSwitch/UplinkPortOrderPolicy.rst

**Comment by rreubenur** [comment]
Interesting thing is the POWER CLI reference has documented that.

https://pubs.vmware.com/vsphere-55/index.jsp?topic=%2Fcom.vmware.powercli.cmdletref.doc%2FSet-VDUplinkTeamingPolicy.html

**Comment by DanielDraganov** [comment]
Outdated
