### ISSUE TITLE
Separate pyvcr testing into separate project?

### ISSUE THREAD

**Issue by reedog117** [vmware/pyvmomi#223]
Is there any push to separate the pyvcr-based test harness into a separate project for continuous integration purposes and/or other projects that directly access the vSphere Web Services API? Alternatively, is there some sort of mock vCenter / vSphere WS simulator available online?

I've authored two modules to interface to vSphere Web Services using Node.js, but would like to be able to test using Travis.

[reedog117/node-vsphere](http://github.com/reedog117/node-vsphere)
which depends on 
[reedog117/node-vsphere-soap](http://github.com/reedog117/node-vsphere-soap)

**Comment by michaelrice** [comment]
I do know there is no public facing vcenters that can be used for these kinds of tests. Thats what caused us to use vcrpy 

It would be great to get vmware to put something online like the HOL stuff where something like travis-ci or drone.io or jenkins could send some event to spin up a new VCSA in simulator mode so you could run an integration test suite.

**Comment by reedog117** [comment]
I asked the same question on [Reddit](http://www.reddit.com/r/vmware/comments/2xwxuw/recommendations_for_vsphere_web_services_sdk/) and was pointed towards the [VCSIM](http://www.virtuallyghetto.com/tag/vcsim) capability that is actually baked into vCenter. Time-permitting I may cobble together a project that automatically spins one of them up in a vSphere environment.

**Comment by michaelrice** [comment]
@reedog117 Thats what I use. I have a simple script for 5.5 I use in Fusion to spin them up and down.

**Comment by hartsock** [comment]
@reedog117 I did start in on [pyVIT](https://github.com/hartsock/pyvmomi-integration-tests) but it's just a sketch. I have limited bandwidth and there was limited interest at the time. The use of `VCSIM` is a fairly good option if you have the right hosting environment. The `vcrpy` option is limited but extremely light weight and portable... *however* it is a bit brittle. That is, you can't alter the test by much without having to rebuild the recording. That brittle nature is enough to strike out the idea of a `vcrpy` based test harness for some use-cases. 

Feel free to reopen the ticket if `VCSIM` doesn't fit your needs. If there's enough interest and volunteer effort we might decide to relaunch a new `pyVIT` project.
