### ISSUE TITLE
'NoneType' object has no attribute 'objects' in StubAdapterAccessorMixin.InvokeAccessor

### ISSUE THREAD

**Issue by mpietrek** [vmware/pyvmomi#227]
It looks like code in InvokeAccessor isn't checking that RetrievePropertiesEx returned something non-None 'result" before trying to use it:

```
  result = self._pc.RetrievePropertiesEx(specSet=[filterSpec],
                                         options=self._pcType.RetrieveOptions(maxObjects=1))
  objectContent = result.objects[0]
```

Here's the call stack, FWIW:

[...calling code...]
    hostinfo['health_status'] = hostMor.overallStatus
  File "/usr/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 560, in **call**
    return self.f(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 383, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1574, in InvokeAccessor
    raise e

**Comment by stoer** [comment]
I get the same error message when trying the following code:
```
cluster = vim.ClusterComputeResource(moid)
cluster.resourcePool
*** AttributeError: 'NoneType' object has no attribute 'InvokeAccessor'
```
When I am using the viewManager to get the cluster, everything is working fine..

**Comment by hartsock** [comment]
`cluster = vim.ClusterComputeResource(moid)`

That shouldn't work since you're trying to make a server-side object locally. Pyvmomi runs in clients and these are server managed objects so you have to ask the server for the object to work with...

Example:

```
       si = connect.Connect(host='my_host_with_clusters', pwd='my_root_password',
                                   sslContext=mySslContext)
        results = [item for item in si.content.viewManager.CreateContainerView(
            si.root_folder, [vim.ClusterComputeResource], recursive=True
        ).view]
        for cluster in results:
            print(cluster.resourcePool.summary.name)
```

... will work perfectly fine.
