### ISSUE TITLE
Cluster names containing spaces are not returned

### ISSUE THREAD

**Issue by nmadhok** [vmware/pyvmomi#228]
##### Here's what I'm doing:
```
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from pyVim.connect import SmartConnect
>>> from pyVmomi import vim
>>> si = SmartConnect(host='vcenter01.domain.com', user='myusername', pwd='mypassword')
>>> inv = si.RetrieveContent()
>>> data_centers = {}
>>> clusters = []
>>> for object in inv.rootFolder.childEntity:
...     if hasattr(object, 'vmFolder'):
...         datacenter = object.name
...         for cluster in object.hostFolder.childEntity:
...             clusters.append(cluster.name)
...         data_centers[datacenter] = clusters
...  
>>> print data_centers
{'Datacenter1': ['Development', 'Monitoring', 'Prod'], 'Datacenter2': ['Development', 'Monitoring', 'Prod']}
```

##### Output Received:
```
{'Datacenter1': ['Development', 'Monitoring', 'Prod'], 'Datacenter2': ['Development', 'Monitoring', 'Prod']}
```

##### Expected Output:
```
{'Datacenter1': ['Development', 'Development - R610', 'Monitoring', 'Prod', 'Problems - R610'], 'Datacenter2': ['Development', 'Development - R610', 'Monitoring', 'Prod', 'Problems - R610']}
```

As you can see that I did not get back the following clusters that contained space in their name:
```
Development - R610
Problems - R610
```

##### Versions:
Running vCenter Server 5.5
```
root@nitin-salt-develop:~$ pip show pyVmomi
---
Name: pyvmomi
Version: 5.5.0.2014.1.1
Location: /usr/lib/python2.6/site-packages
Requires: requests, six
```
```
root@nitin-salt-develop:~$ pip show requests six
---
Name: requests
Version: 2.3.0
Location: /usr/lib/python2.6/site-packages
Requires: 
---
Name: six
Version: 1.9.0
Location: /usr/lib/python2.6/site-packages
Requires: 
```

**Comment by purple4reina** [comment]
To get all cluster names I use CreateContainerView and it works fine.

    objView = si.content.viewManager.CreateContainerView(
         si.content.rootFolder, [pyVmomi.vim.ClusterComputeResource], True
    )
    clusters = objView.view
    objView.Destroy()

**Comment by hartsock** [comment]
So, can you make a recording of your HTTP transactions and post some of those messages for us? Here's how you set up a python script to [record](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/hello_world_vcenter_with_yaml_recorder.py#L80) its HTTP conversations to a YAML file. This can be very helpful in diagnosing whether the trouble occurs in our XML parser or in vCenter.

There are also possible issues with implicit hierarchies. If the `'Development - R610'` resource pool ... or folder or whatever it is ... is nested under another folder, container, resource pool, or whatever it is ... then you won't see them at the top level, you'll have to navigate to them.

The various UI may hide this. And you may have to check the data types that you are listing through. A cluster for example may exist inside an implicit resource pool that may not be explicitly named. If you query directly for the data type or you [recursively](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getallvms.py#L82) navigate your inventory ... you may yet see them.

**Comment by rreubenur** [comment]
There is a bug in your code ! Put the clusters list inside the for loop.

```
    data_centers = {}
    for object in content.rootFolder.childEntity:
        clusters = []
        if hasattr(object, 'vmFolder'):
            datacenter = object.name
            for cluster in object.hostFolder.childEntity:
                clusters.append(cluster.name)
            data_centers[datacenter] = clusters
```

**Comment by nmadhok** [comment]
@rreubenur I don't know how that bug is related to the space issue but actually space in the cluster name is the issue. I wanted the complete list of clusters that's why I'm not resetting ``cluster = []`` for every datacenter.

**Comment by nmadhok** [comment]
@purple4reina Thanks for the example. I will try it and see if it works better.

**Comment by nmadhok** [comment]
@hartsock Thanks for letting me know how to record the HTTP transactions. I will soon record them and post it on this issue.

**Comment by hartsock** [comment]
@nmadhok I assume that this turned out well?

**Comment by nmadhok** [comment]
@hartsock I did it another way. Couldn't figure out what was wrong in this way.
