### ISSUE TITLE
Keep Alive sessions?

### ISSUE THREAD

**Issue by dnaeon** [vmware/pyvmomi#23]
Hi,

How can we have a Keep-Alive session to a vSphere host using pyvmomi?

Thanks,
Marin

**Comment by mygoda** [comment]
@hartsock i use eventlet and everytime make a simple call to vcenter server let session alive，and i see session is alive but that vcenter server memory uasge go down until server can not do anything，i want know why？

**Comment by hartsock** [comment]
This sounds like a completely different conversation. Perhaps you should ask it separately. Also, I don't know enough to make an intelligent response.

Have you tried checking current time on the vSphere server via the vSphere API repeatedly via an eventlet event? Does that help?

**Comment by mygoda** [comment]
@hartsock  hi，that problem i did not know about， maybe eventlet。so i make a simple method that i give up make simple call to let session alive。 now when things come， i make a connection， thing down， disconnect， so i see vcenter memory down 。but another problem come in，that make a connect cost more time，when vcenter platform grow, that time cost more。 i want to know how can i reduce connect time

**Comment by hartsock** [comment]
@mygoda please open a different thread. This comment is off topic. @tianhao64 is the new VMware contact point but I feel that you're asking questions about performance characteristics a that are a bit beyond what we can address from the python language binding. If you're not able to get help from https://www.vmware.com/support/vsphere then we probably should talk and think about why that is in a different forum.

Thanks.

**Comment by Gerardwx** [comment]
A python3 solution:
` 
  class KeepAlive(threading.Thread):
    """Class to keep service instances from going stale"""
    
    object_count = 1
    """Counter for generate thread names"""
    
    def __init__(self,service_instance,sleep_time_seconds:int=600):
        """Create daemon thread to keep service instance alive
        @param service_instance: 
        @param sleep_time_seconds: how long to wait between keep alive access
        """
        super( ).__init__()
        self.service_instance = service_instance
        self.daemon = True
        self.name = "ServiceInstance-KeepAlive-{:d}".format(KeepAlive.object_count)
        KeepAlive.object_count =  KeepAlive.object_count + 1
        
        
    def run(self):
        """access something, sleep until next time"""
        self.service_instance.content.sessionManager.currentSession.key
        time.sleep(self.sleep_time_seconds)`

**Comment by hartsock** [comment]
@tianhao64 

The only comment I might have here is that there is some merit to using the get current time method instead.
