### ISSUE TITLE
UnboundLocalError: local variable 'obj' referenced before assignment in SoapAdapter.py when using VimSessionOrientedStub

### ISSUE THREAD

**Issue by sduehr** [vmware/pyvmomi#239]
When using VimSessionOrientedStub like this:
import pyVmomi
from pyVmomi import vim
from pyVmomi import vmodl
from pyVim.connect import SmartConnect, Disconnect
from pyVmomi import vmodl
from pyVmomi import SoapStubAdapter
from pyVim.connect import VimSessionOrientedStub
soapStub = SoapStubAdapter(host=args.host, ns="vim25/5.5")
sessionStub = VimSessionOrientedStub(soapStub,
   VimSessionOrientedStub.makeUserLoginMethod(args.user, password))
si = vim.ServiceInstance("ServiceInstance", sessionStub)

After waiting 35min, so the connection will become invalid by idle timeout, the next request produces:

Sleeping 35 min...
Done sleeping 35 min...
Wed Apr 22 12:24:21 2015
Traceback (most recent call last):
  File "./relogin_test2.py", line 152, in <module>
    main()
  File "./relogin_test2.py", line 133, in main
    for child in content.rootFolder.childEntity:
  File "/usr/lib/python2.6/site-packages/pyVmomi/VmomiSupport.py", line 560, in **call**
    return self.f(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/pyVmomi/VmomiSupport.py", line 383, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/lib/python2.6/site-packages/pyVmomi/SoapAdapter.py", line 1575, in InvokeAccessor
    return obj
UnboundLocalError: local variable 'obj' referenced before assignment

This is using python-pyvmomi-5.5.0.2014.1.1-3.el6.noarch.rpm from EPEL.

The following patch fixes it:

--- SoapAdapter.py.orig 2014-08-26 18:01:09.000000000 +0200
+++ SoapAdapter.py  2015-04-23 08:31:02.400729023 +0200
@@ -1570,6 +1570,8 @@
             if isinstance(e, self.SESSION_EXCEPTIONS):
                # Our session might've timed out, change our state and retry.
                self._SetStateUnauthenticated()
-               retriesLeft -= 1
-               continue
           else:
              raise e
        return obj

On Git Master the patch would be:

diff --git a/pyVmomi/SoapAdapter.py b/pyVmomi/SoapAdapter.py
index 71fd2e5..8fb9441 100644
--- a/pyVmomi/SoapAdapter.py
+++ b/pyVmomi/SoapAdapter.py
@@ -1569,6 +1569,8 @@ class SessionOrientedStub(StubAdapterBase):
             if isinstance(e, self.SESSION_EXCEPTIONS):
                # Our session might've timed out, change our state and retry.
                self._SetStateUnauthenticated()
-               retriesLeft -= 1
-               continue
           else:
              raise e
        return obj

**Comment by hartsock** [comment]
* I believe this is a class of session management related bugs introduced by auto-reconnect features
* The normal session timeout is 30 minutes
  * to counter the timeout we often advise the use of a [KeepAlive thread](https://github.com/vmware/pyvmomi/issues/23)
* This is a general enhancement and usability issue in the vSphere API (IMHO) that I keep seeing pop up in long-running automations and daemon related projects because certain commands require setup in the user session to execute properly.

**Comment by sduehr** [comment]
Looks like this was fixed, and keepalive seems to be a good idea anyway.
