### ISSUE TITLE
No docs or examples to show how to remove a host

### ISSUE THREAD

**Issue by nmadhok** [vmware/pyvmomi#240]
There is no docs available on how to remove a host from a Cluster. There is a function AddHost but no function for removing the host.

**Comment by michaelrice** [comment]
With the hostsystem you can do a destroy task on it.

**Comment by nmadhok** [comment]
Is destroy task the same as doing a remove Host task from the vcenter UI?

**Comment by michaelrice** [comment]
To find out exactly what happens when you do that in the UI I would suggest
using onyx to see for sure.

I have some code that does all this I can share when I get home later
tonight.

**Comment by michaelrice** [comment]
Hi @nmadhok this is groovy code that uses [yavijava](https://github.com/michaelrice/yavijava) but here is how I do it: https://gist.github.com/michaelrice/1ed5f2d8c352cf14c996

**Comment by nmadhok** [comment]
@michaelrice Thanks for the code snippet!
