### ISSUE TITLE
ipv6 connect to ESXi 

### ISSUE THREAD

**Issue by JigarBhatt03** [vmware/pyvmomi#244]
I am trying to  connect to the esx host using the ipv6 address in connect.smartconnect() but was unable to do and got below error

requests.exceptions.InvalidURL: Failed to parse: xxxx:x:xxx:xxxx::xxx:xxx

**Comment by hartsock** [comment]
I would like this verified with a unit test. If we can verify it, I would classify this high priority to fix ASAP. There's no special tools needed here, so anyone could make a patch for this.

**Comment by JigarBhatt03** [comment]
I went through the code and got the patch for it. We need to add square bracket [] in the url having ipv6 in method  __GetServiceVersionDescription(protocol, server, port, path) in connect.py at line no 433.

 url = "%s://[%s]:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)

But adding [] in url will create issue for ipv4. So we need to parse the ip and then set the url based on it.

**Comment by michaelrice** [comment]
seems like a simple

````python
if '.' not in server:
    url = "%s://[%s]:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)
else:
    url = "%s://%s:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)
```
Should work right? ipv6 is colon separated vs the dot notation in ipv4

**Comment by michaelrice** [comment]
Actually that wouldnt work because simple hostnames would fail.. What about this though

```python
import socket

try:
    socket.inet_pton(socket.AF_INET6, server)
    url = "%s://[%s]:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)
# I hate to go broad here but py3 raises an OSError
# and py2 does socket.error
except:
    url = "%s://%s:%s/%s/vimServiceVersions.xml" % (protocol, server, port, path)
```
I tried to write a test for this but Im an utter network failure and have no idea where to start to get ipv6 stuff

**Comment by JigarBhatt03** [comment]
Thanks for the workaroung michael (y)
