### ISSUE TITLE
Can't add vm to VmGroup

### ISSUE THREAD

**Issue by blackms** [vmware/pyvmomi#245]
Hello, I'm trying to add Vm to a VmGroup in this way:

    def add_vm_to_vm_group(self, vm, cluster):
        # check if VmGroup Exists
        windows_group = filter(lambda x: x.name == 'Windows',
                               filter(lambda x: x.__class__.__name__ == 'vim.cluster.VmGroup',
                                      cluster.configurationEx.group)
                               )
        spec = vim.cluster.ConfigSpecEx()
        if windows_group:
            operation = "edit"
            vm = vm if type(vm) is list else [vm]
            group_vm = vim.cluster.GroupSpec()
            group_vm.info = windows_group[0]
        else:
            operation = "add"
            vm = []
            group_vm = vim.cluster.GroupSpec()
            group_vm.info = vim.cluster.VmGroup()
        group_vm.operation = operation
        if not windows_group:
            group_vm.info.name = "Windows"
        group_vm.info.vm = vm
        spec.groupSpec.append(group_vm)
        task = cluster.ReconfigureComputeResource_Task(spec, True)
        wait_for_task(task)

It creates the VmGroup and the second time that I run it with the edit operation, the task complete successfully, but the Vm is not inside the group.
Is it wrong the way i do it, or could be it a bug?

**Comment by hartsock** [comment]
Try something like...
```
# assuming you've picked a host in your cluster 
# ... or your cluster has auto placement and host is None.
migrate_task = vm.MigrateVM_Task(
    windows_group, 
    some_host, 
    vim.VirtualMachine.MovePriority.defaultPriority)

wait_for_task(migrate_task)
```

**Comment by blackms** [comment]
Just to clarify, I'm trying to do this via API instead of vCenter:
http://i.imgur.com/MEzD6gM.png

**Comment by hartsock** [comment]
Ah, I needed you to pull up your cluster ...

```
migrate_task = vm.MigrateVM_Task(
    cluster.resourcePool, 
    some_host, 
    vim.VirtualMachine.MovePriority.defaultPriority)
```

... yeah, reading more carefully. That's a good thing.

**Comment by blackms** [comment]
Unfortunately not:
AttributeError: 'vim.cluster.VmGroup' object has no attribute 'resourcePool'

**Comment by hartsock** [comment]
NOTE: cluster object, not cluster.VmGroup ... I'm saying that you should try to move the VM into the resource pool above the group and then let the DRS rules fire and place the VM into the VmGroup. (You don't actually place the VM in the group first.) I meant this as a work-around.

After troubleshooting in IRC here's what I'm thinking are the possibilities

* There's a hidden error state we're not seeing
* The XML generator isn't making the `VmGroup` data object properly
* There's a work-around to the API we've missed

**Comment by blackms** [comment]
As we wrote on IRC, I will try to compare the xml with the one generated by powershell or the one generated from official pyVmomi if it works.

**Comment by blackms** [comment]
The problem was the VM passed.

**Comment by hartsock** [comment]
Glad to see we got it figured out. How did you figure out that the VM was the problem? (That might be nice to document in case someone else finds this ticket and wants to figure things out for themselves.)

Note: This falls under "hidden error state we're not seeing" which was one of my guesses :smile:

**Comment by darkknight2206** [comment]
Please help me , I am also trying to add vm in an existing group but I can't. Please help!!!
