### ISSUE TITLE
How to restore a serviceInstance session

### ISSUE THREAD

**Issue by EB123** [vmware/pyvmomi#250]
Let's say i've opened a python shell, imported the required functions and typed:
"si = SmartConnect(host,user,pwd,port)"
i am now connected.
now i typed:
"si = None"

my session still exists (i've checked "si.content.sessionManager.sessionList" from another connected session), is there any way i can "reconnect" to it?

**Comment by hartsock** [comment]
See the [suds-to-pyvmomi.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/suds-to-pyvmomi.py) and [pyvmomi-to-suds.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/pyvmomi-to-suds.py) for examples on how to hack sessions.

The short answer is: build a new session cookie to connect to the correct session.

**Comment by EB123** [comment]
Thanks!

didn't do exactly like in those examples, but even though I still need to test it a little more it seems to be working fine:

>>> from pyVim.connect import SmartConnect
>>> from pyVmomi import vim, vmodl, SoapStubAdapter
>>> si = SmartConnect(host="esxname",user="root",pwd="pwd",port=443)
>>> print si.content.sessionManager.currentSession.key
770b1afe-d279-aa6f-3716-131afae6477a
>>> pycookie = si._stub.cookie
>>> si = None
>>> print si.content.sessionManager.currentSession.key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'content'
>>> soapStub = SoapStubAdapter(host="esxname", ns="vim25/5.5")
>>> si2 = vim.ServiceInstance("ServiceInstance",soapStub)
>>> si2._stub.cookie = pycookie
>>> print si2.content.sessionManager.currentSession.key
770b1afe-d279-aa6f-3716-131afae6477a

is it pretty much what you meant?

**Comment by zuber7** [comment]
It does not work. I tried to add the following to your example at the end:

```
content = si2.RetrieveContent()
print(content.rootFolder.childEntity)
```

It raises an exception at the print statement - pyVmomi.VmomiSupport.MethodNotFound: (vmodl.fault.MethodNotFound)

**Comment by royling** [comment]
> It does not work. I tried to add the following to your example at the end:
> 
> ```
> content = si2.RetrieveContent()
> print(content.rootFolder.childEntity)
> ```
> 
> It raises an exception at the print statement - pyVmomi.VmomiSupport.MethodNotFound: (vmodl.fault.MethodNotFound)

with the latest version, this works well.
