### ISSUE TITLE
Running program in guest (guest operations)

### ISSUE THREAD

**Issue by alans09** [vmware/pyvmomi#253]
Hi,

 I'm looking for possibility of running program in guest using pyvmomi. Is this possible with current pyvmomi? 
I'm looking for something like:
http://www.doublecloud.org/2012/02/run-program-in-guest-operating-system-on-vmware/

I can't find way how to authenticate myself and than run program.  All I got was guestOperationsManager and then I'm stuck.
vm.si.content.guestOperationsManager

Also there is no documentation on  si.content on the page.

**Comment by tsugliani** [comment]
Hi @alans09,

I wrote a pyvmomi sample here on that topic a few weeks ago: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/execute_program_in_vm.py

Hope this helps !

**Comment by alans09** [comment]
Thank you, this was helpful.. closing this 'problem'
