### ISSUE TITLE
pyvmomi vvols support

### ISSUE THREAD

**Issue by sasilevi** [vmware/pyvmomi#254]
Hi,

I would like to use pyvmomi in our automation infrastructure and i need the ability to add vvols data store. 
Is there a branch that support vcenter 6.0 that i can start using?
Where can i find code samples for adding datastores?

Thanks,
Sasi

**Comment by hartsock** [comment]
I'm soliciting VMware staff for help in creating a 6.0 branch from the master on this github repo.

**Comment by DanielDraganov** [comment]
Outdated
