### ISSUE TITLE
readthedocs.org sphinx documentation broken

### ISSUE THREAD

**Issue by jantman** [vmware/pyvmomi#255]
It appears that the sphinx-generated documentation on readthedocs.org is broken (at least for the "latest" version because the links all point to ``.rst`` URLs instead of HTML.

I.e., on http://pyvmomi.readthedocs.org/en/stable/ the first link "vim.AboutInfo" points to http://pyvmomi.readthedocs.org/en/stable/vim/AboutInfo.rst which is 404; it should point to http://pyvmomi.readthedocs.org/en/stable/vim/AboutInfo.html which is correct.

**Comment by jantman** [comment]
Ok... just thought of something and looked around a bit. It looks like this project just _ins't_ configured for Sphinx documentation, but looks like the 'docs/' directory is just setup to be viewed on GitHub. This is improper for a Python package. I suppose this ticket should either be "please use Sphinx documentation" (ideally autodoc, which would've made doc generation a LOT easier for whoever wrote all this) or "please move the docs out of ``docs/`` so people don't expect them to work like normal Python docs".

**Comment by joshk0** [comment]
I maintain the readthedocs setup, so i'll grab this issue.

**Comment by hartsock** [comment]
Thanks @joshk0 glad to know you're on it.

**Comment by jantman** [comment]
Thanks so much!

**Comment by joshk0** [comment]
Shawn and I just decided to just make the github docs canonical. I nuked the readthedocs project.

PS. @hartsock , I'm not marked as a contributor anymore. I can't close this issue. Help? :)

**Comment by hartsock** [comment]
@joshk0 okee dokee

**Comment by hartsock** [comment]
@joshk0 hmm... is this actually fixed if this ...
    http://pyvmomi.readthedocs.org/en/stable/#
... points to this ...
    http://pyvmomi.readthedocs.org/en/stable/vim/AboutInfo.rst

Do I have privileges to edit any of this or are you still owner @joshk0 ?

**Comment by joshk0** [comment]
I actually nuked the project, but for some reason their cache hasn't purged, and the domain still works. I was going to wait a day or two and check again.

It would be kind of lame if a html page linked to a raw rst file. I think the expectation is that the rst is converted to html, and that's linked from on the master page of objects.

**Comment by jantman** [comment]
This is extremely unfortunate for me, but ok.

The best thing about RTD, or any sphinx-compliant documentation generator, is the intersphinx mapping - this allows one project to link module/class/function names directly to the source project's documentation. I was really hoping to be able to make use of that, as that's how we document our internal projects.

**Comment by hartsock** [comment]
@jantman the docs we have were specifically generated for the GitHub render engine which isn't sphinx. We did have someone looking at doing sphinx docs a while ago but I've not seen the pull request.

**Comment by joshk0** [comment]
I think i actually started it, then backed it out because i committed it to master accidentally. Can we repurpose this as a sphinx ticket? You can look at the old change and see how far i got back then.

**Comment by jantman** [comment]
Ok. It would be nice, but I can't commit to doing it myself, so... thanks for at least taking the time to discuss it. If it gets done, wonderful, if not... oh well. I can always link our docs directly to the GitHub stuff, it's just not auto-updating like intersphinx.

**Comment by joshk0** [comment]
Cool.

BTW, looks like the docs have been purged from the site now.

**Comment by hartsock** [comment]
Okay. @joshk0 do you think we could have someone here post new readthedocs pages (some day in the future) without having to get special permission from you?

**Comment by joshk0** [comment]
The project has been deleted, so anyone is free to create a new one with the same name, as far as I know.

**Comment by hartsock** [comment]
@joshk0 thanks!
