### ISSUE TITLE
MAC address changes when editing a network adapter

### ISSUE THREAD

**Issue by EB123** [vmware/pyvmomi#260]
Hi,
I'm trying to edit a network adapter in order to change to portGroup it's assigned to, but for some reason everytime i'm doing this it also changes the MAC address of this adapter. 
Am i doing anything wrong?

This is the code i'm using (dev is the device i'm changing):
```python
newnicspec = vim.vm.device.VirtualDeviceSpec()
newnicspec.operation = vim.vm.device.VirtualDeviceSpec.Operation.edit
newnicspec.device = vim.vm.device.VirtualVmxnet3()
newnicspec.device.key = dev.key
newnicspec.device.deviceInfo = vim.Description()
newnicspec.device.deviceInfo.label = dev.deviceInfo.label
newnicspec.device.deviceInfo.summary = "DVSwitch: " + newswitch
newnicspec.device.backing = vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo()
newnicspec.device.backing.port = vim.dvs.PortConnection()
newnicspec.device.backing.port.portgroupKey = newpg
newnicspec.device.backing.port.switchUuid = newswitch
newnicspec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()

spec = vim.vm.ConfigSpec(deviceChange = [newnicspec])
task = vm.ReconfigVM_Task(spec)
```

**Comment by jm66** [comment]
Hi, I've seen this. Try not creating a new device, just make refer to the existent device.
```
newnicspec = vim.vm.device.VirtualDeviceSpec()
newnicspec.operation = vim.vm.device.VirtualDeviceSpec.Operation.edit
newnicspec.device = dev
```

**Comment by EB123** [comment]
Seems to be working, Thanks!!

Any chance you can explain why it changed the mac address? I mean, it didnt add a new adapter, just edited the existing one, but still it caused a conflict (i assume) that caused the mac address to be changed.

**Comment by jm66** [comment]
No problem. Yeah, what's actually happening is that you replacing an existing device with ```vim.vm.device.VirtualDeviceSpec() ```so it obtains the new mac address.

**Comment by EB123** [comment]
oh i c... ok, thanks for the explanation.
