### ISSUE TITLE
Is there any way to get a reference to a newly cloned VM?

### ISSUE THREAD

**Issue by afengg** [vmware/pyvmomi#265]
Is there a way to, say, have the clone function return the newly created VM (or at least properties like the Uuid)? I see that the clone function, as it is, doesn't do this, so the only way would be to find it from scratch. Is using a property collector after the cloning is done the fastest way to do this? Thanks.

**Comment by michaelrice** [comment]
When you do a clone vm task:

    This method returns a Task object with which to monitor the operation. 
    The info.result property in the Task contains the newly added VirtualMachine upon success.

**Comment by afengg** [comment]
Thanks @michaelrice !
