### ISSUE TITLE
 InsecurePlatformWarning

### ISSUE THREAD

**Issue by eliuha** [vmware/pyvmomi#267]
pip install --upgrade pyvmomi

ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement pyvmomi (from versions: )
No matching distribution found for pyvmomi

**Comment by DanielDraganov** [comment]
Outdated. Cannot reproduce.
