### ISSUE TITLE
connet vmware 6.0 issue 

### ISSUE THREAD

**Issue by spwangbit** [vmware/pyvmomi#269]
This version to connect exsi6.0 will get this.
 ('Connection aborted.', error(111, 'Connection refused'))
Can any one help?

**Comment by dnaeon** [comment]
Current pyVmomi release should be able to authenticate and connect to a vSphere 6.0 host as well.

What's your version of Python and pyVmomi that you are using?

**Comment by spwangbit** [comment]
Thanks.
My python version is 2.7.3
My pyVmomi version is the latest version from github: releases/ commit a261b54706c9f1b32238e44471d4fffd36833b80
Merge: c99ab20 ebf0f79
Author: Shawn Hartsock <shawn.hartsock@gmail.com>
Date:   Mon Sep 22 12:07:08 2014 -0400

and I try SmartConnect and Connect. But it can works for vSphere 5.5. Is there special paremeters for vSphere 6.0 when connect?

**Comment by tianhao64** [comment]
This should be fixed by 6.0 release.
