### ISSUE TITLE
Example of changing disk mode (persistence) needed!

### ISSUE THREAD

**Issue by leowijnhoven** [vmware/pyvmomi#27]
I tried to change the persistence of a disk using pyVmomi Sdk. But i did not succeed.

Any chance that you can make a example for this?

**Comment by shilpa4** [comment]
i also have same problem can some one help me  to change the persistence of a disk using pyVmomi Sdk...

**Comment by anil9841284912** [comment]
Is this issue solved? Couldn't find the solution anywhere to change NonPersistent into Persistent or vice-versa.

**Comment by hartsock** [comment]
It's still "help wanted" here https://github.com/vmware/pyvmomi-community-samples/issues/42

@tianhao64 ... any updates?

**Comment by tianhao64** [comment]
+ GSS team.

Can someone take a look at this API request/question on github?

Thanks,
Tianhao

**Comment by tianhao64** [comment]
Hi Tianhao and Shawn,

We do not have any ready sample on pyVmomi SDK as of now. Still, I will check in my team if anyone has the sample or can help here.

Thank you.

Regards,
Chetan Patidar
VMware SDK Developer Support

[vmware]
