### ISSUE TITLE
pyVmomi, to clone a VM, how to CreateFolder

### ISSUE THREAD

**Issue by ek-sp** [vmware/pyvmomi#273]
I need to create the folder vm_name and get the object for the 1st argument in CloneVM_Task()
destfolder = vm.parent.CreateFolder(vm_name)  # wrong 
task = template.CloneVM_Task(folder=destfolder, name=vm_name, spec=clonespec)
can someone clarify how to create the destfolder object from a folder to be created to hold the new VM?

**Comment by ek-sp** [comment]
I see in the clone_vm examples destfolder = datacenter.vmFolder
but my datacenter is None

**Comment by DanielDraganov** [comment]
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/create_folder_in_datacenter.py
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/create_vm.py
