### ISSUE TITLE
The specified guest user must be logged in interactively to perform this operation

### ISSUE THREAD

**Issue by alans09** [vmware/pyvmomi#280]
Hello... I have this function (kind of long but it is doing its job):

```
def run_program_in_guest(self, guser, gpasswd, path, arguments=None,
                         interactive=None, wait_for_task=None):
    """ Start program in guest and return exitcode
    :param guser: guest user
    :param gpasswd: guest password
    :param path: path to program
    :param arguments: argumets to program
    :param interactive: shows windows on guest user destktop
    :param wait_for_task: wait until task ends
        if waiting, returns also return code
    :returns: process pid or [process_pid, return_code] < if wait_for_task
        is true
    """
    if self._machine_ready():
        gom = self.si.content.guestOperationsManager
        auth = self._authentication(guser, gpasswd)
        valid = 0
        valid = gom.authManager.ValidateCredentialsInGuest(
            self.template, auth
        )
        if valid is None:
            self.log.info("Credentials %s/%s are ok", guser, gpasswd)
        else:
            raise AssertionError("Credentials %s/%s are BAD!!" % (
                guser, gpasswd)
            )
        self.log.info("Interactive session: %s", interactive)
        if interactive:
            self.log.info("Checking of interactive session on guest")
            if not self._check_interactive_status():
                raise AssertionError("Interactive session is not ready")
            auth.interactiveSession = True
        prog = vim.vm.guest.ProcessManager.ProgramSpec()
        prog.programPath = path
        self.log.info("Program path: %s", path)
        if arguments:
            prog.arguments = arguments
            self.log.info("Arguments: %s", arguments)
        proc_manager = gom.processManager
        pid = proc_manager.StartProgramInGuest(self.template,
                                               auth, prog)
        plist = proc_manager.ListProcessesInGuest(self.template,
                                                  auth, [pid])
        self.log.info("Process id is: %s", pid)
        if wait_for_task:
            while plist[0].exitCode is None:
                if interactive:
                    self.log.info(
                        "Checking of interactive session on guest"
                    )
                    if not self._check_interactive_status():
                        raise AssertionError("Interactive session\
                                             is not ready")
                self.log.info("Process %s is still running", pid)
                plist = proc_manager.ListProcessesInGuest(self.template,
                                                          auth, [pid])
                time.sleep(10)
                self.log.debug("Return object: %s", plist[0])
            return [pid, plist[0].exitCode]
        return pid
```

Problem is that if I run some process on remote machine and than I want to wait for task end I got error:
**The specified guest user must be logged in interactively to perform this operation**

This occurs mainly in _while plist[0].exitCode is None_ part of the code (within cycle).

I found that this occurs when client virtual machine is under heavy load for a few minutes (100% cpu)
It looks like it just 'suspend' vmware tools and I get this error. (I can simulate it by getting machine to 100% cpu and wait few minutes)

**Question is: How it is possible that  VMRUN (vix api) does not fails under given circumstances and pyVmomi have problem with this.**

Or maybe a better question is: **How to check if process still running and wait until it ends?**
(I didn't found any example how to run program and wait until it ends)

Thank you in advance

**Comment by lemke1458** [comment]
You're checking for process state the way we designed it to work.

The error you're getting should only occur if you use interactiveSession, which I suggest never setting unless you really need it.  Its more work for Tools, and I've seen too many cases where there isn't really a logged-in user in automation scenarios (auto-logout kicking in, for example). 

I'm also not surprised that it has issues if the guest is overloaded; VMware Tools has to fight for resources then, and things can time out. Without interactiveSession, you may get a SystemError fault if under heavy load; in that case I suggest just retrying.

VIX shares all the same code, but since it doesn't poll for completion, it won't show the same symptoms.  (VIX also can't deal with migration, and it could hide a lot of things in its client-side, which is part of the reason we went to a poll model for the new APIs.)
