### ISSUE TITLE
I am getting error method not found while calling LookupDvPortGroup(port_group_key)

### ISSUE THREAD

**Issue by Rathore2014** [vmware/pyvmomi#282]
I am using pyVmomi api to automate some of vshpere stuff, we have recently upgragded vspher5.5 to vsphre6.0, then we started seeing error

MethodNotFound: (vmodl.fault.MethodNotFound) { dynamicType = , dynamicProperty = (vmodl.DynamicProperty) [], msg = , faultCause = , faultMessage = (vmodl.LocalizableMessage) [], receiver = 'vim.dvs.VmwareDistributedVirtualSwitch:***', method = 'LookupPortgroup' }

When I looked deeper then realize that it has been thrown from

port_group_obj = dvs.LookupDvPortGroup(port_group_key)

Placing entire code for your reference:

def getvmnics(self, vm): 
    nics = [] 
    host_page_dict = self.get_hosts_port_groups(self.hosts) 
    for dev in vm.config.hardware.device: 
        if isinstance(dev, vim.vm.device.VirtualEthernetCard): 
            dev_backing = dev.backing 
           if hasattr(dev_backing, 'port'): 
              port_group_key = dev.backing.port.portgroupKey 
             dvs_uuid = dev.backing.port.switchUuid 
             try: 
                 dvs = self.content.dvSwitchManager.QueryDvsByUuid(dvs_uuid)
           except: 
                port_group_name = "*\* Error: DVS not found **" 
               vlan_id = "NA" v_switch = "NA" 
         else: 
               port_group_obj = dvs.LookupDvPortGroup(port_group_key) 
               port_group_name = port_group_obj.config.name
               vlan_id = str(port_group_obj.config.defaultPortConfig.vlan.vlanId) 
               v_switch = str(dvs.name) 
    else: 
        port_group_name = dev.backing.network.name 
        vmHost = vm.runtime.host
        # global variable hosts is a list, not a dict 
        hosts = self.get_vm_hosts 
        host_pos = hosts.index(vmHost) 
        viewHost = hosts[host_pos] 
        # global variable hostPgDict stores portgroups per host 
       pgs = host_page_dict[viewHost]
       for p in pgs:
           if port_group_name in p.key: 
               vlan_id = str(p.spec.vlanId) 
               v_switch = str(p.spec.vswitchName) 
     if port_group_name is None: 
        port_group_name = 'NA' 
        nics.append({ 
                          'mac_address': dev.macAddress, 
                          'portGroup': port_group_name, 
                          'nic_number': dev.deviceInfo.label,
                          'vSwitch': v_switch, 'VLan': vlan_id 
              }) 
return nics

**Comment by DanielDraganov** [comment]
Outdated
