### ISSUE TITLE
How do import an exception?

### ISSUE THREAD

**Issue by skuzye** [vmware/pyvmomi#285]
I cannot seem to find in the docs how to correctly import an exception defined in vim.fault.

No matter what I try, I get ImportError: No module named vim.fault or something related.

The exception I need to treat is vim.fault.InvalidLogin. Any pointers? Thanks

**Comment by parthgala** [comment]
The following works for me:

>>> import pyVmomi
>>> from pyVmomi import vim
>>> vim.fault.InvalidLogin
<class 'pyVmomi.VmomiSupport.vim.fault.InvalidLogin'>

**Comment by skuzye** [comment]
Thanks!

**Comment by tthayer** [comment]
Here is an example of it being used:

```
def vsphere_login(_host, _user, _pwd, _port=443):
    try:
        si = SmartConnect(host=_host,
                          user=_user,
                          pwd=_pwd,
                          port=int(_port)
                          )
        atexit.register(Disconnect, si)
        return si
    except vim.fault.InvalidLogin:
        raise SystemExit("Invalid username or password.")
```

**Comment by mechaHarry** [comment]
The import doesn't seem to be working for me today, using python3.8.1 with pyVmomi 7.0.

**Comment by rlaunch** [comment]
Having the same issue too. Cannot find where to import faults from in 7.0

**Comment by mechaHarry** [comment]
This is the latest revision I have in my code, not sure if it will work for others.
```
from pyVmomi import vim
...
except vim.fault.InvalidLogin:
...
