### ISSUE TITLE
Question: What version of Python should be supported from pyvmomi?

### ISSUE THREAD

**Issue by alanrenouf** [vmware/pyvmomi#287]
2 Questions.

Currently pyVmomi 5.5.0-2014.1 and later support Python 2.6, 2.7, 3.3 and 3.4

Looking at the Python 2.6.9 release page which is the last release for Python 2.6 it looks like Python has pulled the maintenance plug (https://www.python.org/download/releases/2.6.9/). 
1. What version of Python is everyone using at the moment to develop with pyvmomi?
2. What is the earliest version you think this project should support and test against?

Thanks

Alan

**Comment by michaelrice** [comment]
I use 2.7.8 to develop. Product varies depending on which host the ops team
is deploying to for my stuff. Its always 2.7.x though.

2.6 is supported. Basically at one time the goal was to keep pyvmomi
supporting what ever versions of python that OpenStack supports.

-mike

**Comment by yashikadeva** [comment]
Openstack has dropped Python 2.6 support.:
https://wiki.openstack.org/wiki/Python3#Python_2:_Python_2.6_support_dropped.2C_Python_2.7_only

**Comment by hugovk** [comment]
I think this issue be closed.

Python 2.6 was dropped from pyvmomi in https://github.com/vmware/pyvmomi/pull/308.
