### ISSUE TITLE
makeCertHokTokenLoginMethod() not used?

### ISSUE THREAD

**Issue by keeely** [vmware/pyvmomi#292]
I'm unsure if what I'm seeing is to be believed, but...

The text "makeCertHokTokenLoginMethod":
- gives only two Google references.
- is only found in copies of connect.py on a search of GitHub.

If nobody in the entire universe (my universe is on the small side, including only Google and Github right now :-)) is using it, it should perhaps be removed?

If it's a WiP then how can we finish it?

Thanks!

**Comment by patilav** [comment]
It's a new method in pyvim 6.0 for login using SAML token. I dont know about other people but I am using it :palm_tree:

**Comment by keeely** [comment]
Any chance you can post some example code? :)
