### ISSUE TITLE
Performance manager not returning values

### ISSUE THREAD

**Issue by DeepikaNR** [vmware/pyvmomi#293]
Hi,

I want to retrieve certain performance metrics from host. 
1. I am using PerformanceManager to retrieve available metrics for a host.
2. Query using a spec.

Although metrics list is obtained, the stats list is empty.
[ Pasted the code from python console]
[There was a valid service instance]
................................................................................................

> > > colo = si.content.searchIndex.FindByIp(None, "10.4.32.50", False)
> > > pm = si.content.perfManager
> > > metrics = pm.QueryAvailablePerfMetric(colo)
> > > query = vim.PerformanceManager.QuerySpec(intervalId=60, entity=colo, metricId=metrics)
> > > stats = pm.QueryPerf(querySpec=[query])
> > > stats
> > > (vim.PerformanceManager.EntityMetricBase) []
> > > query
> > > (vim.PerformanceManager.QuerySpec) {
> > >    dynamicType = <unset>,
> > >    dynamicProperty = (vmodl.DynamicProperty) [],
> > >    entity = 'vim.HostSystem:host-163389',
> > >    startTime = <unset>,
> > >    endTime = <unset>,
> > >    maxSample = <unset>,
> > >    metricId = (vim.PerformanceManager.MetricId) [
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 2,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 6,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 12,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 24,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 85,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 86,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 90,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 98,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 102,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 125,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 133,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 143,
> > >          instance = ''
> > >       },
> > >       (vim.PerformanceManager.MetricId) {
> > >          dynamicType = <unset>,
> > >          dynamicProperty = (vmodl.DynamicProperty) [],
> > >          counterId = 155,
> > >          instance = ''
> > >       }
> > >    ],
> > >    intervalId = 60,
> > >    format = <unset>
> > > }
> > > perf_dict = {} 
> > > perfList = si.content.perfManager.perfCounter
> > > for counter in perfList:
> > > ...     counter_full = counter.groupInfo.key + "." + counter.nameInfo.key + "." + counter.rollupType
> > > ...     perf_dict[counter_full] = counter.key
> > > ... 
> > > counter_name = 'cpu.capacity.usage.average'
> > > counterId = perf_dict[counter_name]
> > > counterId
> > > 17
> > > metricId = vim.PerformanceManager.MetricId(counterId=counterId, instance="*")
> > > query1 = vim.PerformanceManager.QuerySpec(intervalId=20, entity=colo, metricId=[metricId])
> > > stats1 = pm.QueryPerf(querySpec=[query])
> > > stats1
> > > (vim.PerformanceManager.EntityMetricBase) []
> > > ................................................................................................
> > > How is it possible that no counters are returned. Atleast values of ''0L" must be returned. 
> > > Am I missing something?
> > > Can you please help me this?

-- Deepika

**Comment by prziborowski** [comment]
Perhaps try with a different intervalId (I'm not sure what 'colo' is a managed object of).
You can use intervalId's that are over the historic rate (which seem like 300 is the smaller).
Or you can call QueryProviderSummary(entity=colo) and use the refreshRate of that (perhaps 20).
