### ISSUE TITLE
vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated)

### ISSUE THREAD

**Issue by shyamachilles** [vmware/pyvmomi#294]
Hi ,

My environment consists of a SAN attached to ESX host. The vsphere version is 6.0

My python test script imports pyvMomi package support to do the following - 

1. Clone "x" VMs and power them on , in a sequence. "x" is passed as an argument to the test. 
2. Perform IO from each cloned VM to a common datastore provided to test as an argument. 
3. Take Snapshots of each clones and Stop IO.
4. Power off VMS and delete them

This test works good for x <= 26 VMs. I tried to scale upto 30 VMs, and I get the following error in Step 4 while I try to power off them - 

  File "/home/usr/banalas/139895/testSW/lib/ClientHostVMware.py", line 682, in vmPowerOff
    dlog.debug("Powering off " + virtualMachine.name)
  File "/home/usr/banalas/139895/testSW/lib/pyVmomi/VmomiSupport.py", line 560, in __call__
    return self.f(*args, **kwargs)
  File "/home/usr/banalas/139895/testSW/lib/pyVmomi/VmomiSupport.py", line 383, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/usr/banalas/139895/testSW/lib/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [], 
   msg = '', 
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [], 
   object = 'vim.VirtualMachine:vm-1050',
   privilegeId = 'System.View'

The pyvMomi package version is pyvmomi-5.5.0.2014.1.1-py2.7.

Could I know how to overcome this situation?

**Comment by hartsock** [comment]
cc @tianhao64

**Comment by shyamachilles** [comment]
@tianhao64

I still see the issue with the latest pyvmomi code - 

This is how am trying to connect to the vsphere client - 

            self.vmServiceInstance = connect.SmartConnect(protocol="https",
                                                          host=self.fqdn,
                                                          user=self.username,
                                                          pwd=self.password)
            atexit.register(connect.Disconnect, self.vmServiceInstance)

**Comment by tianhao64** [comment]
@shyamachilles , can you try following?
import ssl
connect.SmartConnect(protocol="https",
                                                      host=self.fqdn,
                                                      user=self.username,
                                                      pwd=self.password,
                                                      sslContext=ssl._create_unverified_context())

**Comment by shyamachilles** [comment]
Thanks @tianhao64 Ill keep you posted. Could you please confirm if this is the latest code with issue#194 resolved @ https://github.com/vmware/pyvmomi

**Comment by tianhao64** [comment]
@shyamachilles , yes, make sure you are using the latest version: https://github.com/vmware/pyvmomi/releases/tag/v6.0.0

**Comment by shyamachilles** [comment]
@tianhao64 -  I did download the latest code @ https://github.com/vmware/pyvmomi/releases/tag/v6.0.0
I did pass in sslContext=ssl._create_unverified_context() to connect.SmartConnect
for the test trying to do above steps for 3 - 27 clones, it passes without hitting this issue.
Trying to scale above 27-60 vm clones, the test fails with this error trying to power off Vms before deleting them . Typical stack trace looks like this - 

  File "/home/usr/banalas/139895/testSW/testsrc/VMwareVvol/SnapshotCreationTest/SnapshotCreationTest.py", line 171, in run
    self.cloneAndSnapshotVms(vsphere, vmTemplate, dataStore)
  File "/home/usr/banalas/139895/testSW/testsrc/VMwareVvol/SnapshotCreationTest/SnapshotCreationTest.py", line 305, in cloneAndSnapshotVms
    status, tasks = vsphere.vmPowerOff(vmInfo['vm'], waitForComplete=False)
  File "/home/usr/banalas/139895/testSW/idart/ClientHostVMware.py", line 684, in vmPowerOff
    dlog.debug("Powering off " + virtualMachine.name)
  File "/home/usr/banalas/139895/testSW/idart/pyVmomi/VmomiSupport.py", line 564, in __call__
    return self.f(*args, **kwargs)
  File "/home/usr/banalas/139895/testSW/idart/pyVmomi/VmomiSupport.py", line 384, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/usr/banalas/139895/testSW/idart/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.VirtualMachine:vm-1430',
   privilegeId = 'System.View'
}

The very first VM tring to be offline is hitting this issure. Could you please help..

**Comment by shyamachilles** [comment]
in SoapAdapter.py - CONNECTION_POOL_IDLE_TIMEOUT_SEC defaults to 900 secs.

Can I try increasing the CONNECTION_POOL_IDLE_TIMEOUT_SEC to 3600? I do see inactivity for more than 15 mins (900 secs) on the vcenter once the IO is done and snapshots are deleted. During this inactivity, the test tries to stop IO on the VM clones. This activity takes more time, higher the number of clones.

**Comment by tianhao64** [comment]
@shyamachilles did it work after you increase the timeout setting? You can also disable the timeout by set it to '-1'.

**Comment by shyamachilles** [comment]
It did not work robustly after increasing the timeout/ disabling it. I tried issuing heartbeat less than 15 mins, and it worked. Its great to know the disabling part though. How about making this setting customizable.

**Comment by sofiya07** [comment]
Hi, am still experiencing this issue after cloning 9 VMs, let me know if there is any work around
Traceback (most recent call last):
  File "perf_get_HW_info.py", line 2056, in <module>
    main()
  File "perf_get_HW_info.py", line 2034, in main
    cloneInLoop(printHost,sutList,dt_list,pg_list)
  File "perf_get_HW_info.py", line 1565, in cloneInLoop
    host_id = host.name
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 57                                               4, in __call__
    return self.f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 39                                               4, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/StubAdapterAccessorImpl.p                                               y", line 47, in InvokeAccessor
    raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.HostSystem:host-2978',
   privilegeId = 'System.View'
}
