### ISSUE TITLE
How do I add a vswitch with no network adapters?

### ISSUE THREAD

**Issue by psinghsp** [vmware/pyvmomi#299]
VSphere UI and ESX CLI commands let me do it. But I cannot see how I can pass null to:

vss_spec.bridge = vim.host.VirtualSwitch.BondBridge(nicDevice=[])

I always get an exception that I must provide a nicDevice.

Is there any way to do this with Pyvmomi?

**Comment by michaelrice** [comment]
Can you not provide: ```nicDevice=None``` ?

**Comment by rreubenur** [comment]
If you want to create a vSwitch without a physical NIC then you should not use the optional "bridge" parameter. But if you use bridge parameter then the "nicDevice" param is mandatory for BondBridge spec.

The given below spec should work.

```
    vss_spec = vim.host.VirtualSwitch.Specification()
    vss_spec.numPorts = num_ports
    #vss_spec.bridge = vim.host.VirtualSwitch.BondBridge(nicDevice=['vmnic1'])
    host_network_system.AddVirtualSwitch(vswitchName=vss_name, spec=vss_spec)
```

**Comment by psinghsp** [comment]
Thanks let me try.
