### ISSUE TITLE
VSwitches and promiscuous mode

### ISSUE THREAD

**Issue by psinghsp** [vmware/pyvmomi#300]
I can create a vswitch and a portgroup. I can set security policy for the port group and set the promiscuous mode for it. But if I set the security policy for vswitch, I get an error. Is there a way to set VSwitch promiscuous mode?

```
    vss_spec = vim.host.VirtualSwitch.Specification()
    vss_spec.numPorts = 32
    vss_spec.bridge = vim.host.VirtualSwitch.BondBridge(nicDevice=["vmnic1"])

    # security_policy = vim.host.NetworkPolicy.SecurityPolicy()
    # security_policy.allowPromiscuous = True
    # security_policy.forgedTransmits = True
    # security_policy.macChanges = False
    # vss_spec.policy = vim.host.NetworkPolicy(security=security_policy)

    host_network_system.AddVirtualSwitch(vswitchName=vss_name, spec=vss_spec)
```

**Comment by rreubenur** [comment]
I don't know why it don't work for vss. But it will work if you apply the policy on a port group.

**Comment by rreubenur** [comment]
Please post the questions in pyvmomi-community-samples

**Comment by rreubenur** [comment]
Looks like You have to use "HostVirtualSwitchConfig" . But you have to create the vss first then you can update vss with the security policy using the mentioned config.

You can give a try.

**Comment by jeffreyxie888** [comment]
@rreubenur Can you please explain what you mean by use "HostVirtualSwitchConfig"? I've read the documentation but am still having a difficult time changing my vswitch to have allow promiscuous mode

**Comment by jeffreyxie888** [comment]
@rreubenur PLEASE

**Comment by prziborowski** [comment]
@jeffreyxie888 if you have access to the vswitch config, then this should be relatively easy to do.
```
host = si.content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0]
networkSystem = host.configManager.networkSystem
networkConfig = networkSystem.networkConfig
vswitch0 = networkConfig.vswitch[0]
spec = vswitch0.spec
spec.policy.security.allowPromiscuous = True
networkSystem.UpdateVirtualSwitch(vswitch0.name, spec)
```

For brevity I've just picked the first host of the first datacenter, and the first vswitch out of the list.
The HostVirtualSwitchConfig is: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.VirtualSwitch.Config.html
(and in my above snippet that is what vswitch0 is)

**Comment by jeffreyxie888** [comment]
@prziborowski THANK YOU!!!

**Comment by mizsum** [comment]
I am able to set promiscuous mode on a standard vswitch just like @psinghsp did above. But then once I go back to vSphere Client GUI to verify the change, I see the old settings still in there. I noticed there is an 'override' option. Is this 'override' the reason why the promiscuous mode did not take effect? If so, how do I set this so the GUI reflects the change? Thanks for help!

**Comment by ckotte** [comment]
@mizsum Do you use the exact same code? I get "A specified parameter was not correct" all the time..

**Comment by mizsum** [comment]
> @mizsum Do you use the exact same code? I get "A specified parameter was not correct" all the time..

No, I am not using this same code.

**Comment by ckotte** [comment]
Ok. I got it. You need to set every parameter if you want to configure one of the policies on a standard switch. If you forgot a single parameter or have a wrong value, you will get Invalid Argument without any hint what the error could be...

This sample code works for me:
```
vss_spec = vim.host.VirtualSwitch.Specification()
vss_spec.numPorts = 64  # 128 works as well
vss_spec.bridge = vim.host.VirtualSwitch.BondBridge()
vss_spec.bridge.nicDevice = ['vmnic6', 'vmnic7']
# vss_spec.bridge.beacon = vim.host.VirtualSwitch.BeaconConfig()
# vss_spec.bridge.beacon.interval = 1
# vss_spec.bridge.linkDiscoveryProtocolConfig = vim.host.LinkDiscoveryProtocolConfig()
# vss_spec.bridge.linkDiscoveryProtocolConfig.protocol = 'cdp'
# vss_spec.bridge.linkDiscoveryProtocolConfig.operation = 'listen'
# vss_spec.mtu = 9000
vss_spec.policy = vim.host.NetworkPolicy()
vss_spec.policy.security = vim.host.NetworkPolicy.SecurityPolicy()
vss_spec.policy.security.allowPromiscuous = False
vss_spec.policy.security.forgedTransmits = False
vss_spec.policy.security.macChanges = False
vss_spec.policy.offloadPolicy = vim.host.NetOffloadCapabilities()
vss_spec.policy.offloadPolicy.tcpSegmentation = True
vss_spec.policy.offloadPolicy.zeroCopyXmit = True
vss_spec.policy.offloadPolicy.csumOffload = True
vss_spec.policy.shapingPolicy = vim.host.NetworkPolicy.TrafficShapingPolicy()
vss_spec.policy.shapingPolicy.enabled = False
# vss_spec.policy.shapingPolicy.enabled = True
# vss_spec.policy.shapingPolicy.averageBandwidth = 100000 * 1000
# vss_spec.policy.shapingPolicy.peakBandwidth = 100000 * 1000
# vss_spec.policy.shapingPolicy.burstSize = 102400 * 1024
vss_spec.policy.nicTeaming = vim.host.NetworkPolicy.NicTeamingPolicy()
vss_spec.policy.nicTeaming.notifySwitches = True
vss_spec.policy.nicTeaming.rollingOrder = False
# Default values
vss_spec.policy.nicTeaming.failureCriteria = vim.host.NetworkPolicy.NicFailureCriteria()
vss_spec.policy.nicTeaming.failureCriteria.fullDuplex = False
vss_spec.policy.nicTeaming.failureCriteria.percentage = 0
vss_spec.policy.nicTeaming.failureCriteria.checkErrorPercent = False
vss_spec.policy.nicTeaming.failureCriteria.checkDuplex = False
vss_spec.policy.nicTeaming.failureCriteria.checkBeacon = False
vss_spec.policy.nicTeaming.failureCriteria.speed = 10
vss_spec.policy.nicTeaming.failureCriteria.checkSpeed = 'minimum'
vss_spec.policy.nicTeaming.nicOrder = vim.host.NetworkPolicy.NicOrderPolicy()
vss_spec.policy.nicTeaming.nicOrder.activeNic = ['vmnic6', 'vmnic7']
vss_spec.policy.nicTeaming.nicOrder.standbyNic = []
vss_spec.policy.nicTeaming.policy = 'loadbalance_srcid'
vss_spec.policy.nicTeaming.reversePolicy = True
network_mgr = self.host_system.configManager.networkSystem
network_mgr.UpdateVirtualSwitch(vswitchName=self.switch, spec=vss_spec)
```

Beacon, LDP, and MTU doesn't need to be set. Everything else needs to be set.
