### ISSUE TITLE
Creating a NIC adapter and adding to vswitch

### ISSUE THREAD

**Issue by psinghsp** [vmware/pyvmomi#301]
When create a new NIC card for a guest, the code looks like:

```
    nicspec = vim.vm.device.VirtualDeviceSpec()
    nicspec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    nicspec.device = vim.vm.device.VirtualVmxnet3()
    nicspec.device.addressType = 'generated'
    nicspec.device.wakeOnLanEnabled = True
    nicspec.device.unitNumber = 9
    nicspec.device.controllerKey = 100 
    nicspec.device.key = 4000
```

My question is about last three magic numbers. It seems like I have to make sure that they are unique for a guest. Is it possible to omit them and the API to assign them unique numbers?

**Comment by rreubenur** [comment]
Except key the remaining two are not mandatory. Please go through the doc.

**Comment by rreubenur** [comment]
Please post the questions in pyvmomi-community-samples

**Comment by psinghsp** [comment]
Thanks. But if you take a look at this command on ESX, it wants a unit number - but not key or controller key. Does that make unitNumber manadatory?

~ # vim-cmd vmsvc/devices.createnic
Insufficient arguments.
Usage: devices.createnic vmid unit number type network

Add a NIC to this virtual machine.

**Comment by jm66** [comment]
Hi @psinghsp,

Don't need the unitNumber, controllerKey and key. Those should be generated when executed.
