### ISSUE TITLE
Copy File to/from VM get URL Error: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by tobyfan1980** [vmware/pyvmomi#302]
I am trying to copy file to/from VM. I used InitiateFileTransferFromGuest, which return a url like 'https://*:443/guestFile?id=10&token=xxxxxxxxxx'.  

Then I called requests.get(url) but not got any luck, always the same error :<urlopen error [Errno 8] nodename nor servname provided, or not known>

Here is my code:

vm = get_obj(content, [vim.VirtualMachine], vm_name)
creds = vim.vm.guest.NamePasswordAuthentication(username=vm_username, password=vm_password)
fileinfo = content.guestOperationsManager.fileManager.InitiateFileTransferFromGuest(vm, creds, vm_filepath )
resp = requests.get(fileinfo.url, verify=False)

**Comment by rreubenur** [comment]
Replace the ```*``` in the url with your ESXi host IP. You don't have to do this if you directly connect to vCenter Server

**Comment by tobyfan1980** [comment]
Got it. Since I connected to the host not vCenter, I need to replace * with host ip. 

Thanks, rreubenur.
