### ISSUE TITLE
How to delete a disk from a vm

### ISSUE THREAD

**Issue by psinghsp** [vmware/pyvmomi#303]
Hi

I looked at the sample to add a disk to a vm. I want to do opposite. Does anyone have a sample for that? I tried modifying the "add sample" by changing the operation to "remove" and setting the unitNumber in the diskSpec to delete the one I want - but I keep getting errors.

**Comment by jm66** [comment]
HI @psinghsp ,

Try adding the actual object in 

```
```

**Comment by gm0neyl0ve** [comment]
This is the function I use to delete:

```
def delete_disk(dst_disk):
    try:
        diskManager = content.virtualDiskManager
        task = diskManager.DeleteVirtualDisk_Task( name = dst_disk, datacenter = dc)

        while task.info.state in [vim.TaskInfo.State.queued, vim.TaskInfo.State.running]:
            print('.', end='')
        print('Done.')
        print('')
        return
    except vmodl.MethodFault as error:
        print ('Caught vmodl fault : ' , error.msg)
        return -1
```

Where 'dst_disk' is the path to the vmdk [Datastore] vmname\vmname-file.vmdk

**Comment by dinis-cruz-gw** [comment]
@gm0neyl0ve thanks, that worked like a charm :+1:
