### ISSUE TITLE
Any objections if we drop python 2.6 support for vphere 6.0 release?

### ISSUE THREAD

**Issue by tianhao64** [vmware/pyvmomi#306]
Since openstack has dropped python 2.6 support: https://wiki.openstack.org/wiki/Python3#Python_2:_Python_2.6_support_dropped.2C_Python_2.7_only
We plan to drop 2.6 support for pyVmomi too for the 6.0 release. Please let me know if you have any objections.

Thanks,
Tianhao

**Comment by shay-berman** [comment]
No

BTW pyvmomi will support vsphere 6?

**Comment by michaelrice** [comment]
My only concern with it would be when I package it for Fedora and EPEL we would be having to drop support for RHEL 6. I do not use that personally but I do currently publish packages for Fedora 21-Devel and EPEL 6 & 7 https://admin.fedoraproject.org/pkgdb/package/python-pyvmomi/

**Comment by tianhao64** [comment]
@shay-berman Yes, the new version should be available in a couple of days.

**Comment by tianhao64** [comment]
@michaelrice Thanks Michael. Do you think it worth to continue support those version/packages? The reason I am asking is that we do need to include some special handler/fixes just for 2.6 in the new release. I am trying to assess if it worth the effort.

**Comment by michaelrice** [comment]
@tianhao64 personally and professionally Im not a fan of having to worry about python  2.6. Lots of our samples wont work on 2.6 because of simple things like `print "foo {}".format(thing)` where we just left out the index which works on 2.7+ but not on 2.6 What ever yall decide to do I just wanted to point out what will happen if you drop 2.6 support :)

**Comment by rreubenur** [comment]
Ship it

**Comment by twarnock** [comment]
Drop it.  I will agree to anything at this point to get support for 6.0.

**Comment by tianhao64** [comment]
Thanks for all comments. We will drop 2.6 support for new release.
