### ISSUE TITLE
[Docs] vim.host.VsanSystem UpdateVsan function name in docs is incorrect

### ISSUE THREAD

**Issue by rallytime** [vmware/pyvmomi#314]
There is a function listed on the [vim.host.VsanSystem](https://github.com/vmware/pyvmomi/blob/releases/docs/vim/host/VsanSystem.rst) documentation named `UpdateVsan`, but that function doesn't actually exist in the VsanSystem spec. It should be `UpdateVsan_Task`.

For example, I have a VsanSystem object (named vsan_sys) and a vsan.host.ConfigInfo object (named vsan_config) instantiated:
```
>>> type(vsan_sys)
<class 'pyVmomi.VmomiSupport.vim.host.VsanSystem'>
>>> type(vsan_config)
<class 'pyVmomi.VmomiSupport.vim.vsan.host.ConfigInfo'>
>>> vsan_sys
'vim.host.VsanSystem:vsanSystem'
```
However, I get an attributed error when calling `UpdateVsan`:
```
>>> vsan_sys.UpdateVsan(vsan_config)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'vim.host.VsanSystem' object has no attribute 'UpdateVsan'
```
After inspecting `dir`, it appears that the function's name is actually `UpdateVsan_Task`:
```
>>> dir(vsan_sys)
['AddDisks', 'AddDisks_Task', 'Array', 'InitializeDisks', 'InitializeDisks_Task', 'QueryDisksForVsan', 'QueryHostStatus', 'RemoveDisk', 'RemoveDiskMapping', 'RemoveDiskMapping_Task', 'RemoveDisk_Task', 'Update', 'UpdateVsan_Task', '_GetMethodInfo', '_GetMethodList', '_GetMoId', '_GetPropertyInfo', '_GetPropertyList', '_GetServerGuid', '_GetStub', '_InvokeAccessor', '_InvokeMethod', '__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_methodInfo', '_moId', '_propInfo', '_propList', '_serverGuid', '_stub', '_version', '_wsdlName', 'config']
```
Which, after trying the different name, it works as expected (in this case, setting the `enabled` attribute):
```
>>> host_ref.config.vsanHostConfig.enabled
False
>>> vsan_sys.UpdateVsan_Task(vsan_config)
'vim.Task:haTask-ha-host-vim.host.VsanSystem.update-153924198'
>>> host_ref.config.vsanHostConfig.enabled
True
```

Hopefully if anyone runs into this one, this will help them instead of trying to figure out why this isn't working, at least until the docs can be amended.

Thanks!

**Comment by qinmiaoHE** [comment]
hi
  i had the similar problem that i want to use vim.event.EventFilterSpec(),while  they told me that the event didnt exist in vim ...

here is part of my code:

si== connect.SmartConnect(host=args.host,
                                                user=args.user,
                                                pwd=args.password,
                                                port=int(args.port))
atexit.register(connect.Disconnect, service_instance)
filter_spec = pyVmomi.vim.event.EventFilterSpec()   
collector   = si.content.eventManager.CreateCollectorForEvents(filter=filter_spec)

could you tell me sth about this ,thanks very very very much

**Comment by qinmiaoHE** [comment]
Thanks, it worked. 

by the way ,did your pyvmomi code could implement code completion? if so ,do you mind to share the method?   

thanks

**Comment by rallytime** [comment]
@qinmiaoHE I don't have any code completion in place. I am using these bindings for a project I am working on to manage ESXi hosts, and I just noticed I couldn't get the UpdateVsan function to work because the docs were wrong, so I thought I should file an issue and fix it.

**Comment by qinmiaoHE** [comment]
thanks, i am using pyvmomi to get ESXi host's events and tasks.thanks for your help.

**Comment by michaelrice** [comment]
To implement code completion would be hard because the objects are dynamically created based on what is in the ServerObjects and a couple other files. Some IDEs have a way of providing hints but that would be a manual thing you would have to look into for your IDE..
