### ISSUE TITLE
Get exception [AttributeError: 'NoneType' object has no attribute 'fileManager'] on example upload_file_to_vm

### ISSUE THREAD

**Issue by wy65701436** [vmware/pyvmomi#316]
Hi, 

I got this error when to execute the example code to upload file into vm.

url = content.guestOperationsManager.fileManager.InitiateFileTransferToGuest(vm, creds,
AttributeError: 'NoneType' object has no attribute 'fileManager'

Can somebody help?

BTW, I can success run the find_by_uuid.

-Yan

**Comment by wy65701436** [comment]
It's a user error. Works fine now. Close it.

**Comment by ManaswiniS** [comment]
Hi,
I'm also getting the same error when I try to upload files to a vm. How is the issue resolved.
Any help would be appreciated.

-Manaswini
