### ISSUE TITLE
Deploy_ovf gives error after calling ImportVApp function.

### ISSUE THREAD

**Issue by aryaanand** [vmware/pyvmomi#322]
spec_params = vim.OvfManager.CreateImportSpecParams()
        import_spec = manager.CreateImportSpec(ovfd,
                                               objs["resource pool"],
                                               objs["datastore"],
                                               spec_params)
        lease = objs["resource pool"].ImportVApp(import_spec.importSpec)

Error : TypeError: 'vim.vm.device.VirtualDeviceSpec.FileOperation' object is not callable

**Comment by tianhao64** [comment]
@aryaanand It looks like there is an bug in python3. Could you please try it with python2?

**Comment by tianhao64** [comment]
I am seeing the same error with python3, but I able to deploy an ovf with python2.

**Comment by aryaanand** [comment]
Thanks @tianhao64. Do u know why I am getting this error 
(vmodl.fault.NotSupported) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The operation is not supported on the object.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by aryaanand** [comment]
Looks like some feature is not supported on server. I will check..Thanks :)

**Comment by tianhao64** [comment]
I believe this is fixed by https://github.com/vmware/pyvmomi/pull/257

**Comment by aryaanand** [comment]
Thanks @tianhao64

**Comment by ckhoslaVMware** [comment]
Hi Tianhao,

Hope you are doing well!

I am using the same code without any changes but I am getting the below error:

Line: 
manager = si.content.ovfManager
    spec_params = vim.OvfManager.CreateImportSpecParams()
    import_spec = manager.CreateImportSpec(ovfd,
                                           objs["resource pool"],
                                           objs["datastore"],
                                           spec_params)
    lease = objs["resource pool"].ImportVApp(import_spec.importSpec,
                                             objs["datacenter"].vmFolder) // Here it throws the below error

Error:
File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 385, in _InvokeMethod
    list(map(CheckField, info.params, args))
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 915, in CheckField
    raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "spec" not provided (not @optional)

Sample:

https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/deploy_ova.py

Could you please let me know if I am missing something or doing anything wrong. 

Thank you!

Regards,
Chandan Khosla

**Comment by hgadekarvnera** [comment]
Hi Chandan,
I am facing the exact same issue as yours. 
raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "spec" not provided (not @optional)

Were you able to resolve this? If yes, could you please advise.
Thank you in advance.

-Heramb

**Comment by prziborowski** [comment]
@boddapallisankarrao It doesn't have to be an explicit resource pool. But all VMs live in a resource pool, whether defined by the user or implicitly existing. A standalone host / cluster has a root resource pool.

cisr = ovfManager.CreateImportSpec(ovf_handle.get_descriptor(),ds, cisp)
You have removed the 2nd parameter, which is resource pool and that is why it is throwing the error "TypeError: For "resourcePool" expected type vim.ResourcePool, but got vim.Datastore" as the 2nd input is now the datastore.

**Comment by boddapallisankarrao** [comment]
Thanks, OVA deployment problem solved.
But with ovf getting problem like this will u look on to this.

Traceback (most recent call last):
  File "install_ovf.py", line 117, in <module>
    exit(main())
  File "install_ovf.py", line 92, in main
    lease = rp.ImportVApp(import_spec.importSpec,dc.vmFolder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-pac
kages\pyVmomi\VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-pac
kages\pyVmomi\VmomiSupport.py", line 385, in _InvokeMethod
    list(map(CheckField, info.params, args))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-pac
kages\pyVmomi\VmomiSupport.py", line 915, in CheckField
    raise TypeError('Required field "%s" not provided (not @optional)' % info.name)
TypeError: Required field "spec" not provided (not @optional)


and I have checked " objs["datacenter"].vmFolder" is returning the correct"
Please help me on this

**Comment by ckhoslaVMware** [comment]
Hi,

Could you please check if your code looks like below snippet? Or can you copy your code snippet here?

-----------------------------------------------------------------
manager = si.content.ovfManager
    spec_params = vim.OvfManager.CreateImportSpecParams()
    spec_params.entityName = "vmname"
    import_spec = manager.CreateImportSpec(ovfd,
                                           rp,
                                           ds,
                                           spec_params)
    lease = rp.ImportVApp(import_spec.importSpec,
                                             objs["datacenter"].vmFolder)

-----------------------------------------------------------------

Regards,
Chandan Khosla

**Comment by prziborowski** [comment]
> lease = rp.ImportVApp(import_spec.importSpec,dc.vmFolder)

> TypeError: Required field "spec" not provided (not @optional)

It appears that import_spec.importSpec is not set. This likely can happen if there was an error that happened in the CreateImportSpec call.
You might want to add a check:
```
if len(import_spec.warning) > 0:
   print("Warnings during processing: %s" % import_spec.warning)
if len(import_spec.error) > 0:
   print("Errors during processing: %s" % import_spec.error)
if import_spec.importSpec is None:
   print("Spec is empty, cannot continue")
   return
```

**Comment by boddapallisankarrao** [comment]
Hi,
I've checked with following code:
if len(import_spec.warning) > 0:
   print("Warnings during processing: %s" % import_spec.warning)
if len(import_spec.error) > 0:
   print("Errors during processing: %s" % import_spec.error)
if import_spec.importSpec is None:
   print("Spec is empty, cannot continue")
   return

got this errors:
Errors during processing: (vmodl.MethodFault) [
   (vim.fault.OvfXmlFormat) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = "Line 1: Could not parse the document: 'not well-formed (invalid token)'.
",
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      lineNumber = 1,
      description = 'not well-formed (invalid token)'
   }
]
Spec is empty, cannot continue

Actually I've given all correct data but seems like something missing
Please help me on this

**Comment by prziborowski** [comment]
You are using deploy_ovf.py, right? Is the file you are passing a valid OVF file?
That script doesn't handle OVA files.
The error seems to indicate that it can't decode the file as being in an xml format.

**Comment by rkulow** [comment]
After stumbling upon exactly the same error `"spec" not provided`, the solution to this kind of problem is - as mentioned - the use of incorrect file encoding.
So while reading your ovf file you will need to use the correct file encoding:
`open(ovf_path, 'r')` should be for esxi 6.7 `open(ovf_path, 'r', encoding='utf-8-sig')`

**Comment by CrazyKartik** [comment]
> > lease = rp.ImportVApp(import_spec.importSpec,dc.vmFolder)
> 
> > TypeError: Required field "spec" not provided (not @optional)
> 
> It appears that import_spec.importSpec is not set. This likely can happen if there was an error that happened in the CreateImportSpec call. You might want to add a check:
> 
> ```
> if len(import_spec.warning) > 0:
>    print("Warnings during processing: %s" % import_spec.warning)
> if len(import_spec.error) > 0:
>    print("Errors during processing: %s" % import_spec.error)
> if import_spec.importSpec is None:
>    print("Spec is empty, cannot continue")
>    return
> ```

Hi,
I have used above statements to print out the error and have solved it.
It was expecting some "ElementName" tag in there. But, for earlier versions, it was working fine, I used "Description" in place of "ElementName" before stumbling on the error. 
Do you have any idea where can I check what tags/fields are supported by the pyvmomi versions or what ovf versions are supported by it?
