### ISSUE TITLE
How can I specify a portgroup while cloning a vm from the template?

### ISSUE THREAD

**Issue by stanislavhordiyenko** [vmware/pyvmomi#323]
Hi,

I have reviewed all documentation and couldn't find the way how I can specify a portgroup while cloning a vm from the template? I was asked to add functionality to be able to specify a VLAN where to create a vm.

Cheers.

**Comment by prashasthip** [comment]
Once you clone a VM from a template, you can configure the vNIC attached to the VM to the required portgroup/VLAN. 

http://stackoverflow.com/questions/24001697/add-vm-to-vlan-through-pyvmomi-vsphere

**Comment by rreubenur** [comment]
This is not the right place . Please go through https://github.com/vmware/pyvmomi-community-samples/tree/master/samples . There are many examples.
