### ISSUE TITLE
Centos 7 requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by kippie538** [vmware/pyvmomi#324]
I keep getting SSL error.
I'am using Minimal Centos 7 and installed python 2.7.10 and instal pyvmomi via pip and git. By both installations sam problem

requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

How can i fix this.

**Comment by aryaanand** [comment]
Add below lines for setting sslContext

context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
context.verify_mode = ssl.CERT_NONE

        self.si = SmartConnect(host=self.host,
                               user=self.user,
                               pwd=self.password,
                               port=int(self.port),
                               sslContext=context)

**Comment by dancaps** [comment]
I added this to the hello_world_vcenter.py script under the import statements and I get this error. NameError: name 'SmartConnect' is not defined

What am I doing wrong?

**Comment by merrist** [comment]
@dancaps 
You need to use this:
```
from pyVim import connect
```

**Comment by merrist** [comment]
@aryaanand 
thanks.
I see.

**Comment by tianhao64** [comment]
Thx @dancaps
