### ISSUE TITLE
Unable to get the vm's  more than one ip on a vCenter

### ISSUE THREAD

**Issue by 10jschen** [vmware/pyvmomi#327]
When setting up more than one ip on a vm, there is no method to get all of the ip. And I can get one ip by vm.summary.guest.ipAddress. But when I want to get more than one ip on a vm, there is not working. Is there anyone can do this?

**Comment by rreubenur** [comment]
You need the GuestNicInfo[] data object which has an attribute called ipAddress[].

So your code should look like this. I have not tested it !

```
ips = []
vm_nic_infos = vm.guest.net
for nic_info in vm_nic_infos:
    ips.append(nic_info.ipAddress)
vm_ips = list(itertools.chain(*ips))
```

**Comment by tianhao64** [comment]
Thanks @rreubenur 
@10jschen can you close this issue?
