### ISSUE TITLE
pyVmomi 6.0.0 Python 2.6 compatibility/support

### ISSUE THREAD

**Issue by nmadhok** [vmware/pyvmomi#329]
pyVmomi 6.0.0 took Python 2.6 compatibility/support away and now only supports Python 2.7+. This is really annoying because RHEL and Oracle Linux still ship with Python 2.6 natively. 

Can someone please tell me if there are any plans to make the recent changes backwards compatible so it doesn't affect other projects that depend on this library?

ping @tianhao64 @hartsock @michaelrice

**Comment by michaelrice** [comment]
No plans, @tianhao64 asked about removing support for it. Please see #306

**Comment by tianhao64** [comment]
@nmadhok as @michaelrice mentioned python2.6 has been dropped since 6.0 release.
