### ISSUE TITLE
Problem in assigning network for NIC

### ISSUE THREAD

**Issue by reubenur-rahman** [vmware/pyvmomi#33]
I have already asked the question here https://github.com/vmware/pyvmomi-community-samples/issues/9

HI,

host.network returns me a list of available networks on the particular host out of which some are standard and some dvs .

Now with this networks when I am adding or editing NICs I am facing problem for dvs networks. If I right click and see the network settings I find the network label is not getting selected. Where as for standard networks the NIC network label is getting selected.

I have tried to change nicspec.device.backing.network = get_obj(content, [vim.Network], net_name) to nicspec.device.backing.network = get_obj(content, [vim.dvs.DistributedVirtualPortgroup], net_name) . But no luck !

What I am doing is given below :

```
    nicspec = vim.vm.device.VirtualDeviceSpec()
    nicspec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    nicspec.device = vim.vm.device.VirtualVmxnet3()
    nicspec.device.wakeOnLanEnabled = True
    nicspec.device.deviceInfo = vim.Description()
    nicspec.device.deviceInfo.label = net_name
    nicspec.device.deviceInfo.summary = net_name             
    nicspec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
    nicspec.device.backing.network = get_obj(content, [vim.Network], net_name)
    #self.logger.debug ("Assigning network %s for NIC" % net_name)
    nicspec.device.backing.deviceName = net_name
    nicspec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
    nicspec.device.connectable.startConnected = True
    nicspec.device.connectable.allowGuestControl = True
```

![70b397a2-e0d1-11e3-86cd-42d628adf11a](https://cloud.githubusercontent.com/assets/6652363/3043670/c6e429c0-e108-11e3-9f64-5a4ec12fa95c.png)

**Comment by RenoRainz** [comment]
Hi,

Thanks you for the tip :-) 

I have little issue, I create a NIC attached to a virtual distributed switch, but once the VM is created and started, the NIC on VM is not connected, I can edit setting and just click to connect it. 

>  

      for key, ip in enumerate(ip_settings):

        nic = vim.vm.device.VirtualDeviceSpec()
        nic.operation = vim.vm.device.VirtualDeviceSpec.Operation.add  # or edit if a device exists
        nic.device = vim.vm.device.VirtualVmxnet3()
        nic.device.wakeOnLanEnabled = True
        nic.device.addressType = 'assigned'
        nic.device.key = 4000  # 4000 seems to be the value to use for a vmxnet3 device
        nic.device.deviceInfo = vim.Description()
        nic.device.deviceInfo.label = "Network Adapter %s" % key
        nic.device.deviceInfo.summary = vlans_settings[key]
        
        # Get distributed virtual portgroup obj
        pg = get_obj(content, [vim.dvs.DistributedVirtualPortgroup], vlans_settings[key])

        # Get connection information about connection between DVS and PorGroup
        dvs_port_connection = vim.dvs.PortConnection()
        dvs_port_connection.portgroupKey= pg.key
        dvs_port_connection.switchUuid= pg.config.distributedVirtualSwitch.uuid

        nic.device.backing = vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo()
        nic.device.backing.port = dvs_port_connection
        
        nic.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
        nic.device.connectable.startConnected = True
        nic.device.connectable.connected = True
        nic.device.connectable.allowGuestControl = True
        

        devices.append(nic)

Do you have any ideas ?

**Comment by RenoRainz** [comment]
I figured it out, it seems the NIC customization cause this.

**Comment by jgrossmac** [comment]
Anyone who is still looking for the answer to this, the line you need is this:

    nic.device.connectable.connected = True

Most of the sample scripts do not have this piece.

**Comment by karthi81** [comment]
nic.device.connectable.connected = True

This info helped me a lot

**Comment by xueyuanl** [comment]
thanks, your solution is very useful for me
