### ISSUE TITLE
What shoudle i do when i want to export VM?

### ISSUE THREAD

**Issue by xiaochao** [vmware/pyvmomi#333]
I Used ExportVm function to export my vm machine.But i got an error "operation timeout". What shoudle i do. My codes shows below.

```
try:
  si = None
  context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
  context.verify_mode = ssl.CERT_NONE
  si = SmartConnect(host=host, user=user, pwd=pass, sslContext=context)
  if not si:
      print('Cannot connect to specified host using specified username and password')
      sys.exit(-1)
  else:
      print('Connect success')

  atexit.register(Disconnect, si)
  content = si.content
  objView = content.viewManager.CreateContainerView(content.rootFolder, [vim.VirtualMachine], True)
  vmList = objView.view
  objView.Destroy()

  vms = dict()
  machines = sys.argv[1].split(';')
  tasks = list()
  for vm in vmList:
      if vm.name == 'git':
          tasks.append(vm.ExportVm())

  WaitForTasks(tasks, si)
except Exception, e:
   print e
```

**Comment by prziborowski** [comment]
Please see the sample at https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/export_vm.py

A key thing to note is that ExportVm does not return a task. It returns an HttpNfcLease. The lease gives you details for downloading the VM. And during that download, you need to continue to issue progress updates else the server will time out the lease (thinking that you abandoned it).

As you can see from the sample, it is a non-trivial process for exporting a VM (but the sample is a good one to base off of).
