### ISSUE TITLE
Is there way to clone a template to a cluster that does not have resource pool?

### ISSUE THREAD

**Issue by sametimesolutions** [vmware/pyvmomi#337]
The VirtualMachineRelocateSpec seems to have support for host and resource pools but not clusters unless they have a resource pool.

**Comment by sametimesolutions** [comment]
https://www.vmware.com/support/developer/vc-sdk/visdk2xpubs/ReferenceGuide/vim.vm.RelocateSpec.html

**Comment by wiggin15** [comment]
All clusters have the "root resource pool", cluster.resourcePool. If you use it you'll relocate to the cluster.

**Comment by sametimesolutions** [comment]
Thank you wiggin15!,  Using the cluster.resourcePool worked.

**Comment by tianhao64** [comment]
Closing the issue as the question has been answered.
