### ISSUE TITLE
use pyvmomi5.5.0 to interaction with vcenter cause vcenter memory rapid growth

### ISSUE THREAD

**Issue by mygoda** [vmware/pyvmomi#344]
when i use pyvmomi to interaction with vcenter，i can see that vcenter memory rapid growth. in the end，consume all the vcenter memory。that vcenter was down。when i close pyvmomi project，that vcenter memory go down，when i check vcenter log， i can see so many session in vcenter memory 。but i use long connection with vcenter 。my code is Regularly polling use one pyvmomi SmartConnect
interaction with  vcenter。if catch exception ，i set connection is none。and create a new connect to do thing 。all that， why vcenter collect so many session and consume so many memory 。

**Comment by mygoda** [comment]
my python version is 2.7.6

**Comment by mygoda** [comment]
i just want to know 。why vcenter memory growth so rapid when i use pyvmomi to interaction 。and i shutdown pyvmomi ，that vcenter memory go down。i need help。

**Comment by prziborowski** [comment]
How is your code doing the polling?
If you are using a ContainerView, that does use resources on vCenter to maintain it. When you are done with it, you must call Destroy(). (python will not do that for you).

Besides that, I'm not aware of usages of pyVmomi that cause abnormal memory growth on vCenter.

**Comment by mygoda** [comment]
@prziborowski thankyou i think your answer is used for me.

**Comment by mygoda** [comment]
@prziborowski i always use this code def get_obj(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if c.name == name:
            obj = c
            break
    return obj

so how can i use destroy to destroy this.

**Comment by mygoda** [comment]
@prziborowski  i also have a question that when i use short connect that is connect to do something done it and clone connect，that i can not see the vcenter memory grow up。 why ？ thanks。

**Comment by prziborowski** [comment]
I think the below get_obj function would be more correct.
```
def get_obj(content, vimtype, name):
   obj = None
   container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
   for c in container.view:
      if c.name == name:
         obj = c
         break
   container.Destroy()
   return obj
```

I don't think there will be a large growth by having sessions around.
But when you are done with a session you should do:
content.sessionManager.Logout()

And logging out will destroy any of those container views that were linked with the session. Otherwise it will remain until the session times out (maybe 15 minutes later).

**Comment by mygoda** [comment]
@prziborowski  thankyou very much

**Comment by mygoda** [comment]
@prziborowski  i catch new issue in vcenter. could you please help me again. thank you;
issue is: https://github.com/vmware/pyvmomi/issues/440
