### ISSUE TITLE
Is there a way to directly obtain the VMs associated with a portgroup?

### ISSUE THREAD

**Issue by prashasthip** [vmware/pyvmomi#346]
I see two possible ways:
1. Obtain all the VMs in a datacenter and check each to see if it is configured to the required portgroup
2. Get the DistributedVirtualSwitch associated with the portgroup and get the VMs associated with it using DistributedVirtualSwitch.summary.vm. Then check from this smaller pool of VMs if it is configured to the required portgroup.

Is there any better way?

**Comment by prashasthip** [comment]
@hartsock

**Comment by prashasthip** [comment]
I just realized that vim.dvs.DistributedVirtualPortgroup extends vim.Network. vim.Network has an attribute "vm" that retrieves all the VMs associated with the given network.

**Comment by hartsock** [comment]
cc @tianhao64  hey, Tianhao just FYI. Folks are still getting used to you doing the outward facing part of the project. :-)
