### ISSUE TITLE
vim.HostSystem.ConnectionState is missing for pyvmomi 6.0?

### ISSUE THREAD

**Issue by halianka** [vmware/pyvmomi#348]
https://github.com/vmware/pyvmomi/blob/e26718fef6d9dbc8a4da1761b75d9da58bbc0daa/docs/vim/HostSystem/ConnectionState.rst

I don't see it
In [266]: esx
Out[266]: 'vim.HostSystem:host-12'

In [267]: dir(esx)
Out[267]: 
['AcquireCimServicesTicket',
 'Array',
 'Destroy',
 'Destroy_Task',
 'Disconnect',
 'DisconnectHost_Task',
 'EnterLockdownMode',
 'EnterMaintenanceMode',
 'EnterMaintenanceMode_Task',
 'EnterStandbyMode',
 'ExitLockdownMode',
 'ExitMaintenanceMode',
 'ExitMaintenanceMode_Task',
 'ExitStandbyMode',
 'PowerDownHostToStandBy_Task',
 'PowerUpHostFromStandBy_Task',
 'QueryConnectionInfo',
 'QueryHostConnectionInfo',
 'QueryMemoryOverhead',
 'QueryMemoryOverheadEx',
 'QueryOverhead',
 'QueryOverheadEx',
 'QueryTpmAttestationReport',
 'Reboot',
 'RebootHost_Task',
 'ReconfigureDAS',
 'ReconfigureHostForDAS_Task',
 'Reconnect',
 'ReconnectHost_Task',
 'Reload',
 'Rename',
 'Rename_Task',
 'RetrieveHardwareUptime',
 'SetCustomValue',
 'Shutdown',
 'ShutdownHost_Task',
 'UpdateFlags',
 'UpdateIpmi',
 'UpdateSystemResources',
 'UpdateSystemSwapConfiguration',
 '_GetMethodInfo',
 '_GetMethodList',
 '_GetMoId',
 '_GetPropertyInfo',
 '_GetPropertyList',
 '_GetServerGuid',
 '_GetStub',
 '_InvokeAccessor',
 '_InvokeMethod',
 '__class__',
 '**delattr**',
 '**dict**',
 '**doc**',
 '**eq**',
 '**format**',
 '**getattribute**',
 '**hash**',
 '**init**',
 '**module**',
 '**ne**',
 '**new**',
 '**reduce**',
 '**reduce_ex**',
 '**repr**',
 '**setattr**',
 '**sizeof**',
 '**str**',
 '**subclasshook**',
 '**weakref**',
 '_methodInfo',
 '_moId',
 '_propInfo',
 '_propList',
 '_serverGuid',
 '_stub',
 '_version',
 '_wsdlName',
 'alarmActionsEnabled',
 'availableField',
 'capability',
 'config',
 'configIssue',
 'configManager',
 'configStatus',
 'customValue',
 'datastore',
 'datastoreBrowser',
 'declaredAlarmState',
 'disabledMethod',
 'effectiveRole',
 'hardware',
 'licensableResource',
 'name',
 'network',
 'overallStatus',
 'parent',
 'permission',
 'recentTask',
 'runtime',
 'setCustomValue',
 'summary',
 'systemResources',
 'tag',
 'triggeredAlarmState',
 'value',
 'vm']

**Comment by wiggin15** [comment]
The ConnectionState in the documentation you linked is just the definition of the enum type (possible values of the connectionState property). The property itself is part of HostRuntimeInfo - i.e. `esx.runtime.connectionState`

**Comment by DanielDraganov** [comment]
Outdated
