### ISSUE TITLE
Sample getallvm.py is imperfect, if there is vApp in datacenter, then getallvm.py would fail. 

### ISSUE THREAD

**Issue by bjtulq** [vmware/pyvmomi#351]
I think we can get virtualmachine according to "_wsdlName" or vm's object type.

**Comment by prziborowski** [comment]
Yes, I believe rather than using all the hasattr calls, it could use the object types as you say.
isinstance(x, vim.VirtualMachine) / isinstance(x, vim.Folder) / isinstance(x, vim.Datacenter) / isinstance(x, vim.VirtualApp).
