### ISSUE TITLE
PortConnection doesn't accept switchUuid with 'None' value

### ISSUE THREAD

**Issue by borisovano** [vmware/pyvmomi#353]
PortConnection doesn't accept switchUuid with 'None' value. However configuring this via VMware web client it works perfectly.

**Full details:**
I'm using the code below in order to add a NIC configured with DistributedVirtualSwitch to an existing VM (via pyvmomi):

`

```
def __AddNIC(si, vmconf_dict, network_name):
    vm = __get_vm(si, vmconf_dict)
    print " Network label : " + network_name

    devices = []
    nicspec = vim.vm.device.VirtualDeviceSpec()
    nicspec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    nicspec.device = vim.vm.device.VirtualVmxnet3()
    nicspec.device.wakeOnLanEnabled = True
    nicspec.device.deviceInfo = vim.Description()
    nicspec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
    nicspec.device.connectable.startConnected = True
    nicspec.device.connectable.allowGuestControl = True

    network_objref = _get_mor_by_property(si, vim.dvs.DistributedVirtualPortgroup, network_name)
    dswitch_port_connection = vim.dvs.PortConnection(
        portgroupKey=network_objref.key,
        switchUuid=network_objref.config.distributedVirtualSwitch.uuid
    )
    nicspec.device.backing = vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo()
    nicspec.device.backing.port = dswitch_port_connection

    devices.append(nicspec)
    vmconf = vim.vm.ConfigSpec(deviceChange=devices)
    task = vm.ReconfigVM_Task(vmconf)
    tasks.wait_for_tasks(si, [task])`

```

I'm getting the following exception:

`switchUuid=network_objref.config.distributedVirtualSwitch.uuid AttributeError: 'NoneType' object has no attribute 'uuid'
`
After examination of Vcenter Managed Objects(via mob) it appears that some of the DistributedVirtualPortgroup object references does have that (VmwareDistributedVirtualSwitch) property, while others have this property Unset.

![selection_133](https://cloud.githubusercontent.com/assets/10387151/13124705/587d1baa-d5ca-11e5-9ed5-b95d21d4f4f1.png)
![selection_132](https://cloud.githubusercontent.com/assets/10387151/13124713/5a189534-d5ca-11e5-94d7-5f61eb2850e6.png)

I've tried multiple ways to work around that, such as:

Setting: `switchUuid=None` which yielded:

`TypeError: Required field "switchUuid" not provided (not @optional)`

Setting: `dswitch_port_connection`= None which yielded:

`TypeError: Required field "port" not provided (not @optional)`

<br>
**Note:** When I'm using VMware WebClient to configure the above it works perfectly.

**Comment by chinmayb** [comment]
you need to set the switchUuid to UUID of the DVS.
Look at the documentation : 
[https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/vim.dvs.PortConnection.html](url)


This is a python error : 'NoneType' object has no attribute 'uuid' 
this network_objref.config.distributedVirtualSwitch is coming None for some pgs, in your case.

Do you have read privilege to view that property ?

**Comment by borisovano** [comment]
@chinmayb Hi, thanks for the hint. Apparently I don't NOT have a read privilege.

I've deliberately set the UUID to None. As it seemed right value if the MOB browser indicated Unset.
After double checking with our sysadmin this is a **privilege issue indeed.**

**
Additional question before closing the case, do you(or anyone else) know how can assign network to NIC without 'read' privilege on the DVS. It works fine via vSphere client and yet I don't have this privilege (same user as the API)**

**Comment by gthieleb** [comment]
Without privileges to the DVS you may retrieve the network from the [compute_resource.network](https://github.com/vmware/pyvmomi/blob/master/docs/vim/Network.rst) instead.
