### ISSUE TITLE
how to listing/validation guest os 

### ISSUE THREAD

**Issue by hevel** [vmware/pyvmomi#356]
how can i get the os list from current vcenter?
there is a issue #153  talk about [vim.vm.GuestOsDescriptor.GuestOsIdentifier](https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/GuestOsDescriptor/GuestOsIdentifier.rst)
but some values from vim.vm.GuestOsDescriptor.GuestOsIdentifier did not work for some vcenter,it return "A specified parameter was not correct." for the task.

**Comment by prziborowski** [comment]
It is actually more specific than vcenter allowing certain guests, it is determined by the ESXi host (older versions can't handle newer guest identifiers).

There is an object called the EnvironmentBrowser [1] that is accessible from a ComputeResource (also VirtualMachine, but for determining available guest identifiers, it could be consider a little late?)

Assuming you know the virtual hardware version you want to deal with (or just use the default), you can call
QueryConfigOption(). Pass in the host system if you are on VC.

This returns a LOT of data.

Snippet for getting the guestOs names:
```
env = si.content.rootFolder.childEntity[0].hostFolder.childEntity[0].environmentBrowser
cfgOption = env.QueryConfigOption()
print map(lambda x: x.id, cfgOption.guestOSDescriptor)
```
But I'd also encourage you to check out the rest of the data there and how it can be leveraged for VM provisioning (it gives recommended sizes for the different guest types as well as limit and what is supported).

1: https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.EnvironmentBrowser.html (my googling couldn't find the latest, but this object has been around for a while)
