### ISSUE TITLE
Creating a linked clone

### ISSUE THREAD

**Issue by russellpope** [vmware/pyvmomi#362]
Hey folks,

Not sure if this is the appropriate venue for this.

Trying to create a linked clone and I'm not 100% sure what needs to go where. Been hacking on the 'clone_vm.py' and added the following:

`relospec = vim.vm.RelocateSpec(diskMoveType='createNewChildDiskBacking') `

which results in a vCenter (on 5.5) error 'A specified parameter was not correct. spec.snapshot' 

Which I assume means I'm missing the bit where I actually define the snapshot though I'm not sure where I need to be defining it.

**Comment by rreubenur** [comment]
This is what you need:

1. Take snapshot:

```
task = vm.CreateSnapshot_Task(name='my_snapshot', memory=False, quiesce=False)
```

2. Create relocation spec:

```
        relospec = vim.vm.RelocateSpec()
        relospec.diskMoveType = 'createNewChildDiskBacking'
        relospec.host = host
        relospec.pool = resource_pool
```
3. Create clone spec:

```
            clone_spec = vim.vm.CloneSpec(powerOn=True,
                                          template=False,
                                          location=relospec,
                                          config=vmconf,
                                          snapshot=vm.snapshot.
                                          rootSnapshotList[0].snapshot)
```

**Comment by russellcorey** [comment]
Tried bringing your code in as is:

Traceback (most recent call last):

  File "clone_vm.py", line 234, in <module>

    main()

  File "clone_vm.py", line 227, in main

    args.resource_pool, args.power_on)

  File "clone_vm.py", line 194, in clone_vm

    clonespec.snapShot = vim.vm.snapshot.rootSnapshotList[0].snapshot

  File
"/Users/ldh/github.kovarus/venv/tintri/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py",
line 261, in __getattr__

    raise AttributeError(attr)

AttributeError: snapshot


I'm at a loss here. I'm not sure I understand any of these relationships
and the VMware documentation just adds more questions. Pastebin'd code; my
modifications start at line ~184 or so. I have an existing snapshot called
'snap' on my test VM and it's the only VM in inventory. Normal cloning
operations work fine via pyvmomi but I can't sort out what's missing for
linked clones.

**Comment by rreubenur** [comment]
I have created an example here https://github.com/rreubenur/pyvmomi-community-samples/commit/ad80ec9508e5e22561b1f079b03f0cac5097fb6f

**Comment by russellcorey** [comment]
Your sample works perfectly! Thanks.

I'm going to bug some folks on IRC now to help me understand exactly
how/why this works and how to work with the documentation.

**Comment by tianhao64** [comment]
Sample is merged.
