### ISSUE TITLE
VM Customization Fails

### ISSUE THREAD

**Issue by NaveenBellary** [vmware/pyvmomi#365]
I have a VM in powered off state. I try adding a second network adapter by creating necessary spec objects and re-configuring the VM. So, at this step, I am able to see the adapter on vCenter and it is connected to the desired network. But, when I try and **_customize_** the VM by creating a customizationSpec and assigning nicSettingMap along with other attributes, I am faced with the error:
**_fault.CustomizationPending.summary_** and the customization fails.

Where am I going wrong?

Following is how I am trying to customize the VM:

    globalIp = vim.vm.customization.GlobalIPSettings()
    customizationSpec = vim.vm.customization.Specification()
    customizationSpec.identity = spec
    customizationSpec.nicSettingMap = adapterSpecs
    customizationSpec.globalIPSettings = globalIp

**Comment by NaveenBellary** [comment]
I was able to solve the issue. The problem was that in case of VMs with linux guest operating systems, the customization process looks for DNS servers in globalIPSettings object unlike Windows VMs where it is adapter specific.

**Comment by JackDan9** [comment]
Can you give me a hand to solve the VM Customization?
