### ISSUE TITLE
some think about pyvmomi

### ISSUE THREAD

**Issue by mygoda** [vmware/pyvmomi#366]
i do some project with pyvmomi， my project use pyvmomi to clone vm， operation vm。 i want to know why we connect vcenter and get all objects in vcenter，so i see when vcenter has so many vms, that connection will use more time.  so i want to know， if  i just operation only one vm， but pyvmomi connection get all vms connections，i think this is a problem. maybe pyvmomi has some method to do better,  i hope someone tell me . @vito @kevin1024

**Comment by prziborowski** [comment]
pyvmomi should not be getting any VMs by default (it doesn't do anything automatic like that).
If you have lots of VMs and know something about your VM, you can search it faster.

ServiceInstanceContent has searchIndex.
You can call findChild(entity, name), if you know the name. You can use the datacenter you are interested in.
If you know the instanceUuid (a property of the VM that is unique for a vcenter), there is
findByUuid(vmSearch=True, uuid="", instanceUuid=vm.config.instanceUuid)
(other options is findByInventoryPath, findByIp, findAllByIp)
I believe this is what the UI uses for its search bar.

**Comment by mygoda** [comment]
@prziborowski thanks so much.  this is my search for so many time . and i also have a question in this [https://github.com/vmware/pyvmomi/issues/410](url), can you help me again, thanks.
