### ISSUE TITLE
DataStore perfomance stats.

### ISSUE THREAD

**Issue by dsever** [vmware/pyvmomi#372]
Hi,

I'm trying to collect stats for datastores (host level) in esxi using pyvmomi, for host level and vm works ok, but have problem collecting stats for datastore, I'm doing analogy of host and vms.

So I have
query = vim.PerformanceManager.QuerySpec(intervalId=20, entity=vm, metricId=[metricId], startTime=startTime, endTime=endTime)
    perfResults = perfManager.QueryPerf(querySpec=[query])

(vim.PerformanceManager.QuerySpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   entity = 'vim.Datastore:56c63076-3ab2e530-1d15-f8bc1209ee40',
   startTime = 2016-04-13T16:34:32.926633Z,
   endTime = 2016-04-13T16:35:32.926633Z,
   maxSample = <unset>,
   metricId = (vim.PerformanceManager.MetricId) [
      (vim.PerformanceManager.MetricId) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         counterId = 0,
         instance = '*'
      }
   ],
   intervalId = 20,
   format = <unset>
}

and it gives me error:

pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: querySpec[0].entity',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'querySpec[0].entity'
}

I don't know what I've missed.

Thanks

**Comment by dsever** [comment]
Sorry my mistake, after reading of documents I found that actaully it is under systemhost but instance has to be defined

Dubravko

**Comment by shay9748** [comment]
Hey I'm facing a similar issue. What did you mean by "instance has to be defined"? Which instance are you referring to?

**Comment by dsever** [comment]
Do not remember :)

**Comment by pgbidkar** [comment]
Hi @dsever Closing issue. Issue is resolved.

Thanks
