### ISSUE TITLE
How to use the methods given in .rst 

### ISSUE THREAD

**Issue by VijayakumarVellingiri** [vmware/pyvmomi#374]
I found the .rst files for e.g: vmware/pyvmomi/docs/vim/host/HardwareInfo.rst   I am unable to get the docstring for that, When I tried it returns a class and object.

> > > from pyVmomi import vim
> > > vim.Datacenter
> > > <class 'pyVmomi.VmomiSupport.vim.Datacenter'>

 How to use this, what parameters it takes and what output it will give. Please provide the usage details for all operation given in .rst files in pyvmomi/docs/vim/hos/*.rst

**Comment by DanielDraganov** [comment]
docs are no longer part of the project. Outdated.
