### ISSUE TITLE
Creating a resource pool , The object has already been deleted or has not been completely created

### ISSUE THREAD

**Issue by VijayakumarVellingiri** [vmware/pyvmomi#377]
from pyVmomi import vim
from pyVim.connect import SmartConnect, Disconnect
import ssl
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
context.verify_mode = ssl.CERT_NONE
si=SmartConnect(host="xx.xx.xx.230",user="root@abc.welli.com",pwd="Welcome@123",port=443,sslContext=ssl.SSLContext(ssl.PROTOCOL_TLSv1))

rp_ob=vim.ResourcePool('new_rp')

rp_spec=vim.ResourceConfigSpec()

alla=vim.ResourceAllocationInfo()

alla.limit=100
alla.overheadLimit=23
alla.expandableReservation=True
alla.reservation=12

rp_spec.cpuAllocation=alla

blla=vim.ResourceAllocationInfo()
blla.limit=100
blla.overheadLimit=23
blla.expandableReservation=True
blla.reservation=12

rp_spec.memoryAllocation=blla

rp_ob._stub=si._stub

rp_ob.CreateResourcePool('new_rersp',rp_spec)
# 

Traceback (most recent call last):
  File "<pyshell#42>", line 1, in <module>
    rp_ob.CreateResourcePool('new_rersp',rp_spec)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 570, in <lambda>
    self.f(_(self.args + (obj,) + args), *_kwargs)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 376, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "C:\Python27\lib\site-packages\pyVmomi\SoapAdapter.py", line 1335, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
vmodl.fault.ManagedObjectNotFound: (vmodl.fault.ManagedObjectNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The object has already been deleted or has not been completely created',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   obj = 'vim.ManagedEntity:new_rp'
}

**Comment by jasper9** [comment]
Did you figure this out since you posted it?  I'm looking to solve the same thing.

**Comment by VijayakumarVellingiri** [comment]
not yet, Im unable to get the solution

**Comment by prziborowski** [comment]
Sorry that it seems confusing for creating resource pools.
But you'd want to use the ServiceInstance (si) to navigate to an existing resource pool (all ComputeResources have one).
Example:
```
dc = si.content.rootFolder.childEntity[0]
cr = dc.hostFolder.childEntity[0]
rootResourcePool = cr.resourcePool
rp_obj = rootResourcePool.CreateResourcePool('new_rp', rp_spec)
```

**Comment by NaveenBellary** [comment]
`overheadLimit` is not applicable for resourcePools. Can you try without setting that property?

**Comment by dmitrysbor** [comment]
I wonder how can I delete pool using pyvmomi.  I didn't find any api call complimentary to CreateResourcePool.

**Comment by prziborowski** [comment]
> I wonder how can I delete pool using pyvmomi. I didn't find any api call complimentary to CreateResourcePool.

`rp_obj.Destroy()` would be my guess on how to delete the object. https://developer.vmware.com/apis/358/vim.ManagedEntity.html#destroy That is a method the managed entities get.

**Comment by dmitrysbor** [comment]
Thank you. I managed to do it.
--
Отправлено из Mail.ru для Android вторник, 20 февраля 2024г., 20:38 +03:00 от prziborowski  ***@***.*** :
