### ISSUE TITLE
pyvmomi 6.0 being supplied via pip for python 2.6

### ISSUE THREAD

**Issue by bradthurber** [vmware/pyvmomi#388]
Red Hat RHEL 6 is python 2.6 and `pip install pyvmomi` is supplying v6.0 yet pymomi page says `pyVmomi 6.0.0 and later support 2.7, 3.3 and 3.4`. Is this expected behaviour for pip to supply a non-supported version?

Apologies for my lack of knowledge in this space.

**Comment by tianhao64** [comment]
@bradthurber python 2.6 support has been dropped since 6.0 release. Can you use a newer version python to work with pyvmomi?

**Comment by bradthurber** [comment]
@tianhao64 in my particular case I am stuck with python 2.6. I did a `sudo pip install pyvmomi==5.5.0-2014.1.1` and I'm back in business but would hope that pip would have provided that by default by checking my python version. Perhaps that isn't functionality that pip provides.

**Comment by hugovk** [comment]
Can this be closed?

Pinning to an old version or using a virtualenv for Python 2.7 (or 3.6!) is the way to go.

**Comment by bradthurber** [comment]
Yes it can be closed
