### ISSUE TITLE
Getting Error "Required field "objectSet" not provided"  while using poweronvm.py

### ISSUE THREAD

**Issue by smrutim01** [vmware/pyvmomi#391]
smruti@ubuntu-staf10: python poweronvm.py --host hulk.eng.home.com -o 443 -u 'Administrator@vsphere.local' -p 'xxxxx' --vmname 'w3-esxi-01'

Caught Exception : Required field "objectSet" not provided (not @optional)

P.S:
hulk.eng.home.com  --- > Is the vCENTER.

**Comment by tianhao64** [comment]
@smrutim01 I can't reproduce this issue. What's your vcenter version?

**Comment by smrutim01** [comment]
I am using vcenter 6

**Comment by smrutim01** [comment]
I found an interesting stuff:

my password for vcenter is '$mrutI01'

when i issued below command escaping the '$' sign and putting the password field inside double quote, it worked..

**smruti@ubuntu-staf10:** python poweronvm.py --host hulk.eng.home.com -o 443 -u 'Administrator@vsphere.local' -p "\$mrutI01" --vmname 'w3-esxi-01'

Thank you sir, for spending time on this issue. But I am quite skeptical why it didn't work when I gave password as '$mrutI01' ....
