### ISSUE TITLE
Question : how set the disk label

### ISSUE THREAD

**Issue by nlamirault** [vmware/pyvmomi#397]
hi,
i've got a method to create a virtual disk. But all disk have a label "Hard Disk <number>".
I try to set the label using *vim.Description* : 

```python
disk_spec = vim.vm.device.VirtualDeviceSpec()
disk_spec.fileOperation = "create"
disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
disk_spec.device = vim.vm.device.VirtualDisk()
desc = vim.Description()
desc.label = "DD Label"
desc.summary = "DD Summary"
disk_spec.device.deviceInfo = desc
``` 

But label isn't changed. Any idead ?
thanks.

**Comment by emil45** [comment]
I think you need to use a function that reconfigures the disk property using that spec you created.
You can see that VirtualMachine has that kind of function - **ReconfigVM_Task**.

**Comment by jeffhu** [comment]
The label field is presented in the UI as a localized string but it isn't mutable.  The field is ignored when it is sent via the VirtualMachine.Reconfigure and the Folder.CreateVm methods.

**Comment by tianhao64** [comment]
Thanks @jeffhu. Closing this issue as it's not supported.
