### ISSUE TITLE
The difference between the reset and reboot

### ISSUE THREAD

**Issue by mygoda** [vmware/pyvmomi#399]
when i use pyvmomi to reset vm and task is success，but i check that system is not up， so i use vsphere client to reboot it。i can see system is up。so i want to know reset and reboot difference. who can help me. thanks

**Comment by emil45** [comment]
There is a really huge difference between the reset and the reboot functions,

**Reboot**:

> Issues a command to the guest operating system asking it to perform a reboot

**Reset**:

> Resets power on this virtual machine. If the current state is poweredOn, then this method first performs powerOff(hard)

Just like in the real world, if you want to turn off your computer you will click the "Shut Down" button in Windows/Linux  - thats mean **Reboot**.

But if you will press the button on your computer case for a couple of seconds until it power off immediatly - thats mean **Reset** (Try not to do that at all - bad for PC),

**Comment by mygoda** [comment]
@emil45  thanks for your help。

**Comment by gauravkc** [comment]
Hey @emil45 

What does this hard indicate powerOff( hard ). Is it different from the normal powerOff vm task ?

Regards,
Gaurav
