### ISSUE TITLE
Difference:MigrateVM and RelocateVM???

### ISSUE THREAD

**Issue by merrist** [vmware/pyvmomi#401]
I want to know them difference. And I want to know when to use them.
thanks

**Comment by rreubenur** [comment]
Please go through http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.VirtualMachine.html

**Comment by merrist** [comment]
I had seen it. but I am not understand,too.

**Comment by andrew-regan** [comment]
Migrate is vMotion for powered on (i.e. live) VM's. Relocate is for powered off (i.e. cold) VM's. vMotion goes through a VMKernel adapter with vMotion enabled. I believe relocating VM's goes through a VMKernel adpater w/ management or provisioning enabled.

**Comment by merrist** [comment]
I test it. And I have some ideas as follow:
Migrate VM is vMotion for powered on or off.
Relocate VM is Storage vMotion or Storage vMotion + vMotion for powered on or off.

**Comment by prziborowski** [comment]
MigrateVM only lets you change the host (and has an option to restrict based on state).
RelocateVM lets you change host, pool, datastore, disk types (thin <-> thick), network (standard switch -> distributed switch), leverage storage profiles and migrate cross VC.

RelocateVM pretty much does everything MigrateVM does, but much more.
I'd recommend using relocate and ignoring the existence of migrate.

**Comment by merrist** [comment]
@prziborowski  Thanks ^ ^
