### ISSUE TITLE
[Question]: How to distinguish distributed port group from uplink port group?

### ISSUE THREAD

**Issue by yanzhifa** [vmware/pyvmomi#404]
I get DistributedVirtualPortgroup by viewManager.CreateContainerView(), the view contains uplink port group and distributed port group, is there a easy way to find out distributed port groups from the view?

**Comment by rreubenur** [comment]
```view```, ```datacenter.networkFolder.childEntity``` or ```host.network``` will return only the port group object.

To get the uplink pg object you can try either

Invoke the method ```cluster.QueryConfigTarget(host).distributedVirtualPortgroup```

or

``` dvs.FetchDVPorts(vim.dvs.PortCriteria(uplinkPort=True)) ```

**Comment by yanzhifa** [comment]
Thanks rreubenur, i get the distributed pg by assess variable `uplinkPortgroup` true or false in `DistributedVirtualPortgroupInfo` object.
I have another question, there are 6 distribute pgs under distribute switch, but only 4 pgs has been used by host, how do i get 'Assigned port groups'. Thanks a lot.

**Comment by rreubenur** [comment]
I think ```pg_obj.host```  or ```pg_obj.vm``` should satisfy your requirement If I have understood clearly.

**Comment by yanzhifa** [comment]
Thanks @rreubenur .
 I have an question again. I want to config distribute pg name and write a demo, the core code as below
     `for portgroup in cluster.network:
            if portgroup_morid == portgroup._moId:
                continue
            config_spec = vim.dvs.DistributedVirtualPortgroup.ConfigSpec()
            config_spec.name = portgroup.name +'='
            portgroup.ReconfigureDVPortgroup(config_spec)`
but at the last line `portgroup.ReconfigureDVPortgroup(config_spec)` , it raise an error `AttributeError: 'vim.dvs.DistributedVirtualPortgroup' object has no attribute 'ReconfigureDVPortgroup'`, can you give me some suggestions?

**Comment by zhangjianpinghik** [comment]
@rreubenur   how to get the all usb devices in the host. i no use QueryConfigTarget ,bu i do not kown how to use , i have got the host instance.

**Comment by rreubenur** [comment]
```host_usb_details  = cluster.environmentBrowser.QueryConfigTarget(host).usb```

**Comment by zhangjianpinghik** [comment]
@rreubenur  in my vcenbter, i have not configure cluster, i known the metheod need a computerResource, but vm or host is not the computerResource in vcenter,  so want can i do ?

when i run you code e error is occured: global name 'cluster' is not defined ,how to i get a ComputerResource instance?
