### ISSUE TITLE
How to list resource pools in a cluster through service_instance?

### ISSUE THREAD

**Issue by lawre** [vmware/pyvmomi#406]
I'm attempting to list all the resource pools in a cluster, and can only get the top level resourcePool.  Who has the magic for getting the user created resource pools?

```
service_instance = connect.SmartConnect(host=args.host,
                                            user=args.user,
                                            pwd=args.password,
                                            port=int(args.port))

atexit.register(connect.Disconnect, service_instance)
print service_instance.RetrieveContent().rootFolder.childEntity[0].hostFolder.childEntity[4].resourcePool.name
```

Output is: Resources

**Comment by prziborowski** [comment]
The resource pools will just be nested underneath the root one.
So continue to:
```
for pool in service_instance.RetrieveContent().rootFolder.childEntity[0].hostFolder.childEntity[4].resourcePool.resourcePool:
   print pool.name

```
(and if you have more nested ones, they may be under that pool.resourcePool)

**Comment by lawre** [comment]
this worked wonderfully, thank you for the input.  I was missing the nested "resourcePool".  What is a good way to dump all the children of an entity?  I predict myself struggling with this again.

**Comment by prziborowski** [comment]
I believe there are ways to do it with the PropertyCollector and using a traverse spec.

You could probably write a recursive function for it (untested code following):
```
def GetResourcePools(entity):
   pools = []
   for pool in entity.resourcePool:
      pools += GetResourcePools(pool)
   pools.append(entity)
   return pools

dc = service_instance.RetrieveContent().rootFolder.childEntity[0]
pools = GetResourcePools(dc.hostFolder.childEntity[4].resourcePool)

for pool in pools:
   print pool.name
```

**Comment by nikskiz** [comment]
example of how to get a nested pool. My Resource pool under the cluster is called "Root"
for pool in cluster.resourcePool.resourcePool:
        if pool.name == "Root":
           resourcepool = pool
