### ISSUE TITLE
how to get the size of a vmdk

### ISSUE THREAD

**Issue by sunyaxiong** [vmware/pyvmomi#412]
I've been trying to get the size of file like .vmdk . be different from API4.0 , the new version API 'layout.disk' dont have disk.size . if i use 'layout.file' of API4.0 , could not get the size , the type='diskDescriptor' , it size is '0'

Have you guys ever done this?

sunyaxiong

**Comment by prziborowski** [comment]
Disk descriptor is a relatively small file. It is maybe the disk extent that is more relative to what you want.
Also it is going to display the disk size used on the file system, which might not be the actual size of the contents of the file. I believe VMFS5 stores small files in metadata rather than file blocks, so they won't report any size. This is likely why you see size as 0.
Try storing your VM on an NFS and you might notice the size is non-0.

**Comment by sunyaxiong** [comment]
Thank you for your answer

Now I have a lot of vm in my VCenter , I can not change my Storage easily.   
So i just want to get the size of .vmdk which type is 'diskDescriptor' . In my understanding, the 'diskDescriptor' type fie is the disk append to the vm , it size is I delivery to  customers. 

I do not need to know 'actual size of the contents of the file'

I think there must be have a method to get it size, but through the API doc , I just find 'layout.disk' API 
,and it useless to my needs      
![disk](https://cloud.githubusercontent.com/assets/8956366/16290366/463cfc94-392f-11e6-8803-89ebe1fa3c3f.png)

**Comment by prziborowski** [comment]
What you point to in the screenshot is just the capacity, which is in the vm.config.hardware.device[i].capacityInBytes (or capacityInKB).
That would be the maximum amount of disk size the guest could use (vmdk likely won't exceed that, but with snapshots, it could).

'diskDescriptor' is just the vmdk file that contains metadata. It likely won't exceed 1kb. There is a 'diskExtent' which will contain actual data (usually ending with -flat.vmdk, or similar).

**Comment by sunyaxiong** [comment]
As you ever said, in the api   vm.config.hardware.device has ''The set of virtual devices belonging to the virtual machine'.
But, the API's  return value has exception should be handled. I think  this API's return value config.hardware.device  should be more improve, not return a class, but a str.  The following is my code

` config = virtual_machine.config
    disks = config.hardware.device
    print type(disks)
    for i in disks:
        try:
            disk_kb = i.capacityInKB
            print disk_kb / 1024 /1024
        except Exception, e:
            pass`

again thanks for answer

**Comment by prziborowski** [comment]
Since config.hardware.device will not only contain disks but other devices, you won't be able to fetch capacityInKB from the other devices.

So something along the lines of:
```
from pyVmomi import vim
...
config = virtual_machine.config
devices = config.hardware.device
for device in devices:
   if isinstance(device, vim.vm.device.VirtualDisk):
      disk_kb = device.capacityInKB
      print disk_kb / 1024 / 1024
```
