### ISSUE TITLE
QueryPerf outputting inconsistent results

### ISSUE THREAD

**Issue by bwalsh434** [vmware/pyvmomi#414]
In the code snippet at the bottom of this post, we are using vim.PerformanceManager.QuerySpec to generate a query, and then using vcenter_service_instance.RetrieveContent().perfManager.QueryPerf to get results back.  This code works really well for the first 20,000 queries or so, but we have a LOT of VMs and after a certain point instead of perf_results being filled with something useful like this: 

> (vim.PerformanceManager.EntityMetricBase) [
>    (vim.PerformanceManager.EntityMetric) {
>       dynamicType = <unset>,
>       dynamicProperty = (vmodl.DynamicProperty) [],
>       entity = 'vim.VirtualMachine:vm-13618',
>       sampleInfo = (vim.PerformanceManager.SampleInfo) [
>          (vim.PerformanceManager.SampleInfo) {
>             dynamicType = <unset>,
>             dynamicProperty = (vmodl.DynamicProperty) [],
>             timestamp = 2016-06-26T17:32:40Z,
>             interval = 20
>          },
>          (vim.PerformanceManager.SampleInfo) {
>             dynamicType = <unset>,
>             dynamicProperty = (vmodl.DynamicProperty) [],
>             timestamp = 2016-06-26T17:33:00Z,
>             interval = 20
>          },
>          (vim.PerformanceManager.SampleInfo) {
>             dynamicType = <unset>,
>             dynamicProperty = (vmodl.DynamicProperty) [],
>             timestamp = 2016-06-26T17:33:20Z,
>             interval = 20
>          }
>       ],
>       value = (vim.PerformanceManager.MetricSeries) [
>          (vim.PerformanceManager.IntSeries) {
>             dynamicType = <unset>,
>             dynamicProperty = (vmodl.DynamicProperty) [],
>             id = (vim.PerformanceManager.MetricId) {
>                dynamicType = <unset>,
>                dynamicProperty = (vmodl.DynamicProperty) [],
>                counterId = 11,
>                instance = ''
>             },
>             value = (long) [
>                74190L,
>                56890L,
>                73214L
>             ]
>          }
>       ]
>    }
> ]

perf_results starts returning this:

> (vim.PerformanceManager.EntityMetricBase) []

Please help us figure out why the query is not returning data after a certain point.  In testing we have just set the script to query one object over and over until we start getting bad data, but still cannot figure out what changes to make this happen.
###### ############# CODE SNIPPET

```
from __future__ import print_function
import sys
# vSphere specific modules
from pyVim.connect import SmartConnect
from pyVmomi import vim

def connect_vcenter(vcenter_server):
    """
    Create a vCenter service instance.
    :param vcenter_server: Fully qualified name or IP of the vCenter server to connect to.
    :return: service_instance  # The vCenter service instance object.
    """
    try:
        # Define the vCenter service instance to connect to.
        vcenter_service_instance = SmartConnect(host=vcenter_server,
                                        user=sa_username,
                                        pwd=sa_password,
                                        port=int(443),
                                        sslContext=context)

        return service_instance

class GetSomeAwesomeVmPerformanceStats(object):
    def __init__(self, vcenter, vcenter_service_instance, query_range, time_interval, formatted_params, hr_params):
        """
        Initialize input parameters and build some basic objects to be used throughout the class.
        :param vcenter: The vCenter server that the vcenter_service_instance is built against.
        :param vcenter_service_instance: The vCenter service instance object.
        :param query_range: The range, in minutes, to find performance statistics for.
        :param time_interval: The interval, in seconds, to find performance stats for.
        :param formatted_params: The parameters to search on, formatted for the query.
        :param hr_params: The human-readable parameters that will be returned for each vm.
        """
        # Assign input parameters.
        self.vcenter = vcenter
        self.vcenter_service_instance = vcenter_service_instance
        self.query_range = query_range
        self.time_interval = time_interval
        self.formatted_params = formatted_params
        self.hr_params = hr_params

        self.content = self.vcenter_service_instance.RetrieveContent()  # Content of service instance.
        self.vc_time = self.vcenter_service_instance.CurrentTime()  # Current time on the vCenter
        self.vm_stats = []  # List of VM statistics information, updated by multiple methods.

        # Get all the performance counters, add to dictionary.
        self.perf_dict = {}
        perf_list = self.content.perfManager.perfCounter
        for counter in perf_list:
            counter_full = "{}.{}.{}".format(counter.groupInfo.key, counter.nameInfo.key, counter.rollupType)
            self.perf_dict[counter_full] = counter.key

        # get the performance manager, start time, and end time
        self.perf_manager = self.content.perfManager  # Perf manager content object, used to build query.
        self.start_time = self.vc_time - timedelta(minutes=(self.query_range + 1))  # Start time for query range.
        self.end_time = self.vc_time - timedelta(minutes=1)  # End time for query range.

    def build_query(self, counter_id, vm):  # pass a list here
        """
        get the vm's data for the given parameter
        :param counter_id: the the key of the parameter to search on
        :param vm: the vm object to query
        :return: None
        """
        metric_id = vim.PerformanceManager.MetricId(counterId=counter_id, instance="")
        query = vim.PerformanceManager.QuerySpec(intervalId=self.time_interval, entity=vm,
                                                 metricId=[metric_id], startTime=self.start_time,
                                                 endTime=self.end_time)
        perf_results = self.perf_manager.QueryPerf(querySpec=[query])
        print('perf_results size:', sys.getsizeof(perf_results))
        print('perf_results:', perf_results)

        do_something_with_perf_results(perf_results)
```

**Comment by bwalsh434** [comment]
Anyone have any ideas on this?

**Comment by tianhao64** [comment]
@bwalsh434 I'd like to confirm what do you mean by "In testing we have just set the script to query one object over and over until we start getting bad data". Do you mean you query the performance info for the same vm and from certain point you start to get empty result?

**Comment by bwalsh434** [comment]
Yes exactly, also getting the empty result after a certain point querying unique VMs.

**Comment by tianhao64** [comment]
@bwalsh434 What's the query_range used in the queryspec? I am wondering if it's because the number of result is less than 20,000 within the query period? In the sample output, I can see the query results are 20sec apart, so if the query period is shorter than 20 * 20,000 = 400,000 secs, you will see less than 20,000 perf results. Please confirm.

**Comment by bwalsh434** [comment]
@tianhao64 The working run at the top was querying 20 second intervals for 1 minute (3 queries per VM). We found that if we run for up to 25 minutes, whether it be 20 second intervals or 5 minute intervals, it starts with good data and starts returning bad data (empty result) after about ~16000 queries. If we run for more than 25 minutes at either time interval, we are immediately receiving bad data (empty result).

**Comment by tianhao64** [comment]
@bwalsh434 Do you mind to share more code, including the call to those two methods with the parameter values? I am interested in query_range, start_time, end_time and counter_id.

**Comment by bwalsh434** [comment]
@tianhao64 Could you send me an email at brian.walsh2@ge.com so I can share the code with you?

**Comment by DanielDraganov** [comment]
No response from the reporter. I'm closing the issue.
