### ISSUE TITLE
Can we create host profile using Pyvmomi

### ISSUE THREAD

**Issue by RobertClove** [vmware/pyvmomi#415]
How can i create Host Profile using Pyvmomi

**Comment by pavan099** [comment]
do you want to extract a host profile from a host?
i can give a simple example

**Comment by tzakrajs** [comment]
Here is how you create a host profile using a vpf file in py3:
```
content = connection.RetrieveContent()
profile_manager = content.hostProfileManager
spec = pyVmomi.vim.profile.host.HostProfile.SerializedHostProfileSpec()
spec.profileConfigString = open('path/to/hostprofile.vpf, 'rb').read().decode()
spec.name = self.name
profile_manager.CreateProfile(spec)
```

**Comment by jianlwu** [comment]
if we just want to extract a host profile from a host, how to do it?

**Comment by jianlwu** [comment]
@pavan099 can you share your example? thx

**Comment by prziborowski** [comment]
@jianlwu you would have to create a profile, and base it on a host. If you want to "extract" it, you can extract it as an xml or I believe there is a csv format.
```
# assumes si is your service instance and 'host' is a vim.HostSystem
from pyVmomi import vim
...
hpm = si.content.hostProfileManager
spec = vim.profile.host.HostProfile.HostBasedConfigSpec()
spec.name = 'hp-' + host.name
spec.enabled = False
spec.host = host
spec.useHostProfileEngine = True
profile = hpm.CreateProfile(spec)
xmlProfile = profile.ExportProfile()
profile.DestroyProfile()
```

**Comment by surbhig20** [comment]
How can I apply the created profile to a host?

**Comment by prziborowski** [comment]
There is some specific documentation in [vim.profile.host.HostProfile](https://code.vmware.com/apis/196/vsphere#/doc/vim.profile.host.HostProfile.html)
It appears you would call:
`execute = profile.Execute(host=host)`
And use the execute result to call
```
from pyVim.task import WaitForTask
task = hpm.ApplyHostConfiguration(host=host, configSpec=execute.configSpec,
                                  requireInput=execute.requireInput)
WaitForTask(task)
```

**Comment by surbhig20** [comment]
Thanks @prziborowski! That worked to apply the profile, would there be a way to attach a profile to the host as well?

**Comment by prziborowski** [comment]
You could try:
`profile.AssociateEntities(entity=[host])`

That is just a guess (I've only played around with host profiles once before and it was quite a while back).

**Comment by fanxun828** [comment]
anyone can help that, how can I edit an existing hostprofile, looks like I should be able to do it by editing existing hostprofile's spec and use existinghostfile.UpdateHostProfile(spec).  but I can't figure out how to get spec and edit it. any suggestion will be appreciate.

**Comment by DanielDraganov** [comment]
I'm closing this one. For further assistance please use the Discussions section.

**Comment by rootclay** [comment]
How can I modify the created profile? For example, I want to change the user password in profile. @prziborowski

**Comment by prziborowski** [comment]
> How can I modify the created profile? For example, I want to change the user password in profile. @prziborowski

I am just going by documentation at https://developer.vmware.com/apis/358/vim.profile.host.HostProfile.html
> To update an existing profile, use the [HostProfile](https://developer.vmware.com/apis/358/vim.profile.host.HostProfile.html).[UpdateHostProfile](https://developer.vmware.com/apis/358/vim.profile.host.HostProfile.html#update) method.

I'm not positive, but the `config` parameter to that method could be https://developer.vmware.com/apis/358/vim.profile.host.HostProfile.CompleteConfigSpec.html, which seems to allow a lot of information (applyProfile portion of that has userAccount profiles).

So the profile you create is a managed object meaning it also has functions you can call on it.
I hope that helps. I haven't really used host profile beyond the UI of creating and applying, so if that doesn't work then I don't have any other ideas.
