### ISSUE TITLE
Does anyone has sample to create cdrom and get the cdrom drive name for VM?

### ISSUE THREAD

**Issue by RobertClove** [vmware/pyvmomi#416]
Ho,
Can we create cdrom and get the cdrom drive name for VM using pyvmomi

**Comment by pburdine** [comment]
Creating a CDROM can be done by the following:
`
    device = vim.vm.device.VirtualCdrom()
    key = config.get('key', 3002)
    # The controller is not part of the VM yet, add it now
    # Create the controller device specification:
    dev_spec = vim.vm.device.VirtualDeviceSpec()
    controller = [x for x in get_attached_devices_by_type(vm, vim.vm.device.VirtualCdrom) if x.key == key]
    if controller:
        dev_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.edit
    else:
        dev_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
    dev_spec.device.key = key
    dev_spec.device.deviceInfo = vim.Description()
    dev_spec.device.deviceInfo.label = 'CD/DVD drive {}'.format(key - 3002)
    dev_spec.device.backing = vim.vm.device.VirtualCdrom.RemoteAtapiBackingInfo()
    dev_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
    dev_spec.device.connectable.startConnected = False
    dev_spec.device.connectable.allowGuestControl = True
    dev_spec.device.controllerKey = config['controller']['key']

    spec = vim.vm.ConfigSpec()
    spec.deviceChange = [dev_spec]
    task = vm.ReconfigVM_Task(spec=spec)
`

What do you mean be getting the drive name?
