### ISSUE TITLE
clone catch vim.fault.CannotAccessVmConfig 

### ISSUE THREAD

**Issue by mygoda** [vmware/pyvmomi#417]
i have a vcenter clusters, that has 4 cluster, named clu1, clu2, clu3, clu4, this when i clone clu1 vm to clu3 use pyvmomi that alert this exception:

vim.fault.CannotAccessVmConfig: (vim.fault.CannotAccessVmConfig) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Unable to access the virtual machine configuration: Unable to access file [POD14-CLU01-VSP01-VOL07] E004308-ubuntu14.1064-20160629134557-7G8NJT3T/E004308-ubuntu14.1064-20160629134557-7G8NJT3T.vmx',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = (vim.fault.CannotAccessFile) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'Unable to access file [POD14-CLU01-VSP01-VOL07] E004308-ubuntu14.1064-20160629134557-7G8NJT3T/E004308-ubuntu14.1064-20160629134557-7G8NJT3T.vmx',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      file = '[POD14-CLU01-VSP01-VOL07] E004308-ubuntu14.1064-20160629134557-7G8NJT3T/E004308-ubuntu14.1064-20160629134557-7G8NJT3T.vmx'
   }
}

so what can i do, and why cause this error. but i clone vm from clu1 to clu3 use vsphere client has no error.and do success. so what casue this.

**Comment by mygoda** [comment]
@dyno @vito  plaease help me, thanks.

**Comment by prziborowski** [comment]
What are you providing for the CloneSpec (and in particular the location/RelocateSpec inside of it)?
If you are providing a destination datastore (assuming that the hosts in clu3 can't access the datastore the source VM is on), then I wouldn't expect you hit this exception.

**Comment by DanielDraganov** [comment]
No response from the reporter. Closing the issue.
