### ISSUE TITLE
How to get the ''Memory usage'' of a host

### ISSUE THREAD

**Issue by sunyaxiong** [vmware/pyvmomi#418]
There a demand that get the ''Memory usage'' through VMware API.
Now I can got the memorySize and numCpuCores ,the API summary.hardware, but can not get ''Memory usage'', the percentage info.
I print the API capability and summary, and so on,  there no that info.

Whether there has an API could satisfy my demand

Have you guys could give me advice,  thanks first

![hostinfo](https://cloud.githubusercontent.com/assets/8956366/16476148/fd0a8d1a-3eb6-11e6-8abb-d4b0cefee515.jpg)

**Comment by prziborowski** [comment]
I believe you will find that information in the ResourcePool (accessible from the ComputeResource, which is the parent of the HostSystem).
ResourcePool's runtime.memory.reservationUsed

Alternatively (I haven't compared the values), under HostSytem's summary.quickStats. overallMemoryUsage.

**Comment by sunyaxiong** [comment]
yeah, as you say, host.summary.quickStats.* has usage of a host

demo for other people who need it
```
def host_mem(self):
        hosts = self.hosts_info()
        vc_usage_mem = 0
        vc_all_mem = 0
        for host in hosts:
            # cpu_usage = host.summary.quickStats.overallCpuUsage
            mem_usage = host.summary.quickStats.overallMemoryUsage
            all_mem = host.hardware.memorySize / 1024 / 1024
            vc_usage_mem += mem_usage
            vc_all_mem += all_mem
            print 'host:{0} usage mem：{1}'.format(host.name, mem_usage)
        print 'VC all usage{0}'.format(vc_usage_mem)
        print 'VC：{0}'.format(vc_all_mem)
```

thanks @prziborowski

**Comment by sunyaxiong** [comment]
Hi, @prziborowski    should I ask one more question?
When i use VirtualMachine's 'runtime.host.summary.managementServerIp' API to get the VCenter IP ,there has a lot of instance's return value is None.
Whether the API which I used is right or there is a bug ?

**Comment by prziborowski** [comment]
If the host is added to vCenter, I would normally expect that value to be populated.
It would be none if the host is not added to vCenter.

If you are seeing inconsistencies with what I'd expect, then I'd say it is a bug.
(vCenter itself queries that property when adding the host to prompt the user that it is already added to a different vCenter).

**Comment by sunyaxiong** [comment]
all the host has added to vCenter allready.

Now I checked all the host again, found that the host return value is NONE ,just happen to three specific host. I think there must be have some configurations or another else different form other hosts.

**Comment by prziborowski** [comment]
Are you saying that VirtualMachine's runtime.host is None?
This case can happen if the VirtualMachine is marked as a template.

**Comment by sunyaxiong** [comment]
not runtime.host, is  'runtime.host.summary.managementServerIp'  ,this api should return the vCenter IP in normal
