### ISSUE TITLE
Delete directory on Datastore

### ISSUE THREAD

**Issue by RobertClove** [vmware/pyvmomi#422]
Can someone please provide a sample to delete a directory on datastore?

**Comment by prziborowski** [comment]
Based on the example for creating a directory:
content.fileManager.DeleteFile("[datastore1] foldername", dc_obj)

(ref: http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.FileManager.html
DeleteDatastoreFile_Task

Deletes the specified file or folder from the datastore. If a file of a virtual machine is deleted, it may corrupt that virtual machine. Folder deletes are always recursive. The datacenter parameter may be omitted if a URL is used to name the file or folder.
If the source is an extent of a virtual disk, this operation treats the extent as a file.

It is important to note that this operation will provide transactional guarantees only for a file. No guarantees are provided when deleting folders. If the intent is to delete a virtual machine registered in the inventory, please refer to Destroy_Task.

Requires Datastore.FileManagement privilege on the datastore.

Required Privileges
Dynamic - See discussion above
Parameters
NAME	TYPE	DESCRIPTION
_this	ManagedObjectReference	A reference to the FileManager used to make the method call.
name	xsd:string	
The name of the file or folder, either a URL or a datastore path referring to the file or folder to be deleted. 
datacenter* P	ManagedObjectReference
to a Datacenter	
If name is a datastore path, the datacenter for that datastore path. Not needed when invoked directly on ESX. If not specified on a call to VirtualCenter, name must be a URL. 
*Need not be set P Required privilege: System.View )

**Comment by RobertClove** [comment]
Can you provide some sample of that ?
I thought of writing the code like this 
def delfile(si,datastorepath):
    content = si.RetrieveContent()
    session_manager = content.sessionManager

    # Get the list of all datacenters we have available to us
    datacenters_object_view = content.viewManager.CreateContainerView(content.rootFolder, [vim.Datacenter],
                                                                      True)

    # Find the datastore and datacenter we are using
    datacenter = None
    datastore = None
    for dc in datacenters_object_view.view:
        datastores_object_view = content.viewManager.CreateContainerView(dc, [vim.Datastore], True)
    content.fileManager.DeleteFile(datastorepath, dc)

Is it correct?

**Comment by prziborowski** [comment]
Do note that calling CreateContainerView should afterward be followed with a Destroy() of that view as vCenter allocates memory for those views and you could end up using quite a bit of resources if you don't clean up (I believe it is freed when your Session logs out, but it is a good pattern to Destroy it when you are finished).

Something tricky with this is any of the datacenters can have a datastore with that path and it may not be unique (which is why the API requires you pass in a datacenter). So having a generic function just pass in a path could technically result in you deleting the wrong folder.

So it might be useful if the user could provide a datacenter unless they are fine with the above.

I'm not too familiar with the container views, so the below is what I'd come up with an example.
Yours would probably work as well (just remember to destroy the views when you are finished).
```
import re

def get_datacenter_datastore(si, dsname):
   for dc in si.content.rootFolder.childEntity:
      for ds in dc.datastore:
         if ds.name == dsname:
            return dc, ds
   raise Exception("Datastore with %s name not found" % dsname)

def delfile(si, datastorepath):
   m = re.match("\[(.*?)\].*", datastorepath)
   if m is None:
      raise Exception("Path does not contain datastore")
   dsname = m.group(1)
   dc, ds = get_datacenter_datastore(si, dsname)
   si.content.fileManager.DeleteFile(datastorepath, dc)
```

**Comment by RobertClove** [comment]
thanks for the file i am also trying for directory 
```
def DeleteDatastoreFile(si, datacenter, datastorename, datastorePath):
    try:
        content = si.RetrieveContent()
        session_manager = content.sessionManager

        # Get the list of all datacenters we have available to us
        datacenters_object_view = content.viewManager.CreateContainerView(content.rootFolder, [vim.Datacenter],
                                                                          True)

        # Find the datastore and datacenter we are using
        datacenter1 = None
        datastore = None
        for dc in datacenters_object_view.view:
            datastores_object_view = content.viewManager.CreateContainerView(dc, [vim.Datastore], True)
            for ds in datastores_object_view.view:
                # if ds.info.name == "datastore1":
                if ds.info.name == datastorename:
                    datacenter11 = dc
                    datastore = ds
                    print type(dc)
                    print dc
                    print type(datacenter11)
                    print datacenter11
        if not datacenter11 or not datastore:
            print("Could not find the datastore specified")
            raise Exception("Could not find the datastore specified {}.".format(datastorename))
        print "BEFORE"
        print type(datacenter11)
        print datacenter11

        #https://github.com/vmware/pyvmomi/blob/master/docs/vim/DatastoreNamespaceManager.rst
        #vim.DatastoreNamespaceManager.DeleteDirectory(datacenter11, datastorePath)
        content.datastoreNamespaceManager.DeleteDirectory(datacenter11, datastorePath)
        print "AFTER"
        #vim.host.DatastoreBrowser.DeleteFile(path)
       # task = vim.FileManager.DeleteDatastoreFile(name, datacenter)
        #time.sleep(50)
        print "DELETED PLEASE CHECK"
    except vmodl.MethodFault as e:
        print("Caught vmodl fault : " + e.msg)
        message = ("Caught vmodl fault : " + e.msg)
        raise Exception(message)

```

i am getting this error 

> <class 'pyVmomi.VmomiSupport.vim.Datacenter'>
> 'vim.Datacenter:datacenter-2'
> <class 'pyVmomi.VmomiSupport.vim.Datacenter'>
> 'vim.Datacenter:datacenter-2'
> BEFORE
> <class 'pyVmomi.VmomiSupport.vim.Datacenter'>
> 'vim.Datacenter:datacenter-2'
> Caught vmodl fault : Invalid datastore path '[datastore1] test'.
> Exception Exception: Caught vmodl fault : Invalid datastore path '[datastore1] test'.

**Comment by prziborowski** [comment]
The datastoreNamespaceManager is used for datastores that don't support a traditional directory creation (I'm thinking things like VSAN or VVOL).
It looks to want it in the /vmfs/volumes/[datastore-uuid]/[directory-uuid] format.

Assuming you are using VMFS or NFS, the fileManager.DeleteFile should also support deleting directories.

**Comment by RobertClove** [comment]
oh ok then how to delete directory from datastores.
If you can provide the code for same i will put it in community sample

**Comment by RobertClove** [comment]
i will post the sample, resolved the issue thanks
