### ISSUE TITLE
Is there a way to open remote power shell as admin using VM ware tools

### ISSUE THREAD

**Issue by RobertClove** [vmware/pyvmomi#427]
I have a python framewrok that uses pyvmomi library of VMWare to perform operations on remote VM. I open the remote VM Power Shell using Pyvmomi library like this 

vim.vm.guest.ProcessManager.ProgramSpec(
        programPath="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe")

This open power shell not as admin.

**Comment by gm0neyl0ve** [comment]
This will, I believe,  connnect as the user you made  the Service Instance connection as. 

If you want to run the command  as a particular user you can try something like this.
It's a way to add users to Admin group on A Windows VM. 

vmcreds = vim.vm.guest.NamePasswordAuthentication(username= vmuser, password=vmpassword)
def RemoteCmd(si, vm, vmcreds, prog, pargs):
    try:
        #vm = vmutils.get_vm_by_name(si, args.vmname)
        cmdspec = vim.vm.guest.ProcessManager.ProgramSpec( arguments=pargs,
                                                                                                    programPath=prog)
        cmdout = si.content.guestOperationsManager.processManager.StartProgramInGuest(vm  = vm,
                                                                                                                                                 auth= creds,
                                                                                                                                                spec= cmdspec)
 
    except vmodl.MethodFault as error:
        print ("Caught vmodl fault : ", error.msg)
        return -1

RemoteCmd(si, vm, vmcreds, 'c:/windows/system32/net.exe', 'localgroup administrators AD DOMAIN\\'+somuser+' /add')
