### ISSUE TITLE
Instant cloning bindings

### ISSUE THREAD

**Issue by Svieg** [vmware/pyvmomi#428]
Hi !
Those python bindings for the vSphere API are really nice. As I was reading about ["instant cloning" on PowerCLI](http://blogs.vmware.com/PowerCLI/2015/08/using-vmware-instant-clone-via-powercli-extensions-fling.html), I wondered if you guys had any bindings for this or even support them on the vSphere API. Do you ? 

Thank you !

**Comment by prziborowski** [comment]
Your timing of question is fairly apt.
Today a fling for instant cloning with pyVmomi was released: https://labs.vmware.com/flings/vmfork-for-pyvmomi

(I have yet to try it)
