### ISSUE TITLE
How to get esxi host in a cluster?

### ISSUE THREAD

**Issue by yangyangyang001** [vmware/pyvmomi#429]
I can get cluster in a datacenter with datacenter.hostFolder.childEntity. but i cann‘t get esxi host info in a cluster, anyone can help me?

**Comment by angarg** [comment]
`cluster.host` should give you a list of `vim.HostSystem` objects

**Comment by sathvikm** [comment]
Below is the script which will display all the Hosts in a given cluster if cluster is not provided displays list of all clusters in the vCenter. 
`

    #!/usr/bin/env python

    """List Of Hosts in a Cluster."""
    from pyVmomi import vim
    from pyVim.connect import SmartConnect, Disconnect
    import atexit
    import argparse
    import getpass
    import ssl
    import requests

    def get_args():
        """Get arguments from CLI."""
        parser = argparse.ArgumentParser(
            description='Arguments for talking to vCenter')

        parser.add_argument('-s', '--host',
                            required=True,
                            action='store',
                            help='vSpehre service to connect to')

        parser.add_argument('-o', '--port',
                            type=int,
                            default=443,
                            action='store',
                            help='Port to connect on')

        parser.add_argument('-u', '--user',
                            required=True,
                            action='store',
                            help='Username to use')

        parser.add_argument('-p', '--password',
                            required=False,
                            action='store',
                            help='Password to use')

        parser.add_argument('--cluster-name',
                            required=False,
                            action='store',
                            default=None,
                            help='Name of the cluster you wish to list the hosts')

        args = parser.parse_args()

        if not args.password:
            args.password = getpass.getpass(
                prompt='Enter password')

        return args


    def get_obj(content, vimtype, name=None):
        return [item for item in content.viewManager.CreateContainerView(
            content.rootFolder, [vimtype], recursive=True).view]

  
    def main():
        args = get_args()
        # Disabling urllib3 ssl warnings
        requests.packages.urllib3.disable_warnings()

        # Disabling SSL certificate verification
        context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        context.verify_mode = ssl.CERT_NONE

        # connect this thing
        si = SmartConnect(
            host=args.host,
            user=args.user,
            pwd=args.password,
            port=args.port,
            sslContext=context)

        # disconnect this thing
        atexit.register(Disconnect, si)

        content = si.RetrieveContent()
        for cluster_obj in get_obj(
                content,
                vim.ComputeResource,
                args.cluster_name):
            if args.cluster_name:
                if cluster_obj.name == args.cluster_name:
                    for host in cluster_obj.host:
                        print host.name
            else:
                print cluster_obj.name


    # start this thing
    if __name__ == "__main__":
        main()
`
