### ISSUE TITLE
Get physical disk info on an esxi host？

### ISSUE THREAD

**Issue by yangyangyang001** [vmware/pyvmomi#431]
I want to find unused disk on an esxi，but I cann‘t’ get physical disk info. anyone can help 么？

**Comment by chengpeng21186** [comment]
I also have this problem , anyone can help?

**Comment by chengpeng21186** [comment]
# datastore information
            storage_system = esxi_host1.configManager.storageSystem
            host_file_sys_vol_mount_info = storage_system.fileSystemVolumeInfo.mountInfo
            for host_mount_info in host_file_sys_vol_mount_info:
                #print host_mount_info
                if host_mount_info.volume.type == "VMFS" or host_mount_info.volume.type == "NFS":
                    #print host_mount_info
                    print 'Datastore name:', host_mount_info.volume.name
                    print 'Datastore capacity:', sizeof_fmt(host_mount_info.volume.capacity)

**Comment by chengpeng21186** [comment]
# datastore information
            storage_system = esxi_host1.configManager.storageSystem
            host_file_sys_vol_mount_info = storage_system.fileSystemVolumeInfo.mountInfo
            for host_mount_info in host_file_sys_vol_mount_info:
                #print host_mount_info
                if host_mount_info.volume.type == "VMFS" or host_mount_info.volume.type == "NFS":
                    #print host_mount_info
                    print 'Datastore name:', host_mount_info.volume.name
                    print 'Datastore capacity:', sizeof_fmt(host_mount_info.volume.capacity)

**Comment by pavan099** [comment]
href [ host reference/host MOB]
datastoreSystem1=href.configManager.datastoreSystem
free_disks=datastoreSystem1.QueryAvailableDisksForVmfs() // list of device which are available to create vmfs.
