### ISSUE TITLE
VimSessionOrientedStub - makeUserLoginMethod

### ISSUE THREAD

**Issue by RainTomassi** [vmware/pyvmomi#432]
Hi, new to pyVmomi, Python, VMWare, etc. :-)   Tasked with moving existing pySphere code to pyVmomi.  We are registering an extension with the extension manager with pySphere (Storing certificate, then logging in later via certificate).  I'd like to do the same with pyVmomi but I'm having some difficulty.  Searching yielded that I'll need to use the makeExtensionLoginMethod(), however, I could not get this to 'work', so as a sanity check and baseline, I tried makeUserLoginMethod() as follows.

```
stub = SoapStubAdapter(host='<fqdn>', ns="vim25/5.5")
sessionStub = VimSessionOrientedStub(stub, VimSessionOrientedStub.makeUserLoginMethod(user, password), 1)
si = vim.ServiceInstance("ServiceInstance", sessionStub)
si.content.sessionManager.sessionList
```

However, this also fails for me.  I traced my issue into the _doLogin() of makeUserLoginMethod().  
```
si = vim.ServiceInstance("ServiceInstance", soapStub)
sm = si.content.sessionManager --> Throws exception

```
si.content.sessionManager seems to throw an exception that _CallLoginMethod() traps in the finally clause.  I don't have much more information than that at the moment. 

My ultimate goal is to get makeExtensionLoginMethod() working, but I'd like to first see makeUserLoginMethod() work as a sanity check.  Any advice, pointers, etc. would be greatly appreciated.   I'm going to dig into this more as I'm adjusting to Python (just learned about pdb), but wanted to get this posted to see if anyone had any ideas. 

Thanks!

**Comment by prziborowski** [comment]
I wish I could say I could reproduce what you are seeing, but using a combination of what you have, it seems to work for me:
```
from pyVmomi import SoapStubAdapter, vim
from pyVim.connect import VimSessionOrientedStub

stub = SoapStubAdapter(host='<ip address>', ns='vim25/5.5')
sessionStub = VimSessionOrientedStub(stub, VimSessionOrientedStub.makeUserLoginMethod('<user>', '<pwd>'), 1)
si = vim.ServiceInstance('ServiceInstance', sessionStub)
si.content.sessionManager.sessionList # lists the sessions
```

For making use of makeExtensionLoginMethod, I'd assume it is similar but your SoapStubAdapter should also include certFile and certKeyFile that point to the certificate you used to register your extension (I also have entries for httpProxyPort=80, httpProxyHost=host and I connect to port 8089 rather than 443 for tunneling).

**Comment by RainTomassi** [comment]
Thank you very much for trying it.  I am embarrassed to say that it was a configuration issue.  The hosts file for the fqdn was pointing to the wrong ip.  Argh.  I printed out the exception returned and it stated a 404 which gave me the clue that something was amiss.  It now works and apologies again :-)   Now, on to the makeExtensionLoginMethod().  

I am structuring it as you mentioned with the cert and key in the SoapStubAdapter, however, I neglected to add the httpProxyPort.  I do recall reading about tunneling the ssl connection through the http connection, so what you say makes sense.  Trying to get all this under my belt, so I really appreciate the advice, thanks again!

**Comment by gthieleb** [comment]
@RainTomassi do you have an example of registering an extension to vcenter and login using certificate using pyvmomi?

**Comment by amudhar** [comment]
@RainTomassi, asking similar to @gthieleb, do you have a working sample of registering an extension with vcenter using SSL cert and key, and then login using the certificate using pyvmomi?

**Comment by RainTomassi** [comment]
@amudhar , @gthieleb 

I've moved away from the VMware world for a while now and haven't kept up to date with these notifications. Apologies for the delay in responding.  I looked through my old code and here's a snippet of my implementation.   I can't offer much else, as I've swapped nearly everything VMware related out of my mind. 

```
  stub = SoapStubAdapter(
          version='vim.version.version10',  # Version5 or higher required
          certFile=self.cert_file,              # Path to certificate file
          certKeyFile=self.key_file,            # Path to private key file
          httpProxyHost=self.hostname,              
          url='https://sdkTunnel:8089/sdk/vimService')    # Tunnel secure connection over http (port 80)
  sessionStub = VimSessionOrientedStub(stub, VimSessionOrientedStub.makeExtensionLoginMethod(self.key))
  self.service_instance = vim.ServiceInstance("ServiceInstance", sessionStub)

```

**Comment by manikantanallagatla** [comment]
Instead of tunneling, can't we directly do https connection with cert and key file generated?
Why are we using HTTP port 80 for tunneling? Can't we use https?
Any help would be appreciated!!
