### ISSUE TITLE
Create Snapshot using virtual machine’s memory and Quiesce guest file system

### ISSUE THREAD

**Issue by RobertClove** [vmware/pyvmomi#436]
Hi,

I want to take snapshot of vm with these following parameter:
1>Snapshot the virtual machine’s memory (memsnap -- boolean)
2>Quiesce guest file system (filesystem ---boolean)

eg def takesnapshot(vmname, memsnap, memsnap):

Can someone provide me the link for the same

**Comment by pavan099** [comment]
vmRef - VM reference obj
vmRef.CreateSnapshot(vm_ref.name, 'foo',memory,quiesce)
memory - True/False
quiesce - True/False
