### ISSUE TITLE
Is there has another  way to get the default IP 

### ISSUE THREAD

**Issue by sunyaxiong** [vmware/pyvmomi#437]
I use pyvmomi to gather the guestInfo,  when the guests are cluster, 'virtualMachine.guest.ipAddress' is the cluster's virtual IP like：‘169.254.1.172’.
 Is there has another way to get the real public IP 

thanks
@prziborowski   I wonder if you can help me

**Comment by prziborowski** [comment]
The vm tools usually expose what the guest reports for its interfaces.
virtualMachine.guest.ipAddress is the best guess, but sometimes not the correct (or desired) one.

Also try under virtualMachine.guest.net[#].ipConfig.ipAddress[#].ipAddress
Note it can be ipv4 and ipv6 addresses.

**Comment by sunyaxiong** [comment]
Thank you for your guidance
virtualMachine.guest.net[#].ipConfig.ipAddress[#].ipAddress is very usefully
this is my code:

<pre>
def get_public_ip(vm):
    guest = vm.guest
    summary = vm.summary
    if hasattr(guest, 'net'):
        if not guest.net:
            # print 'there guest.net is Null'
            ip = summary.guest.ipAddress
            return ip
        else:
            public_nic = guest.net[-1]
            if hasattr(public_nic.ipConfig, 'ipAddress'):
                public_ip = public_nic.ipConfig.ipAddress
                for i in public_ip:
                    if i.state == 'preferred':
                        # print 'guest.net[-1].ipConfig.ipAddress[].ipAddress:state=preferred'
                        ip = i.ipAddress
                        return ip
            else:
                # print 'public_nic.ipconfig has no ipAddress'
                ip = summary.guest.ipAddress
                return ip
</pre>

But this method is not perfect, can this method could be optimizati
@prziborowski

**Comment by prziborowski** [comment]
I'm not positive about what assumptions can be made for the public ip.
I'd also hope that you don't need to have the hasattr for 'net' and 'ipAddress'. They should be at a minimum existing and 0-length.
So you might have to consider that you have to try more than 1 address.
```
def get_public_ip(vm):
   guest = vm.guest
   summary = vm.summary
   if guest is not None:
      ip = [ip.ipAddress for nic in guest.net for ip in nic.ipConfig.ipAddress if ip.state == 'preferred']
   elif summary.guest is not None:
      return [summary.guest.ipAddress]
   else:
      return []
```

Note I haven't tested this out except in my simple environment.

**Comment by sunyaxiong** [comment]
In my production environment , there has an exception in ipConfig.ipAddress that called "AttributeError: 'NoneType' object has no attribute 'ipAddress'".
Here is the code modified:

> <pre>
def print_vm_info(vm):
    guest = vm.guest
    summary = vm.summary
    if guest is not None:
        try:
            ip = [ip.ipAddress for nic in guest.net for ip in nic.ipConfig.ipAddress if ip.state == 'preferred']
            print ip
        except Exception, e:
            print e.message
            ip = [summary.guest.ipAddress]
            print ip
    else:
        print []
</pre>

**Comment by prziborowski** [comment]
I see. I didn't realize that ipConfig could be unset.
A slightly unwieldy line could be:
```
ip = [ip.ipAddress for nic in guest.net if nic.ipConfig is not None for ip in nic.ipConfig.ipAddress if ip.state == 'preferred']
```

**Comment by 15038944478** [comment]
> The vm tools usually expose what the guest reports for its interfaces.
> virtualMachine.guest.ipAddress is the best guess, but sometimes not the correct (or desired) one.
> 
> Also try under virtualMachine.guest.net[#].ipConfig.ipAddress[#].ipAddress
> Note it can be ipv4 and ipv6 addresses.

Excuse me, how to get IPv4 instead of IPv6
