### ISSUE TITLE
Support new version API vim.version.version11

### ISSUE THREAD

**Issue by ray-sh** [vmware/pyvmomi#438]
Any plan to support vim.version.version11?
/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.pyc in CreateDataType(vmodlName, wsdlName, parent, version, props)
    665          vmodlName = ".".join(name[0].lower() + name[1:] for name in names)
    666       _AddToDependencyMap(names)
--> 667       typeNs = GetWsdlNamespace(version)
    668
    669       _dataDefMap[vmodlName] = dic

/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.pyc in GetWsdlNamespace(version)
   1135 def GetWsdlNamespace(version):
   1136    """ Get wsdl namespace from version """
-> 1137    return "urn:" + serviceNsMap[version]
   1138
   1139 ## Get all the versions for the service with specified namespace (partially) ordered

KeyError: 'vim.version.version11'

**Comment by tianhao64** [comment]
@leiding version11 will be supported when the vSphere 6.5 is released, around Dec 2016.

**Comment by alanrenouf** [comment]
We are currently at version 10 in the current API with vSphere 6.0, clearly when version 11 becomes available in a future product version we will move to support this.

**Comment by dasrab** [comment]
how to solve this error

**Comment by DanielDraganov** [comment]
Outdated. vim.version.version11 is currently supported.
