### ISSUE TITLE
ServiceInstance content containerview return incorrect object during high parallel query

### ISSUE THREAD

**Issue by charlesxu2000** [vmware/pyvmomi#445]
Version:
vSphere: v5.5 update 2.
Pyvmomi: 5.5.0.2014.1.1

Issue:
During a parallel execution of retrieving VM objects by VM name:
...
si = si.RetrieveContent();
si.viewManager.CreateContainerView(container, vimtype, True);
for c in containerView.view:
    if c.name == name:
        obj = c
...

The vm object could return wrong object. For example:
We get the VM worker19 from VI which is vm-843.
2016-08-23 16:36:00,724 vmutil.py L67(1599)[INFO]:(worker19) VIM 'vim.VirtualMachine:vm-843'
...
Later, we got exception state the VM no longer existed, but actually the vm object has been changed to vm-861:

2016-08-23 16:36:06,056 api.py L714(1599)[ERROR]:(vmodl.fault.ManagedObjectNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The object has already been deleted or has not been completely created',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   obj = 'vim.VirtualMachine:vm-861'
}

Is VI API and python binding thread safe?  

This problem only occurs when we have highly parallel VI API query/update.

**Comment by tianhao64** [comment]
@charlesxu2000 What operations did you perform on those vms? Did the vm get deleted and recreated by another thread? Do you have multiple vms with the same name? Can you be more specific about what parallel execution means. Are you creating multiple connections? The container view should reflect the actual states in vSphere. If the vm id is different it means it's different vm.

**Comment by charlesxu2000** [comment]
Here is the steps to reproduce this problem:
1) Have created 100 VMs. Each VM has different name.
2) Run 100 different processes try to delete these 100 VMs concurrently by using the VM's name (each VM has different name). Each process does the following steps:
    2.1) Get VI connection by calling connect.Connect() to get connection SI.
    2.2) Get container view by calling SI.RetrieveContent().viewManager.CreateContainerView().
    2.3) Get VM object by iterating through the view and find the name of the VM.
           containerView = content.viewManager.CreateContainerView(container, vimtype, True)
            for c in containerView.view:
                if c.name == name:
                    obj = c
                    return obj
    2.4) Use the VM object to delete that VM.

The problem occurs at step 2.3), it returns the VM object which does not match the VM name. 

There are varies of possibilities the thing goes wrong

- Maybe the vCenter can not handle that many concurrent connection? (but at least we did not see the error when doing the connect.Connect())

- Maybe the containerView returned by the CreateContainerView() is not a snapshot of the current view? After deleting VM, the view name to object mapping shifted?

**Comment by tianhao64** [comment]
@charlesxu2000 You mentioned the vm id was changed. When did you get the id the first time? Did you ever recreated the vm with the same name after it's deleted? Once the vm is created, the id should be the same until it's deleted. 

One possibility I can think of is that the vm may be deleted by another thread after you retrieve the view and before you actually make the delete call. And by the time VC got the delete call, the vm is already deleted and you will get the same message. But you mentioned that each process will only deletes a vm with a specific name and they won't delete other process's vm, then this should not happen.  Have you checked when you get the exception, is the vm with the expected ID still in VC? If not when and how it's deleted?

**Comment by charlesxu2000** [comment]
The following steps are done consecutively:
1) Connect to vCenter, get container view.
2) Retrieve VM object by name from the container view.
3) Delete the VM.

So to answer your first question, get the VM object and delete VM happened one after another, there is no gap in between.

For your second question, every VM has different name. It is not another thread deleted the VM I try to delete in this thread, it is the current thread gets wrong VM object which has been deleted by another thread. So it ends up with the VM I try to delete still exists in vCenter.

Does anyone report the similar issue with vSphere: v5.5 update 2, Pyvmomi: 5.5.0.2014.1.1 before?

**Comment by videte47** [comment]
👍

**Comment by jogipraveen** [comment]
I too have the same problem with 
pyvmomi 6.5
python 2.7.12 

Steps to reproduce:
1. Connect to vSphere.
2. Iterate through list of VM(s).
3. Any other process/script tries to delete/create a VM.

Instead of it's trowing an exception the total script itself failing completely. IMO, we should get an exception to catch.

```  File "/app/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/app/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/app/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/app/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in 
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/app/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/app/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.ManagedObjectNotFound: (vmodl.fault.ManagedObjectNotFound) {
   dynamicType = ,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "The object 'vim.VirtualMachine:vm-230514' has already been deleted or has not been completely created",
   faultCause = ,
   faultMessage = (vmodl.LocalizableMessage) [],
   obj = 'vim.VirtualMachine:vm-230514'
}```

Is there any workaround or fix this kind failure?

**Comment by prziborowski** [comment]
@jogipraveen It just looks like an exception to me. You can catch vmodl.fault.ManagedObjectNotFound and continue, e.g.
```
for vm in view.view:
   try:
      ... # do your action
   except vmodl.fault.ManagedObjectNotFound:
      pass # VM went away, nothing we can really do about that.
```

**Comment by jogipraveen** [comment]
Good catch. Thanks @prziborowski
