### ISSUE TITLE
Modifying virtual machine custom attributes values using pyvmomi

### ISSUE THREAD

**Issue by arvindchandra** [vmware/pyvmomi#447]
There is a thread which talks about creating virtual machine custom attributes https://communities.vmware.com/thread/474322?start=0&tstart=0.

I want to set/get the value of virtual machine custom attribute using pyvmomi.

For example:
We created custom attribute
Name : owner
Type : Virtual Machine

For virtual machine “myvm” I would like to

1. Set the Value to “Bob”
2. Get the Value 
3. Update the Value to “Mike”

using pyvmomi

**Comment by prziborowski** [comment]
Hi Arvind,

Let me start by pointing to the documentation: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.CustomFieldsManager.html

In my example, I already have si, which is my ServiceInstance and vm, which is my VirtualMachine.
```
from pyVmomi import vim

fd = si.content.customFieldsManager.AddFieldDefinition(name='owner', moType=vim.VirtualMachine)
si.content.customFieldsManager.SetField(entity=vm, key=fd.key, value='Bob')
si.content.customFieldsManager.SetField(entity=vm, key=fd.key, value='Mike')
```

The data as it goes through:
```
>>> fd
(vim.CustomFieldsManager.FieldDef) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   key = 8,
   name = 'owner',
   type = str,
   managedObjectType = vim.VirtualMachine,
   fieldDefPrivileges = <unset>,
   fieldInstancePrivileges = <unset>
}

>>> vm.customValue
(vim.CustomFieldsManager.Value) [
   (vim.CustomFieldsManager.StringValue) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      key = 8,
      value = 'Bob'
   }
]
>>> si.content.customFieldsManager.SetField(entity=vm, key=fd.key, value='Mike')
>>> vm.customValue
(vim.CustomFieldsManager.Value) [
   (vim.CustomFieldsManager.StringValue) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      key = 8,
      value = 'Mike'
   }
]
```

Let me know if you need further clarification.

**Comment by arvindchandra** [comment]
I agree with with you partially and I was able to see that information when I was investigating. Issue is that  we can not see which value is for which Name

Suppose this is the use case

Name: Owner
Value: Bob
Type : Virtual Machine

And 
Name: Location
Value: NY
Type: Virtual Machine

When I look at the values I can get "Bob" and "NY". But will not know if "Bob" is value for "Owner"' or "Location".

Is there a way for us to get both Name and Value. That will help in establishing the context.

Thanks
Arvind

**Comment by prziborowski** [comment]
I think you'd have to combine both the field and value to get the name value tuple.
E.g.
```
f = si.content.customFieldsManager.field
for k, v in [(x.name, v.value) for x in f for v in vm.customValue if x.key == v.key]:
   print "Name: %s\nValue: %s" % (k, v)
```
Name: location
Value: NY
Name: owner
Value: Mike

Or if you just want to get the tuples:
```
[(x.name, v.value) for x in f for v in vm.customValue if x.key == v.key]
```
would give you:
[('location', 'NY'), ('owner', 'Mike')]

**Comment by arvindchandra** [comment]
Thanks prziborowski it worked beautifully.
-Arvind

**Comment by Balaji555** [comment]
How can we update the value of existing attribute using java?
