### ISSUE TITLE
Trying to clone a template in a vcenter environment that is not clustered

### ISSUE THREAD

**Issue by pilyk** [vmware/pyvmomi#449]
Hi,

I am trying to clone from a template to a specific ESXi host leveraging the following code snippet:

    relospec = vim.vm.RelocateSpec()
    relospec.host = vmhost
    relospec.datastore = datastore
    relospec.pool = resource_pool

It fails with the following error details:
   error = (vmodl.fault.InvalidArgument) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'A specified parameter was not correct. \n',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      invalidProperty = <unset>
   },

However, if I comment out the line "relospec.host = vmhost", it works by going to a different (default) ESXi host.  

Please note that I have multiple ESXi servers but they are not clustered.  Each ESXi host has the same resourcepools for easy vmotions.

Is there a reason why I encounter an error when specifying relospec.host?  Thanks for the help

**Comment by prziborowski** [comment]
It is hard for me to conclude, but if resource_pool conflicts with vmhost, then it will likely throw an error.
Could you try with:
```
relospec = vim.vm.RelocateSpec()
relospec.host = vmhost
relospec.datastore = datastore
relospec.pool = vmhost.parent.resourcePool
```
and let me know if that succeeds (the VM might end up in the wrong pool)?

**Comment by pilyk** [comment]
Your method did work.  It went to the right vmhost.  However, the VM went to the root of the folder and not in the resource pool as expected.  

It seems that the resource pool found in vCenter (first hit) is not the right one since there will be multiple same resource pool names.  I was able to find the right one using the following code:

    for rp in vmhost.parent.resourcePool.resourcePool:
        if resourcepool:
            if rp.name == resourcepool:
                resource_pool = rp

However, I am wondering if there is a cleaner way to find the right resource pool for a particular host server.  Would I be able to leverage content.viewManager.CreateContainerView(content.rootFolder, vimtype, True) somehow?  If so, then I can use the sample get_obj function and pass the necessary parameters.  Can the content.rootFolder be changed to a particular host? 

I am new to all this so appreciate your patience.

**Comment by prziborowski** [comment]
I believe you can change it to a particular host or compute (or many different objects) to limit the view.
ref: http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.view.ViewManager.html

So perhaps you would need to modify get_obj (I'm not sure how'd you want to go about that), but here is an example (not tested):
```
def get_rp(content, container, vimtype, name):
   obj = None
   cv = content.viewManager.CreateContainerView(container, vimtype, True):
   for view in cv.view:
      if view.name == name:
         obj = view
         break
   return obj

resource_pool = get_rp(content, vmhost.parent, vim.ResourcePool, resourcepool)
```

**Comment by pilyk** [comment]
Thanks for the response.  I will try this out.  The hard part that I didn't get but got from your code is the container and the example of the container which in this case is the vmhost.parent.  Really appreciate it.  I will close this issue as I got what I needed.
