### ISSUE TITLE
How to run a customization during clone?

### ISSUE THREAD

**Issue by go2fast** [vmware/pyvmomi#455]
How do I run a customization (from the vCTR customization specification manager) during a clone? 

I see network customizations, but not something as simple as adding the clone to a domain. I must be missing something basic.

**Comment by prziborowski** [comment]
I've never used customization, so I can't say absolutely, but what I do notice is that customization has an [identity](http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.customization.IdentitySettings.html):
that is subclasses for either windows or linux.

In the linux case the class is vim.vm.customization.LinuxPrep
and has a property for domain.

In the windows case there is either a text blob or a number of properties in vim.vm.customization.Sysprep.
Under identification ([vim.vm.customization.Identification](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.customization.Identification.html)) there are 3 properties that seem relevant:
```
domainAdmin*	xsd:string	
This is the domain user account used for authentication if the virtual machine is joining a domain. The user does not need to be a domain administrator, but the account must have the privileges required to add computers to the domain. 
domainAdminPassword*	CustomizationPassword	
This is the password for the domain user account used for authentication if the virtual machine is joining a domain. 
joinDomain*	xsd:string	
The domain that the virtual machine should join. If this value is supplied, then domainAdmin and domainAdminPassword must also be supplied, and the workgroup name must be empty. 
```

(Sorry for the delay in responding. Let me know if that helps.)

**Comment by gm0neyl0ve** [comment]
Something like this should help:

Customization = vim.vm.customization
sysprep_id = Customization.Identification(joinDomain = 'your.domain.com',
domainAdmin = user+'@your.domain.com', domainAdminPassword = Customization.Password(value=password, plainText=True))
