### ISSUE TITLE
how to get the history of vMotion or Storage vMotion

### ISSUE THREAD

**Issue by jyokako** [vmware/pyvmomi#457]
how to get the history of vMotion or Storage vMotion from vCenter
or which log can get the history like this way by PowerShell
http://www.lucd.info/2013/03/31/get-the-vmotionsvmotion-history/

thank you!

**Comment by prziborowski** [comment]
I have added a sample [relocate_events.py](https://github.com/prziborowski/pyvmomi-community-samples/blob/4e3328722f167dd0165ad24dcd2a709bb248784f/samples/relocate_events.py) that hopefully will be pulled in soon.
Try it out or take a look to see if it does what you want.

**Comment by jyokako** [comment]
@prziborowski 
thank you very much 
i will try your script
