### ISSUE TITLE
Error: 'The input arguments had entities that did not belong to the same datacenter'

### ISSUE THREAD

**Issue by youngbupark** [vmware/pyvmomi#458]
- two datacenters, e.g. datacenter1, datacenter2
- each datacenter has two CLUSTERs e.g. cluster1, cluster2
- the vm template is located in datacenter1 

I tried to clone the template in datacenter1 to new vm in datacenter1 by the below code.
it worked fine when there was only datacenter. but when new datacenter2 was added and the same script ran, the below error happened. 

It worked fine only when I tried to clone to datacenter2, but it doesn't work with the error when trying to clone to datacenter1. 

is there something wrong?

```
datacenter = get_obj(content, [vim.Datacenter], datacenter1)
destfolder = datacenter.vmFolder
datastore = get_obj(content, [vim.Datastore], datastore_name)
cluster = get_obj(content, [vim.ClusterComputeResource], cluster_name)

resource_pool = cluster.resourcePool

# set relospec
relospec = vim.vm.RelocateSpec()
relospec.datastore = datastore
relospec.pool = resource_pool

clonespec = vim.vm.CloneSpec()
clonespec.location = relospec
clonespec.powerOn = power_on

task = template.Clone(folder=destfolder, name=vm_name, spec=clonespec)
wait_for_task(task)
```

Error

  (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: spec.location.host',
   faultCause = (vim.fault.DatacenterMismatch) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = 'The input arguments had entities that did not belong to the same datacenter.',
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      invalidArgument = (vim.fault.DatacenterMismatch.Argument) [
         (vim.fault.DatacenterMismatch.Argument) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            entity = 'vim.HostSystem:host-16',
            inputDatacenter = 'vim.Datacenter:datacenter-2'
         },
         (vim.fault.DatacenterMismatch.Argument) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            entity = 'vim.Folder:group-v3',
            inputDatacenter = 'vim.Datacenter:datacenter-2'
         },
         (vim.fault.DatacenterMismatch.Argument) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            entity = 'vim.ResourcePool:resgroup-8',
            inputDatacenter = 'vim.Datacenter:datacenter-2'
         }
      ],
      expectedDatacenter = 'vim.Datacenter:datacenter-690'
   },
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = 'spec.location.host'
  }

**Comment by gitkodak** [comment]
Did you ever figure this out?  We're getting the exact same issue.

**Comment by superhaoyu** [comment]
I have the same eror

**Comment by prziborowski** [comment]
I would suggest making sure that the resource pool, datastore, vm folder, host all match up to the correct destination datacenter.
It might be necessary with some versions of vCenter to specify other of the optional parameters when changing datacenter (e.g. instead of leaving host blank, try picking one from the cluster).

**Comment by gothicsquash** [comment]
Same problem here in 2019.

**Comment by prziborowski** [comment]
> Same problem here in 2019.

Same suggestion from 2017. Make sure everything points to the same datacenter.
Most likely when using things like:
```datastore = get_obj(content, [vim.Datastore], datastore_name)```
You could get a datastore with the same name on a different datacenter.
Even if they point to the same underlying storage, vCenter will give it a different ID on each datacenter.

Instead try:
```datastore = get_obj(datacenter, [vim.Datastore], datastore_name```

**Comment by gothicsquash** [comment]
Here is a solution.

The problem happens when you have multiple clonespec elements that actually belong to different DataCenters.
In my case it happened that multiple DataCenters shared the same DataStore (or the same name for their DataStores).

To find what's wrong, at first you should look into your clonespec:
```
(vim.vm.CloneSpec) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   location = (vim.vm.RelocateSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      service = <unset>,
      folder = <unset>,
      datastore = 'vim.Datastore:datastore-521',
      diskMoveType = <unset>,
      pool = 'vim.ResourcePool:resgroup-2411',
      host = 'vim.HostSystem:host-43',
      disk = (vim.vm.RelocateSpec.DiskLocator) [],
      transform = <unset>,
      deviceChange = (vim.vm.device.VirtualDeviceSpec) [],
      profile = (vim.vm.ProfileSpec) []
   },
   template = false,
   config = <unset>,
   customization = <unset>,
   powerOn = false,
   snapshot = <unset>,
   memory = <unset>
}
```
Look for fields that are not empty.
Then try this:
```
for item in [clonespec.location.datastore, clonespec.location.pool, clonespec.location.host]:
    while item.parent:
        print{"{} has name {} and its parent {} {}".format(item, item.name, item.parent, item.parent.name)}
        item = item.parent
```
You will see conflicting element right away.

Then, just put the right object to your clonespec, and you're good.
