### ISSUE TITLE
Remove Orphaned VM entries from vCenter when VMs deleted via pyVmomi 

### ISSUE THREAD

**Issue by satwikk** [vmware/pyvmomi#459]
Hello.

I am using two methods to delete VMs-

* vm_ref_1.Destroy_Task()
* vm_ref_2.UnregisterVM()

**In both the cases these two VMs are registered as Orphaned in vCenter** (managing their hosts - while both vm_ref_1 and vm_ref_2 are on the same ESXi host).

**Is there a way to clean those orphaned entries in vCenter via some apis or any script that can be executed on vCenter Server Machine?** _Or a way to refresh the vCenter VM list so that all the orphaned vm entries will disappear!_

Please help with this!

**Comment by prziborowski** [comment]
It sounds like you are destroy/unregistering the VMs directly from the host.
If you do it from vCenter then they won't become orphaned.

If you want to just go through and remove orphaned VMs, you could do:
```
vms = get_obj(content, [vim.VirtualMachine], None)
orphaned = filter(lambda x: x.summary.runtime.connectionState == 'orphaned', vms)
for vm in orphaned:
   vm.Unregister()
```

**Comment by satwikk** [comment]
Accidentally, I found out the solution to my own problem.

There are many sample scripts online available, like the one available [here](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getorphanedvms.py).

But my scenario was specific, 

* I have one vCenter Server machine to manage multiple ESXi hosts in a clustered setup
* Also I am using pyVmomi to automate VM provisioning and their life cycle management

* **What was happening is that, when I deleted a VM via pyVmomi, it used to become "orphaned" in my vCenter Server**

*And I wanted to automatically remove these "Orphaned VM" entries from my vCenter Server*

And the simple solution was to **connect to my vCenter Server machine using pyVmomi apis** (with the same credentials that I used to log into vCenter), and use **UnregisterVM()** of [vim.VirtualMachine](https://github.com/vmware/pyvmomi/blob/master/docs/vim/VirtualMachine.rst)

```python
vmware_session = connect.SmartConnect(host=<vCenter Host IP>, 
					     user=<administrator@vsphere-local>,
					     pwd=<password>)
vm_folders = vmware_session.content.rootFolder.childEntity[0].vmFolder.childEntity

for each_folder in vm_folders:
        vm_s = each_folder.childEntity
        for vm in vm_s:
                if vm.runtime.connectionState == 'orphaned':
                        print "Removing from inventory : ", vm.name
                        vm.UnregisterVM()

```

*And Its Done!*

**Comment by satwikk** [comment]
@prziborowski Thanks for your suggestion buddy, that will also do the trick!

Will close the issue now.
