### ISSUE TITLE
Error in documentation vim.DistributedVirtualSwitch for ReconfigureDVPort

### ISSUE THREAD

**Issue by arielik** [vmware/pyvmomi#471]
In documentation at https://github.com/vmware/pyvmomi/blob/master/docs/vim/DistributedVirtualSwitch.rst the method for reconfigure DVPort is named ReconfigureDVPort and should be ReconfigureDVPort_Task, also the input value should be a list of ConfigSpec type (ConfigSpec[]) and not a single ConfigSpec Object. Please modify.

**Comment by DanielDraganov** [comment]
Outdated
