### ISSUE TITLE
pyvmomi does not set User Agent

### ISSUE THREAD

**Issue by lamw** [vmware/pyvmomi#477]
It seems that pyvmomi does not actually set a User Agent when making requests to vSphere endpoint. It would be really useful if it did set this so that we can identify a given vSphere login that is using pyvmomi. 

Please refer to the following blog post for more details: http://www.virtuallyghetto.com/2016/11/an-update-on-how-to-retrieve-useful-information-from-a-vsphere-login.html

**Comment by tianhao64** [comment]
Thanks @lamw I will take a look at this.
