### ISSUE TITLE
error while using upload file to vm 

### ISSUE THREAD

**Issue by jwed** [vmware/pyvmomi#482]
Hi all, 

I'm facing an error when I use upload_file_to_vm.py it's give me the following error:

Traceback (most recent call last):
  File "upload_file_to_vm.py", line 126, in <module>
    main()
  File "upload_file_to_vm.py", line 92, in main
    tools_status = vm.guest.toolsStatus
AttributeError: 'NoneType' object has no attribute 'guest'

and I checked in vSphere Client the status of the vmtool and it's status was:

VMware Tools: Running (Current).

so what is the problem and is any body used this sample before ??

Thank you

**Comment by gm0neyl0ve** [comment]
Are you using this from the samples?
 
You have not succeeded in getting the vm object. 
I'd throw something like:

print ("VM obj:", vm) 

If it comes back with "None", then your vm info is wrong I'm guessing.
