### ISSUE TITLE
execute_program_in_vm.py in windows VM

### ISSUE THREAD

**Issue by jwed** [vmware/pyvmomi#483]
hello

I used this sample execute_program_in_vm.py on Windows VM and it's give me the following output 

`Program executed, PID is 2772`

but on the other side there is nothing happen, because I'm wating to execute my python file but my python file didn't show anything.

what is the problem and is this sample running on WIndows Vm ??

Thank you

**Comment by cruzanstx** [comment]
Yes the program is running on the windows vm. In order to get output you will have to modify the example to execute cmd.exe with arguments /c "your program" and redirect it's output to a file, then get that file off of the vm via a copy guest to local.
