### ISSUE TITLE
Exception: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by alvion** [vmware/pyvmomi#487]
Exception: <type 'exceptions.RuntimeError'>-- maximum recursion depth exceeded
```

'  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 580, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1364, in InvokeMethod\n    self.ReturnConnection(conn)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1436, in ReturnConnection\n    self._CloseIdleConnections()\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1384, in _CloseIdleConnections\n    i = self.pool.index((conn, lastAccessTime))\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
 '  File "build/bdist.linux-x86_64/egg/pyVmomi/SoapAdapter.py", line 1060, in __getattr__\n    return getattr(self._wrapped, item)\n',
```

**Comment by alvion** [comment]
This is the diff for the fix what I modified, so far so good. for you reference.
[fix-478.diff.txt](https://github.com/vmware/pyvmomi/files/617485/fix-478.diff.txt)

**Comment by magianxd** [comment]
I have met the same exception. Any ideas on this?

**Comment by tianhao64** [comment]
@alvion @magianxd How to reproduce this issue?

**Comment by alvion** [comment]
This is my fix for you guys reference. 

====================
diff --git a/pyVmomi/SoapAdapter.py b/pyVmomi/SoapAdapter.py
index 76b1841..7338c2b 100644
--- a/pyVmomi/SoapAdapter.py
+++ b/pyVmomi/SoapAdapter.py
@@ -1054,10 +1054,10 @@ class _HTTPSConnection(http_client.HTTPSConnection):
          #      dercert = self.sock.getpeercert(False)
          #      # pemcert = ssl.DER_cert_to_PEM_cert(dercert)
 
-   def __getattr__(self, item):
-      if item == 'connect':
-         return self.connect(self._wrapped)
-      return getattr(self._wrapped, item)
+   #def __getattr__(self, item):
+   #   if item == 'connect':
+   #      return self.connect()
+   #   return getattr(self, item)
 
 ## Stand-in for the HTTPSConnection class that will connect to a proxy and
 ## issue a CONNECT command to start an SSL tunnel.
@@ -1281,7 +1281,10 @@ class SoapStubAdapter(SoapStubAdapterBase):
          conn.close()
    else:
       def _CloseConnection(self, conn):
-         conn.close()
+         try:
+            conn.close()
+         except AttributeError:
+             del conn
 
    # Context modifier used to modify the SOAP request.
    # @param func The func that takes in the serialized message and modifies the
@@ -1379,12 +1382,11 @@ class SoapStubAdapter(SoapStubAdapterBase):
       if self.connectionPoolTimeout >= 0:
          currentTime = time.time()
          idleConnections = []
-         for conn, lastAccessTime in self.pool:
-            idleTime = currentTime - lastAccessTime
+         for idx, content in enumerate(self.pool):
+            idleTime = currentTime - content[1]
             if idleTime >= self.connectionPoolTimeout:
-               i = self.pool.index((conn, lastAccessTime))
-               idleConnections = self.pool[i:]
-               self.pool = self.pool[:i]
+               idleConnections = self.pool[idx:]
+               self.pool = self.pool[:idx]
                break
 
          for conn, _ in idleConnections:

====================
The root cause is __getattr__ hit the infinity loop, also I do some improvement on close idle connections.

Thanks,
Alvion
