### ISSUE TITLE
Sample request: Add and remove existing disk to VM

### ISSUE THREAD

**Issue by kunjanramk** [vmware/pyvmomi#489]
I have a VM with 2 disks attached to it. I need to remove one disk temporarily, do some tasks and add again.
I am looking for a sample which can remove disk from a VM and add it back to the VM.

**Comment by DanielDraganov** [comment]
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_raw_disk_to_vm.py
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/delete_disk_from_vm.py
