### ISSUE TITLE
does pyvmomi support migrate vm from one cluster to another cluster

### ISSUE THREAD

**Issue by mygoda** [vmware/pyvmomi#495]
ok，in our company we always have to migrate vm from one cluster to another cluster， i  want to know does pyvmomi support this， and how to do。 i read doc and get like this       
`MigrateVM(pool, host, priority, state):
Migrates a virtual machine's execution to a specific resource pool or host.Requires Resource.HotMigrate privilege if the virtual machine is powered on or Resource.ColdMigrate privilege if the virtual machine is powered off or suspended.`     
does this work for me。

**Comment by mygoda** [comment]
@vito @sigma thanks

**Comment by dorroddorrod** [comment]
Hi,
i'm facing with the same problem..
trying to Relocate() vm to other cluster i get:
a specified parameter was not correct
Selecting destination host and pool

def migrate_vm_to_other_cluster(vm,esx): 
    resource_pool = vm.resourcePool
    vm_relocate_spec = vim.vm.RelocateSpec(host=esx, pool=resource_pool)
    task = vm.Relocate(spec=vm_relocate_spec)
    wait_for_task(task)

someone can help?

**Comment by prziborowski** [comment]
@dorroddorrod Since the VM is changing cluster, the resource pool it is going to use is also going to change, so you can't provide "vm.resourcePool".
You could try using the default resource pool of the host, which can be gather from its parent.
```resource_pool = esx.parent.resourcePool```

**Comment by sankeerthsuru** [comment]
Hi @prziborowski @mygoda @dorroddorrod 
I am trying to migrate VM to a different cluster. With below code, i am able to migrate powered off VMs but Powered on VMs failing with error:
Code
def migrate_Host_StorageVmotion(vm, destination_cluster, destination_ds):
resource_pool = destination_cluster.resourcePool
migrate_priority = vim.VirtualMachine.MovePriority.defaultPriority
vm_relocate_spec = vim.vm.RelocateSpec()
vm_relocate_spec.datastore = destination_ds
vm_relocate_spec.pool = resource_pool
task = vm.Migrate(pool=resource_pool, priority=migrate_priority)
task = vm.Relocate(spec=vm_relocate_spec)
vm relocate spec:
(vim.vm.RelocateSpec) {

   dynamicType = ,

   dynamicProperty = (vmodl.DynamicProperty) [],

   service = ,

   folder = ,

   datastore = 'vim.Datastore:datastore-53003',

   diskMoveType = ,

   pool = 'vim.ResourcePool:resgroup-10067',

   host = ,

   disk = (vim.vm.RelocateSpec.DiskLocator) [],

   transform = ,

   deviceChange = (vim.vm.device.VirtualDeviceSpec) [],

   profile = (vim.vm.ProfileSpec) []

}
Error:
pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {

   dynamicType = ,

   dynamicProperty = (vmodl.DynamicProperty) [],

   msg = 'A specified parameter was not correct: ',

   faultCause = ,

   faultMessage = (vmodl.LocalizableMessage) [],

   invalidProperty =

}

Request you guys to help me with this.

**Comment by prziborowski** [comment]
Do you have a DRS enabled cluster?
The docs state (https://code.vmware.com/apis/358/vsphere/doc/vim.vm.RelocateSpec.html):
> if resource pool is specified, the virtual machine is powered on, and the target pool represents a DRS-enabled cluster, a host selected by DRS is used.
> if resource pool is specified, the virtual machine is powered on, and the target pool represents a cluster without DRS enabled, an InvalidArgument exception is thrown.

So if you don't have DRS enabled, you will have to pick one of the hosts in that cluster and set vm_relocate_spec.host.

**Comment by sankeerthsuru** [comment]
Thanks for your quick response @prziborowski .
We have DRS enabled clusters only. I am not sure why this issue occured. Do you think any other parameter, i have to change

**Comment by prziborowski** [comment]
I would try also specifying a host in the cluster to see if that works or not. According to the docs it shouldn't be needed, but there might be some quirks where a combination of other parameters (such as datastore change the behavior).

**Comment by sankeerthsuru** [comment]
I tried specifying host also and started working.

Thanks @prziborowski

**Comment by pgbidkar** [comment]
Hi @sankeerthsuru , Can we close issue, if it is resolved

Thanks

**Comment by sankeerthsuru** [comment]
> Hi @sankeerthsuru , Can we close issue, if it is resolved
> 
> Thanks

Yes. Please
Thanks
