### ISSUE TITLE
TypeError: 'LazyType' object is not iterable

### ISSUE THREAD

**Issue by zdxerr** [vmware/pyvmomi#496]
I get a type error when trying to create a _ContainerView_ with all _ComputeResource_ on my Server.

Here is the stack trace:

```
  File "D:\Tools\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\pyVmomi\VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "D:\Tools\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\pyVmomi\VmomiSupport.py", line 385, in _InvokeMethod
    list(map(CheckField, info.params, args))
  File "D:\Tools\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\pyVmomi\VmomiSupport.py", line 953, in CheckField
    for it in val:
TypeError: 'LazyType' object is not iterable
```

This can be solved by commenting line 385 in `VmomiSupport.py`:

    # list(map(CheckField, info.params, args))

**Comment by tianhao64** [comment]
@zdxerr Thanks for reporting this issue. Could you share the code snippet that can reproduce this?

**Comment by fwiesel** [comment]
@zdxerr  I would suggest to check that you are passing a list, e.g. `obj_type=[vim.ComputeResource]` instead of `obj_type=vim.ComputeResource`.
At least that was the solution to my problem, which had the same symptom.

**Comment by justjais** [comment]
@zdxerr I am also facing the same issue when trying to create _ContainerView_, but the suggestion for commenting `# list(map(CheckField, info.params, args)` is not working for me. I am trying to create container view for _HostSystem i.e. <class 'pyVmomi.VmomiSupport.vim.HostSystem'>_. Can any one let me know if I am doing something wrong or how can I resolve the respective error.

**Comment by prziborowski** [comment]
@justjais you can follow the sample at [vSphereAutoRestartManager.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vSphereAutoRestartManager.py#L37):
```
    container = content.viewManager.CreateContainerView(
        content.rootFolder, [vim.HostSystem], True)
```

Basically it wants a list() of a type, but you are only giving it the type itself, which it can't iterate.

**Comment by justjais** [comment]
@prziborowski yea it worked as expected when _hostsystem_ passed as list[], thanks.
