### ISSUE TITLE
Get VM resource pool

### ISSUE THREAD

**Issue by cwebb3000** [vmware/pyvmomi#501]
Is there a way to get the resource pool each VM is located in?  I'm working on a cost breakdown script and I need to have it determine what pool the VM is located in using Python.

**Comment by prziborowski** [comment]
At the individual level, each VM object exposes the property of the resource pool it is in.
E.g.: vm.resourcePool

If you are collecting all the VMs and want the associated resource pools, I'd think using the property collector would be faster to run (but maybe take longer to write)
