### ISSUE TITLE
OVF import spec: How to set networkMapping property?

### ISSUE THREAD

**Issue by Tatsh** [vmware/pyvmomi#502]
Anyone know? What I am doing:

```python
    manager = si.content.ovfManager
    spec_params = vim.OvfManager.CreateImportSpecParams(entityName=args.name)
    spec_params.diskProvisioning = args.disk_provisioning

    if args.network_adapter_1:
        dc = objs['datacenter']
        network = get_obj_in_list(args.network_adapter_1, dc.network, module)
        nma = vim.OvfManager.NetworkMapping.Array()
        nm = vim.OvfManager.NetworkMapping(name=args.network_adapter_1,
                                           network=network)
        nma.append(nm)
        spec_params.networkMapping = nma

    import_spec = manager.CreateImportSpec(ovfd,
                                           objs['resource pool'],
                                           objs['datastore'],
                                           spec_params)
```

Under the `if` statement what am I doing wrong? This machine comes up it has some 'default' network.

**Comment by OlhaLesk** [comment]
Have you found out the right configuration? I have the same issue.

**Comment by Tatsh** [comment]
Unfortunately no.

On this project we used Ansible so I used the VMware API to get a shell into the machine and then set up another interface with nmcli. Once that was done, the Ansible playbook switched to SSH.

**Comment by spatjoshi** [comment]
nm = vim.OvfManager.NetworkMapping(name=args.network_adapter_1,
                                           network=network)
VMware docs : A NetworkMapping is a choice made by the caller about which VI network to use for a specific network in the OVF descriptor.

The name is for network name in the OVF not in the host/vcenter
The network is for the port_group network in the host/vcenter

This is the mapping between the OVF network and the actual network in the host. I changed the name to "VM Network" and it worked for me.

**Comment by gurushashank** [comment]
Hi, After a referring a few articles the following worked for me.
```    
`       network = get_obj_in_list("VirtualInterface", dc.network)
        # Virtual interface is the name of the port group network
        nma = vim.OvfManager.NetworkMapping.Array()
        # Let the name equal to VM Network and not the name of the portgroup network
        nm = vim.OvfManager.NetworkMapping(name="VM Network", network=network)
        nma.append(nm)

        cisp = vim.OvfManager.CreateImportSpecParams(diskProvisioning="thin", networkMapping=nma)
        cisp.entityName = gmsname[i]
        cisr = ovfManager.CreateImportSpec(ovf_handle.get_descriptor(),
                                           rp, ds, cisp)
```
`
get_obj_in_list function is as follows:
```
def get_obj_in_list(obj_name, obj_list):
    """
    Gets an object out of a list (obj_list) whose name matches obj_name.
    """
    for o in obj_list:
        if o.name == obj_name:
            return o
    print("Unable to find object by the name of %s in list:\n%s" %
           (o.name, map(lambda o: o.name, obj_list)))
    exit(1)`
`
```
Thanks @spatjoshi , your comment helped me save a lot of time.

**Comment by JacobPersi** [comment]
In the above is `VM Network` the name of the network, or some magic constant?

**Comment by kunal-pmj** [comment]
"VM Network" is name of the network
