### ISSUE TITLE
Creating new Resource Pool, InvalidArgument Error

### ISSUE THREAD

**Issue by NaveenBellary** [vmware/pyvmomi#503]
Hi,

I am trying to create a new resource pool under a cluster and it's giving me InvalidArgumentError. Going through the docs, I realized that the error is thrown if the pool specification is invalid. But, I'm able to manually create the resource pool on vCenter with the same specification. Following is what I'm doing,

```python
configSpec = vim.ResourceConfigSpec()
cpuAllocationInfo = vim.ResourceAllocationInfo()
memAllocationInfo = vim.ResourceAllocationInfo()

 cpuAllocationInfo.limit = 50
 memAllocationInfo.limit = 20

 configSpec.cpuAllocation = cpuAllocationInfo
 configSpec.memoryAllocation = memAllocationInfo

cluster.resourcePool.CreateResourcePool(name, configSpec)
```

I've verified that `cluster` is referring to the same cluster that I want to. The following is the error that gets thrown,

```
 File "test.py", line 1929, in create
    cluster..resourcePool.CreateResourcePool(name, configSpec)
  File "python2.7/site-packages/pyVmomi/VmomiSupport.py", line 570, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "python2.7/site-packages/pyVmomi/VmomiSupport.py", line 376, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1335, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: ',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = <unset>
}
```

**Comment by prziborowski** [comment]
I can understand your confusion, especially since InvalidArgument doesn't list what argument is invalid.
It might be possible that you need to provide more parameters that the UI might be doing without your knowledge.

Try providing some values for reservation, expandableReservation and shares.
E.g.
```
configSpec.cpuAllocation.reservation = 0
configSpec.cpuAllocation.expandableReservation = False
configSpec.cpuAllocation.shares = vim.SharesInfo(shares=10, level='custom')
configSpec.memoryAllocation.reservation = 0
configSpec.memoryAllocation.expandableReservation = False
configSpec.memoryAllocation.shares = vim.SharesInfo(shares=10, level='custom')
```

**Comment by NaveenBellary** [comment]
Hey @prziborowski , no luck even after I made the changes. The status in vCenter for the request is "**A Specified parameter was not correct**" and that doesn't shed any new light.  Is there any way to get to know more about the error?

**Comment by prziborowski** [comment]
Unfortunately when I was testing out, I didn't get any additional details from VC's logs.

VC is checking that all the fields in cpuAllocation and memoryAllocation are set.
It also is validating reservation >= 0, limit >= -1, and shares if they are custom are >= 0.

It could be possible something else is causing the fault in your setup. I was able to have it work with mine with a combination of your code with mine on a DRS cluster with vCenter 6.5.

**Comment by NaveenBellary** [comment]
Thanks @prziborowski , that helped! I am able to create the resource pool now. 

_It would have been easy if pyVmomi displayed the error in a more detailed manner._

**Comment by prziborowski** [comment]
> It would have been easy if pyVmomi displayed the error in a more detailed manner.
Personally, I'm curious of what was the problem in your case?

I will follow up with VMware so that the fault will include more details on invalid arguments.

**Comment by NaveenBellary** [comment]
That would be awesome, thanks!!

The following is the code that worked for me,

```python
    configSpec = vim.ResourceConfigSpec()
    cpuAllocationInfo = vim.ResourceAllocationInfo()
    memAllocationInfo = vim.ResourceAllocationInfo()
    sharesInfo = vim.SharesInfo(level='normal')

    cpuAllocationInfo.reservation = 0
    cpuAllocationInfo.expandableReservation = False
    cpuAllocationInfo.shares = sharesInfo
    cpuAllocationInfo.limit = cpuLimit

    memAllocationInfo.reservation = 0
    memAllocationInfo.expandableReservation = False
    memAllocationInfo.shares = sharesInfo
    memAllocationInfo.limit = memLimit

    
    configSpec.cpuAllocation = cpuAllocationInfo
    configSpec.memoryAllocation = memAllocationInfo

    cluster.resourcePool.CreateResourcePool(name, configSpec)
```
