### ISSUE TITLE
clarify vim.HostSystem.ShutdownHost behaviour

### ISSUE THREAD

**Issue by uganjha** [vmware/pyvmomi#506]
If i will do shutdownHost(force) then it will first power off the vms then it will go for shutdown or directly it will go for shutdown.

Because one of our ESXi contains vcenter so we are doing direct shutdown for that host without powering off vcenter .So do i need to power on vcenter vm again when i power on esxi or vcenter will be in power on state ?

**Comment by prziborowski** [comment]
Shutdown will not poweroff any VMs before running. It is the equivalent of running "/sbin/poweroff" in the console/ssh.
The force option is just letting you run the command without being in maintenance mode first. Maintenance mode would be what relocates the VMs or requires you to power off first.

ESXi will not power on these VMs automatically when it starts back up by default. You would have to use the Autostart feature and enable it for the VMs you want to power on with the host.
From the vSphere Web Client, that would be under the host -> Configure -> VM Startup/Shutdown.
