### ISSUE TITLE
datacenter.py does not have sample code to remove a datacenter

### ISSUE THREAD

**Issue by shashi2713** [vmware/pyvmomi#509]
I am a beginner with python and pyvmomi, i have managed to execute creation of vmare datacenter with datacenter.py, i need a script that can delete (unmanage) a datacenter

**Comment by prziborowski** [comment]
With the managed object, you can typically call Destroy method on it to delete it.
Note for a datacenter, it will unmanage any hosts under it.

If you want an example by supplying the name, you could try the following.
I'm copying quite a bit from datacenter.py.
```
from pyVim.task import WaitForTask
from pyVim.connect import SmartConnect, Disconnect
import cli
PARSER = cli.build_arg_parser()
PARSER.add_argument("-n", "--name",
                    required=True,
                    action="store",
                    help="Name of the Datacenter to create.")
MY_ARGS = PARSER.parse_args()
cli.prompt_for_password(MY_ARGS)
SI = SmartConnect(host=MY_ARGS.host,
                  user=MY_ARGS.user,
                  pwd=MY_ARGS.password,
                  port=MY_ARGS.port)
rootFolder = SI.content.rootFolder
for dc in rootFolder.childEntity:
   if dc.name == MY_ARGS.name:
      WaitForTask(dc.Destroy())
      break
Disconnect(SI)

```

**Comment by shashi2713** [comment]
Thank you for the code, wrote a modified version of the code, It worked.
If there is a better way to map the object rather than looping with for please let me know.
"""
Written by Shashidhar Kulkarni
Github: https://github.com/shashi2713

This sample can be run directly to delete a datacenter, but may be more
useful to import into another project where you need to delete a datacenter
NOTE : for a datacenter, it will unmanage any hosts under it
"""
from pyVmomi import vim
from pyVim.task import WaitForTask
import cli
import ssl
import atexit
from pyVim import connect

def destroy_datacenter(dcname=None, service_instance=None, folder=None):
    """
    Deletes a datacenter with the given name.
    Any % (percent) character used in this name parameter must be escaped,
    unless it is used to start an escape sequence. Clients may also escape
    any other characters in this name parameter.

    An entity name must be a non-empty string of
    less than 80 characters. The slash (/), backslash (\) and percent (%)
    will be escaped using the URL syntax. For example, %2F

    This can raise the following exceptions:
    vim.fault.InvalidName
    vmodl.fault.NotSupported
    vmodl.fault.RuntimeFault
    ValueError raised if the name len is > 79
    https://github.com/vmware/pyvmomi/blob/master/docs/vim/Folder.rst

    :param folder: Folder object to create DC in. If None it will default to
                   rootFolder
    :param dcname: Name for the new datacenter.
    :param service_instance: ServiceInstance connection to a given vCenter
    :return:
    """
    if len(dcname) > 79:
        raise ValueError("The name of the datacenter must be under "
                         "80 characters.")
    if folder is None:
        folder = service_instance.content.rootFolder

    if folder is not None and isinstance(folder, vim.Folder):
        for dc in folder.childEntity:
            if dc.name == MY_ARGS.name:
                print "found datacenter, deleting..."
                is_destroyed = WaitForTask(dc.Destroy())
                break
                return is_destroyed
###################### MAIN #########################################
if __name__ == "__main__":
    PARSER = cli.build_arg_parser()
    PARSER.add_argument("-n", "--name",
                        required=True,
                        action="store",
                        help="Name of the Datacenter to create.")
    MY_ARGS = PARSER.parse_args()
    cli.prompt_for_password(MY_ARGS)
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE
    SI = connect.SmartConnect(host=MY_ARGS.host,
                              user=MY_ARGS.user,
                              pwd=MY_ARGS.password,
                              port=MY_ARGS.port,
                              sslContext=context)
    destroy_datacenter(dcname=MY_ARGS.name, service_instance=SI)
    atexit.register(connect.Disconnect, SI)

**Comment by prziborowski** [comment]
You could try using [SearchIndex](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html)
```
searchIndex = SI.content.searchIndex
dc = searchIndex.FindChild(SI.context.rootFolder, MY_ARGS.name)
if dc is None:
   raise Exception("Unable to find datacenter %s" % MY_ARGS.name)
WaitForTask(dc.Destroy())
```

**Comment by shashi2713** [comment]
Thank you
