### ISSUE TITLE
Get Firewall Rules

### ISSUE THREAD

**Issue by ben29** [vmware/pyvmomi#511]
there is way to get all firewall rules?
and create/edit ?

**Comment by prziborowski** [comment]
Each host has their set of firewall rules.
You can't create them. You can update the list of allowed hosts for a particular rule.
Check out the methods in the [FirewallSystem](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.FirewallSystem.html)

```
host = si.content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0] # first host of the first datacenter
firewallSystem = host.configManager.firewallSystem

# And a trivial example of adding a host to the allowed list for the first rule:
ruleset = firewallSystem.firewallInfo.ruleset[0]
allowedHosts = ruleset.allowedHosts
allowedHosts.ipAddress.append('192.0.20.10')
rulesetSpec = vim.host.Ruleset.RulesetSpec(allowedHosts=allowedHosts)
firewallSystem.UpdateRuleset(ruleset.key, rulesetSpec)
```

I wish I could offer more.
(perhaps someone know other tricks that I don't)

**Comment by ben29** [comment]
i need to print firewallSystem to see all rules?
i try to use also cli.py to edit/remove
but i got error

> Traceback (most recent call last):
>   File "cli.py", line 29, in <module>
>     from tools import cli
> ImportError: cannot import name cli

and i did pip install tools...

**Comment by prziborowski** [comment]
You could print firewallSystem.firewallInfo.ruleset to see all the rules.
I'm not sure why you can't import tools.cli. It should be available under samples (nothing additional to install with pip), so if your working directory is samples, it should import fine.

**Comment by ben29** [comment]
can you give me th efull how to get all firewall rules?
i don't understand..

**Comment by ben29** [comment]
hi thanks for your help
ruleset = firewallSystem.firewallInfo.ruleset[0]
how can i enter service name instead of rule number?
like i want append to ssh-server

thanks

**Comment by prziborowski** [comment]
You could convert it into a dictionary if that makes it easier:
```
rules = dict((x.key, x) for x in firewallSystem.firewallInfo.ruleset)
>>> rules['sshServer']
(vim.host.Ruleset) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   key = 'sshServer',
   label = 'SSH Server',
   required = true,
   rule = (vim.host.Ruleset.Rule) [
      (vim.host.Ruleset.Rule) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         port = 22,
         endPort = <unset>,
         direction = 'inbound',
         portType = 'dst',
         protocol = 'tcp'
      }
   ],
   service = <unset>,
   enabled = true,
   allowedHosts = (vim.host.Ruleset.IpList) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      ipAddress = (str) [],
      ipNetwork = (vim.host.Ruleset.IpNetwork) [],
      allIp = true
   }
}
```

**Comment by ben29** [comment]
thanks..
as you told be before i try to add ip to allow host i get an error:

> (vim.fault.RestrictedVersion) {
>    dynamicType = <unset>,
>    dynamicProperty = (vmodl.DynamicProperty) [],
>    msg = 'Current license or ESXi version prohibits execution of the requested operation.',
>    faultCause = <unset>,
>    faultMessage = (vmodl.LocalizableMessage) []
> }

something wrong with this.
maybe ip limit license.

so how can i change the current ip to new one?

sorry for crazy you.

**Comment by prziborowski** [comment]
That fault actually implies that the license you are using doesn't support using the API.
You need at least a Foundation level license for vSphere API usage.

**Comment by ben29** [comment]
thanks a lot you great person
