### ISSUE TITLE
How to create filtered views?

### ISSUE THREAD

**Issue by hryamzik** [vmware/pyvmomi#512]
Everything I've found on google points to perl implementations, like [this post](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/55a8bd37-3cb5-47bf-b523-cdc55a9d29c6/0a25a243-2c31-4093-b351-ae2065dc490f/doc/viperl_advancedtopics.5.2.html).

Is there a way to get a list of only powered on VMs without receiving all `vim.VirtualMachine` objects and then filtering them?

**Comment by prziborowski** [comment]
I don't know of anything built into the server-side to give that kind of filtering.
Also pyVmomi doesn't seem to offer find_entity_view(s) functions, which appears to do client-side filtering.

The lightest-weight (in regards to a large environment and reducing round-trips) would be to use the [PropertyCollector](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vmodl.query.PropertyCollector.html)
and filter on the runtime.powerState for vim.VirtualMachine object.
Then return all the VMs that match the powerState you are interested in.

Code-wise it is more than I'd like to dump into a comment, so I'll add a sample script and point you there...

**Comment by prziborowski** [comment]
Here is an example of using the property collector as a first step to filtering: [filter_vms.py](https://github.com/prziborowski/pyvmomi-community-samples/blob/master/samples/filter_vms.py)

**Comment by hryamzik** [comment]
Wow, thanks @prziborowski!
