### ISSUE TITLE
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission)

### ISSUE THREAD

**Issue by Sglua** [vmware/pyvmomi#513]
I use pyVmomi6.0.0 and python 2.7.12 
code:
import ssl
from pyVim import connect
from pyVim.connect import SmartConnect
sslcontext=ssl._create_unverified_context()
connection = SmartConnect(host=self.ipadd, port=443, user=self.user, pwd=self.password, sslContext=sslcontext)

When i connect to vcenter5.5,it`s success. but when i try to connect vcenter6.0,I receive the following error :
pyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Permission to perform this operation was denied.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'

**Comment by Sglua** [comment]
I had found the reason:
https://kb.vmware.com/selfservice/search.do?cmd=displayKC&docType=kc&docTypeID=DT_KB_1_1&externalId=2114561

**Comment by einarc** [comment]
Thanks so much!!! This helped

**Comment by DruvaIT** [comment]
The above link is not working can you please provide the updated link

**Comment by hikari661** [comment]
> The above link is not working can you please provide the updated link

Searching the broadcom support site for the vmware kb no. of 2114561 returns this article. It seems to be relevant to the problem, though I'm not 100% sure.

https://knowledge.broadcom.com/external/article?articleNumber=335973
