### ISSUE TITLE
Do I need vCenter to using pyvmomi?

### ISSUE THREAD

**Issue by rehmanzile** [vmware/pyvmomi#515]
I would like to use pyvmomi for ESX chassis without the vCenter/vSphere. Does this tool allow me to provision VMs on ESX without having a vCenter or vSphere license? Thanks.

**Comment by prziborowski** [comment]
The ESXi hosts will need at least a Foundation license to use the API.

**Comment by rehmanzile** [comment]
So I don't have to have a vCenter license? Correct?

**Comment by prziborowski** [comment]
That is correct.

**Comment by rehmanzile** [comment]
👍
