### ISSUE TITLE
Guest operations

### ISSUE THREAD

**Issue by emil45** [vmware/pyvmomi#530]
Hello guys,
If I want to preform an operation on guest OS,
Like vm.guest.guestFamily or guestOperationManager,
What should I check to know I can preform the operations:
1. vm.guest.toolsRunningStatus
2. vm.guest.interactiveGuestOperationReady

I very confused because Im used to check the vTools, if vTools is 'guestToolsRunning' so I know I can preform actions on guest OS.
But now I saw this new method 'interactiveGuestOperationReady', what should I use ?

Thank you !

**Comment by emil45** [comment]
Someone ?

**Comment by prziborowski** [comment]
#2 will either be vm.guest.guestOperationReady or vm.guest.interactiveGuestOperationReady depending on what [authentication](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.guest.GuestAuthentication.html) you use.
If you set interactiveSession=true in that (and use NamePasswordAuthentication), then you need to ensure interactiveGuestOperationReady is true.

I'm hazy on the details of the interactive one. I thought it was more of the session that is currently active (similar to if you viewed it with the remote console of the UI client).
