### ISSUE TITLE
Managed objects timeout

### ISSUE THREAD

**Issue by emil45** [vmware/pyvmomi#531]
Hello guys,

In our project we use the same VirtualMachine managed object very often, and then there is a long period of time that we dont use the object and dont use the service_instance (the code keeps running - service).

And after that time if the code tries to get the virtual machine name it get exception of "Unauhorized",
But the weird thing that the service_instance is alive !
He can reqeust the vcenter without any exception.

Is there any timeout to managed objects ?

**Comment by tianhao64** [comment]
@emil45 I believe the session is timed out and you need to use sessionManager to login again. 
You can increase the timeout setting by following here: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2004663

**Comment by emil45** [comment]
Thanks man, it seems like you are right.
