### ISSUE TITLE
Is there some api for deploying ova file?

### ISSUE THREAD

**Issue by Bindong18** [vmware/pyvmomi#532]

**Comment by prziborowski** [comment]
There isn't an API for deploying ova or ovf in 1 step.
ova is just an archived ovf + disks, so with some work you could treat it similar to deploying ovf + disks.

https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/deploy_ovf.py
is an example for deploying ovf.

**Comment by Bindong18** [comment]
@prziborowski 
Thank you very much. 
With the sample you provided:
keepalive_thread = Thread(target=keep_lease_alive, args=(lease,))
            keepalive_thread.start()
            # POST the VMDK to the host via curl. Requests library would work
            # too.
            curl_cmd = (
                "curl -Ss -X POST --insecure -T %s -H 'Content-Type: \
                application/x-vnd.vmware-streamVmdk' %s" %
                (args.vmdk_path, url))
            system(curl_cmd)
            lease.HttpNfcLeaseComplete()
            keepalive_thread.join()
I encountered one issue below:
IO errorcurl: (6) Could not resolve host: application

Could you pls. tell me how to resolve?

BTW: How can I set the  propertyMapping for vim.OvfManager.CreateImportSpecParams ?
Suppose I have property :  --prop:"vami.ipv4.Search"="192.168.2.2/24" 

Thank you very much

**Comment by Bindong18** [comment]
@prziborowski  
I have resolved the issue : IO errorcurl: (6) Could not resolve host: application

Could you pls. tell me how I can set the propertyMapping for vim.OvfManager.CreateImportSpecParams ?

 Suppose I have property : --prop:"vami.ipv4.Search"="192.168.2.2/24"

My sample code is as follows:
 propertyMappingDict ={'ipv4': '192.168.2.2/24'}                     
 spec_params = vim.OvfManager.CreateImportSpecParams(entityName='test',
                                                        diskProvisioning ='thin',
                                                        propertyMapping= propertyMappingDict
But I got the following error:
TypeError: For "propertyMapping" expected type vim.KeyValue, but got str

Thank you very much

**Comment by prziborowski** [comment]
As it wants a [KeyValue](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.KeyValue.html) array then perhaps we can go with that:
```
from pyVmomi import vim

propertyMappingDict ={'ipv4': '192.168.2.2/24'}
mapping = []
for k in propertyMappingDict:
   v = propertyMappingDict[k]
   mapping.append(vim.KeyValue(key=k, value=v))

spec_params = vim.OvfManager.CreateImportSpecParams(entityName='test',
                                                    diskProvisioning='thin',
                                                    propertyMapping=mapping)

```

**Comment by Bindong18** [comment]
@prziborowski 
Thank you very much. It's working.

I have another question:
Is there some code to get ovf and vmdk from ova( suppose there is only ova in the folder) ?

**Comment by Bindong18** [comment]
@prziborowski 
Or is there some code to unzip OVA file?

**Comment by prziborowski** [comment]
Sorry for the delay. I don't know of a method if the ova file is remote (a url).
If the file is local then you can use [tarfile](https://docs.python.org/2/library/tarfile.html) module
```
import tarfile
t = tarfile.open('/path/to/ova')
ovffilename = list(filter(lambda x: x.endswith(".ovf"), t.getnames()))[0]
ovffile = t.extractfile(ovffilename)
# you can modify sample's get_ovf_descriptor to take in a file object rather than opening
# and pass in ovffile
```

And for the disks you can extract them from the ova in a similar manner (or iterate t.getnames() for them).

**Comment by Bindong18** [comment]
@prziborowski 
Thank you very much, I can get ovf descriptor  with your sample code.

But I still don't know how to get vmdk and pass it to the following curl command.(Pls. see vmdkPath)
 curl_cmd = (
                "curl -Ss -X POST --insecure -T %s -H 'Content-Type:application/x-vnd.vmware-streamVmdk' %s" %
                (vmdkPath, url))

Could you pls. help more?

Thank you very much

**Comment by prziborowski** [comment]
You might be able to do something like:
```
for deviceUrl in lease.info.deviceUrl:
   url = deviceUrl.url.replace('*', args.host)
   ovffilename = list(filter(lambda x: x == deviceUrl.importKey))[0]
   ovffile = t.extractfile(ovffilename)

   headers = { 'Content-Length' : ovffile.size }
   response = urllib2.urlopen(url, ovffile, headers)
```

But I haven't tried it, so any of that might not work. Ideally with a file handle rather than an extracted file, it should save time & space to not really extract the file. But for this you'd have to not call out to curl itself. If the above doesn't work, perhaps pycurl would help in this.

**Comment by Bindong18** [comment]
@prziborowski 
Thank you very much.
Let me try

**Comment by prziborowski** [comment]
My sample had lots of issues with it.
https://gist.github.com/prziborowski/1d6b803b56abde2f0d0a4f4d2d7d0b49
I actually tested the above out and it worked on my ESXi box, so I hope that is better to work from.

**Comment by DanyC97** [comment]
so i guess we can close this issue as being done now that @prziborowski provided the script ?

**Comment by kiranbanna** [comment]
I am trying to deploy a VM from an ova file located in the content library of a vmware host. Is there a sample that I can use to do that through pyvmomi? I just started using pyvmomi sdk. I found the following code to do that through vmware sdk:

Python Example of Deploying a Virtual Machine from a Library Item on a Resource Pool
This example is based on the deploy_ovf_template.py sample fileǯ This file is located in the following vSphere Automation SDK for Python
directory: /client/samples/src/vsphere/samples/contentlibrary/ovfdeploy.

from com.vmware.vcenter import ovf_client
import uuid

# Create a VM deployment specification to accept any network resource.
deployment_spec = ovf_client.LibraryItem.ResourcePoolDeploymentSpec()
deployment_spec.accept_all_eula = True

# Create deployment target spec to accept any resource pool.
target_spec = ovf_client.LibraryItem.DeploymentTarget()

# Initiate synchronous deployment operation.
item_stub = ovf_client.LibraryItem(my_stub_config)
result = item_stub.deploy(my_library_item_id,
                                            target_spec,
                                            deployment_spec,
                                            client_token=str(uuid.uuid4())

# Verify deployment status.
print("Resource Type={} (ID={}) status:".format(result.resource_id.type, result.resource_id.id))
if result.succeeded == True :
   print("Resource instantiated.”)
else :
  print("Instantiation failed.")
if result.error is not None :
   for error in result.error.errors :
         print("Error {}".format(error.message))
   if len(result.error.warnings) > 0 :
         print("Warnings:")
         for warning in result.error.warnings :
              print("{}".format(warning.message))
  if len(result.error.information) > 0 :
         print("Messages:")
         for info in result.error.information :
               for message in info.messages :
                     print("{}".format(message))

I looked at the samples and found deploy_ova.py but it deploys vm using ova files on a local machine. 

I appreciate any help related to this.

**Comment by prziborowski** [comment]
deploy_ova.py can deploy remote (http) paths. It does pass traffic through the local machine though.

**Comment by kiranbanna** [comment]
yes. deploy_ova can deploy local file or remote http paths. But it doesn't deploy a ova file located in a content library on a vmware host machine. Is there any code snippet that I can use to do that.

**Comment by prziborowski** [comment]
There is no content library interaction with pyVmomi. It is not part of this API.
I'd have to point you over to content library samples: https://github.com/vmware/content-library-api-samples

**Comment by srg1177** [comment]
hey @prziborowski, thanks for all your work! 
Asking just in case, do you  have a similar script but for export_ova ?

**Comment by DanielDraganov** [comment]
I guess this could help: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/export_vm.py
