### ISSUE TITLE
/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 451, in _Serialize\n    self.writer.write('<{0}{1}>{2}</{0}>'.format(info.name, attr, result))\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by HappyFreeAngel** [vmware/pyvmomi#533]
[centos@localhost happy.vmware]$ more vmware_guest_demo.yml
---
# Create a new VM on an ESX server

- name: create some vms
  hosts: localhost
  connection: local

  tasks:
  - name: create the VM from template
    vmware_guest:
      hostname: vcenter.myvcenter.com
      username: administrator@vsphere.local
      password: mypassword
      validate_certs: no
      esxi_hostname: 192.168.2.20
      datacenter: mydatacenter
#      folder: ansible_deploy
      name: testvm_2
      state: poweredon
#      guest_id: centos64guest
      disk:
      - size_gb: 10
        type: thin
        datastore: sas_datastore
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
      nic:
      - type: vmxnet3
        network: VM Network
        network_type: standard 

#      networks:
#      - name: VM Network
#        ip: 192.168.2.44
#        netmask: 255.255.255.0
#        mac: 'aa:bb:dd:aa:00:14'
      template: centos7dockerjdk8template
      wait_for_ip_address: yes
    register: deploy
[centos@localhost happy.vmware]$ 

[centos@localhost happy.vmware]$ ansible-playbook -vvv vmware_guest_demo.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

PLAYBOOK: vmware_guest_demo.yml ************************************************
1 plays in vmware_guest_demo.yml

PLAY [create some vms] *********************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: centos
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430 `" && echo ansible-tmp-1490832657.66-250974702644430="` echo ~/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpa3Zjrg TO /home/centos/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430/ /home/centos/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/centos/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430/setup.py; rm -rf "/home/centos/.ansible/tmp/ansible-tmp-1490832657.66-250974702644430/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [create the VM from template] *********************************************
task path: /home/centos/happy.vmware/vmware_guest_demo.yml:9
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: centos
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727 `" && echo ansible-tmp-1490832658.07-122352786121727="` echo ~/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpr1hb3W TO /home/centos/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/centos/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727/ /home/centos/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/centos/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727/vmware_guest.py; rm -rf "/home/centos/.ansible/tmp/ansible-tmp-1490832658.07-122352786121727/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_o4WYMG/ansible_module_vmware_guest.py", line 959, in <module>
    main()
  File "/tmp/ansible_o4WYMG/ansible_module_vmware_guest.py", line 937, in main
    wait_for_ip=module.params['wait_for_ip_address']
  File "/tmp/ansible_o4WYMG/ansible_module_vmware_guest.py", line 632, in deploy_template
    task = template.Clone(folder=destfolder, name=self.params['name'], spec=clonespec)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1318, in InvokeMethod
    req = self.SerializeRequest(mo, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 938, in SerializeRequest
    result.append(_SerializeToUnicode(arg, param, self.version, nsMap))
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 180, in _SerializeToUnicode
    SoapSerializer(writer, version, nsMap).Serialize(val, info)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 255, in Serialize
    self._Serialize(val, info, self.defaultNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 387, in _Serialize
    self._Serialize(it, itemInfo, defNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 451, in _Serialize
    self.writer.write('<{0}{1}>{2}</{0}>'.format(info.name, attr, result))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "vmware_guest"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_o4WYMG/ansible_module_vmware_guest.py\", line 959, in <module>\n    main()\n  File \"/tmp/ansible_o4WYMG/ansible_module_vmware_guest.py\", line 937, in main\n    wait_for_ip=module.params['wait_for_ip_address']\n  File \"/tmp/ansible_o4WYMG/ansible_module_vmware_guest.py\", line 632, in deploy_template\n    task = template.Clone(folder=destfolder, name=self.params['name'], spec=clonespec)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 580, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 386, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 1318, in InvokeMethod\n    req = self.SerializeRequest(mo, info, args)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 938, in SerializeRequest\n    result.append(_SerializeToUnicode(arg, param, self.version, nsMap))\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 180, in _SerializeToUnicode\n    SoapSerializer(writer, version, nsMap).Serialize(val, info)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 255, in Serialize\n    self._Serialize(val, info, self.defaultNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 340, in _Serialize\n    self._SerializeDataObject(val, info, attr, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 483, in _SerializeDataObject\n    self._Serialize(getattr(val, prop.name), prop, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 340, in _Serialize\n    self._SerializeDataObject(val, info, attr, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 483, in _SerializeDataObject\n    self._Serialize(getattr(val, prop.name), prop, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 387, in _Serialize\n    self._Serialize(it, itemInfo, defNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 340, in _Serialize\n    self._SerializeDataObject(val, info, attr, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 483, in _SerializeDataObject\n    self._Serialize(getattr(val, prop.name), prop, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 340, in _Serialize\n    self._SerializeDataObject(val, info, attr, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 483, in _SerializeDataObject\n    self._Serialize(getattr(val, prop.name), prop, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 340, in _Serialize\n    self._SerializeDataObject(val, info, attr, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 483, in _SerializeDataObject\n    self._Serialize(getattr(val, prop.name), prop, currDefNS)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 451, in _Serialize\n    self.writer.write('<{0}{1}>{2}</{0}>'.format(info.name, attr, result))\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
	to retry, use: --limit @/home/centos/happy.vmware/vmware_guest_demo.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

[centos@localhost happy.vmware]$

**Comment by tianhao64** [comment]
This is fixed in #528
