### ISSUE TITLE
I am unable to add a new RDM, need help with right code

### ISSUE THREAD

**Issue by shashi2713** [vmware/pyvmomi#534]
# Define spec
                disk_spec = self.pyVmomi.vim.vm.device.VirtualDeviceSpec()

                # Spec for operation
                disk_spec.operation = self.pyVmomi.vim.vm.device.VirtualDeviceSpec.Operation.add

                # Define device
                disk_spec.device = self.pyVmomi.vim.vm.device.VirtualDisk()
                disk_spec.device.unitNumber = unit_number
                disk_spec.device.controllerKey = 1000

                # Define file operation
                disk_spec.fileOperation = "create"

                # Disk is being backed by object tat has capability to add RDM
                #disk_spec.device.backing = self.pyVmomi.vim.vm.device.VirtualDisk.RawDiskMappingVer1BackingInfo()
                disk_spec.device.backing = self.pyVmomi.vim.vm.device.VirtualDisk.RawDiskVer2BackingInfo()
                #disk_spec.device.backing.diskMode = 'persistent'
                #disk_spec.device.backing.lunUuid = "0200050000600601606d2122006a9a04aca5dfe111524149442035"
                #disk_spec.device.backing.compatibilityMode = "physical"

**Comment by shashi2713** [comment]
Need help. can anybody help??

**Comment by vikentiik** [comment]
you never described your problem.
could you share what is the error message that you receive?
could you remove comments and leave lines that you actually run?

I'd say RawDiskMappingVer1BackingInfo is the correct type for the backing. 
Also IIRC you should also set disk_spec.device.backing.deviceName which is 'vml.' + disk_spec.device.backing.lunUuid

My approach always has been to find the type I need (RawDiskMappingVer1BackingInfo) in vSphere API reference, and just see which fields are mandatory. Then figure out where it comes from.

**Comment by skmuttlu** [comment]
disk_mode = str(options['disk_mode'])
        vmdisk_type = str(options['vmdisk_type'])
        comp_mode = "physicalMode"
        if vmdisk_type.lower() == "vrdm":
            comp_mode = "virtualMode"

        pvlun = self._get_pvlun(lunobj)
        assert pvlun, "Failed to fetch pyvomi lun object for {}".format(
            lunobj.vol_uuid)
        search_index = self._esxhost.serviceinstance.content.searchIndex
        pvvm = search_index.FindByUuid(None, vmobj.bios_uuid, True)
        assert pvvm, "{} VM not found".format(vmobj.name)
        dev_changes = []

        datastore = self.local_datastores[0]
        # create DS dir on a given datastore
        ds_name = datastore.info.name.strip()
        path_on_ds = '[' + ds_name + ']' + pvvm.name
        content = self._esxhost.serviceinstance.RetrieveContent()
        # If DS dir is already exists
        try:
            content.fileManager.MakeDirectory(path_on_ds)
        except vim.fault.FileAlreadyExists:
            pass

        # Check for free slots in an active vSCSI controller
        self._scsi_cntlr, self._unit_number =\
            self._verify_add_vscsi_cntlr(pvvm, disk_count, self._unit_number)

        spec = vim.vm.ConfigSpec()
        disk_spec = vim.vm.device.VirtualDeviceSpec()
        # Spec for operation
        disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
        disk_spec.fileOperation = "create"
        # Define device
        disk_spec.device = vim.vm.device.VirtualDisk()
        disk_spec.device.unitNumber = self._unit_number
        disk_spec.device.controllerKey = self._scsi_cntlr.key

        # Disk is being backed by an object that has capability to add RDM
        disk_spec.device.backing = vim.vm.device.VirtualDisk.RawDiskMappingVer1BackingInfo()
        disk_spec.device.backing.lunUuid = pvlun.uuid
        disk_spec.device.backing.compatibilityMode = comp_mode
        disk_spec.device.backing.fileName = path_on_ds + '/' + \
            pvvm.name + '_rdm_' + str(self._unit_number) + '.vmdk'
        if (comp_mode == "virtual" and disk_mode.lower() not in VDSMS):
            disk_mode = "Persistent"
        disk_spec.device.backing.diskMode = disk_mode
        disk_spec.device.backing.deviceName = pvlun.deviceName
        disk_spec.device.backing.datastore = datastore
        dev_changes.append(disk_spec)
        spec.deviceChange = dev_changes
        task = pvvm.ReconfigVM_Task(spec=spec)
