### ISSUE TITLE
API support to create a file on VM

### ISSUE THREAD

**Issue by shyamachilles** [vmware/pyvmomi#535]
Do we have any API support to create an empty file at a given location with the name chosen by the user on a VM just cloned/created, assuming we know its IP address.

**Comment by vikentiik** [comment]
I'm not saying no, but I would just scp the file to the VM.

**Comment by alanjcastonguay** [comment]
This is possible via VMware Tools and https://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/vim.vm.guest.FileManager.html#initiateFileTransferToGuest - take a look at the sample https://github.com/vmware/pyvmomi-community-samples/blob/836eddf1586a917710d4dcf2ab631fb6c1e45699/samples/upload_file_to_vm.py

**Comment by shyamachilles** [comment]
Thanks @vikentiik anf @alanjcastonguay for the replies. 

Many thanks @alanjcastonguay - your pointers helped. I used fileManager.CreateTemporaryFileInGuest().

Closing this issue.
