### ISSUE TITLE
Not getting viewManager value from content while serviceInstance created using SoapStubAdapter

### ISSUE THREAD

**Issue by ekta-dakwala** [vmware/pyvmomi#537]
Hi All

I do connection to vSphere Client using SmartConnect method for the first time and store cookie getting from serviceInstance
`service_instance._stub.cookie`

Now next time, instead of doing connection again through SmartConnect, i want to use stored cookie to create service instance.
I am doing so using below code

```
cookie = cache_details['cookie']  # fetching already stored cookie
soapStub = SoapStubAdapter(host=args.host, sslContext=context)
service_instance = vim.ServiceInstance("ServiceInstance",soapStub)
service_instance._stub.cookie = cookie
content = service_instance.RetrieveContent()
```

But by this way, i am not getting value for many properties from content, specifically viewManager.
Without viewManager, i cant go further to collect data of any type.

To explain this, i have created and attached sample script here.
Run test_view_manager.py file by passing these args:  -s VSPHERE_HOST -u USER -p PASSWORD

You can run script first time and see printed result of service content. All properties are set.
i store cookie value in file 'cache_info.txt'.

Now run it aging and see printed result, it has many  property values <unset>
This time i am creating service instance using SoapStubAdapter by setting stored cookie value.

Am i doing something wrong?
or there is no way to get all content properties by creating service Instance using existing cookie?

Please help.

Thanks

[sample_script.zip](https://github.com/vmware/pyvmomi/files/902482/sample_script.zip)

**Comment by prziborowski** [comment]
The cookie that you are storing will only be valid while the session is still active.
You have ```        atexit.register(connect.Disconnect, service_instance)```
which is going to disconnect the session as soon as the script finishes.
You should remove that.

**Comment by ekta-dakwala** [comment]
@prziborowski 
i tried after removing code of disconnect from my script, but still getting same result
```
atexit.register(connect.Disconnect, service_instance)
atexit.register(endit)
```
So it can not be that issue, because if you have seen by running my script, i get some other properties like about info, propertyCollector, rootFolder, SessionManager etc. in response while connecting through cookie. 
If it's connection issue, then i won't get other properties as well.

I have attached file showing response i am getting while retrieving content in case of cookie

[response_through_cookie.txt](https://github.com/vmware/pyvmomi/files/905711/response_through_cookie.txt)

**Comment by prziborowski** [comment]
OK, I see what else is going on.
In addition to saving the cookie, you probably should be saving the version you connected with as that information isn't being passed along when you create SoapStubAdapter in the second call.

```
        cache_dict = {}
        cache_dict.update({args.host:
             {'cookie': service_instance._stub.cookie,
              'time': time.strftime("%Y-%m-%d %H:%M:%S"),
              'version': service_instance._stub.version,
             }})
        write_cache(cache_dict)
```

And reading:
```
            version = cache_details['version']

            soapStub = SoapStubAdapter(host=args.host, version=version)
```

**Comment by ekta-dakwala** [comment]
@prziborowski 
Yes it worked as expected after passing version in SoapStubAdapter.
Thank you 👍

**Comment by zagpoint** [comment]
How do I detect a session that is saved in my cookie cache but terminated already on vc side?

pyVmomi.VmomiSupport.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'Sessions.TerminateSession'
}

**Comment by zagpoint** [comment]
ok. It appears that I can inspect the si.content.sessionManager.currentSession. An expired session would have this set to None.
