### ISSUE TITLE
How to override VLAN settings in DistributedVirtualPort ?

### ISSUE THREAD

**Issue by rreubenur** [vmware/pyvmomi#538]
I have enabled the override option in the portgroup manually.

Now I'm trying to override a particular port's VLAN settings. Continuously getting the error that ``` Cannot complete operation due to concurrent modification by another operation ``` . The given below code shows that I'm trying to modify a single port . So not sure why I'm getting concurrent modification error.

I'm also not able to figure out the override vlan option in the DVPortConfigSpec.  

```

        dvs = get_obj(si.content, [vim.DistributedVirtualSwitch],
                      dvs_name, si.content.rootFolder)
        dv_port_config_spec = vim.dvs.DistributedVirtualPort.ConfigSpec()
        dv_port_config_spec.key = '8' # The port's key whose VLAN settings I wanna change
        dv_port_config_spec.operation = 'edit'
        dv_port_config_spec.configVersion = dvs.config.configVersion

        vlan_policy = vim.dvs.VmwareDistributedVirtualSwitch.VlanIdSpec()
        vlan_policy.vlanId = 100

        dv_port_setting = vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy()
        dv_port_setting.vlan = vlan_policy
        dv_port_setting.blocked = vim.BoolPolicy(value=False)

        dv_port_config_spec.setting = dv_port_setting

        task = dvs.ReconfigureDVPort_Task(port=[dv_port_config_spec])
        wait_for_task(task, si)

```

Any idea what's wrong am I doing ? Or am I missing any specs ?

**Comment by rreubenur** [comment]
@tianhao64  @hartsock  @prziborowski any clue ?

**Comment by avinashsavaliya** [comment]
I am getting same error.Any update on this problem?

**Comment by rreubenur** [comment]
@avinashsavaliya  share your code snippet. The above code should work if you only change the spec from ```dv_port_config_spec.configVersion = dvs.config.configVersion```   to   ```dv_port_config_spec.configVersion = dv_port.config.configVersion```

```dv_port.config.configVersion``` you can enter manually or get the dv_port object and use the ```dv_port.config.configVersion``` property

**Comment by avinashsavaliya** [comment]
Here Simply I want to reconfigure vlan ID only.
dv_pg = get_obj(content,
                    [vim.dvs.DistributedVirtualPortgroup],
                    dv_port_name)
    dv_pg_spec = vim.dvs.DistributedVirtualPortgroup.ConfigSpec()
    dv_pg_spec.configVersion = "1"
    dv_pg_spec.defaultPortConfig.vlan = \
        vim.dvs.VmwareDistributedVirtualSwitch.VlanIdSpec()
    dv_pg_spec.defaultPortConfig.vlan.vlanId = vlan_id
    task = dv_pg.ReconfigureDVPortgroup_Task(dv_pg_spec)
    time.sleep(90)
    wait_for_task(args, task, si)
    dv_pg_mob = get_obj(content,
                        [vim.dvs.DistributedVirtualPortgroup],
                        dv_port_name)
    if dv_pg_mob is not None:
        return True
    else:
        return False

**Comment by rreubenur** [comment]
When you are reconfiguring  DVPortgroup then you have to use the portgroup's config version.
```dv_pg_spec.configVersion = dv_pg.config.configVersion``` . Try this let me know.

Also few question:
1. Why sleeping when you are already waiting for the task to complete ?
2. Why retrieving the pg object again after wait_for_task ?

**Comment by avinashsavaliya** [comment]
Reconfigured As per your suggestion:

dv_pg = get_obj(content,
                    [vim.dvs.DistributedVirtualPortgroup],
                    dv_port_name)
    dv_pg_spec = vim.dvs.DistributedVirtualPortgroup.ConfigSpec()
    dv_pg_spec.configVersion = dv_pg.config.configVersion
    dv_pg_spec.defaultPortConfig.vlan = \
        vim.dvs.VmwareDistributedVirtualSwitch.VlanIdSpec()
    dv_pg_spec.defaultPortConfig.vlan.vlanId = vlan_id
    task = dv_pg.ReconfigureDVPortgroup_Task(dv_pg_spec)
    wait_for_task(args, task, si)

Error message:
vim.dvs.VmwareDistributedVirtualSwitch.VlanIdSpec()
AttributeError: 'NoneType' object has no attribute 'vlan'

**Comment by avinashsavaliya** [comment]
Or can you let me know dv_pg_spec.configVersion for this attribute what manual value we should pass.I will try that option with manual value

**Comment by rreubenur** [comment]
Where have you defined ```dv_pg_spec.defaultPortConfig.```  ???
Initialize it with ```dv_pg_spec.defaultPortConfig = vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy()```

The above error has nothing to do with configVersion. And you should not pass manually the configVersion !

**Comment by ram-yadav** [comment]
@rreubenur,  did you figure out how to set the vlan override for DVPortConfigSpec, if yes can you post the code snippet?

Thanks

**Comment by surya-cs** [comment]
@avinashsavaliya @reubenur-rahman can you please share the working code snippet. Thank you.

**Comment by avinashsavaliya** [comment]
@surya-cs  what workflow you are looking?
