### ISSUE TITLE
if Improved disk capacity by pyvmomi must poweroff the vm

### ISSUE THREAD

**Issue by liuhetongzi** [vmware/pyvmomi#539]
My improved disk capacity py is：

    for device in vm.config.hardware.device:
        if type(device).__name__ == 'vim.vm.device.VirtualDisk':
            file_name = device.backing.fileName
    virtualDiskManager = si.content.virtualDiskManager
    datacenter = vm.parent.parent
    task = virtualDiskManager.ExtendVirtualDisk(file_name, datacenter, int(314572800), False) 

When the vm is poweron ，I run my py，the Vcenter console display disk file vmdk is locked，you can not access it。But when the vm is poweroff，I run my py ，it success。
If the vm is must poweroff，when I want improved disk capacity by pyvmomi，because  If I improved disk capacity by Vcenter console，the vm can be poweron。So I has a doubt。Please explain for me。
Thanks。。。

**Comment by prziborowski** [comment]
vCenter is not using virtualDiskManager to extend your disk if there is a VM associated with it.
You can resize the VM by doing a reconfigure.

```
from pyVim.task import WaitForTask
from pyVmomi import vim
...
disk = None
for device in vm.config.hardware.device:
   if isinstance(device, vim.vm.device.VirtualDisk):
      disk = device
      break
if disk is None:
   raise Exception("Failed to find disk for VM")
disk.capacityInBytes = 314572800
spec = vim.vm.ConfigSpec()
devSpec = vim.vm.device.VirtualDeviceSpec(device=disk, operation="edit")
spec.deviceChange.append(devSpec)
WaitForTask(vm.Reconfigure(spec))
```

**Comment by liuhetongzi** [comment]
Thanks..Your answer resolves my problem.Thank you very much.
