### ISSUE TITLE
how to get ilo and ESXi ip after connecting to vCenter

### ISSUE THREAD

**Issue by uganjha** [vmware/pyvmomi#543]
I am just wondering if it is possible to retrieve ilo ip and ESXi ip managed from vCenter.I want to query that info and store for further uses

**Comment by prziborowski** [comment]
I don't think vCenter has the information by default. I also don't know if it has iLO.
VC can store the IPMI information if it was user provided (via HostSystem.UpdateIpmi). This would be available under the HostSystem.config.ipmi.
