### ISSUE TITLE
Host based Vm Performance Metrics

### ISSUE THREAD

**Issue by kgrvamsi** [vmware/pyvmomi#544]
How can we get the below performance metrics of the vm's running in a specific host

![image](https://cloud.githubusercontent.com/assets/1199031/25648066/68947bfa-2f8d-11e7-87e8-a2320d5e4365.png)

![image](https://cloud.githubusercontent.com/assets/1199031/25648129/29241164-2f8e-11e7-9803-cb2508b2052c.png)

![image](https://cloud.githubusercontent.com/assets/1199031/25648270/d55962b2-2f8f-11e7-8927-bc619f0fabb7.png)

do we have to use vim.PerformanceManager??

**Comment by prziborowski** [comment]
> do we have to use vim.PerformanceManager??

You almost make it sound like a bad thing. Yes, I believe [PerfManager](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.PerformanceManager.html) would be the way to do it.

I think [vm_perf_example.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vm_perf_example.py) would be a good starting point.

If you want to get only VMs of a specific host, then you could (1) use CreateContainerView on a vim.HostSystem and look through that list to find it, (2) use CreateContainerView on a vim.Datacenter and call si.content.[searchIndex](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html).FindByIp(dc, ip, False) to find a host by IP.

For the custom date, you'd modify the [QuerySpec](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.PerformanceManager.QuerySpec.html) to include a startTime, endTime as well as specifying an intervalId (20/300/1800/7200/86400)

**Comment by kgrvamsi** [comment]
Hi @prziborowski Thanks for the reply and sorry my question sounded wrong.

I tried looking into the perf python example and tried running it but the values for me looks bit different.

Consider here is the Queryspec I wrote to fetch the below data

```
today=datetime.datetime.today()
three_month=today + dateutil.relativedelta.relativedelta(months=-3)
 spec = vim.PerformanceManager.QuerySpec(maxSample=1,
                                                startTime=three_month,
                                                endTime=today,
                                                entity=child,
                                                metricId=metricIDs,
                                                intervalId=300)
```
The output from the above block of the script

![image](https://cloud.githubusercontent.com/assets/1199031/25729795/56a928f2-30fd-11e7-9848-54dd363e334b.png)

But want I need looks in vsphere with different numbers

![image](https://cloud.githubusercontent.com/assets/1199031/25729898/2ad5cc98-30fe-11e7-8d3b-612b8677917b.png)

**Comment by prziborowski** [comment]
The 339 for mem.usage.average does look close to the latest 3.12, just it is multiplied by 100 (since it is an integer rather than a float).
I don't know if the max/min/average is being calculated by the client using the values of the samples.

I haven't played around with the PerfManager much before, so I don't know exactly how I should be reading its data. 

```
 spec = vim.PerformanceManager.QuerySpec(maxSample=1,
                                                startTime=three_month,
                                                endTime=today,
                                                entity=child,
                                                metricId=metricIDs,
                                                intervalId=300)
```
I don't know how the data is coming out for you, but I think if you have a startTime and endTime, then you might not need intervalId and maxSample.
If you want to track real-time info, then intervalId or 0 or 20 and maxSample is used.
