### ISSUE TITLE
StartProgramInGuest Fails connecting to VM with updated tools

### ISSUE THREAD

**Issue by ghost** [vmware/pyvmomi#545]
Hello.
We are having problems using pyvmomi function (StartProgramInGuest) to run simple commands on an VM, the problems occur after updating the version of VMwareTools. It is happening only on Windows guests.

When we use this method with older version of the tools everything works correctly, but afterwards we get an "Invalid Argument" error.

Here is the code we are using:

> creds = vim.vm.guest.NamePasswordAuthentication(username='user', password='pass')
> 
> cmdspec = vim.vm.guest.ProcessManager.ProgramSpec(
>   programPath='C:\\windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe',
>   arguments='-Command echo test >C:\\TEMP\\out.txt'
> )
> 
> pid = si.content.guestOperationsManager.processManager.StartProgramInGuest(
>   vm = vm,
>   auth = creds,
>   spec = cmdspec
> )

When we use the script with the VMwareTools version 9.0.12 everything work fine, but after updating (to 10.0.9) we get this error:

> Traceback (most recent call last):
>   File "<stdin>", line 4, in <module>
>   File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
>     self.f(*(self.args + (obj,) + args), **kwargs)
>   File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
>     return self._stub.InvokeMethod(self, info, args)
>   File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1370, in InvokeMethod
>     raise obj # pylint: disable-msg=E0702
> pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
>    dynamicType = <unset>,
>    dynamicProperty = (vmodl.DynamicProperty) [],
>    msg = 'A specified parameter was not correct: ',
>    faultCause = <unset>,
>    faultMessage = (vmodl.LocalizableMessage) [],
>    invalidProperty = <unset>
> }

We have tried the same attempt with rbvmomi and we are getting the same error (We will open another issue on their git project).

Maybe it is due to any change on the SDK on the communication between vCenter and VMwareTools agent.
Thanks advance.
Best regards.

**Comment by prziborowski** [comment]
I'm not sure if this is the issue you are hitting, but the thing that always gets me with windows paths is that the delimiter is the same as an escape.
```
>>> programPath='C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
>>> print programPath
C:\windows\system32\WindowsPowerShell
                                     1.0\powershell.exe
>>> programPath=r'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
>>> print programPath
C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe
```

**Comment by alv000h** [comment]
+1

**Comment by tianhao64** [comment]
This looks like a known issue which will be fixed in 10.2.0

**Comment by alv000h** [comment]
There is a workaround, it should work if you define username like this :
username: "WINDOWS_hostname\User",

PD.- change WINDOWS_hostname for the real windows configured hostname as per needed.

**Comment by manojs17** [comment]
Hello Tianhao,

We are facing this same issue after updating VM Tools. Do you know if there is an issue already open with VMWare for VMTools 10.2 and when could it be fixed and released ?

Thanks,
Manoj

**Comment by tianhao64** [comment]
@manojs17 I am checking with Tools team about this.

**Comment by tianhao64** [comment]
@manojs17 What's the username format you are using?

**Comment by manojs17** [comment]
The username is used as <domainname>\<username>.  Just providing the username or <computername>\<username> works. However this will not work for us since the user can be a domain user. With 9.4.10 version of tools this works without any issue.

**Comment by lemke1458** [comment]
There was a regession and usernames of the form .\username were broken.  This is fixed in an upcoming release.
