### ISSUE TITLE
vSphere pyVmomi module. Fetch All VM's

### ISSUE THREAD

**Issue by LetsCodeCloud** [vmware/pyvmomi#549]
Hi All,

I want to build up a python function which can fetch all VMs from a vCenter, or if I pass a single VM, it should return a single VM.

I am trying with below code but it takes lot of time while appending the list array andVC's with high number of VM's.

I am checking below script but it normally prints the output and approach is not function wise.
https://github.com/vmware/pyvmomi/blob/master/sample/getallvms.py

I am new to python, so trying different options and want to have quickest way to return vm/vms.

Please advise (below is the function I am trying to create).
========
def GetVM(service_instance, vmname=None):
    vm_view = 	(service_instance, [vim.VirtualMachine], None)
    vms = vm_view.view
    vm_view.Destroy()

    if vmname:
        vmlist = []

        for vm in vms:
            if vmname in vm.summary.config.name:
                vmlist.append(vm)

        return vmlist
    else:
        return vms
========================

**Comment by DanielDraganov** [comment]
I guess this could be helpful: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getallvms.py
