### ISSUE TITLE
Global Name 'vim' not defined error when called from Ansible

### ISSUE THREAD

**Issue by Illydth** [vmware/pyvmomi#556]
Using Ansible 2.3.1.0 and the vmware_guest action to attempt to clone a template to a VM.

The action returns the following:
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_30LSXu/ansible_module_vmware_guest.py", line 1332, in <module>
    main()
  File "/tmp/ansible_30LSXu/ansible_module_vmware_guest.py", line 1291, in main
    pyv = PyVmomiHelper(module)
  File "/tmp/ansible_30LSXu/ansible_module_vmware_guest.py", line 436, in __init__
    self.content = connect_to_api(self.module)
  File "/tmp/ansible_30LSXu/ansible_modlib.zip/ansible/module_utils/vmware.py", line 321, in connect_to_api
NameError: global name 'vim' is not defined

Note that 2 other installations of ansible DO NOT have this issue.

"pip list" on the working version of pyvmomi shows: pyvmomi (6.5)
"pip list" on the unworking version of pyvmomi shows: pyvmomi (6.5.0.2017.5.post1)

Conclusion:  The most recent version has broken something or has removed compatibility with Ansible's VMWare Plugin.

Help?

**Comment by tianhao64** [comment]
@Illydth It's not obvious to me what's the problem based on the log. Do you have more logging on pyvmomi side?

**Comment by tianhao64** [comment]
Looking at file https://github.com/ansible/ansible/blob/bfc551b3f8fb09cb7b259459abfa554edabbc10b/lib/ansible/module_utils/vmware.py
Line 321 is:  if validate_certs and not hasattr(ssl, 'SSLContext')
which shouldn't throws this error. 
What version of the file are you using? Can you share a link or the content?

**Comment by Illydth** [comment]
I actually don't know how to get more logging.  I've cross posted this over on the ansible github issues as well as I'm not sure whether this is an issue on pyvmomi's side or an implementation on ansible's side.

The thing is, I have 2 boxes showing (6.5) as the version for pyvmomi when I do a pip list, both of those boxes execute the vmcreation just fine.  The one box listing (6.5.0.2017.5.post1) is the one failing, meaning something that changed between 6.5 and 6.5.0.2017.5.post1 LOOKS to be the culprit here.  

Again, whether this is because the ansible folks need to update their code in some way (it looks like the "VIM" variable is not recognized as a global anymore) or something on your end I have no idea.
-----
Regarding the comment you just made; yea, I have the same issue...the line numbers aren't matching up because I assume they've commited more to the file since they released 2.3.1.0.  let me see if I can track down some matching code.

**Comment by Illydth** [comment]
You can find the code here: https://github.com/ansible/ansible/blob/stable-2.3/lib/ansible/module_utils/vmware.py

Need to be on the 2.3 stable branch, not the devel branch.

**Comment by tianhao64** [comment]
hmm... Can you try execute:"from pyVmomi import vim" in your box with 6.5.0.2017.5.post1 installed?

**Comment by Illydth** [comment]
That appears to have worked.  

$ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyVmomi import vim
>>> dir(vim)
['__call__', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'name']
>>>

**Comment by Illydth** [comment]
Just checked it on one of the "working" machines.  Upgrading to PyvMomi 6.5.0.2017 from 6.5 does not appear to be what breaks this.  I'm now lost as to what's going on with my Jenkins docker container, but it doesn't appear to be pyvmomi at fault.

You can probably close this out.

**Comment by Illydth** [comment]
Just to leave a note in case anyone else stumbles across this in the future:

Upon testing, after I 'apt-get purge python-pip' (as part of trying to keep container size down) this occurs.  With debian's "python-pip" (and it's dependencies) installed, ansible properly handles the pyVMomi call.  

With python-pip and it's dependencies removed, the "vim" global error happens.

**Comment by tianhao64** [comment]
@Illydth Thanks for sharing this.

**Comment by Illydth** [comment]
The broken issue appears to be related to debian 8 (jessie) and the packages "python-requests" and "python-urllib3".

apt-get install python-pip installs these two packages as part of PIP's dependencies.  However it will also remove these two packages as part of a apt-get purge.

Apparently, Ansible's "vmware_guest" module cannot use pyVMomi's library without these two packages installed.  Any attempt to call the vmware_guest module after removing either of these two packages will cause the error noted above.
