### ISSUE TITLE
importVapp raising MemoryError

### ISSUE THREAD

**Issue by tejinderss** [vmware/pyvmomi#557]
I am using pyvmomi 6.5.2017.5. I am trying to call importVapp on the resource pool object but getting the following error:

http://dpaste.com/1XWFE58

I tried opening the file both in 'rb' and 'wb' and also changing the encoding to UTF-8 without any luck. The ova file is around 1GB and i have around 2 gb free memory available to the sytem. Not sure what decision led to call .decode on the file contents, that will be very inefficient way to handle the file objects

**Comment by prziborowski** [comment]
For an ova file, I'd suggest something like the [deploy_ova.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/deploy_ova.py) sample in using tarfile to extract the ovf file from the bundle.
(The decode() would be needed as typically file objects are in bytes, so it needs to be converted to a string).

**Comment by tejinderss** [comment]
Ok in that case I think I would use ovftool . Cheers
