### ISSUE TITLE
Import inconsistency for EamObjects.py

### ISSUE THREAD

**Issue by RainTomassi** [vmware/pyvmomi#560]
Thank you for open sourcing EamObjects.py.  It is nice to see the fruition of the request. 

There is a slight inconsistency though that causes us an issue when importing.  The other Objects.py files (PbmObjects.py, SmsObjects.py, ServerObjects) use 'from pyVmomi.VmomiSupport', whereas EamObjects.py is simply using 'from VmomiSupport.'

For consistency, can you update that? 

Thanks.

**Comment by tianhao64** [comment]
@RainTomassi Thanks for reporting this. Fixed.
