### ISSUE TITLE
CreateTemporaryFileInGuest() appends "vmware<someNumber>" to the file name. 

### ISSUE THREAD

**Issue by shyamachilles** [vmware/pyvmomi#563]
For example, I have a requirement to create an empty file "hello.txt" at "/tmp". I researched and found out 
we can use CreateTemporaryFileInGuest() lib support as below  which would return absolute path -

>>> path=si.content.guestOperationsManager.fileManager.CreateTemporaryFileInGuest(vm=vm,
auth=credentials,prefix="hello",suffix=".txt",directoryPath="/tmp")

But, I do see some additional characters being appended to filename which in this case  is "vmware237"
>>> path
'/tmp/hellovmware237.txt'

 To give more datapoints , I tried creating "/tmp/world.txt"

>>> path=si.content.guestOperationsManager.fileManager.CreateTemporaryFileInGuest(vm=vm,auth=credentials,prefix="world",suffix=".txt",directoryPath="/tmp")

But saw "vmware77" appended to the filename.

>>> path
'/tmp/worldvmware77.txt'

Last trial - 

>>> path=si.content.guestOperationsManager.fileManager.CreateTemporaryFileInGuest(vm=vm,auth=credentials,prefix="totallyNew",suffix=".txt",directoryPath="/tmp") 
>>> path
'/tmp/totallyNewvmware19.txt'

So, "vmware[someRandomNumber]" is being appended to the filename. Could someone please guide me if I am doing something wrong.

**Comment by prziborowski** [comment]
I think the idea for this function is that it gives you a unique file that is owned by your user and hence might require some randomness.
(Usually for temporary files, the name is not important).

You could try CreateTemporaryFileInGuest followed by MoveFileInGuest to get your blank file with the name that you want it.

**Comment by shyamachilles** [comment]
Thanks @prziborowski , I just need to add temporary file to alter the state of the VM. So this helps. 

Closing this issue.
