### ISSUE TITLE
Is there a way to enable and disable a SSH on a host?

### ISSUE THREAD

**Issue by jonnymier** [vmware/pyvmomi#565]
I am writing a script where I need to check the SSH status and possibly enable it and disables it when I am done. Thanks in advance.

**Comment by prziborowski** [comment]
SSH is a service that should be listed in the hostSystem.configManager.serviceSystem.service
```
serviceSystem = hostSystem.configManager.serviceSystem
sshService = [x for x in serviceSystem.serviceInfo.service if x.key == 'TSM-SSH'][0]
if not sshService.running:
   serviceSystem.Start(sshService.key)
...
serviceSystem.Stop(sshService.key) # Done with it, can disable now.
```
Do note that there is a default timeout for the SSH service to disable itself.
If you want to change that value you can use the advancedOption and update it.
```
from pyVmomi import VmomiSupport
optManager = hostSystem.configManager.advancedOption
sshTimeout = optManager.QueryView('UserVars.ESXiShellTimeOut')
print("SSH will disable itself after %d seconds" % sshTimeout[0].value)
# Now update it to 1 minute.
sshTimeout[0].value = VmomiSupport.vmodlTypes['long'](60)
optManager.UpdateValues(sshTimeout)
```

**Comment by jonnymier** [comment]
When I enter
`serviceSystem = hostSystem.configManager.serviceSystem`
 
I get an error 
in InvokeAccessor
    raise objectContent.missingSet[0].fault
vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated) {

**Comment by prziborowski** [comment]
OK, that is unexpected.
Up until getting hostSystem (something like si = SmartConnectNoSSL(); hostSystem = si.content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0]) you had a valid connection.
And then when it tries to read a couple more properties, it is no longer authenticated?

If I think of something else to try, I'll let you know. Otherwise I'm very confused.

**Comment by jonnymier** [comment]
Nevermind, I got it! Thank you!!!!

**Comment by rmdcoding** [comment]
@prziborowski Is there a way to leave SSH enabled? How can I disable the timeout for SSH?

**Comment by prziborowski** [comment]
@rmdcoding Set the timeout to 0 to disable it.
Below is slightly modified from Jun 23, 2017 comment:
```
from pyVmomi import VmomiSupport
...
optManager = hostSystem.configManager.advancedOption
sshTimeout = optManager.QueryView('UserVars.ESXiShellTimeOut')
sshTimeout[0].value = VmomiSupport.vmodlTypes['long'](0)
optManager.UpdateValues(sshTimeout)
```

**Comment by rmdcoding** [comment]
@prziborowski Wow. That was fast! Thanks!
