### ISSUE TITLE
Documentation links now broken after the WSS SDK knowledgebase was abruptly removed from vmware.com

### ISSUE THREAD

**Issue by smiley** [vmware/pyvmomi#566]
Since around today, the documentation links in `/docs` and on the GitHub wiki are broken. They either return a 404 or redirect to https://code.vmware.com/sdks (which doesn't have the WSS listed). I've looked for it for a while now, but the closest product I could find documentation for is the "Web Client SDK".

Where was the documentation moved to? Right now the only ones usable (at least as I see it) are vSphere 4.1 docs (which are still partially online) and this repository's `/docs` folder.

**Comment by prziborowski** [comment]
I've found: https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/index.html
From https://code.vmware.com/web/sdk/65/vsphere-management: vSphere Web Services API Reference

**Comment by tianhao64** [comment]
The link is fixed.
