### ISSUE TITLE
How can you create a DVPortgroup and change specs on it once created.

### ISSUE THREAD

**Issue by jonnymier** [vmware/pyvmomi#569]
I want to create a DVPortgroup and set the uplink ports to all active. I want to go in and change those to uplink ports to something else.

**Comment by jonnymier** [comment]
@prziborowski any idea?

**Comment by prziborowski** [comment]
I am not too familiar with vDS in general.
If you have access to the DVPortgroup [managed object](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.dvs.DistributedVirtualPortgroup.html), you should be able to reconfigure it with a [vim.dvs.DistributedVirtualPortgroup.ConfigSpec](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.dvs.DistributedVirtualPortgroup.ConfigSpec.html).

But it sounds like you are trying to do something outside of those properties.
If you want to remove that DVPortgroup from the uplinks, then I think you need to [DVSwitch](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.DistributedVirtualSwitch.html%23field_detail).reconfigure([vim.DistributedVirtualSwitch.ConfigSpec](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.DistributedVirtualSwitch.ConfigSpec.html)) and don't include the uplinkPortgroup that you don't want.

Again, I'm just taking a guess based on what APIs I see available.

**Comment by jonnymier** [comment]
I am such a noob to VMWare and this library. I have the specs all in place I just dont know how to feed them to my DVPortgroup. 



`dv_pg_spec = vim.dvs.DistributedVirtualPortgroup.ConfigSpec()`

`dv_pg_spec.defaultPortConfig = vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy()`

`dv_pg_spec.defaultPortConfig.uplinkTeamingPolicy = vim.dvs.VmwareDistributedVirtualSwitch.UplinkPortTeamingPolicy()  dv_pg_spec.defaultPortConfig.uplinkTeamingPolicy.uplinkPortOrder = vim.dvs.VmwareDistributedVirtualSwitch.UplinkPortOrderPolicy()`

`dv_pg_spec.defaultPortConfig.uplinkTeamingPolicy.uplinkPortOrder.standbyUplinkPort = "Uplink 1"
dv_pg_spec.defaultPortConfig.uplinkTeamingPolicy.uplinkPortOrder.activeUplinkPort =  ["Uplink 2","Uplink 3","Uplink 4"]`

@prziborowski

**Comment by jonnymier** [comment]
I am stuck on how "dv_pg_spec" to my DVPortgroup managed object

**Comment by prziborowski** [comment]
OK, I see you have the spec set up.
If you have not retrieved the DVPortgroup you wish to reconfigure, then that would be the next step.
And if you have not retrieved the DVSwitch that holds the DVPortgroup, that might be needed as well.

You can either navigate the inventory:
```
def GetDVSwitch(si, name):
   for dc in si.content.rootFolder.childEntity:
      for network in dc.networkFolder.childEntity:
         # I'm assuming you don't have network folders, if you do https://github.com/vmware/pyvmomi-community-samples/tree/master/samples has a lot of samples for get_obj function to use CreateContainerView
         if network.name == name:
            return network
   raise Exception("DVSwitch %s not found" % name)

def GetDVPortgroup(dvs, name):
   for portgroup in dvs.portgroup:
      if portgroup.name == name:
         return portgroup
   raise Exception("Portgroup %s not found." % name)

from pyVim.task import WaitForTask
dvs = GetDVSwitch(si, 'dvswitch')
dvportgroup = GetDVPortgroup(dvs, 'dvportgroup')
WaitForTask(dvportgroup.Reconfigure(dv_pg_spec))
```

**Comment by jonnymier** [comment]
@prziborowski Once again you are a life saver! Thank you.

**Comment by jonnymier** [comment]
@prziborowski Actually it didnt work =(. I got this error.
`raise task.info.error
vmodl.fault.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: spec.configVersion',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [
      (vmodl.LocalizableMessage) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'com.vmware.vim.vpxd.dvs.invalidArg.unSetlabel',
         arg = (vmodl.KeyAnyValue) [
            (vmodl.KeyAnyValue) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               key = 'property',
               value = 'configVersion'
            }
         ],
         message = 'The configVersion value is not set in the .'
      }
   ],
   invalidProperty = u'spec.configVersion'
}`

**Comment by jonnymier** [comment]
@prziborowski nvm fixed it
