### ISSUE TITLE
List of snapshot objects for a particular VM 

### ISSUE THREAD

**Issue by shyamachilles** [vmware/pyvmomi#570]
How do we get a list of pyVmomi snapshot objects for a particular VM?

I do see some examples involving recursive methods. Is there any simpler approach?

**Comment by sathvikm** [comment]
Hi Shyamchilles,
Below is my code, which will list all snapshots for a given Virtual Machine. 

Most of the code is taken from getallvms.py. 
 
`
    from __future__ import print_function
    from pyVim.connect import SmartConnect, Disconnect
    from pyVmomi import vim
    import argparse
    import atexit
    import getpass
    import ssl


    def GetArgs():
        """Support the command-line arguments listed below."""
        parser = argparse.ArgumentParser(
            description='Process args for retrieving all the Virtual Machines')
        parser.add_argument(
            '-s', '--host', required=True, action='store',
            help='Remote host to connect to'
        )
        parser.add_argument(
            '-o', '--port', type=int, default=443, action='store',
            help='Port to connect on'
        )
        parser.add_argument(
            '-u', '--user', required=True, action='store',
            help='User name to use when connecting to host'
        )
        parser.add_argument(
            '-p', '--password', required=False, action='store',
            help='Password to use when connecting to host'
        )
        parser.add_argument(
            '-v', '--vmname', required=True, action='store',
            help='Provide the VM name for which you snapshot list is printed.'
        )
        args = parser.parse_args()
        return args


    def printSnapInfo(snapshotlist, depth=1):
        """Print the List of Snapshots."""
        maxdepth = 10
        if depth < maxdepth:
            if len(snapshotlist.childSnapshotList) > 0:
                for i in snapshotlist.childSnapshotList:
                    space = " " * 4 * depth
                    print(space, "Snapshot   : ", i.name)
                    if hasattr(i, "childSnapshotList"):
                        printSnapInfo(i, depth + 1)
        return


    def PrintVmInfo(vm, vmname, depth=1):
        """
        Print information for a particular virtual machine or recurse into a folder
        or vApp with depth protection.
        """
        maxdepth = 10

        # if this is a group it will have children. if it does, recurse into them
        # and then return
        if hasattr(vm, 'childEntity'):
            if depth > maxdepth:
                return
            vmList = vm.childEntity
            for c in vmList:
                PrintVmInfo(c, vmname, depth + 1)
            return

        # if this is a vApp, it likely contains child VMs
        # (vApps can nest vApps, but it is hardly a common usecase, so ignore that)
        if isinstance(vm, vim.VirtualApp):
            vmList = vm.vm
            for c in vmList:
                PrintVmInfo(c, vmname, depth + 1)
            return

        summary = vm.summary
        if summary.config.name == vmname:
            print("Name       : ", summary.config.name)
            print("Path       : ", summary.config.vmPathName)
            print("Guest      : ", summary.config.guestFullName)
            for i in vm.snapshot.rootSnapshotList:
                print("Snapshot   : ", i.name)
                # print(vm.snapshot.rootSnapshotList)
                printSnapInfo(i)
        return


    def main():
        """Simple program for listing all Snapshots of a given VM on a system."""
        args = GetArgs()
        if args.password:
            password = args.password
        else:
            password = getpass.getpass(
                prompt='Enter password for host %s and '
                'user %s: ' % (args.host, args.user)
            )

        context = None
        if hasattr(ssl, '_create_unverified_context'):
            context = ssl._create_unverified_context()
        si = SmartConnect(
            host=args.host,
            user=args.user,
            pwd=password,
            port=int(args.port),
            sslContext=context)
        if not si:
            print(
                "Could not connect to the specified host using specified ",
                "username and password"
            )
            return -1

        atexit.register(Disconnect, si)
        content = si.RetrieveContent()
        for child in content.rootFolder.childEntity:
            if hasattr(child, 'vmFolder'):
                datacenter = child
                vmFolder = datacenter.vmFolder
                vmList = vmFolder.childEntity
                for vm in vmList:
                    PrintVmInfo(vm, str(args.vmname))
        return 0


    # Start program
    if __name__ == "__main__":
        main()


`

I hope this solves your problem.
Thanks

**Comment by shyamachilles** [comment]
Thanks @sathvikm . Much appreciate it.
