### ISSUE TITLE
how to set annotation for a vm by pyvmomi?

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi#571]
in the vcenter i can set a annotation for a vm or template, but how to do it by pyvmomi?

**Comment by prziborowski** [comment]
Annotation can be set by doing a reconfigure setting the annotation in the vim.vm.ConfigSpec.
```
from pyVim.task import WaitForTask

annotation="This is the annotation for this VM"
configSpec = vim.vm.ConfigSpec(annotation=annotation)
task = vm.Reconfigure(configSpec)
WaitForTask(task)
```

**Comment by zhangjianpinghik** [comment]
@prziborowski  thanks!

**Comment by zhangjianpinghik** [comment]
@prziborowski   how to set annotation for a host?

**Comment by prziborowski** [comment]
A host doesn't have any annotation as far as I am aware.
There is tagging, but I believe setting tagging requires using a different API instead of pyvmomi.

**Comment by zhangjianpinghik** [comment]
@prziborowski   in the client ui ,user can set the annotation for host by key/value. and i can get the info by pyvmomi like this:host.summary.customValue, but i can not known how to set the customValue for the host,  please help me.

**Comment by prziborowski** [comment]
Thank you for pointing me to that. It appears that you need to use the [CustomFieldsManager](https://code.vmware.com/apis/196/vsphere#/doc/vim.CustomFieldsManager.html).[SetField](https://code.vmware.com/apis/196/vsphere#/doc/vim.CustomFieldsManager.html#setField)(entity, key, value).

I believe the key you use is the return value from [addFieldDefinition](https://code.vmware.com/apis/196/vsphere#/doc/vim.CustomFieldsManager.html#addFieldDefinition), or use an existing one in CustomFieldsManager.field

It seems the only required parameters for addFieldDefinition is the name.

**Comment by zhangjianpinghik** [comment]
can you give me a example?
