### ISSUE TITLE
Wrong documentation about vim.action.MethodAction ?

### ISSUE THREAD

**Issue by blacksponge** [vmware/pyvmomi#579]
Hello,

I wanted wanted to use the task scheduler but I can't manage to create a `vim.action.MethodAction` the right way.
The `name` property that it say to be a `str` in the documentation raise a error when I try to set it:
```
*** TypeError: For "name" expected type ManagedMethod, but got str
```
Furthermore I can't find any explanation on how to use that class.

---

EDIT: Problem solved, it was the same as #452 but I think that it should be documented somehow.

**Comment by DanielDraganov** [comment]
Currently one of the samples contains such example: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/scheduled_poweroff.py
