### ISSUE TITLE
How can I find this "vim" in pyVmomi?

### ISSUE THREAD

**Issue by baijieX** [vmware/pyvmomi#589]

**Comment by prziborowski** [comment]
It is defined in the __init__.py file of pyVmomi directory (one of the many try/except blocks, I believe ServerObjects.py).

You can just import it with:
from pyVmomi import vim

**Comment by baijieX** [comment]
Thanks a lot ! Emm..In fact I am wondering where or what this "vim" is exactly, and what classes and functions this "vim" provides. I am totally new to it^_^!

**Comment by baijieX** [comment]
Thanks again. BTW, is there a doc or something that tells how pyvmomi works?Like pypi does?I don't if it is right to put it this way..Now I can only study it by reading those samples, whitch is not so interesting for me a beginner^_^

**Comment by prziborowski** [comment]
I'm not aware of a doc that goes into much detail on how pyvmomi works.
There is a huge guide in general about the [web services sdk](https://vdc-download.vmware.com/vmwb-repository/dcr-public/dcde9f41-d477-4b57-8252-d7df7ffaa189/222f2d87-ac4d-4842-af01-4d63092b8f78/vsphere-web-services-sdk-65-programming-guide.pdf), of which pyVmomi is the python bindings for. That definitely isn't like the pypi docs.
But the [community samples](https://github.com/vmware/pyvmomi-community-samples/tree/master/samples) is probably the easiest to reference along with the other documents to get an understanding of how things work.
