### ISSUE TITLE
list  all alrams

### ISSUE THREAD

**Issue by ahmedrabie** [vmware/pyvmomi#593]
hi 
I need  to list all alram s on  vcenter

**Comment by gm0neyl0ve** [comment]
Take a look at 
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/list_host_alarms.py

Will list host alarms but you can adapt it pretty easy I bet to get other MOR's alarms

**Comment by MONSTERdemo** [comment]
@gm0neyl0ve Excuse me，how  to creat a alarm by pyvmomi? could you give me an example? Thanks!

**Comment by davehouser1** [comment]
@gm0neyl0ve
This module is just plain broken. Also it makes you provide a UUID to specific hosts, this does not scale well at all. 
There is no easy way around it, you need to learn how to use pyvmomi. I am not a python developer, and do not have time to do this. 

Is there a way to gather this info just from the REST API? or some other means?

**Comment by mechaHarry** [comment]
Echoing the same concern, we have a business need to list alarms of a host.
We already use a get_host_view() function to collect properties, and there are simply no obvious or compliant ways to do something as simple as listing the alarms that a host has triggered.

The samples provided are simply too niche or obtuse to fit into our existing codebase.

Please advise.

**Comment by prziborowski** [comment]
> Echoing the same concern, we have a business need to list alarms of a host.
> We already use a get_host_view() function to collect properties, and there are simply no obvious or compliant ways to do something as simple as listing the alarms that a host has triggered.
> 
> The samples provided are simply too niche or obtuse to fit into our existing codebase.
> 
> Please advise.

I am not an active user of alarms, so I don't know exactly what @mechaHarry wants, but there is an [AlarmManager](https://code.vmware.com/apis/358/vsphere/doc/vim.alarm.AlarmManager.html), which provides a lot of functionality for alarms.

So if you have a service instance (call it `si`), then to get the AlarmManager, it would be:
```alarmMgr = si.content.alarmManager```
And if you want to see the [states of the alarms](https://code.vmware.com/apis/358/vsphere/doc/vim.alarm.AlarmState.html), it would be:
```
alarmStates = alarmMgr.GetAlarmState(host) # host being the managed object for the host you are interested in.
for alarmState in alarmStates:
   if not alarmState.acknowledged:
      print("Alarm %s has not been acknowledged and was triggered at %s" % (alarmState.alarm.info, alarmState.time))
```

**Comment by mechaHarry** [comment]
@prziborowski The example provided has sufficed in showing us how to get alarms for hosts.
We have integrated this into our source code to gather all alarms for each host, along with how to connect via SI.

Much Appreciated, and well done.

**Comment by mechaHarry** [comment]
As a note, to filter for alarms that are triggered, a check like should suffice:
`if alarmState.time:`
The assumption is that an alarmState can only have a nonempty time response if it was triggered in the first place, since the time value stores when an alarm was triggered.
