### ISSUE TITLE
Mapping the VM created in the vcenter to the volume or lun created in the NetApp filer or cluster

### ISSUE THREAD

**Issue by Amruthapv** [vmware/pyvmomi#598]
Iam trying to write a VMware module of the above description . Given the following credentials -
1. Vcenter username and password
2. Cluster username and password
3. datastore name
4. VM name

I should be able to get the volume to which the VM is mapped. Ofcourse there are no direct API calls from VMware to NetApp filer. It has to be done via datastore then lif then svm the volume. How can I use the pyVmomi library for the same

**Comment by Amruthapv** [comment]
found this [link](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2060770)

I want to the corresponding python SDK

**Comment by prziborowski** [comment]
That link (at least to me) is not very clear in how to correlate the VM's ConfigInfo to the host's storageDevice.
Also I don't has a NetApp filer, and not sure to what extent you want to correlate to.

What I do to kind of get an idea of what data structures I'll need with pyVmomi (since navigating through interactive mode is not very easy) is to [enable mob](https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2108405) and browse that.

Then you can say view: https://$IP/mob/?moid=storageSystem and see if what you want is in fileSystemVolumeInfo/storageDeviceInfo or a combination, etc.
To get to the above with pyVmomi, you connect to host like:
```
from pyVim.connect import SmartConnectNoSSL
si = SmartConnectNoSSL(host=$IP, user=$USSER, pwd=$PWD)
dc = si.content.rootFolder.childEntity[0] # First datacenter
cr = dc.hostFolder.childEntity[0] # First compute resource
hostSystem = cr.host[0] # First host, for a non-cluster, it is the only host.
storageSystem = hostSystem.configManager.storageSystem
```
Which is the same in MOB navigating from:
https://$IP/mob/?moid=ServiceInstance (selecting content, then rootFolder, then the first entry in childEntity, etc).

**Comment by Amruthapv** [comment]
@prziborowski  okay will try that .

**Comment by Amruthapv** [comment]
@prziborowski  if  "/$IP/mob/?moid=storageSystem" doesn't display anything does it mean there are no data structures for the same?

**Comment by prziborowski** [comment]
That path would have to be run through the ESXi host.
If you run from vCenter, then you might have to navigate to the approach host via the ServiceInstance.

**Comment by Amruthapv** [comment]
hmm actually StorageSystem is not an allowable value according to [this](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vmodl.ManagedObjectReference.html)

**Comment by prziborowski** [comment]
It is there under:
"HostStorageSystem" | - HostStorageSystem Managed Object.
Also reference to the latest (6.5) [API](https://code.vmware.com/apis/196/vsphere#/doc/vim.host.StorageSystem.html)
The wsdl name is HostStorageSystem. For pyVmomi, it is under vim.host.StorageSystem.

But the moId (managed object ID) for ESXi is hard-coded as "storageSystem". But vCenter, since it can contain more than 1 host, does not hard code such managed object id.

**Comment by Amruthapv** [comment]
Okay Thank you

**Comment by Amruthapv** [comment]
Hi,
def printVmInformation(virtual_machine, depth=1):
    maxdepth = 10
    if hasattr(virtual_machine, 'childEntity'):
        if depth > maxdepth:
            return
        vmList = virtual_machine.childEntity
        for c in vmList:
            printVmInformation(c, depth + 1)
        return

    try:
        summary = virtual_machine.summary
#        ds = [virtual_machine.datastore]
        print "##################################################"
        print "Name : ", summary.config.name
        print "MoRef : ", summary.vm
#        print "State : ", summary.runtime.powerState
        print "##################################################"
        print "Datastore : ", virtual_machine.datastore
        print "Vms datastore:", virtual_machine.config.datastoreurlpair.name
    except Exception as error:
        print "Unable to access summary for VM: ", virtual_machine.name
        print error
        pass
 

**I get the error:  'vim.vm.ConfigInfo' object has no attribute 'datastoreurlpair'**

**Comment by prziborowski** [comment]
I should you need to replace ```datastoreurlpair``` with ```datastoreUrl```

**Comment by Amruthapv** [comment]
@prziborowski  I did that too . It still gives me this error: **Vms datastore: Unable to access summary for VM:  newvm001
virtual_machine**

**Comment by prziborowski** [comment]
Sorry, I forgot that datastoreUrl is an array, so you'd want something like:
```
    print "Vms datastore:", [dsUrl.name for dsUrl in virtual_machine.config.datastoreUrl]
```
I don't see any other error besides that.

**Comment by Amruthapv** [comment]
@prziborowski  cool that works! thank you

**Comment by Amruthapv** [comment]
**on printing the datastore info of a particular VM, I get this huge array.**

[(vim.host.VmfsDatastoreInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   name = 'VMFS_datastore1',
   url = 'ds:///vmfs/volumes/59b62a9f-79413b46-0389-005056a4e8c4/',
   freeSpace = 1439694848L,
   maxFileSize = 69201586814976L,
   maxVirtualDiskCapacity = 68169720922112L,
   maxMemoryFileSize = 70368744177664L,
   timestamp = 2017-09-11T06:28:03.107447Z,
   containerId = <unset>,
   maxPhysicalRDMFileSize = 70368744177664L,
   maxVirtualRDMFileSize = 68169720922112L,
   vmfs = (vim.host.VmfsVolume) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      type = 'VMFS',
      name = 'VMFS_datastore1',
      capacity = 4294967296L,
      blockSizeMb = 1,
      blockSize = 1024,
      unmapGranularity = <unset>,
      unmapPriority = <unset>,
      maxBlocks = 63963136,
      majorVersion = 5,
      version = '5.81',
      uuid = '59b62a9f-79413b46-0389-005056a4e8c4',
      extent = (vim.host.ScsiDisk.Partition) [
         (vim.host.ScsiDisk.Partition) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            **diskName = 'naa.600a098077744a4d7a244b5959525959',**
            partition = 1
         }
      ],
      vmfsUpgradable = false,
      forceMountedInfo = <unset>,
      ssd = false,
      local = false,
      scsiDiskType = <unset>
   },
   **lun = (vim.host.VmfsDatastoreInfo.ScsiLunInfo)** []
}]


**how do I get only the "diskname" and "lun" values  , as highlighted using python. If I get that then I will be almost near to my problem statement.**

**Comment by prziborowski** [comment]
You can use list comprehension to get the results. It might look a bit messy and I'm not positive this will work as my environment does really have any luns or more than 1 disk extent.
```
diskNameAndLun = [(e.diskName, info.lun) for e in info.vmfs.extent for info in infos if isinstance(info, vim.host.VmfsDatastoreInfo)]
```

**Comment by Amruthapv** [comment]
Hmm ok . but what is the difference between host and hostsystem in the pyvmomi library
