### ISSUE TITLE
create a vm from template

### ISSUE THREAD

**Issue by iahmad-khan** [vmware/pyvmomi#601]
Hi , 

I want to create a vm with default settings , created from an existing template. The vm will get its ip from dhcp already setup. The rest of the things will be done from puppet and foreman. 

Is there any simple code in samples to do this , or can such a sample be put there , with name create-from-template.py

One other thing that is very problematic is that sometimes , i find some code to create a vm but that requires a lot of parameters , to be given to that ,  therefore , i wonder if there are some samples or methods , that we can run to get those parameters from our cluster first and then use them in vm creation. 

such as:

       - resource pools
      - folders
      - networks
     - data-stores  (  thanks there is a sample for it)

so , i will be very thankful , if someone has a solution for creating a vm from template , plus a way of getting all those parameters from vpshere cluster on run time , so that we can feed it into vm creation process if needed.

thanks

**Comment by prziborowski** [comment]
If you already have a template, then it sounds like you just want to clone it.
Depending on your specific needs, you might want guest customization for the DHCP part.

For the clone part, I think the [clone_vm.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/clone_vm.py) sample is what you are looking for.
Typically the parameters like cluster, etc are optional, but it appears the this sample wants to populate it. (If you leave it blank on the spec, it will use the same value as the source VM).

I don't see anything for the guest customization part here, but part of something usable could be [pyvmomi-clone-vm.py](https://github.com/yfauser/pyvmomi-clone-vm/blob/master/pyvmomi-clone-vm.py).

For creating guest customization from the fly, you can do something like this [gist](https://gist.github.com/snobear/8788977), but you want to use
```
        guest_map.adapter.ip = vim.vm.customization.DhcpIpGenerator()
```
 rather than:
```
        guest_map.adapter.ip = vim.vm.customization.FixedIp()
        guest_map.adapter.ip.ipAddress = str(ip_settings[key]["ip"])
```

**Comment by iahmad-khan** [comment]
Hi , Thanks. I will give it a try.

Is there anything that can help us getting the current mapping of VMs to datastores , resource pools , networks , folders etc ? info like this:
  
        -  vm-name   host      cluster      data-store  resource-pool  folder 

Thanks

**Comment by prziborowski** [comment]
I'm not aware of a same that lists that, but most of those are retrievable from properties of the VM.
```
vm # is the object
vm.resourcePool # is the resource pool it belongs to
vm.parent # should be the folder
vm.name # is the VM name
vm.runtime.host # is the host
vm.runtime.host.parent # is either the cluster or compute resource (if it is standalone)
vm.datastore # is the list of datastores it belongs to. Disks could be on different datastore than vmx.
```

**Comment by iahmad-khan** [comment]
Thanks , awsome

**Comment by iahmad-khan** [comment]
@prziborowski   in the clone_vm.py sample:

can we set the Folder to be taken from the tepmlate instead:

destfolder = datacenter.vmFolder

like:

destfolder = template.vmFolder


thanks

**Comment by iahmad-khan** [comment]
even without any change , it throws an error , in the web console it says:

A specified parameter was not correct: spec.location.host

**Comment by prziborowski** [comment]
You can set the Folder to be the template.parent, which should be a vmFolder.

The error you are getting could be a conflict between the vmFolder and where the template is (if you have more than 1 datacenter). The host and the vmFolder need to be part of the same datacenter.

**Comment by iahmad-khan** [comment]
In my settings , there is one datacenter , and i have set vmFolder to be template.parent , but still the same error.

**Comment by prziborowski** [comment]
That is strange. Is it possible that the template's runtime.host is None?
If that happens to be the case, then you'd have to specify something, but I'm not aware of a case that happens.
What release of vCenter are you using?

**Comment by iahmad-khan** [comment]
it is vpshere 6

**Comment by iahmad-khan** [comment]
Hi , you are right , there was some problem with the template , i tried another template and  it worked. 

Is there any way to sepcifify the vm macAddress ?

**Comment by prziborowski** [comment]
I think there are a couple ways.
One way is to use the [guest customization](https://code.vmware.com/apis/196/vsphere#/doc/vim.vm.customization.Specification.html) that works with something like sysprep.

Another way it to use the cloneSpec.config. The documentation says to use cloneSpec.location.deviceChange for disks and networks, so I'd recommend first trying cloneSpec.location.deviceChange (for each ethernet card you have, update the macAddress and set addressType to "Manual"). It is similar to a reconfigure operation of the cloned VM.

**Comment by iahmad-khan** [comment]
Hi , got it.

When problem when i specify the folder name with complete path like ES/xyx/pg

it says folder nout found

what path separater to use in this case.

I need full path becuze we have a setting like this:

    ES/xcx/pg
    ES/xyz/pg

if i just specify the pg it will rnadmly pick one.

**Comment by prziborowski** [comment]
Can you clarify what kind of folder this is?
If you know the path then you can use the [SearchIndex](https://code.vmware.com/apis/196/vsphere#/doc/vim.SearchIndex.html).[FindByInventoryPath](https://code.vmware.com/apis/196/vsphere#/doc/vim.SearchIndex.html#findByInventoryPath)
E.g. if si is ServiceInstance, then something like si.content.searchIndex.FindByInventoryPath('ES/xcx/pg'),
But the example mentions "vm" as if that is the datacenter.vmFolder being 'datacenter/vm/', so I'm not sure on the specifics.

**Comment by iahmad-khan** [comment]
Hi , 

Currently i worked around this by adding an extra parameter which is the parent folder , and get the folder in a particular parent folder only.

thanks

**Comment by iahmad-khan** [comment]
the only problem now is to figure out it works with some of the templates and not with others. 
how can we check in web client that : template's runtime.host is None or not.?

**Comment by iahmad-khan** [comment]
Hi , 

I figured out that there was no problem with templates , but in the second case where i was facing problem was a datacenter with two clusters and i just needed to specify the cluster name in that case.

closing.

thanks
