### ISSUE TITLE
ImportVApp failing where ovftool does not

### ISSUE THREAD

**Issue by sivel** [vmware/pyvmomi#602]
I have a free ESXi license, and cannot seem to import an OVF using pyvmomi via ImportVApp.

I get an error of:

```
pyVmomi.VmomiSupport.RestrictedVersion: (vim.fault.RestrictedVersion) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Current license or ESXi version prohibits execution of the requested operation.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

ovftool however does not fail with this message and will deploy correctly.  I'm not sure how ovftool supports this when pyvmomi does not.

Any insight would be appreciated.

**Comment by prziborowski** [comment]
Unfortunately the free license doesn't include using the API. It just includes client based interactions. I guess ovftool counts as a client.

I can't provide more details than that.
