### ISSUE TITLE
Can't set connect timeout parameter

### ISSUE THREAD

**Issue by louishot** [vmware/pyvmomi#604]
Hi, guys

`       si = SmartConnect(host=host,
                          user=user,
                          pwd=password,
                          port=int(port),
                          sslContext=context)

`

I can't see have anyway to set connect timeout parameter

the connect to server default time out looks like is 60s
I don't know how to change it because 60 as too long 

thanks

**Comment by kricd** [comment]
If you still have no solution:
https://github.com/vmware/pyvmomi/issues/627

**Comment by DanielDraganov** [comment]
Since https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1 `httpConnectionTimeout` was introduced in `SmartConnect`
