### ISSUE TITLE
can not exec from tools import cli

### ISSUE THREAD

**Issue by bainianminguo** [vmware/pyvmomi#606]
hi,i cat not exec "from tools import cli",which module do i should to import or install?

information:
from tools import cli
ImportError: cannot import name 'cli'

**Comment by iahmad-khan** [comment]
hi

its in the community samples repo:

https://github.com/vmware/pyvmomi-community-samples/tree/master/samples/tools

cheers

**Comment by bainianminguo** [comment]
thank you very much!

**Comment by iahmad-khan** [comment]
welcome

**Comment by robooo** [comment]
couldn't be this somehow forked into this repo? or downloaded during the installation... I had same issue today

**Comment by Patelvijaykumar** [comment]
Can someone please suggest the solution as I am facing the same error
`ImportError: cannot import name cli
`

**Comment by devino21** [comment]
> Can someone please suggest the solution as I am facing the same error
> `ImportError: cannot import name cli `

Save this CLI.py in your C:\Users\*username*\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\tools path and it will run, dont right click - save link as as thats HTML...
