### ISSUE TITLE
Trying to obtain vim.host.vmfsdatastoreinfo

### ISSUE THREAD

**Issue by Amruthapv** [vmware/pyvmomi#609]
def main():
    args = GetArgs()
    # try:
    si = SmartConnect(host=args.host, user=args.user,
                      pwd=args.password, port=int(args.port),
                      )
)
    atexit.register(Disconnect, si)

    content = si.RetrieveContent()

    hostid=si.content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0]
    print "hossss", hostid
    print "vmfs", hostid.VmfsDatastoreInfo

I get the following error: AttributeError: 'vim.HostSystem' object has no attribute 'VmfsDatastoreInfo'

How to retrieve the th evmfsdatastore info from a host

**Comment by prziborowski** [comment]
This is the documentation for [HostSystem](https://code.vmware.com/apis/196/vsphere#/doc/vim.HostSystem.html), which is what you get from "si.content.rootFolder.childEntity[0].hostFolder.childEntity[0].host[0]".
Let me break that path down a bit into some links:
[si](https://code.vmware.com/apis/196/vsphere#/doc/vim.ServiceInstance.html).[content](https://code.vmware.com/apis/196/vsphere#/doc/vim.ServiceInstanceContent.html).[rootFolder](https://code.vmware.com/apis/196/vsphere#/doc/vim.Folder.html).[childEntity[0]](https://code.vmware.com/apis/196/vsphere#/doc/vim.Datacenter.html).[hostFolder](https://code.vmware.com/apis/196/vsphere#/doc/vim.Folder.html).[childEntity[0]](https://code.vmware.com/apis/196/vsphere#/doc/vim.ComputeResource.html).[host[0]](https://code.vmware.com/apis/196/vsphere#/doc/vim.HostSystem.html)

So from there, I see a possibility of the [datastore](https://code.vmware.com/apis/196/vsphere#/doc/vim.Datastore.html) array and its [info](https://code.vmware.com/apis/196/vsphere#/doc/vim.Datastore.Info.html) property getting you what you need. Note that DatastoreInfo might be Vmfs, Nas, Vvol depending on what datastores the host has.
