### ISSUE TITLE
Property Collector: Getting the NIC of a vm

### ISSUE THREAD

**Issue by jdor300** [vmware/pyvmomi#612]
Hi,
I'm trying to collect the NICs of a vm with the property collector.
I know it exists in the config.hardware.device of the vm but the devicearray contains many unrelevant objects.
Is there a way to specify only the device items of type vim.vm.device.VirtualEthernetCard ?

Thank you :)

**Comment by prziborowski** [comment]
I am not aware of that mechanism. I think the property collector returns the entire property.
It should be easier to filter on the client side though:
```
devices = []
for dev in config.hardware.device:
   if isinstance(dev, vim.vm.device.VirtualEthernetCard):
      devices.append(dev)
```
