### ISSUE TITLE
AttributeError: 'vim.vm.FileLayoutEx.DiskLayout[]' object has no attribute 'chain'

### ISSUE THREAD

**Issue by p1t3r** [vmware/pyvmomi#615]
Hi,

I am searching for files which a snapshot is made of.

I'm getting the following error:

```
Traceback (most recent call last):
  File "dev/tmp/test0.py", line 44, in <module>
    for x in [snapshot_list.disk.chain.fileKey]:
AttributeError: 'vim.vm.FileLayoutEx.DiskLayout[]' object has no attribute 'chain'
```

The code:

```
vm_con = SmartConnect(host=host, user=user, pwd=password)

for entity0 in vm_con.content.rootFolder.childEntity[0].vmFolder.childEntity:

    if "vim.Folder" in str(entity0) and "vim.Folder" in str(entity0.childEntity):
        print "Parent folder"  
      
        for entity1 in entity0.childEntity:            
            if "vim.Folder" in str(entity1):
                print "Nested folder" 
               
                for entity2 in entity1.childEntity:                    
                    if entity2.layoutEx.snapshot:
                        print entity2.name  
                      
                        for snapshot_name in entity2.snapshot.rootSnapshotList:
                            print snapshot_name.name
                        
                        for snapshot_list in entity2.layoutEx.snapshot:
                            # This is the line 44:
                            print snapshot_list.disk.chain.fileKey
```

This code is only a draft - for now I have been simply trying to go through the MOB structure to find out whether it is possible to get data which contains indexes of files which in turn add up to a snapshot.

I can reach as far as to "content.rootFolder.childEntity[0].vmFolder.childEntity.layoutEx.snapshot.disk" (class 'pyVmomi.VmomiSupport.vim.vm.FileLayoutEx.DiskLayout[]). Anything beyond that e.g. "chain.fileKey" is not available - you cannot go deeper in the structure and retrieve the data.

Do you have idea whether and how it would be possible to extract this data?

Thanks in advance ;-)

**Comment by prziborowski** [comment]
The error you are getting is that you are trying to access 'chain' from a list.
You likely need to loop on that and access 'chain' from its elements.
Starting from [layoutEx](https://code.vmware.com/apis/196/vsphere#/doc/vim.vm.FileLayoutEx.html), disk is an array and chain is an array, and fileKey in an array. Similar for layoutEx.snapshot[].disk[].chain[].fileKey
```
for snapshot in entity2.layoutEx.snapshot:
   for disk in snapshot.disk:
      for chain in disk.chain:
         for fileKey in chain.fileKey:
            print("%d" % fileKey)
```

**Comment by p1t3r** [comment]
Thanks for quick response. I've tried your solution but I still get the same error :-(

```
AttributeError: 'vim.vm.FileLayoutEx.DiskLayout[]' object has no attribute 'chain'
```

**Comment by p1t3r** [comment]
Thanks for quick response. It works perfectly ;-)
