### ISSUE TITLE
CreateSnapshot_Task information

### ISSUE THREAD

**Issue by danielman111** [vmware/pyvmomi#617]
Hi, after using the CreateSnapshot_Task method, can I have the information of the snapshot id via the task return object?

    task = vm.CreateSnapshot_Task(name=snapshot_name,
                                  description=snapshot_desc,
                                  memory=True,
                                  quiesce=False)

Or I need to query the snapshot info again from the specific vm?

**Comment by prziborowski** [comment]
It will be part of the task.info.result once the task completes.
```
from pyVim.task import WaitForTask
...
task = vm.CreateSnapshot_Task(name=snapshot_name,
                              description=snapshot_desc,
                              memory=True,
                              quiesce=False)
WaitForTask(task)
snapshot = task.info.result
```
