### ISSUE TITLE
vim.vm.GuestInfo.NicInfo.network on v6.5.0.10100

### ISSUE THREAD

**Issue by senilio** [vmware/pyvmomi#618]
Hi. 

First of all, I don't know if this is an issue with pyvmomi or the vSphere API, but I'll still give it a go. I'm using pyvmomi (6.5.0.2017.5.post1) from pip.

I upgraded the company vCenter to 6.5.0.10100 today, and after doing this I noticed that some of our polling scripts that make use of vim.vm.GuestInfo.NicInfo.network now return the dvSwitch ID instead of portGroup name as before. This used to work as expected in earlier 6.5.0 versions.

This is what the output of NicInfo looks like:

```
(vim.vm.GuestInfo.NicInfo) [
   (vim.vm.GuestInfo.NicInfo) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      network = '57 2a 19 50 d0 ca 1d a8-78 15 6f d6 91 e4 4d 3e',
      ipAddress = (str) [],
      macAddress = '00:50:56:99:6b:b3',
      connected = false,
      deviceConfigId = 4000,
      dnsConfig = <unset>,
      ipConfig = <unset>,
      netBIOSConfig = <unset>
   }
]
```

The weird thing is that some of our VMs still display the real portgroup name, but it's maybe 1 out of 50, and I don't see a specific pattern among the VMs that still "works".

Have anyone else noticed this? Our dvSwitch version is still on v5.1... I don't think this has anything do do with it, since this behaviour started with v10100.

**Comment by jianz** [comment]
I find a workaround for this issue, just rename the distributed vswitch will correct all the VM's GuestInfo.NicInfo.network name that connect to this DVS. I guess rename the DVS's name will cause the refresh of the VM NIC's network. But the root cause of why it became the dvSwitch ID in the first place is still a mystery.
