### ISSUE TITLE
Task Error message information

### ISSUE THREAD

**Issue by danielman111** [vmware/pyvmomi#619]
Hi there, Is there any way to get the vSphere error message when running a task, for example running 
`task = vm.PowerOff()`
when the vm is already powered off will result in the following error in the vSphere 

"The attempted operation cannot be performed in the current state (Powered off)."

I can know the status of the task (error)
`  status = WaitForTask(task=task, si=service_instance, raiseOnError=False)`
but couldn`t find the message.

**Comment by danielman111** [comment]
Found that by
`task.info.error._wsdlName`

**Comment by prziborowski** [comment]
What I typically do it something like:
```
try:
   WaitForTask(vm.PowerOff())
except Exception as e:
   print ("Hit %s" % e.msg)
```
That would give you message of the fault.
Sometime you'll get more details in: e.faultMessage
And some faults give more details than other, so you can look at https://code.vmware.com/apis/196/vsphere, and for the above case: [InvalidPowerState](https://code.vmware.com/apis/196/vsphere#/doc/vim.fault.InvalidPowerState.html) for more details (i.e. existingState and requestedState properties should be there as well).

And you could handle individual faults easier with try/except:
```
from pyVmomi import vim, vmodl
...

try:
   ...
except vim.fault.InvalidPowerState:
   ...
except vmodl.MethodFault: # the base of the faults
   ...
except Exception: # something unrelated to the API call
   ...
```
