### ISSUE TITLE
proxy settings for SmartConnectNoSSL

### ISSUE THREAD

**Issue by danielhass** [vmware/pyvmomi#620]
I need to use an HTTPS proxy to connect to my vSphere API.

Currently I open the connection like this:

```
# create connection object
service_instance = connect.SmartConnectNoSSL(protocol='https', host=host, user=user, pwd=pwd, port=443)
```

The HTTPS proxy on the linux system the script runs on is set via an environment variable:

```
https_proxy=http://myproxy.example.com
```

Sadly it looks like pyvmomi doesn't make use of the env variable.

How do I set the proxy properly to get this scenario working?

**Comment by cloos** [comment]
This issue is related to #198 .
