### ISSUE TITLE
how to add a hard disk to a vm by pyvmomi?

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi#624]
example:
my vm the disk space is 200G , i want to add 100G to it ,how can i do it by pyvmomi?

**Comment by prziborowski** [comment]
Take a look at this sample: [add_disk_to_vm.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py).
The argument --disk-size would be 100 for your use-case.

**Comment by zhangjianpinghik** [comment]
@prziborowski  i get it ,thanks!
