### ISSUE TITLE
Caught vmodl fault : Current license or ESXi version prohibits execution of the requested operation.

### ISSUE THREAD

**Issue by amoghmahesh** [vmware/pyvmomi#625]
I have latest version of ESXi i.e. 6.5, even then I am getting this error..
Caught vmodl fault : Current license or ESXi version prohibits execution of the requested operation.
May I know why??

**Comment by prziborowski** [comment]
What type of license do you have for the ESXi host?
I believe Hypervisor license does not support API calls.
Only Foundation and above have that feature support.

**Comment by amoghmahesh** [comment]
yes, my ESXi has hypervisor license.
Then what is the alternative way to make this support API calls?
The other sample (getallvms.py) worked and poweronvm.py didn't

**Comment by prziborowski** [comment]
There really isn't any other way to make that license support those API calls.
I think getallvms.py is working because it is just reading information and not trying to perform an action. Since poweronvm.py will try to PowerOn, that is more than just reading information.
