### ISSUE TITLE
Adding nestedHVEnabled = True in to configspec does nothing.

### ISSUE THREAD

**Issue by peturgq** [vmware/pyvmomi#629]
Steps to reproduce:
Boot VM with nestedHVEnabled setting set to True in config spec.

Get vm capability,
nestedHVSupported will be set to false.

I am unable to utilize hypervisor nesting with pyvmomi and I'm at a point where I believe I have tried everything.

Any suggestions?

**Comment by prziborowski** [comment]
I think in order for nestedHVEnabled set to true in ConfigInfo after setting it to true in ConfigSpec, vm capability of nestedHVSupported has to be true.
Most likely the virtual hardware version needs to be 9 or higher.

**Comment by peturgq** [comment]
Additional steps taken to try and get HV working:
spec.flags.virtualExecUsage = vim.vm.FlagInfo.VirtualExecUsage.hvOn
spec.flags.virtualMmuUsage = vim.vm.FlagInfo.VirtualMmuUsage.on

I can see that "spec.flags.virtualMmuUsage = vim.vm.FlagInfo.VirtualMmuUsage.on" gets added to vm capability but "spec.flags.virtualExecUsage = vim.vm.FlagInfo.VirtualExecUsage.hvOn" does not show in capability.

If I check the "Expose hardware assisted virtualization to guest" in the UI I am able to use the VM as a nested hypervisor.

But this really needs to be acheived programmatically for the project I am working on.

**Comment by peturgq** [comment]
More things I've tried include injecting the ovf property 'vhv.enable = TRUE" on the vm's.

**Comment by peturgq** [comment]
@prziborowski Hardware virtualization seems to work if I do it in the UI, so my guess is that this is a bug with pyvmomi or I am just not understanding how to enable in pyvmomi.

**Comment by peturgq** [comment]
What I need is basically the equivalent of checking that box "Expose hardware assisted virtualization to guest" in the cpu menu with pyvmomi.

**Comment by prziborowski** [comment]
I will admit I don't have many samples of enabling it with pyVmomi.
```
from pyVim.task import WaitForTask
from pyVmomi import vim
... # find vm I'm interested in and set it to vm.
WaitForTask(vm.Reconfigure(vim.vm.ConfigSpec(nestedHVEnabled=True)))
```
```
>>> vm.config.nestedHVEnabled
True
>>> vm.config.version
'vmx-11'
>>> vm.capability.nestedHVSupported
True
```

**Comment by peturgq** [comment]
do you know if nestedHV == "Expose hardware assisted virtualization to guest" button?

**Comment by prziborowski** [comment]
Yes, they are the same.
I had to refresh the UI after doing the API change for the UI to notice it (I think it cached the data).

**Comment by peturgq** [comment]
Thats strange because I don't see any diff in capabilities when toggling that button.

**Comment by peturgq** [comment]
vim.vm.ConfigSpec(nestedHVEnabled=True) is what I have been using, is there anywhere I can see any logs in case this is not being applied correctly?

**Comment by peturgq** [comment]
Btw using the same user in UI and for interacting with API.

**Comment by prziborowski** [comment]
I don't think it is logged by default.
You might have to bump it up to trivia for hostd to see what it is receiving for the ConfigSpec.
https://kb.vmware.com/s/article/1004795 for instructions on that.

2017-11-13T18:39:38.743Z trivia hostd[B603B70] [Originator@6876 sub=Vmsvc.vm:/vm
fs/volumes/xxxxxxxx-xxxxxxxx-xxxx-xxxxxxxxxxxx/esx-6.5/esx-6.5.vmx opID=a29c1363
 user=root] Reconfigure: (vim.vm.ConfigSpec) {
...
-->    nestedHVEnabled = false,
...
--> }
When I disabled it via the UI.

If it shows up as true in your case, then I'll have to think about what could be going wrong.

**Comment by peturgq** [comment]
The only difference I see immediately is that I am using vmx-13
vm being a vim.vm object.
WaitForTask(vm.Reconfigure(vim.vm.ConfigSpec(nestedHVEnabled=True)))
print(vm.config.version)
vmx-13
print(vm.capability.nestedHVSupported)
False

**Comment by prziborowski** [comment]
Can you also check what vm.runtime.host.capability.nestedHVSupported ?
(I'd hope that at least returns true).

**Comment by peturgq** [comment]
vm.runtime.host.capability.nestedHVSupported gives me false. 
So strange..

**Comment by prziborowski** [comment]
How are you connecting to vCenter/ESXi with the API?
Are you using SmartConnect/SmartConnectNoSSL or something else?
(it could be possible if you connect with an older 'version' then it will filter out fields like nestedHVSupported as well as the fields for nestedHVEnabled when you do a reconfigure call).

**Comment by peturgq** [comment]
I am using ConnectNoSSL from pyVim.connect

**Comment by prziborowski** [comment]
I'd suggest unless you need to use the non-Smart version that you use SmartConnectNoSSL instead.
Otherwise, if you don't specify a version to ConnectNoSSL, it seems to default to 'vim.version.version6', which is earlier than nestedHV properties.

**Comment by peturgq** [comment]
Thank you so much for your time @prziborowski, looks like ConnectNoSSL was the culprit here!

I will close this ticket.
