### ISSUE TITLE
Unable to use VmDiskQuery.Details with VmDiskQuery

### ISSUE THREAD

**Issue by brunoer** [vmware/pyvmomi#635]
This works
search_spec = vim.host.DatastoreBrowser.SearchSpec(query=[vim.host.DatastoreBrowser.VmDiskQuery()])
queryDetails = vim.host.DatastoreBrowser.FileInfo.Details()
queryDetails.fileSize = True
queryDetails.modification = True
queryDetails.fileType = True
queryDetails.fileOwner = True
search_spec.details = queryDetails

This fails with the following exception:
search_spec = vim.host.DatastoreBrowser.SearchSpec(query=[vim.host.DatastoreBrowser.VmDiskQuery()])
queryDetailsDisk = vim.host.DatastoreBrowser.VmDiskQuery.Details()
queryDetailsDisk.capacityKb = True
queryDetailsDisk.diskType = True
queryDetailsDisk.hardwareVersion = True
queryDetailsDisk.thin = True
search_spec.details = queryDetailsDisk  ****** exception happens on this line.
  File "./test.py", line 500, in myTestFunction
    search_spec.details = queryDetailsDisk
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 537, in __setattr__
    CheckField(self._GetPropertyInfo(name), val)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 972, in CheckField
    % (info.name, info.type.__name__, valType.__name__))
TypeError: For "details" expected type vim.host.DatastoreBrowser.FileInfo.Details, but got vim.host.DatastoreBrowser.VmDiskQuery.Details

Target is a standalone ESXI V6.5 server.

**Comment by prziborowski** [comment]
The search_spec.details needs to be vim.host.DatastoreBrowser.FileInfo.Details. You could have it the same as the working example.
Under the search_spec.query[0] # which is a VmDiskQuery
you can set the details there to include capacityKb/diskType/hardwareVersion/thin.

E.g.
```
search_spec = vim.host.DatastoreBrowser.SearchSpec()
queryDetails = vim.host.DatastoreBrowser.FileInfo.Details()
queryDetails.fileSize = True
queryDetails.modification = True
queryDetails.fileType = True
queryDetails.fileOwner = True
search_spec.details = queryDetails

queryDetailsDisk = vim.host.DatastoreBrowser.VmDiskQuery.Details()
queryDetailsDisk.capacityKb = True
queryDetailsDisk.diskType = True
queryDetailsDisk.hardwareVersion = True
queryDetailsDisk.thin = True
search_spec.query = [queryDetailsDisk]
```

**Comment by brunoer** [comment]
I see my error now, thanks,
I refactored the code as follows:
                        queryDetailsDisk = vim.host.DatastoreBrowser.VmDiskQuery.Details()
                        queryDetailsDisk.capacityKb = True
                        queryDetailsDisk.diskType = True
                        queryDetailsDisk.hardwareVersion = True
                        queryDetailsDisk.thin = True
                        search_spec = vim.host.DatastoreBrowser.SearchSpec(query=[vim.host.DatastoreBrowser.VmDiskQuery(details=queryDetailsDisk)])
                        queryDetails = vim.host.DatastoreBrowser.FileInfo.Details()
                        queryDetails.fileSize = True
                        queryDetails.modification = True
                        queryDetails.fileType = True
                        queryDetails.fileOwner = True
                        search_spec.details = queryDetails

which gives me the result
(vim.host.DatastoreBrowser.SearchResults) [
   (vim.host.DatastoreBrowser.SearchResults) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      datastore = 'vim.Datastore:5a0b9c4b-a00d82ea-d687-9457a5657e98',
      folderPath = '[datastore1] XXXXXXXXXXXXX',
      file = (vim.host.DatastoreBrowser.FileInfo) [
         (vim.host.DatastoreBrowser.VmDiskInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            path = 'XXXXXXXXXXX.vmdk',
            friendlyName = <unset>,
            fileSize = 2097152L,
            modification = 2017-11-22T22:43:03Z,
            owner = 'root',
            diskType = vim.vm.device.VirtualDisk.FlatVer2BackingInfo,
            capacityKb = 167772160L,
            hardwareVersion = 13,
            controllerType = <unset>,
            diskExtents = (str) [],
            thin = true,
            encryption = <unset>
         }
      ]
   }
]

Which is what I was looking for.

**Comment by bonkeydcow** [comment]
What about VVOLs? When I run this it works for normal datastores, but the queryspec gives an invalid argument error if I query a vvol.
