### ISSUE TITLE
Get task from task key

### ISSUE THREAD

**Issue by rmb938** [vmware/pyvmomi#642]
I have a task key (which belongs to a clone vm task) and I need to check the status of the task.

I have done some research and it looks like there is a TaskCollector that I can use but I can't really find a way to filter it by task key.

I see that it can be filtered by parentTaskKey and rootTask key however my task doesn't have any of those since it was called manually.

Any ideas?

**Comment by prziborowski** [comment]
You can look at the code to see how [pyVim/task.py](https://github.com/vmware/pyvmomi/blob/master/pyVim/task.py) gets the task status.
Typically if you made the API call with pyVmomi, then you should have a vim.Task object and you can use something like pyVim.task.WaitForTask to wait on it (it throws an exception on failure, so you can use a try/except block on the method).

**Comment by rmb938** [comment]
Right but I don't have the task object, I just have the task id.

**Comment by prziborowski** [comment]
You could reconstruct a vim.Task with the id and a _stub from an existing/valid connection.
E.g. if `si` is your ServiceInstance, you could do
`cloneTask = vim.Task('task-12345', _stub=si._stub)`
And then:
```
from pyVim.task import WaitForTask
WaitForTask(cloneTask)
```

**Comment by rmb938** [comment]
Ok great, that will work. Thanks!

**Comment by praysad** [comment]
Please share me the code for getting the task based on task key.
I am getting _stub not recognised

**Comment by rmb938** [comment]
@praysad You can find my code here: https://github.com/sandwichcloud/deli/blob/master/deli/manager/vmware.py#L289
