### ISSUE TITLE
HttpNfcLeaseDeviceUrl has asterisk (*) as hostname

### ISSUE THREAD

**Issue by kouellette** [vmware/pyvmomi#645]
When trying to use export_vm.py my Device URL has an asterisk as the hostname which causes the export to fail because "URL has an invalid label". I have no knowledge in NFC leases and google has not proven to be any help to me. If anyone knows what causes this and how I can fix it, that would be great. Below is a snippet of the output I am getting.

> Downloading https://*/ha-nfc/52f3fd4b-5c42-ab8c-6a4c-71a9ca7127ef/disk-0.vmdk to /home/tester/529c5644-a946-a725-7977-75865a1788f7/disk-0.vmdk
> URL has an invalid label.

**Comment by prziborowski** [comment]
This was also brought up [here](https://github.com/vmware/pyvmomi-community-samples/pull/250#issuecomment-320092693).
A couple line change should be needed. Can you see if that works?

**Comment by kouellette** [comment]
Yup that did it! And my bad, I accidentally created this issue on the wrong repo. I'll check if there's already an open pull request addressing that and if not I'll open one. Thanks for the help!
