### ISSUE TITLE
missing pchelper

### ISSUE THREAD

**Issue by jediller** [vmware/pyvmomi#651]
Trying to run some of the samples here using python 2.7.12+.  

Some have a dependency of pchelper, that I have not been able to satisfy. For example in vminfo_quick.py there is

view = pchelper.get_container_view(service_instance,
                                   obj_type=[vim.VirtualMachine])

prior there an 'import pchelper'
in other samples there is: 'from tools import pchelper'
And though I was able to do a pip install tools
this did not help. Either way I get an import error

    import pchelper
ImportError: No module named pchelper

How do I satisfy this?
pip install pchelper
does not find any matching distributions.

**Comment by gm0neyl0ve** [comment]
Not sure if this is the best way or not but what I do is just grab the pchelper  and cli  from here:
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/tools/


Then  the same directory as where I'm  running the vminfo_quick.py I create a dir called tools.
Save cli and pchelper  in tools dir.

Hope that gets you going.
