### ISSUE TITLE
ImportError: No module named connect

### ISSUE THREAD

**Issue by prakashranjan2004** [vmware/pyvmomi#653]
Hi,

I am trying to use this code. I installed pyvim, but not getting module "connect".

error:-

ImportError: No module named connect

python version = Python 2.7.13

Please suggest.

-Prakash

**Comment by 192dot** [comment]
How did you import pyvim?
e.g.
`from pyVim import connect
`

Do you have pyvim installed? Run
`pip install pyvim`

**Comment by prakashranjan2004** [comment]
Thanks for answering. I was doing exactly the same bit it wasn’t
downloading connect. I googled and got some solution. I downloaded some
package from git for connect.

-Prakash

**Comment by pgbidkar** [comment]
@prakashranjan2004  looks like issue is resolved. Closing the issue

**Comment by alevas** [comment]
Hi, @prakashranjan2004 , can you share your actions as I am facing the exact issue? I have installed pyvim as @192dot mentions but no luck :-)

**Comment by pgbidkar** [comment]
Hi @alevas Please can you do these steps
1. Create fresh virtual env and activate it
2. Install pyVmomi (pip install pyVmomi) (Dont install pyVim separately.)
3. Then try import pyVim.connect
Please can you share your findings?
Thanks

**Comment by prakashranjan2004** [comment]
Hi,

I am not working on this currently. So no clue about this. When I will work
again, can share.
