### ISSUE TITLE
Can not find tags info after calling RetriveContent API

### ISSUE THREAD

**Issue by easonlau02** [vmware/pyvmomi#661]
Dear All,

I am using pyvmomi to fetch VM object info from VMWare. But I can not find tags info return from pyvmomi.

Per check, pyvmomi wrapped vmware API to fetch VM object info. 
Anyone know if tags not provide by vmware API or not? And any solution we can use now? Which got me frustrated.

vCenter: 6.0

Thanks/Eason

**Comment by pgbidkar** [comment]
Tagging APIs are added from 6.0, in new SDK. Please can you check VMware new SDK repo https://github.com/vmware/vsphere-automation-sdk-python to get tagging info?

**Comment by easonlau02** [comment]
@pgbidkar Thanks for your advise. Let me try to extract the info.

**Comment by pgbidkar** [comment]
@easonlau02 Please can you confirm if this issue can be closed?

**Comment by easonlau02** [comment]
@pgbidkar I found it is too hard to do the testing, which required setup testing env like vcenter. So till now, I still have no result to confirm. But anyway, please close first. I have the direction at least. Thanks for your help.

**Comment by pgbidkar** [comment]
@easonlau02 Closing it for now. Please reopen if You find any issue once you get test env setup
Thanks
