### ISSUE TITLE
DVS LACP not enabled

### ISSUE THREAD

**Issue by pponker** [vmware/pyvmomi#662]
I'm looking for an example on how to create or update a DVS so that LACP is enabled.     When I create a DVS manually via vCenter 6.5, LACP is automatically available.   However, I've been unable to figure out to do this through just pyvmomi.   Does anyone know whether this is a bug?

**Comment by giridshar** [comment]
you need to make LACP version as multipleLag. Then the LACP config shows on DVS

version = 'multipleLag'
dvsConfigSpec = Vim.Dvs.VmwareDistributedVirtualSwitch.ConfigSpec()
dvsConfigSpec.configVersion = dvs.config.configVersion
dvsConfigSpec.lacpApiVersion = version
updateTask = dvs.Reconfigure(dvsConfigSpec)
task.WaitForTask(updateTask)

**Comment by dujoshi** [comment]
dvs_config_spec = vim.dvs.VmwareDistributedVirtualSwitch.ConfigSpec()
            dvs_config_spec.uplinkPortPolicy = vim.DistributedVirtualSwitch.NameArrayUplinkPortPolicy()
            dvs_config_spec.lacpApiVersion = 'multipleLag'
            dvs_config_spec.uplinkPortPolicy.uplinkPortName = uplink_port_names
            dvs_config_spec.name = self.dvs_name
            dvs_create_spec.configSpec = dvs_config_spec
            dvs_create_spec.productInfo = vim.dvs.ProductSpec(version='{}.0'.format(self.version))
            task = network_folder.CreateDVS_Task(dvs_create_spec)
            exp=self.vapi.wait_for_task(task)
