### ISSUE TITLE
pyvmomi - Add VM to Existing VmGroup

### ISSUE THREAD

**Issue by sthoreson** [vmware/pyvmomi#663]
Fellow Python Addicts,
Newbie python script help is needed.  I am attempting to add/modify an existing VM to an Existing VmGroup without CLI or GUI using standard python pyvmomi and vmware standard API's.

Currently: Using vcenter mob to navigate and show settings:
The VM: SNUFFYapp(vm-348204) is NOT located within the VmGroup listed below:
ClusterGroupInfo> configrationEx.group > VmGroup > Name "Oracle Dbs"

Can anyone assist in how to code the change/add the existing VM to the existing VmGroup?
Thank you

**Comment by prziborowski** [comment]
I haven't tried this myself, but assuming you have your [ClusterComputeResource](https://code.vmware.com/apis/196/vsphere#/doc/vim.ClusterComputeResource.html) then you should be able to use the [configurationEx](https://code.vmware.com/apis/196/vsphere#/doc/vim.cluster.ConfigInfoEx.html) property (inherited from ComputeResource).
There is an array of group property in that, which is either [ClusterHostGroup](https://code.vmware.com/apis/196/vsphere#/doc/vim.cluster.HostGroup.html) or [ClusterVmGroup](https://code.vmware.com/apis/196/vsphere#/doc/vim.cluster.VmGroup.html). You can use that to find the vmGroup you are interested in, append your vm and call [ReconfigureEx](https://code.vmware.com/apis/196/vsphere#/doc/vim.ComputeResource.html#reconfigureEx).

E.g.
```
from pyVmomi import vim
from pyVim.task import WaitForTask
cluster # This is your cluster object
name # Name of the vmGroup
vm # The VM you want to add

for group in cluster.configurationEx.group:
   if group.name == name:
      group.vm.append(vm)
      spec = vim.cluster.ConfigSpecEx(groupSpec=[vim.cluster.GroupSpec(info=group)])
      WaitForTask(cluster.ReconfigureEx(spec=spec, modify=True))
      break
else:
   raise Exception("Failed to find group %s" % name)
```

**Comment by sthoreson** [comment]
Thank you for the response.  Currently working through an error on a simplified version of the code posted:
cluster = "Test-Cluster"
name    = "Oracle DBs"
vm      = "vm-252648"

for group in cluster.configurationEx.group:
        if group.name == name:
                print group.name

Errors:
  File "startoverdrs.py", line 89, in <module>
    for group in cluster.configurationEx.group:
AttributeError: 'str' object has no attribute 'configurationEx'

**Comment by prziborowski** [comment]
Sorry, cluster and vm should be managed objects and not just the name/id of them.
You can look at the example in [linked_clone.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/linked_clone.py) for `cluster = get_obj(content, [vim.ClusterComputeResource], args.cluster_name, datacenter.hostFolder)`
You could do something similar with the VM, or if you have the moId, then you could make the object from that:
`vm = vim.VirtualMachine("vm-252648", si._stub) # si would be your ServiceInstance from connecting`

**Comment by sthoreson** [comment]
Thanks again.  Very close now.  Only one issue remains.  Operator  add/edit.
The pertinent snippet of code, results in the following error:  Attempting to figure if ArrayUpdateOperation is also required:

cluster_name = "Test-Cluster"
drs_groupname= "Oracle DBs"

cluster    = get_appsvmhost(content, [vim.ClusterComputeResource], cluster_name)

host_obj   = None
for host in cluster.host:
        if host.name == apps_target_vm_name:
                host_obj = host
                break

vm = get_appsvmhost(content, [vim.VirtualMachine], apps_target_vm_name)
oper                    = "Add" #Edit has the same error

for group in cluster.configurationEx.group:
        if group.name == drs_groupname:
                group.vm.append(vm)
                # This is the command that isn't working.  Doesn't like operation operand.
                spec = vim.cluster.ConfigSpecEx(groupSpec=[vim.cluster.GroupSpec(info=group,operation=oper)])
                WaitForTask(cluster.ReconfigureEx(spec=spec, modify=True))
                break

   msg = '\nError parsing string Add as enum type ArrayUpdateOperation\n\nwhile parsing serialized value of type vim.option.ArrayUpdateSpec.Operation\nat line 3, column 167\n\nwhile parsing property "operation" of static type ArrayUpdateOperation\n\nwhile parsing serialized DataObject of type vim.cluster.GroupSpec\nat line 3, column 156\n\nwhile parsing property "groupSpec" of static type ArrayOfClusterGroupSpec\n\nwhile parsing serialized DataObject of type vim.cluster.ConfigSpecEx\nat line 3, column 119\n\nwhile parsing call information for method ReconfigureComputeResource_Task\nat line 3, column 14\n\nwhile parsing SOAP body\nat line 3, column 0\n\nwhile parsing SOAP envelope\nat line 2, column 0\n\nwhile parsing HTTP request for method reconfigureEx\non object of type vim.ComputeResource\nat line 1, column 0',

**Comment by prziborowski** [comment]
Try using all lowercase "add"/"edit"
Or use: vim.option.ArrayUpdateSpec.Operation.add / vim.option.ArrayUpdateSpec.Operation.edit

**Comment by sthoreson** [comment]
That did it.  In this case...no pun intended, lower case 'edit' worked.   Truly thankful for your assistance in point the right direction out.  For anyone else, here is the main course:

# Set Smart Connect to ausvcenter
si              = SmartConnectNoSSL(host=input_host_name,user=userName,pwd=password,port=443)
content         = si.RetrieveContent()
atexit.register(Disconnect, si)

# DEFINE APPS Tier Get_APPSVMHost
def get_appsvmhost(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj = c
            break
    return obj

cluster_name = "Test-Cluster"
drs_groupname= "Oracle DBs"

cluster    = get_appsvmhost(content, [vim.ClusterComputeResource], cluster_name)

host_obj   = None
for host in cluster.host:
        if host.name == apps_target_vm_name: #This is a source variable imported from a parameter.py file or just use a inclusive variable like appstarget = "yourvmname"
                host_obj = host
                break

vm = get_appsvmhost(content, [vim.VirtualMachine], apps_target_vm_name)
oper                    = "edit"

for group in cluster.configurationEx.group:
        if group.name == drs_groupname:
                group.vm.append(vm)
                spec = vim.cluster.ConfigSpecEx(groupSpec=[vim.cluster.GroupSpec(info=group,operation=oper)])
                WaitForTask(cluster.ReconfigureEx(spec=spec, modify=True))
                break
        else:
                raise Exception("Failed to find group %s" % name)

print("SPEC: "+str(spec))

**Comment by Sathyafish** [comment]
@sthoreson  I am working on a same task to automate using python. Can you share the actual code. If it is in github let me know the link. Thanks

**Comment by cvachta** [comment]
I created and tested this code:

```
#!/usr/bin/env python

import atexit

from pyVim import connect, task
from pyVmomi import vim
from tools import cli
from tools import tasks

def setup_args():
    """
    Adds additional args to allow the vm uuid to
    be set.
    """
    parser = cli.build_arg_parser()
    # using j here because -u is used for user
    parser.add_argument('-j', '--uuid',
                        required=True,
                        help='UUID of the machine you want to add')
    parser.add_argument('-c', '--cluster',
                        required=True,
                        help="Cluster name")
    parser.add_argument('-g', '--group',
                        required=True,
                        help="Group name")
    my_args = parser.parse_args()
    return cli.prompt_for_password(my_args)

args = setup_args()

def get_obj(content, vimtype, name, folder=None):
    obj = None
    if not folder:
        folder = content.rootFolder
    container = content.viewManager.CreateContainerView(folder, vimtype, True)
    for item in container.view:
        if item.name == name:
            obj = item
            break
    return obj

si = None
try:
    si = connect.SmartConnectNoSSL(host=args.host,
                                   user=args.user,
                                   pwd=args.password,
                                   port=int(args.port))
    atexit.register(connect.Disconnect, si)
except IOError as e:
    print(e)
    pass

if not si:
    raise SystemExit("Unable to connect to host with supplied info.")

vm = si.content.searchIndex.FindByUuid(None, args.uuid, True, True)
if not vm:
    raise SystemExit("Unable to locate VirtualMachine.")

print("Found: {0}".format(vm.name))

cluster = get_obj(si.RetrieveContent(), [vim.ClusterComputeResource], args.cluster)
if not cluster:
    raise SystemExit("Unable to locate cluster.")

for group in cluster.configurationEx.group:
    if group.name == args.group:
       group.vm.append(vm)
       spec = vim.cluster.ConfigSpecEx(groupSpec=[vim.cluster.GroupSpec(info=group,operation="edit")])
       task.WaitForTask(cluster.ReconfigureEx(spec=spec, modify=True))
       break
else:
   raise Exception("Failed to find group %s" % args.group)

print("Done.")

```
