### ISSUE TITLE
pyvmomi EstimateStorageForConsolidateSnapshots_Task and ConsolidateVMDisks_Task seem to be removed

### ISSUE THREAD

**Issue by hobbitten123** [vmware/pyvmomi#664]
Hi -

In the latest version of pyvmomi  are EstimateStorageForConsolidateSnapshots and ConsolidateVMDisks removed ... and what is the replacement?

Because this refers to it:
    https://github.com/vmware/pyvmomi/blob/master/docs/vim/VirtualMachine.rst

But if I try to use it I get:

   (vmodl.fault.MethodNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = <unset>,
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   receiver = 'vim.VirtualMachine:vm-37445',
   method = 'EstimateStorageRequirementForConsolidate'

Please help.

**Comment by prziborowski** [comment]
I don't think the method has been deprecated.
How are you connecting to ESX/VC? If you are using SmartConnect[NoSSL] then it should pick a recent version. If you are just using Connect[NoSSL] then you have to pick a version7 or higher as the default might be lower.

**Comment by hobbitten123** [comment]
Thank you SmartConnect solved it.
