### ISSUE TITLE
Intermittent issue when applying a license

### ISSUE THREAD

**Issue by Saamy88** [vmware/pyvmomi#665]
Hello, 

Have any of you seen this error when applying a license? 
```
File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in 
self.f(*(self.args + (obj,) + args), **kwargs)
File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
return self._stub.InvokeMethod(self, info, args)
File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
raise obj # pylint: disable-msg=E0702
vmodl.fault.InvalidArgument: (vmodl.fault.InvalidArgument) {
dynamicType = ,
dynamicProperty = (vmodl.DynamicProperty) [],
msg = 'A specified parameter was not correct: entityId',
faultCause = ,
faultMessage = (vmodl.LocalizableMessage) [],
invalidProperty = u'entityId'
}
```
This is the code that calls the application of the license:
```
ic_mgr = content.licenseManager
    lic_mgr.AddLicense(lic_key)
    if description:
        lic_mgr.licenseAssignmentManager.UpdateAssignedLicense(entity_id, lic_key, description)
```
We are getting an error with the entity_id variable even though we assign that variable with a hard-coded value when applying a NSX license. Retrying solves this issue, however, I want to know if you guys are aware of this or know a little bit more about this issue? Any ideas on how to stop getting this?

**Comment by pgbidkar** [comment]
@Saamy88 AddLicense & UpdateAssignedLicense APIs are deprecated 
Deprecated. As of vSphere API 6.0 use cis.license.management.SystemManagementService

Please can you share vSphere Version You are working with?

**Comment by Tomorrow9** [comment]
Hi, when assign license to vCenter, you can use it's "instanceUuid" as the "entity" value, but for ESXi host, you need to use the HostSystem's "Managed Object ID", e.g, "host-05" as the value of "entity" parameter.
Hope this helps. Thanks.
