### ISSUE TITLE
pyvmomi: How to list the content of folder inside the datacenter.

### ISSUE THREAD

**Issue by srinivasguttur** [vmware/pyvmomi#666]
Hi,
anybody knows how to list the content of a folder inside the datacenter? 
My actual requirement is: Using pyVmomi module I need to clone from VM which are reside in specific folder under the Datacenter.
Ex: /DC/Templates/vms

Any suggestions much appreciated.

Thanks
Srini

**Comment by pgbidkar** [comment]
Please try if this works for You?

from __future__ import print_function
import sys
sys.path.append('../')
from pyVmomi import vim

from pyVim.connect import SmartConnect, Disconnect

import atexit
import getpass
import ssl

def main():
    """
    Simple command-line program for creating host and VM folders in a
    datacenter.
    """
    sslContext = ssl._create_unverified_context()
    si = SmartConnect(host='<VCIP>',
                      user='<VCUserName>',
                      pwd='<VCPassWord',
                      sslContext=sslContext)
    if not si:
        print("Could not connect to the specified host using specified "
              "username and password")
        return -1

    atexit.register(Disconnect, si)

    content = si.RetrieveContent()
    container = content.viewManager.CreateContainerView(
                                content.rootFolder, [vim.Folder], True)
    for c in container.view:
        print ('FolderName'.format(c.name))
        print (c.childEntity)

# Start program
if __name__ == "__main__":
    `main()`

**Comment by srinivasguttur** [comment]
Ah... Its fixed my requirement!!. Thanks a lot for quick turn around.
Much appreciated. 

I was missing chidEntity stuffs.

**Comment by srinivasguttur** [comment]
Also, I have a confusion with the pyVmomi module called "vim". I no where find this method inside the pyVmomi module. We just import from the pyVmomi which not visible inside of that module.

If you could throw few comments over this will be much appreciated.

Thanks again....

**Comment by prziborowski** [comment]
pyVmomi/__init__.py does a number of imports.
pyVmomi/ServerObject.py contains all the vim namespace types

**Comment by pgbidkar** [comment]
Thanks
Closing the issue
