### ISSUE TITLE
Need to Run Sh Script on Remote VM with Networking Off

### ISSUE THREAD

**Issue by sthoreson** [vmware/pyvmomi#667]
Peeps,
Using pyvmomi, I clone a VCenter VM with Network Flag Off and PowerOn.  
With Networking Off, I have to login to the VM manually and modify the standard Linux OS Network settings.  Ex..IP/Hostname, etc.

Is there a way through Python, to modify files or call a shell script on the remote target VM with Networking Off?

**Comment by sthoreson** [comment]
Using network_config.py, the script allows for /etc/hosts change and it creates a new ifcfg-eth1 but is lacking many parameters changes required.

So, the updated question is, can I use a .py code similar to above, but call an .sh script from within the Cloned VM that will make all the necessary Linux OS changes required?

**Comment by emil45** [comment]
You can upload .sh script to the VM.
Then execute the script with a command.

You have examples in pyvmomi-community-examples
