### ISSUE TITLE
pyvmomi - How to detach disks/luns of a particular VM

### ISSUE THREAD

**Issue by Atrko** [vmware/pyvmomi#668]

**Comment by Shkurupii** [comment]
Hi, @Atrko . I guess it helps you [pyvmomi-community-samples/samples/delete_disk_from_vm.py](url)

**Comment by Atrko** [comment]
@Shkurupii thanks! It helps. Any idea what is the port of credential referring to? vCenter port?

**Comment by Shkurupii** [comment]
443 by default

**Comment by Atrko** [comment]
Thanks!

**Comment by jeking3** [comment]
@Atrko please close this issue if your question was answered.
