### ISSUE TITLE
Not able to update pyvmomi environment to vSphere 6.7 updates

### ISSUE THREAD

**Issue by vThinkBeyondVM** [vmware/pyvmomi#671]
Hi Experts,

 Whether pyVmomi supports vSphere 6.7? I think, it is supported based on recent updates.

I tried running this command "pip3 install --upgrade pyvmomi" but it says "Requirement already up-to-date: idna<2.7,>=2.5 in ./.local/lib/python3.5/site-pa              ckages (from requests>=2.3.0->pyvmomi)
" 
Can you please help on how to go about ?

**Comment by pgbidkar** [comment]
Hi,
Please can you just try pip install pyvmomi & also please pip list output

Thanks

**Comment by vThinkBeyondVM** [comment]
Hi Pavan,

Thanks for looking into it. Below are the output for these commands. 

**vmware@localhost:~$ pip install  pyvmomi**
Requirement already satisfied: pyvmomi in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python2.7/dist-packages (from pyvmomi)
Requirement already satisfied: requests>=2.3.0 in ./.local/lib/python2.7/site-packages (from pyvmomi)
Requirement already satisfied: idna<2.6,>=2.5 in ./.local/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in ./.local/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python2.7/site-packages (from requests>=2.3.0->pyvmomi)

**vmware@localhost:~$ pip3 install  pyvmomi**
Requirement already satisfied: pyvmomi in ./.local/lib/python3.5/site-packages
Requirement already satisfied: six>=1.7.3 in ./.local/lib/python3.5/site-packages (from pyvmomi)
Requirement already satisfied: requests>=2.3.0 in ./.local/lib/python3.5/site-packages (from pyvmomi)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.5/site-packages (from requests>=2.3.0->pyvmomi)
Requirement already satisfied: idna<2.7,>=2.5 in ./.local/lib/python3.5/site-packages (from requests>=2.3.0->pyvmomi)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.5/site-packages (from requests>=2.3.0->pyvmomi)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./.local/lib/python3.5/site-packages (from requests>=2.3.0->pyvmomi)

**vmware@localhost:~$ pip list output**
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
adium-theme-ubuntu (0.3.4)
certifi (2017.4.17)
chardet (3.0.4)
docopt (0.6.2)
httplib2 (0.10.3)
idna (2.5)
pip (9.0.1)
prompt-toolkit (1.0.15)
pyflakes (1.6.0)
Pygments (2.2.0)
pyvim (0.0.21)
pyvmomi (6.5.0.2017.5.post1)
requests (2.18.1)
setuptools (20.7.0)
six (1.11.0)
unity-lens-photos (1.0)
urllib3 (1.21.1)
wcwidth (0.1.7)
wheel (0.29.0)
vmware@localhost:~$

**Comment by vThinkBeyondVM** [comment]
This looks like issue with my local environment. Closing it.
