### ISSUE TITLE
socket stays in established state after Disconnect(si).

### ISSUE THREAD

**Issue by kobayashi** [vmware/pyvmomi#675]
Hi folks,

I find sockets remains established state after Disconnect(si). Is this design spec?

### my environment
- pyvmomi 6.7.0
- Python 3.6.3

### steps to reproduce
```
$ python
>>> from  pyVim import connect
>>> connection = connect.SmartConnectNoSSL(host='host', user='my-user', pwd='my-pwd')
>>> connection.RetrieveContent().rootFolder.childEntity
(ManagedObject) [
  ‘vim.Datacenter:datacenter-21’
]
>>>
```

then, check socket connectivity
```
$ lsof -i@host
COMMAND     PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
python3   16739         ubuntu    3u  IPv4 0x5c747029726c879f      0t0  TCP my-ip:53790->host:https (ESTABLISHED)
```

disconect
```
>>> connect.Disconnect(connection)
>>> connection.RetrieveContent().rootFolder.childEntity
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.virtualenvs/test/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/test/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/ubuntu/.virtualenvs/test/lib/python3.6/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 47, in InvokeAccessor       raise objectContent.missingSet[0].fault
pyVmomi.VmomiSupport.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'
}

```

check file discripter again
```
$ lsof -i@host
COMMAND     PID             USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
python3.6 16739 ubuntu    3u  IPv4 0x5c747029726c879f      0t0  TCP my-ip:53790->host:https (ESTABLISHED)
```

**Comment by lxd235** [comment]
same bug,use python 3.4.5 ,i walk round 
```
        try:
            connect.Disconnect(si)  # logout session
            si._stub._CloseConnection(si._stub.pool[0][0].sock)  # only logout session will not close socket
        except Exception as e:
            log somthing
```

**Comment by atwolf0** [comment]
I have been experiencing this problem as well to the point of locking the server running the scripts and the vcenter itself.

I have applied a fix in my code that seems to be working but its messy and im not sure what part of it is the bit that's working.

The 1st fix involves forcing the timeout on the socket. When checking it seems that the socket in the pool does not time out. Even when setting a connectionPoolTimeout which was somethign i saw in another post the underlying socket still did not time out.
After doing the smart connect setting the timeout on the socket manually seems to have helped
`si._stub.pool[0][0].sock.settimeout(TIMEOUT)`

The other attempted fix was to force the socket close similar to suggested by lxd235 above but calling shutdown and close directly instead of calling _CloseConnection

`si._stub.pool[0][0].sock.shutdown(2)
si._stub.pool[0][0].sock.close()
`

With both of these in place i no longer get several hundred thousand sockets stuck open and i don't run out of file handles anymore.

**Comment by pgbidkar** [comment]
All the pyVmomi samples handle disconnect like
```
# disconnect this thing
atexit.register(Disconnect, si)
```
Please can you try if this works for you? 

If we look at Disconnect() method, https://github.com/vmware/pyvmomi/blob/3ffcb23bf77d757175c0d5216ba9a25345d824cd/pyVim/connect.py#L310 it is Just LogOut() not actual disconnect.

**Comment by levsh** [comment]
@pgbidkar thanks for your reply. But I have a long running service that periodically connects to different vmware servers so it is necessary to close connection manually after it is no longer needed.

**Comment by pgbidkar** [comment]
Hi @levsh Can you please try this
si.content.sessionManager.Terminate(session_id)

You can get the session_id like this
si.content.sessionManager.sessionList[0].key

**Comment by tgolly** [comment]
Hi @levsh, did the above suggestion from @pgbidkar work for you?

**Comment by vmotso** [comment]
@tgolly if you need close connection you can use:
`si._stub.GetConnection().close()`

**Comment by Qliphort** [comment]
Try 
si._stub.DropConnection() 
after Disconnect()

**Comment by rsimac** [comment]
We too have problem with our server side background process having hundreds of leftover connections to vcenters in CLOSE_WAIT state. 

It appears, the pyvmomi api code does not at any point call the close(socket). At Disconnect(), It merely logs out of vcenter, the vcenter side does close the socket, but pyvmomi keeps its side open.

The workarounds above may be functional but are violating the API calling syntax and may break when api code is updated.

For continuously running servers serving end customers such leaks are not good. It would be very good if pyvmomi code is fixed to actually close its socket. when calling Disconnect(). Thanks.

**Comment by Adithyakanthadai** [comment]
This issue is affecting our environment in a very bad way, we are breaching more than 3072 active envoy connections after grading our VCenter to 7.0 and VMware had no clue as to where to look, I am surprised to see that this is not yet addressed.

**Comment by DanielDraganov** [comment]
Fix: https://github.com/vmware/pyvmomi/commit/095ac14d3a95061ead3064eff002bb3b685cf988

**Comment by iammathh** [comment]
You only need to:
`si.content.sessionManager.Logout() `
