### ISSUE TITLE
Setting eam.Agency.ComputeResourceScope to ESXi host does not work

### ISSUE THREAD

**Issue by amudhar** [vmware/pyvmomi#678]
Hello,

From the document reference below, it states the AgencyScope can be set to Cluster or ESXi Host.

ESX Agency Scope
When you create an ESX agency, you must de ne the scope of the agency. You de ne the scope of an ESX agent in terms of compute resources, namely standalone hosts or clusters.
For example, ESX agents can run on standalone ESXi hosts or on clusters of ESXi hosts.
A solution must obtain from vCenter Server the set of compute resource instances on which to deploy ESX agents. For example, you can implement a query in your solution that obtains a list of all the hosts that are running in a vCenter Server instance. Users can then select the hosts on which to deploy ESX agents.

def get_obj(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for c in container.view:
        if c.name == name:
            obj = c
            break
    return obj

    compute_host = get_obj(content, [vim.ComputeResource], 'b4s4')
    compute_scope = eam.Agency.ComputeResourceScope()
    compute_scope.computeResource.append(compute_host)
    agency_config.scope = compute_scope

This leaves the scope unset where 'b4s4' is an ESXi host added to a cluster, while it works
if a cluster is specified instead.

   scope = (eam.Agency.ComputeResourceScope) {
      computeResource = <unset>,
   },
}

Can AgencyScope can be set at ESXi host level? 
What in the above code is incorrect to find the compute resource MOB of ESXi host?

Thanks,
Amudha

**Comment by lepovica** [comment]
If you check EAM documentation you will see that Agency's scope accepts array of ComputeResources. Where cluster is wrapped by ClusterComputeResource and standalone ESXi is wrapped by ComputeResource.

You need to specify the compute resource moRef(moId), i.e the ESXi parent in vCenter, you can see it from VC_IP/mob -> navigate to the ESXi and check it's parent ID.

-Konstantin

**Comment by amudhar** [comment]
@lepovica Thank you. Figured out, standalone host as compute resource scope works, if it is a cluster manager host, then the compute resource is at cluster level.

-Amudha
