### ISSUE TITLE
How to create a new user in vcenter(vcenter level Single sign on - Users and groups) using pyvmomi

### ISSUE THREAD

**Issue by mulamrkreddy** [vmware/pyvmomi#679]
Hi, 

We need to create a new user on vcenter using pyvmomi API, Can you please me in this?
Do we have proper API in pyvmomi?

I know that, we can create user in ESX level using below API's. [https://github.com/vmware/pyvmomi/blob/master/docs/vim/HostSystem.rst](url)
[https://github.com/vmware/pyvmomi/blob/master/docs/vim/host/ConfigManager.rst](url)

Can you please let me know about to create an user in vcenter single sign on level?
<img width="1275" alt="screen shot 2018-05-18 at 3 09 05 pm" src="https://user-images.githubusercontent.com/1698478/40227933-7a8b62d2-5aad-11e8-923d-453315fc9918.png">

Thanks in Advance.

Thanks, 
Ram.

**Comment by prziborowski** [comment]
I'm not aware of a pyVmomi api to create vcenter SSO users.
If someone else knows how, I'd appreciate that so I can also make use of it.

**Comment by mulamrkreddy** [comment]
Thanks @prziborowski  for response. I know that from vcenter CLI, we can create SSO user using `dir-cli` cli command. Ex: 

`/usr/lib/vmware-vmafd/bin/dir-cli user create --account krishnareddy --first-name rama --last-name krishna --password`. 

But now here the problem is: How to ssh to vcenter and run this command.

when we ssh to vcenter we get a command prompt 

> **$ ssh root@<vcenter.sqa.com>
> 
> VMware vCenter Server Appliance 6.5.0.5300
> 
> Type: vCenter Server with an embedded Platform Services Controller
> 
> root@vcenter.sqa.com's password:
> Last login: Thu May 17 09:03:23 2018 from 192.168.200.148
> Connected to service
> 
>     * List APIs: "help api list"
>     * List Plugins: "help pi list"
>     * Launch BASH: "shell"
> 
> Command> shell
> Shell access is granted to root
> root@vcenter [ ~ ]#

> root@vcenter [ ~ ]# /usr/lib/vmware-vmafd/bin/dir-cli user create --account krishnareddy --first-name rama --last-name krishna --password
> Enter password for administrator@vsphere.local:
> Enter password for krishnareddy@vsphere.local:
> User account [krishnareddy] created successfully
> root@vcenter [ ~ ]#


Now I need to automate this to create SSO user on vcenter. 
I have used paramiko to automate this. But not sure how to handle this `Command>` in paramiko. 
Can you guys help me with this?

**Comment by prziborowski** [comment]
You could change the default shell from appliancesh to bash to be more friendly for such automation: https://kb.vmware.com/s/article/2100508

**Comment by EleanorRigby** [comment]
I am trying same thing in rbvmomi. So far no success.

**Comment by j2clerck** [comment]
Hello,

I've tried something like this to circumvene the appliance shell
```
ssh root@vcenter.lab.local 'shell' < this_script.sh

```
where my script would be something like this:
```
#!/bin/bash
for i in $(seq 1 6); do
    /usr/lib/vmware-vmafd/bin/dir-cli user create --account user-$i --user-password VMware$i! --login administrator@vsphere.local --password Password1234! --first-name user-$i --last-name user-$i
done
```
It is far from perfect as I need to hardcode the administrator credentials and I still need to type in the root password.

**Comment by mrlesmithjr** [comment]
I was just getting ready to dig into this and came across this. Anyone been successful at all yet?

**Comment by redteamnow** [comment]
you can do this to paramiko into vcenter local and execute shell:

stdin, stdout, stderr = client.exec_command('shell {}'.format(cmd))

In the case of setting a user to not expire:

cmd = "/usr/lib/vmware-vmafd/bin/dir-cli user modify --account administrator --password-never-expires --password {}".format(password)

stdin, stdout, stderr = client.exec_command('shell {}'.format(cmd))

Hope that helps
