### ISSUE TITLE
How can I cloning virtual machine from a template  concurrently?

### ISSUE THREAD

**Issue by cundi** [vmware/pyvmomi#680]
As the title says, I want to clone 40 virtual machine simultaneously.  
Do I need using `concurrent.futures.ThreadPoolExecutor` or other asynchronous library ?

**Comment by evilensky** [comment]
@cundi Did you ever find a solution?

**Comment by prziborowski** [comment]
The API returns a task, so you should be able to just call the Clone method 40 times (with unique names of the VM) and keep track of the tasks to wait on later.
```
from pyVim.task import WaitForTasks

spec = vim.vm.CloneSpec()
... # all the parts to fill out the spec
tasks = []
base_name = "Cloned-VM"
for i in range(40):
   tasks.append(vm.Clone(folder, "%s-%d" % (base_name, i), spec))
WaitForTasks(tasks, raiseOnErrors=False)
clonedVms = []
for task in tasks:
   if task.info.result is not None:
      clonedVms.append(task.info.result)
# you could check for task.info.error for why VMs might not have cloned
```

**Comment by prziborowski** [comment]
Sorry, the documentation for rescanAllHBA is not a taskhttps://code.vmware.com/apis/358/vsphere/doc/vim.host.StorageSystem.html#rescanAllHba
The signs of task is naming with _Task for the WSDL function name, and return type of "ManagedObjectReference to a Task".

These APIs don't give the client the flexibility of choosing between sync and async. The REST based APIs are a bit more flexible in that (although not all options has both task and non-task), but there isn't feature parity and I don't see s rescanAllHBA function there.

I think all I do in that case is spin off a thread to run the method and later join it (or could use ThreadPoolExecutor)

**Comment by evilensky** [comment]
I tried this way, but it begins to block immediate.  I realize this issue is way off topic now but thank you for any help. Your propery filter examples have been very valuable.


```
rescans = []
with ThreadPoolExecutor(max_workers=10) as executor:
    for host in esxi_hosts:  # just a list of hosts 
        rescans.append(executor.submit(host.configManager.storageSystem.rescanAllHBA()))

for task in as_completed(rescans):
    print(rescans.result())
       
```

**Comment by cundi** [comment]
Oh God,  you send me an answer after two years later.  I have discarded it from our company's project .
