### ISSUE TITLE
How to get vAppState from vim.VirtualApp object using PropertyCollector

### ISSUE THREAD

**Issue by ggmesh** [vmware/pyvmomi#681]
Specifying "summary" as a property to collect successfully grabs vAppState, along with everything else. Trying to specify "summary.vAppState"returns an "vmodl.query.InvalidProperty" error.

Is there a way to grab VirtualApp's specific information through PropertyCollector()?

Here's the information I'm trying for:
https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.VirtualApp.Summary.html

**Comment by prziborowski** [comment]
Unfortunately this is currently a limitation in the property collector that it can not filter on properties that are not present in the base class. vAppState is not part of the [ResourcePool.summary](https://code.vmware.com/apis/358/vsphere#/doc/vim.ResourcePool.Summary.html) that is derives from.
You would have to grab all of "summary" and filter out the parts you don't want at the client level.

**Comment by ggmesh** [comment]
Thank you, I'm guessing the best way to do it is convert to a string and parse that?

`    result = pc.RetrievePropertiesEx([filter_spec], options)
    for item in result.objects:
        print(item)
        print("-----------------------------------------------------------------------------------")`

The above code just treats all of the information returned from the "summary" Data Object as one whole object.

**Comment by prziborowski** [comment]
`pc.RetrievePropertiesEx([filter_spec], options).objects[0].propSet[0].val.vAppState` should give you the vAppState
(the indexing of 0 and 0 is just a short-hand as I just did the filter on 1 object with 1 property, but it is an example that you can get the data without having to do special parsing).
