### ISSUE TITLE
Why? is not a VIM server

### ISSUE THREAD

**Issue by iandriyanov** [vmware/pyvmomi#686]
I tried to connect on vCenter (5.5) from ansible 2.5 module vmware_guest_facts and from sample getallvm.
And every time receive exception:

```The full traceback is:
  File "/tmp/ansible_KTZRHn/ansible_modlib.zip/ansible/module_utils/vmware.py", line 500, in connect_to_api
    service_instance = connect.SmartConnect(host=hostname, user=username, pwd=password, sslContext=ssl_context, port=port)
  File "/usr/local/lib/python2.7/dist-packages/pyVim/connect.py", line 840, in SmartConnect
    raise Exception("%s:%s is not a VIM server" % (host, port))

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "name",
            "folder": "/vm",
            "hostname": "hostname.tld",
            "name": null,
            "name_match": "first",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "username": "name@domain",
            "uuid": "dasd-21312-dasd-32423-dsad",
            "validate_certs": true
        }
    },
    "msg": "Unknown error while connecting to vCenter or ESXi API at hostname.tld:443 : hostname.tld:443 is not a VIM server"
}

**Comment by prziborowski** [comment]
I don't know if you replaced `hostname.tld` when posting here or that was the output. If the latter then it is likely something you need to configure for specifying the hostname properly.
I'm not familiar with ansible, so can't really help with where the config settings are.
The SmartConnect function tries to connect to `hostname.tld` port 443 and can't reach it.

**Comment by iandriyanov** [comment]
ofc i replaced hostname

**Comment by prziborowski** [comment]
Are you able to reach that hostname and port 443? Also /sdk/.
Do you have any proxy settings (environment variables like http_proxy/https_proxy) that might be getting used that could prevent connection to hostname.tld?

Those are the couple things I'd try if I experienced this error.

**Comment by iandriyanov** [comment]
- No one proxies
- I have custom port 9443

BUT! One thing: If i try connect from python via pyvim & pyvmomi into vcenter i have success connection. I can list vm, i can show datacenter and cluster settings

If i use samples "pyvmomi-community-samples" i have the same problem like as above "hostname is not a VIM". But this mini-hack resolve an error.

```python
import ssl
try:
   _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
   pass
else:
   ssl._create_default_https_context = _create_unverified_https_context
```

But in ansible (vmware modules) i have no idea where and how to resolve.

**Comment by iandriyanov** [comment]
This work too

```python
# If you use self signed certificates Python will not connect.
# This will give you an error for the check, but continues.
import ssl
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    print ("There was an error with the SSL certificates. Continuing..")
    ssl._create_default_https_context = _create_unverified_https_context
```

**Comment by iandriyanov** [comment]
I think need to apply somewhere like this:

```python
        context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
        context.verify_mode = ssl.CERT_NONE
        service_instance = connect.SmartConnect(host=args.host,
                                                user=args.user,
                                                pwd=args.password,
                                                port=int(args.port),
                                                sslContext=context)
```

**Comment by prziborowski** [comment]
A lot of our samples use SmartConnectNoSSL function rather than SmartConnect, which is basically the equivalent to the ssl._create_unverified_context code you have above.

I don't know where in ansible that type of change could be made though.
