### ISSUE TITLE
How do I get the variable of type vim.Folder for a folder created using content.fileManager.MakeDirectory(name, datacenter) 

### ISSUE THREAD

**Issue by s1dsaharan** [vmware/pyvmomi#690]
Since content.fileManager.MakeDirectory(name, datacenter) returns no value and the folder does not contain any virtual machine (so it can't be located in vm-folders) . How can I obtain a [vim.Folder] type variable for such a folder.

**Comment by prziborowski** [comment]
The MakeDirectory function is a file system operation, while the vim.Folder type is an inventory concept.
They don't have any interaction.
If you want to make a folder in the vmFolders then you should be able to call CreateFolder from one folder to make a sub-folder.

If you want to interact somehow with the MakeDirectory file system function, then I think you'd have to rely on the [DatastoreBrowser](https://code.vmware.com/apis/358/vsphere#/doc/vim.host.DatastoreBrowser.html).Search/SearchSubFolders that is a property (browser) of the [Datastore](https://code.vmware.com/apis/358/vsphere#/doc/vim.Datastore.html).

**Comment by s1dsaharan** [comment]
Thx mate for your answer.
I actually want to register a vm by copying .vmx file and .vmdk file of another vm.
To register a vm I will need to have a vim.Folder object.
Is there any other way of registering the VM without the folder object.

**Comment by prziborowski** [comment]
You will need a vim.Folder object for any VM or template to be in.
If you have a datacenter (e.g. you used that for content.fileManager.MakeDirectory input) then you could use the root vmFolder with datacenter.vmFolder

**Comment by s1dsaharan** [comment]
Ok got it thx
