### ISSUE TITLE
error for mount snapshot vmfs. "vim.host.UnresolvedVmfsResolutionSpec is not iterable"

### ISSUE THREAD

**Issue by lihlcnkr** [vmware/pyvmomi#699]
When we are trying to mount snapshot vmfs(Resignature or 'Force Mount' unbound VMFS volumes) we are failing with error "vim.host.UnresolvedVmfsResolutionSpec is not iterable"

the code is like this:
`    
    storageSystem = host.configManager.storageSystem
    unresolvedVolumes = storageSystem.QueryUnresolvedVmfsVolume()
    volume = None
    for unresolvedVolume in unresolvedVolumes:
        print("unresolvedVolume:", unresolvedVolume)
        if unresolvedVolume.vmfsLabel == volumename:
            volume = unresolvedVolume
            break

    resolutionSpec = vim.host.UnresolvedVmfsResolutionSpec()
    paths = []
    for extent in volume.extent:
        paths.append(extent.devicePath)
    resolutionSpec.extentDevicePath = paths
    #task = storageSystem.ResolveMultipleUnresolvedVmfsVolumes(resolutionSpec)
    task = storageSystem.ResolveMultipleUnresolvedVmfsVolumesEx(resolutionSpec)

    tasks.wait_for_tasks(si, [task])
`

Using this code failed with below error:

> File "/usr/local/****/VmomiSuppport.py", Line 953, in CheckField
> for it in val:
> TypeError: 'vim.host.UnresolvedVmfsResolutionSpec' object is not iterable

how to fix this error? is it bug?

**Comment by prziborowski** [comment]
[ResolveMultiUnresolveVmfsVolumes](https://code.vmware.com/apis/358/vsphere#/doc/vim.host.StorageSystem.html#resolveMultipleUnresolvedVmfsVolumes) takes as input an array of UnresolvedVmfsResolutionSpec.
You could change:
```
- task = storageSystem.ResolveMultipleUnresolvedVmfsVolumesEx(resolutionSpec)
+ task = storageSystem.ResolveMultipleUnresolvedVmfsVolumesEx([resolutionSpec])
```
And it might get further along.
Well, also resolutionSpec.uuidResolution needs to be set as well (it is not optional).

**Comment by lihlcnkr** [comment]
tanks @prziborowski 
but after using 
`task = storageSystem.ResolveMultipleUnresolvedVmfsVolumesEx([resolutionSpec])`
the thrown error is gone.  and  the task will be return 'success' status.

but  the snap vmfs still unmounted.
the taks.info.result(UnresolvedVmfsResolutionResult object) have fault porperty, 
and it is vim.fault.HostConfigFault
the msg is localizeblemessage, it's messy code， I can't see why it fail.
`(vim.host.UnresolvedVmfsResolutionResult) {
  vmfs = <unset>, 
  fault = (vim.fault.HostConfigFault) {
msg = 'it's messy code',
faultCause = <unset>,
faultMessage = (vmodl.LocalizableMessage) []
}
}
`
do you have any idea what cause it? 
thanks

**Comment by prziborowski** [comment]
Sorry, I don't have a clue.
Also the error message isn't helpful.
If you have access to the /var/run/log/hostd.log log file on the ESXi host, it might provide a bit of more insight (maybe also /var/run/log/vmkernel.log).
I've never used that API before and don't have any unresolved VMFS volumes on my host(s) to try it out with.

**Comment by lihlcnkr** [comment]
thanks @prziborowski

in new pyvmomi version, this issue is resolved. 
after using
task = storageSystem.ResolveMultipleUnresolvedVmfsVolumesEx([resolutionSpec])
the datastore si successfully mounted. 

Thansk very much.

**Comment by pgbidkar** [comment]
> thanks @prziborowski
> 
> in new pyvmomi version, this issue is resolved.
> after using
> task = storageSystem.ResolveMultipleUnresolvedVmfsVolumesEx([resolutionSpec])
> the datastore si successfully mounted.
> 
> Thansk very much.

Hi @lihlcnkr , Can we close this issue?

Thanks
