### ISSUE TITLE
How to fetch volume information of a VM

### ISSUE THREAD

**Issue by akhilesh-agrhari** [vmware/pyvmomi#701]
How can I fetch volumes information of any VM?
I want to fetch the following information of a volume.
Name, DiskID, Creation Date, Disk Type, Status, Description, Attached value, Attached VM
Performance - Disk Read/Write, Disk Read/Write Latency

I tried to understand the sample code but I found no solution there.
I would be grateful to you, Thank you.

**Comment by jeking3** [comment]
The vm.guest.disk array plus vm.config.hardware.device array should contain all the information you need to figure out the volumes and disks.

As for performance, have you tried using the PerformanceManager object (top level)?
