### ISSUE TITLE
netStackInstanceKey on vnic is returned as None although it is set.

### ISSUE THREAD

**Issue by jonathanmier** [vmware/pyvmomi#703]
When trying to get the netstack instance key from a vnic on a host it is returned as None. I can see through the MOB that is it indeed set? Any ideas?

**Comment by rreubenur** [comment]
How are you accessing the data ?

This works for me 

```
    vnic_infos = host.configManager.virtualNicManager.info.netConfig
    for vnic_info in vnic_infos:
        print vnic_info.candidateVnic[0].spec.netStackInstanceKey

```

**Comment by jonathanmier** [comment]
I tried running your code and I still get None returned. Not sure what is going on, in the MOB I can see that the values are set.

**Comment by jonathanmier** [comment]
@rreubenur Do you mind showing me how you are connecting and retrieving the host object? I might not be retrieving the host object in the correct manner?
