### ISSUE TITLE
Documentation cleanup - fix bulleted list

### ISSUE THREAD

**Issue by hartsock** [vmware/pyvmomi#71]
The [EventManager](https://github.com/vmware/pyvmomi/blob/master/docs/vim/event/EventManager.rst) documentation for PostEvent has a number of bulleted lists that do not render properly. Fix the extra bullets and line breaks in the page.

**Comment by Aayush-Kasurde** [comment]
@hartsock I guess this issue is addressed, could you please confirm and close this ?

**Comment by hartsock** [comment]
Looks like it's okay. Thanks for pinging me on this.
