### ISSUE TITLE
Instant cloning support

### ISSUE THREAD

**Issue by raymondhoagland** [vmware/pyvmomi#717]
Now that instant cloning has made it into the VSphere 6.7 APIs, is there current support or a plan to support invoking it from pyvmomi?

**Comment by prziborowski** [comment]
You should be able to call [vm.InstantClone](https://code.vmware.com/apis/358/vsphere#/doc/vim.VirtualMachine.html#instantClone) and provide the [InstantCloneSpec](https://code.vmware.com/apis/358/vsphere#/doc/vim.vm.InstantCloneSpec.html)
I haven't tried it yet, but I see the methods in pyVmomi for it.

**Comment by raymondhoagland** [comment]
Yep looks like you're right and I just didn't try hard enough, thanks!
