### ISSUE TITLE
how to power on a esxi host by pyvmomi

### ISSUE THREAD

**Issue by CengSin** [vmware/pyvmomi#719]
the esxi host is power off, so , i hope i can do something for power on the host

**Comment by prziborowski** [comment]
pyVmomi can not power on a host directly against the ESXi host.
If the host is part of a cluster and is in a standby state I think the [vim.HostSystem#exitStandbyMode](https://code.vmware.com/apis/358/vsphere#/doc/vim.HostSystem.html#exitStandbyMode) can be used.

**Comment by CengSin** [comment]
@prziborowski thx, but the host is in a shutdown state, so.... I will use the ipmitools to power on the host

**Comment by zjcnew** [comment]
Only press the power button?
