### ISSUE TITLE
Best way to get one VM object?

### ISSUE THREAD

**Issue by raphoun** [vmware/pyvmomi#721]
Hello,
 
I am looking for the best method to get a VM by hostname on a vCenter with a lot of VMs (more than 12000)
Actually with a container view then browse the object it is **very slow**
From: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/clone_vm.py

```
def get_obj(content, vimtype, name):
	"""
	Return an object by name, if name is None the
	first found object is returned
	"""
	obj = None
	container = content.viewManager.CreateContainerView(
	content.rootFolder, vimtype, True)
	for c in container.view:
	if name:
	if c.name == name:
	obj = c
	break
	else:
	obj = c
	break
	
	return obj
```

 
I tried the method **search_index.FindByUuid** and it is very fast (less than 1s) but I really need to get by hostname.
I also tried  **FindChild(entity, name)** with a recursive function (we have a lot of folders) but it is quite slow too.
 
Do you have any idea how to get a VM object in a sec with hostname like with UUID? I cannot believe it is impossible.

Raphaël

**Comment by prziborowski** [comment]
If you are basing it on a property of the VM, then I'd recommend something like the example: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/filter_vms.py

Basically it uses the containerView to get the VMs but then uses the property collector on those VMs to fetch a property and then on the client side looks to match for value (since it has all the data via that one call).

**Comment by jeking3** [comment]
You'll need to deal with the possibility that multiple objects can have the same name.  Returning the "first found object" is a bad idea because the order in which the server returns objects is not deterministic.  You could get a different "first found object" on different queries.

**Comment by jeking3** [comment]
@raphoun do you still need help with this?  If not please close it.

**Comment by makusudi** [comment]
Up! pyvmomi library is really very slow if you want to get some specific information about VMs or pools. And documantation is rather fluent. In my case I want to get all VMs in pool by poolname. How can I do it faster than it was in example?

**Comment by prziborowski** [comment]
> Up! pyvmomi library is really very slow if you want to get some specific information about VMs or pools. And documantation is rather fluent. In my case I want to get all VMs in pool by poolname. How can I do it faster than it was in example?

I have a gist that is a bit more specific for another user: https://gist.github.com/prziborowski/ba3ebf610dd6cca3f4e7be5e2874499f 
You could modify that gist with:
```
    pools = collect_properties(si, si.content.rootFolder, vim.ResourcePool,
                             ['name', 'vm'])
```
And then I think iterate pools for the name you want:
```
named_pools = [x for x in pools where x['name'] == poolname]
if len(named_pools) == 0:
   raise Exception("Found no pools with name %s" % poolname)
for pool in named_pools:
   print("VMs: %s" % pool['vm'])
```

**Comment by makusudi** [comment]
No, I mean I need to get all VMs of some pool with theirs configurations and parameters include custom attributes :) Now it taskes 30 seconds on python, that is very slow for us.
On the other hand we have GOlang API with analog of pyvmomi that does similar process for less than 3 seconds :(

**Comment by prziborowski** [comment]
I don't see a reason it would take 30 seconds on python.
Fetching the VMs with the above query should be < 1 second, and a second query to fetch properties shouldn't take long, but depends on how many VMs you have in the pool(s) (it did take me 13 seconds for 1000 VMs).
If you need it to work in 1 query, that is also possible, but you need to use the TraversalSpec in a more nested fashion, so it could grab each managed object's properties that you want. But you probably end up grabbing more as I don't think you can filter out based on values (such as you don't care about VMs in other resource pools)

**Comment by makusudi** [comment]
So It takes only 1 second to fetch all VMs with only 1 parameter - "name". But if I want to query all VMs and get parameter "config" the process could take more than 20 seconds...It's all in one query. If you could tell me how to fetch all VMs in 2 queries with less time it'll be great :)
Or maybe somebody knows where I can read about filtering and queries in pyvmomi. This is even the preferred option.

P.S. maybe the main reason of a long query timing is in our VMs quantity: 2300 VMs in all pools.
In one part of functionality I need to search VM by name in all pools in a realtime, in other part of functionality I only need to get all VMs of some pool.
