### ISSUE TITLE
Add excitant tag to a VM

### ISSUE THREAD

**Issue by HammerZ3it** [vmware/pyvmomi#722]
Hi everyone,

I am trying to fully automated our chain of supply for Virtual machine created with VMWARE.
In this process I have to assign already excitant tag to this VM.
I already noticed some issues about this kind of demand but none is referencing tags that are not newly created.
I am using ansible to achieve my goal but there is no module allowing to assign tag... 

Any help will be appreciate.

Regards,

**Comment by VamsikrishnaNallabothu** [comment]
Any solution for this yet?

Why cant pyvmomi support a simple feature like tagging. Really disappointed VMWare!

**Comment by pgbidkar** [comment]
Hi @VamsikrishnaNallabothu Please refer repo https://github.com/vmware/vsphere-automation-sdk-python for tagging APIs.
Tagging APIs are REST based APIs. Hence are part of new SDK repo.
Please let us know if you find any issue
Thanks

**Comment by Akasurde** [comment]
@VamsikrishnaNallabothu You can use Ansible module - [`vmware_tag_manager`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_tag_manager.py) which is based on vSphere Automation SDK - Python.
