### ISSUE TITLE
How to use CreateListView (or, how do I make a ManagedObjectReference)?

### ISSUE THREAD

**Issue by jeking3** [vmware/pyvmomi#723]
The call to [CreateListView](https://code.vmware.com/apis/358/vsphere#/doc/vim.view.ViewManager.html#createListView) takes an optional array of ManagedObjectReference.

I know the type and the value I want to pass in, but I see no way to create a ManagedObjectReference.  For example:
```
  File "/opt/stackstorm/packs.dev/vsphere/actions/vmwarelib/collector.py", line 46, in collect
    moRef = pyVmomi.vmodl.ManagedObjectReference()
  File "/opt/stackstorm/virtualenvs/vsphere/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 247, in __getattr__
    raise AttributeError(attr)
AttributeError: ManagedObjectReference
```

**Comment by prziborowski** [comment]
For pyVmomi, I think you'd pass in the objects themselves.
So it might be vim.VirtualMachine('vm-1234', stub=si._stub), vim.HostSystem('host-2345', stub=si._stub)
Or if you have the object from navigating si.content.rootFolder's inventory, you could pass that in.

**Comment by prziborowski** [comment]
> Do I have to make a conversion utility that supports every ManagedObjectReference.type value possible and return an object?

I think we have one as part of pyVmomi.VmomiSupport:
```
from pyVmomi import VmomiSupport
VmomiSupport.GetWsdlType('urn:vim25', 'VirtualMachine')
```
<class 'pyVmomi.VmomiSupport.vim.VirtualMachine'>
```
VmomiSupport.GetWsdlType('urn:vim25', 'VirtualMachine')('vm-1234')
```
'vim.VirtualMachine:vm-1234'

**Comment by jeking3** [comment]
Thanks - that worked as something passed into ModifyListView(add=[...])!
