### ISSUE TITLE
how to send nmi to VM using pyvmomi?

### ISSUE THREAD

**Issue by lihlcnkr** [vmware/pyvmomi#726]
I wanna send NMI to VM(hang VM, and generate dump file), and the following API is not works.
`vm.SendNMI()`
after call SendNMI() method, following error is occurred.
> requested operation is not implemented by the server.

how to send NMI to VM? 
thanks.

**Comment by lihlcnkr** [comment]
@prziborowski, thanks very much. 
It's sad news for me: (

**Comment by prziborowski** [comment]
Yes, that is a good point. You could use vm-support as an indirect way to send an NMI.
I haven't tried that, but here is the [gist](https://gist.github.com/prziborowski/1a8ee0e3e4185e07f208212fcc083078) of it.
It might need some tweaks to work in your environment.

**Comment by lihlcnkr** [comment]
> Yes, that is a good point. You could use vm-support as an indirect way to send an NMI.
> I haven't tried that, but here is the [gist](https://gist.github.com/prziborowski/1a8ee0e3e4185e07f208212fcc083078) of it.
> It might need some tweaks to work in your environment.
thanks, @prziborowski 
it works well, 

and your code is let me know how Host Server API works.

**Comment by prziborowski** [comment]
I don't have any work around for that one.
Can you see if VC allows you to do the method from the UI for the 6.0 host?
> From the vCenter flash based web client, right click on the required VM and click on 'Export System Logs'.
> I can see "HungVM" -> "Send_NMI_To_Guest" menu, and it works well.

If that works correctly, then I'll try to take a look at it further. If it doesn't work, then I think there was an issue in the vm-support script in 6.0 and was fixed in 6.5.
