### ISSUE TITLE
For "entity" expected type vim.ManagedEntity, but got ManagedObject for PermissionAddedEvent and when a VM is created

### ISSUE THREAD

**Issue by arunpatyal** [vmware/pyvmomi#728]
[error.txt](https://github.com/vmware/pyvmomi/files/2487783/error.txt)
 ESX  6.5
 Tried with pyvmomi 6.5 and 6.7
Create a new user and assign a permission ( I assigned administrator)
OR
Create a VM ( I cloned existing VM)
Script: 

byTime = vim.event.EventFilterSpec.ByTime(beginTime=beginTime, endTime=endTime)
    filterSpec = vim.event.EventFilterSpec(time=byTime)
    eventManager = serverConn.content.eventManager
    eventCollector = eventManager.CreateCollectorForEvents(filterSpec)
    eventCollector.RewindCollector()
    eventsArray = eventCollector.ReadNextEvents(maxCount=400)

Error:
for entity expected type vim.managedentity, but got managed object 
  *** pyVmomi.SoapAdapter.ParserError: 'xml document: <http.client.HTTPResponse object at 0x00000000059F9978> parse error at: line:7, col:404'

Attached is the full stacktrace.

Thanks

**Comment by arunpatyal** [comment]
The VM Creation event which is failing is VMBeingCreatedEvent

**Comment by arunpatyal** [comment]
The above script works without any issues with a vcenter but fails for an esxi host. Can esxi and vcenter have different implementations?

**Comment by jeking3** [comment]
Yes they do; I recommend you go through vCenter wherever possible.
