### ISSUE TITLE
Add stale issue robot to GitHub to eliminate the backlog of issues

### ISSUE THREAD

**Issue by jeking3** [vmware/pyvmomi#737]
Let's face it, 300+ issues is a lot.  A lot of these look like questions that have been answered but the author never came back to close it.  Consider adding this to the GitHub repo to clean it up:

https://github.com/probot/stale

Thanks.

**Comment by jeking3** [comment]
@tianhao64 if you add probot/stale to your github project, it will automatically force authors or interested parties to keep their issues alove or be closed due to inactivity.  The issues list goes back to 2014 and contains questions that are in all likelihood no longer interesting or relevant to the original authors, and they never came back to check on or close them.  Please consider doing this to clean up this backlog automatically.

**Comment by DanielDraganov** [comment]
Hi @jeking3. Thanks for the suggestion! We are currently trying to put some order in the project's issues and pull requests. Probably all issues that are actually question will be moved to the Discussions section and Issues will be used only for actionable items - enchantments and bugs.
