### ISSUE TITLE
Trying to get vm datastore name fails

### ISSUE THREAD

**Issue by castertr0y357** [vmware/pyvmomi#747]
Hello,

I'm trying to create a script that will go through and grab relevant VM attributes that I want to inventory, and when I try to pull it from vim.VirtualMachine.datastore.info.name it tells me that ManagedObject[] object doesn't have the attribute 'info'

Code below: scrubbed for sensitive data

```
from pyVmomi import vim, vmodl
from pyVim import connect
import atexit

service_instance = connect.SmartConnectNoSSL(host='hostname',
                               user='user',
                               pwd='password',
                               port=443)

atexit.register(connect.Disconnect, service_instance)

content = service_instance.RetrieveContent()

container = content.rootFolder
viewType = [vim.VirtualMachine]
recursive = True
containerView = content.viewManager.CreateContainerView(container, viewType, recursive)

children = containerView.view

for child in children:
    vm = child

    # Relevant VM attributes

    name = vm.summary.config.name
    template = vm.summary.config.template
    numCPU = vm.summary.config.numCpu
    cpuReservation = vm.summary.config.cpuReservation
    memoryReservation = int(vm.summary.config.memoryReservation / 1024)
    memorySizeGB = int(vm.summary.config.memorySizeMB / 1024)
    host = vm.runtime.host.summary.config.name
    toolsStatus = vm.guest.toolsVersionStatus2
    toolsVersion = vm.config.tools.toolsVersion
    guestId = vm.config.guestId
    guestFullName = vm.config.guestFullName
    guestAlternateName = vm.config.alternateGuestName
    description = vm.config.annotation
    instanceUuid = vm.config.instanceUuid
    dataStore = vm.datastore.info.name
    powerState = vm.runtime.powerState
    perDataStoreUsage = vm.storage.perDatastoreUsage

    # Print test

    print("Name                         : ", name)
    print("Power State                  : ", powerState)
    print("Is VM a template?            : ", template)
    print("Host                         : ", host)
    print("Number of CPUs               : ", numCPU)
    print("CPU reservations             : ", cpuReservation)
    print("Memory Allocated in GB       : ", memorySizeGB)
    print("Memory reserved in GB        : ", memoryReservation)
    print("Are VMware tools installed?  : ", toolsStatus)
    print("VMware tools version         : ", toolsVersion)
    print("OS short name                : ", guestId)
    print("OS full name                 : ", guestFullName)
    print("OS alternate name            : ", guestAlternateName)
    print("VM description               : ", description)
    print("VM UUID                      : ", instanceUuid)
    print("Datastore name               : ", dataStore)
    print("Datastore usage              : ", perDataStoreUsage)

    break
```

Output:

Traceback (most recent call last):
  File "C:/Users/jfort/PycharmProjects/VMware test/VMware test.py", line 40, in <module>
    dataStore = vm.datastore.info.name
AttributeError: 'ManagedObject[]' object has no attribute 'info'

If I remove the .info.name from that line it simply responds with:
Datastore name               :  (ManagedObject) [
   'vim.Datastore:datastore-59546'
]

Am I missing something here? Or is this not working as intended?  If I change to pulling datastores directly, I can pull the name just fine, but I'm trying to work with the VMs as the main object, and then I can pull related information about the VM host or datastore in separate requests.

**Comment by prziborowski** [comment]
vm.datastore is going to be a list of datastores that are associated with the VM (disks can be on different datastores, etc).
So you would have to iterate that list and for each of them get the info.name (or possibly just name).

**Comment by castertr0y357** [comment]
It works!

I thought it would list the primary datastore of a VM like it does when you look at it directly in vCenter.  That also resolves a similar issue I had with the vm.storage.perDatastoreUsage field as well.  I have to specify a list index in order to see the attributes.

Thank you!
