### ISSUE TITLE
Error in si.content.sessionManager.SessionIsActive

### ISSUE THREAD

**Issue by luminostech1089** [vmware/pyvmomi#749]
I am using si.content.sessionManager.SessionIsActive to check if the current session is active or not.
I am using pyvmomi version: 
Here is my code:6.7.0.2018.9

si = connect.SmartConnect(host='192.168.200.10', user='root', pwd=r'abc123', port=443, sslContext=ssl._create_unverified_context())
sessionid = si.content.sessionManager.currentSession.key
print si.content.sessionManager.SessionIsActive(sessionid, 'root')

The above code throws an below exception at line 'print si.content.sessionManager.SessionIsActive(sessionid, 'root')'

Traceback (most recent call last):
  File "vsphereUtils.py", line 448, in <module>
    print si.content.sessionManager.SessionIsActive(sessionid, 'root') 
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.NotImplemented: (vmodl.fault.NotImplemented) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The requested operation is not implemented by the server.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []

**Comment by pgbidkar** [comment]
What is the VCenter version?
I have tested with 6.7, 6.5 & 6.0 It works fine for me.

>>> sessionid = si.content.sessionManager.currentSession.key
>>> print si.content.sessionManager.SessionIsActive(sessionid, '<VC UserName>')
True

**Comment by prziborowski** [comment]
> si = connect.SmartConnect(host='192.168.200.10', user='root', pwd=r'abc123', port=443, sslContext=ssl._create_unverified_context())

Are you connecting to vCenter or directly to the ESXi host?
It is not implemented against the ESXi host.

**Comment by pgbidkar** [comment]
Yes! it is not implemented against ESXi Host. 
With vCenter it works fine

**Comment by pgbidkar** [comment]
@prziborowski Can I close this issue?

**Comment by luminostech1089** [comment]
oh I see, i am connecting directly to esxi. Is there any other way we can do it for ESXi?
