### ISSUE TITLE
how to find the vim(by hostname) blong to which cluster?

### ISSUE THREAD

**Issue by shrekee** [vmware/pyvmomi#758]
when connect to the vCenter, I can get all VMs. But, how can i find the VM blong to which cluster?
I need your help

**Comment by pgbidkar** [comment]
Refer Sample, if it helps 
 https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getvmsbycluster.py

**Comment by pgbidkar** [comment]
Hi @shrekee Can we close this issue if your query is answered?

Thanks

**Comment by shrekee** [comment]
@pgbidkar It worked .thanks a lot .
