### ISSUE TITLE
How to InstanClone

### ISSUE THREAD

**Issue by Rouss0107** [vmware/pyvmomi#760]
Hey everyone,
I'm trying to create a script to clone a VM, in order to prepare a preproduction environment out of a production server.

So far, I've been able to clone a VM from the CloneVM sample available. Now I would like to try the InstantClone functionality, but I'm unable to make it work.

This works:
```
    # Prepare the clone spec
    clonespec = vim.vm.CloneSpec()
    clonespec.location = relospec
    clonespec.powerOn = power_on
    clonespec.customization = customizationSpec;

    # Cloning VM
    task = template.Clone(folder=destfolder, name=vm_name, spec=clonespec)
    wait_for_task(task)
```

This doesn't:
```
    # Prepare the instant clone spec
    instantCloneSpec = vim.vm.InstantCloneSpec()
    instantCloneSpec.location = relospec
    instantCloneSpec.name = vm_name

    # Instant cloning VM
    task = template.InstantClone(spec = instantCloneSpec)
    wait_for_task(task)
```

I receive this error:
```
Exception has occurred: pyVmomi.VmomiSupport.vmodl.fault.MethodNotFound
(vmodl.fault.MethodNotFound) {    dynamicType = <unset>,    dynamicProperty = (vmodl.DynamicProperty) [],    msg = <unset>,    faultCause = <unset>,    faultMessage = (vmodl.LocalizableMessage) [],    receiver = 'vim.VirtualMachine:vm-2471',    method = 'InstantClone' }
  File "...\Script.py", line 266, in clone_vm
    task = template.InstantClone(spec = instantCloneSpec)
  File "...\Script.py", line 329, in main
    args.destination_IP_Address)
  File "...\Script.py", line 335, in <module>
    main()
```

I'm usually used to work with C#, but the vSphere API done in C# is just awfully implemented. So I switched to the python version. I'm not used to python, so it may be a newbie mistake.

Thanks for the help

**Comment by Rouss0107** [comment]
You mean the vCenter Server version ?
My vSphere Client is telling me the server is in version 6.0.0.
So I guess that's the issue. I'll try to find out how to update the VC version.

Thanks for the help. I'll close this issue, and reopen it in case I've got issue once my VC will be updated to the last version

**Comment by JackDan9** [comment]
Hi，@Rouss0107 
```
    # Prepare the clone spec
    clonespec = vim.vm.CloneSpec()
    clonespec.location = relospec
    clonespec.powerOn = power_on
    clonespec.customization = customizationSpec;

    # Cloning VM
    task = template.Clone(folder=destfolder, name=vm_name, spec=clonespec)
    wait_for_task(task)
```
Has your CustomizationSpec been successfully implemented in the first way?
