### ISSUE TITLE
Unable to add New Disk to an Existing VM - Invalid Configuration for Device '1'

### ISSUE THREAD

**Issue by sujeetkp** [vmware/pyvmomi#762]
I am trying to create a VM and add NIC, Disk to it.
I am able to create the VM, add the NIC, also able to create a controller, but when I try to add the disk, I am getting the error as 'invalid configuration for Device 0'.

I am not sure what I am doing wrong. Please help.

    service_instance = ConnectToVMWare(ServiceProviderDetails)  
    content = service_instance.RetrieveContent()  
    atexit.register(Disconnect, si)   
    name = 'MyVM'  
    datastore = 'datastore1'       
    datacenter = content.rootFolder.childEntity[0]
    vmfolder = datacenter.vmFolder   
    hosts = datacenter.hostFolder.childEntity  
    resource_pool = hosts[0].resourcePool
          
	print("Creating VM !!!!!! ")
	
	devices = []

	nic_type = 'E1000E'
	net_name = 'VM Network02'
	vm_name = name
	datastore_path = '[' + datastore + '] ' + vm_name
	
	content = service_instance.RetrieveContent()
		
	vmx_file = vim.vm.FileInfo(logDirectory=None,
															snapshotDirectory=None,
															suspendDirectory=None,
															vmPathName=datastore_path)
	#Add Network Card
	nicspec = vim.vm.device.VirtualDeviceSpec()
	nicspec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
	nicspec.device =  vim.vm.device.VirtualE1000e()
	nicspec.device.deviceInfo = vim.Description()
	nicspec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
	nicspec.device.backing.deviceName = net_name
	nicspec.device.backing.network = Get_Obj(content, [vim.Network], net_name)
	nicspec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
	nicspec.device.connectable.startConnected = True
	nicspec.device.connectable.allowGuestControl = True
	nicspec.device.connectable.connected = True
	
	devices.append(nicspec)
	
	config = vim.vm.ConfigSpec(name=vm_name, memoryMB=1024, numCPUs=1,
															files=vmx_file, guestId='rhel6_64Guest',
															version='vmx-09', deviceChange=devices)
	
	print ("Creating VM %s" % (vm_name))
	
	tasks = vm_folder.CreateVM_Task(config=config, pool=resource_pool)
	
	devices = []

	time.sleep(10)
	
	vmobj = Get_Obj(content, [vim.VirtualMachine],'MyVM')
	
	print(vmobj)
	
	datastore = Get_All_Objs_New(content, [vim.Datastore])
	
	#Add Hard Disk
	
	#Add Controller
	
	spec = vim.vm.ConfigSpec()
	scsi_ctr = vim.vm.device.VirtualDeviceSpec()
	scsi_ctr.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
	scsi_ctr.device = vim.vm.device.VirtualLsiLogicController()
	scsi_ctr.device.deviceInfo = vim.Description()
	scsi_ctr.device.slotInfo = vim.vm.device.VirtualDevice.PciBusSlotInfo()
	scsi_ctr.device.slotInfo.pciSlotNumber = 16
	scsi_ctr.device.controllerKey = 100
	scsi_ctr.device.unitNumber = 3
	scsi_ctr.device.busNumber = 0
	scsi_ctr.device.hotAddRemove = True
	scsi_ctr.device.sharedBus = 'noSharing'
	scsi_ctr.device.scsiCtlrUnitNumber = 7
	
	unit_number = 3
	new_disk_kb = 16 * 1024 * 1024
	print(new_disk_kb)
	disk_spec = vim.vm.device.VirtualDeviceSpec()
	disk_spec.fileOperation = "create"
	disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
	disk_spec.device = vim.vm.device.VirtualDisk()
	disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()
	disk_spec.device.backing.thinProvisioned = True
	disk_spec.device.backing.diskMode = 'Dependent'        
	disk_spec.device.capacityInKB = int(new_disk_kb)
	disk_spec.device.unitNumber = unit_number
	disk_spec.device.backing.datastore = datastore[4]
	disk_spec.device.controllerKey = 100        
	
	devices.append( scsi_ctr )
	devices.append( disk_spec )
	spec.deviceChange = devices

	vmobj.ReconfigVM_Task( spec=spec )

**Comment by pgbidkar** [comment]
Hi @sujeetkp Please can you refer sample https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py?

**Comment by Chandan-Hegde** [comment]
Are you adding existing disk or fresh disk ?

**Comment by Chandan-Hegde** [comment]
I also see that the SCSI controller unit number is specified as  "scsi_ctr.device.scsiCtlrUnitNumber = 7" and unit number is specified as 3 while adding the disk to that controller.

**Comment by pgbidkar** [comment]
Sample adds Fresh Disk to VM.
As mentioned in the sample "**unit_number 7 reserved for scsi controller**" . Hence 7 is not added as Unit number to the Disk. You can keep adding Unit number to each disk you add Except 7
Unit number 3 means VM already has 3 disks probably.

Thanks

**Comment by sujeetkp** [comment]
Thanks a lot @pgbidkar.
unit_number was the issue. I fixed it. :)
