### ISSUE TITLE
How to get tags and configurations of all VMs

### ISSUE THREAD

**Issue by shekharHPE** [vmware/pyvmomi#765]
How to get tags and configurations of all VMs
I need the information about tags and configurations assigned to all the Clusters and VMs.
Any help would be appreciated.

**Comment by pgbidkar** [comment]
Hi @shekharHPE Please refer SDK https://github.com/vmware/vsphere-automation-sdk-python for Tagging operations.
Specific Sample would be https://github.com/vmware/vsphere-automation-sdk-python/blob/master/samples/vsphere/tagging/tagging_workflow.py

Thanks

**Comment by shekharHPE** [comment]
Thank you Pavan Bidkar
