### ISSUE TITLE
pyvmomi - Get VM information through VM Id

### ISSUE THREAD

**Issue by JackDan9** [vmware/pyvmomi#767]
I just want to query the information of this VM Id separately. How can I get it?

**Comment by pgbidkar** [comment]
Hi @JackDan9 Refer Sample https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vminfo_quick.py

**Comment by pgbidkar** [comment]
Hi @JackDan9 Closing this issue. Please update and reopen if you are finding issue.

Thanks

**Comment by JackDan9** [comment]
Ok，Thank you very much! @pgbidkar
