### ISSUE TITLE
Anyone knows how to create a vm from a template in content library using pyvmomi? 

### ISSUE THREAD

**Issue by bowanggu** [vmware/pyvmomi#789]
Does pyvmomi currently support content library?

**Comment by prziborowski** [comment]
pyVmomi is the binding for the "vSphere Web Services API". Content library is part of "vSphere Automation API", which are REST based. They aren't interchangeable and pyVmomi doesn't have support for those APIs.

**Comment by bowanggu** [comment]
Thanks for your quick reply. I am trying to automatic the vcenter action to do `New VM from Library` as shown here in the vsphere interface
![Screen Shot 2019-04-17 at 5 08 42 PM](https://user-images.githubusercontent.com/25350728/56326536-a15d8d80-6133-11e9-9fb1-403eb813c29c.png)
Any suggestions?

**Comment by pgbidkar** [comment]
Hi @bowanggu Please refer vsphere-automation-python-sdk repo https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/contentlibrary for content library APIs and samples.

As mentioned by @prziborowski  contentLibrary Samples are REST based, which are not supported by pyVmomi

Thanks
