### ISSUE TITLE
How to list all VMs absolute folder path

### ISSUE THREAD

**Issue by vmovva** [vmware/pyvmomi#790]
I am trying to list all VMs in VCSA and their absolute Folder Path. 

For example : 

> [DC1,Folder_A,Folder_AA,myVM1]
> [DC1,Folder_A,myVM0]
> ....

I found samples to list VMs and also find folder for a given VM. However, i didn't find any sample to list all VMs with it's absolute folder path.

**Comment by Akasurde** [comment]
https://github.com/Akasurde/ansible-reproducers/blob/master/790/get_all_vms.py

**Comment by kumahesh** [comment]
Hi @vmovva , Can we close the issue?
@Akasurde ,  I have gone through your sample. Could you add those modifications to the community sample [getallvms.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getallvms.py) and raise pull request?
