### ISSUE TITLE
Enhanced linked mode

### ISSUE THREAD

**Issue by ariksa** [vmware/pyvmomi#798]
Hi,

Could you please advise how can I get info about all linked vCenter servers?
I would expect something like:
```
si = connect.SmartConnect(host, username, password)
content = si.RetrieveContent()
linked_content = content.get_all_linked_vcenters()
```

Ideally I would like to be able to perform operations (e.g. deploy VM) on the linked vCenter, the same way it is possible from the web UI.

Thanks.

**Comment by pgbidkar** [comment]
Hi @ariksa , Please can you check if this helps. https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/vcenter/hvc

Thanks

**Comment by pgbidkar** [comment]
Hi @ariksa , Please let me know if we can close this issue?

Thanks
