### ISSUE TITLE
Datastore Over Provisioning

### ISSUE THREAD

**Issue by Imranatnisum** [vmware/pyvmomi#802]
Would you pls  share some way to to get Datastore Over Provisioning 

python version:
3.7
vSphere version:
6.0, 6.5 and 6.7
Operating System/Shell (used to run SDK-based apps):
Mac os

**Comment by kumahesh** [comment]
From your comment, I understand that you wanted to avoid the problem of over provisioning the resource. Did you check this [community thread](https://communities.vmware.com/thread/508059)?. please do correct my understanding if I am wrong.

**Comment by Imranatnisum** [comment]
Yes, I did check. But i would like to get metrics for data store over provisioning through API call by pymomi . Like for example, using pymomi we can get amount of cpu  for a virtual machine.

**Comment by kumahesh** [comment]
Hi @Imranatnisum , Have you used QueryPerf method of [vim.performanceManager](https://www.vmware.com/support/developer/converter-sdk/conv43_apireference/vim.PerformanceManager.html#queryStats)? you have to construct queyspec object which should include datastore object as entity that you interested to collect metrics.

**Comment by kumahesh** [comment]
Hi @Imranatnisum , Is that issue got resolved?
