### ISSUE TITLE
Handling Login Failures

### ISSUE THREAD

**Issue by tomburge** [vmware/pyvmomi#803]
I can't seem to figure out how to handle a failed login gracefully. When the proper user credentials are entered its easy to check. But if its a failed credential, it dumps  a stack trace. 

Is there a better way to handle this exception than dumping a stack trace? Like http status code 401 or something like that. There is a message about login failed, but I can't seem to catch it to raise the proper exception.

`{'hostname': 'celery@ba3d63430bb0', 'id': 'f29e9886-d0de-46a0-8595-40f80b502f40', 'name': 'call.vcenter.test', 'exc': '(DataObject) {\n\n}', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/app/app.py", line 87, in call_vcenter_test\n    code = test_vcenter_connect(vchost, vcuser, vcpass, vcport)\n  File "/app/test_connect.py", line 23, in test_vcenter_connect\n    service_instance = connect.SmartConnect(host=vchost, user=vcuser, pwd=vcpass, port=int(vcport), sslContext=context)\n  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 856, in SmartConnect\n    mechanism=mechanism)\n  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 266, in Connect\n    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)\n  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 390, in __Login\n    x = content.sessionManager.Login(user, pwd, None)\n  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File "/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File "/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.vim.fault.InvalidLogin: (vim.fault.InvalidLogin) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = \'Cannot complete login due to an incorrect user name or password.\',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}\n', 'args': "['vc01.home.lab', 'administrator@vsphere.local', 'pass', '443']", 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False}`

**Comment by tomburge** [comment]
I was able to resolve with this code:

`def test_vcenter_connect(vchost, vcuser, vcpass, vcport):
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE
    try:
        service_instance = connect.SmartConnect(host=vchost, user=vcuser, pwd=vcpass, port=int(vcport), sslContext=context)
        if service_instance:
            return 200
    except Exception:
        return 401`

**Comment by kumahesh** [comment]
Hi @tomburge,
Why don't you catch the exception object "vim.fault.InvalidLogin" that could provide nice handle over login failure scenario?

**Comment by kumahesh** [comment]
Hi @tomburge , Can we close the issue?
