### ISSUE TITLE
How can I Enable Network I/O Control on a vSphere Distributed Switch ?

### ISSUE THREAD

**Issue by JackDan9** [vmware/pyvmomi#804]
The DVSFeatureCapability data object represents the capabilities supported by a DistributedVirtualSwitch. These properties are read-only with the exception of vmDirectPathGen2Supported. [https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.DistributedVirtualSwitch.Capability.html](https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.DistributedVirtualSwitch.Capability.html)
How can i Enable Network I/O Control on a vSphere Distributed Switch ?

**Comment by JackDan9** [comment]
@prziborowski any idea?

**Comment by prziborowski** [comment]
Sorry I'm not familiar with this part of the product.

**Comment by jobingeo** [comment]
Will this help?
https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.DistributedVirtualSwitch.html#enableNetworkResourceManagement

**Comment by JackDan9** [comment]
Thanks! @jobingeo i will try it.

**Comment by JackDan9** [comment]
@prziborowski @@jobingeo  Thank you very much, I solve this problem by the way.

**Comment by cjain85** [comment]
@JackDan9 I am working on enabling network i/o control on distributed switch . May I know how did you solve this
