### ISSUE TITLE
Can the API create a virtual machine?

### ISSUE THREAD

**Issue by yJun-Chen** [vmware/pyvmomi#805]
I want to create virtual machines in batches using api, but I don't know what to do or I don't know if I have this feature?

**Comment by prziborowski** [comment]
A very basic sample of the create VM api is at: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/create_random_marvel_vms.py
Also there are a number of scripts that can reconfigure VMs to add devices, or make other changes.
Usually you can do all of that in the CreateVm API call, so you can combine multiple parts of scripts as examples.

**Comment by kumahesh** [comment]
@yJun-Chen , I hope @prziborowski answer solved your query. Can we close the issue?
