### ISSUE TITLE
Creating RP for a clutser

### ISSUE THREAD

**Issue by djcutch** [vmware/pyvmomi#806]
Hello,

I am trying to create a RP with pyvmomi but am having issues

# Connect to vCenter Server
si = SmartConnectNoSSL(host=hostname, user=serverusername, pwd=serverpassword, port=int(443))

# Disconnect from vCenter upon exit
atexit.register(Disconnect, si)

def create_rp(datacenter, clusterName, rpname):
    # ---------------CreateResourcePool---------------
    
    spec = vim.ResourceConfigSpec()
    spec.memoryAllocation = vim.ResourceAllocationInfo()
    spec.memoryAllocation.shares = vim.SharesInfo()
    spec.memoryAllocation.shares.shares = 163840
    spec.memoryAllocation.shares.level = 'normal'
    spec.memoryAllocation.limit = -1
    spec.memoryAllocation.reservation = 0
    spec.memoryAllocation.expandableReservation = True
    spec.cpuAllocation = vim.ResourceAllocationInfo()
    spec.cpuAllocation.shares = vim.SharesInfo()
    spec.cpuAllocation.shares.shares = 4000
    spec.cpuAllocation.shares.level = 'normal'
    spec.cpuAllocation.limit = -1
    spec.cpuAllocation.reservation = 0
    spec.cpuAllocation.expandableReservation = True
    content = si.content
    dc = get_obj(content, vimtype=[vim.Datacenter], name=datacenter)
    cluster = get_obj(content, [vim.ClusterComputeResource], cluster_name)
    rootResourcePool  = cluster.resourcePool
    print('{}'.format(rpname))
    rp_obj = rootResourcePool .CreateResourcePool(rpname, spec)

(ManagedObject) [
   'vim.Datacenter:ha-datacenter'
]
(ManagedObject) []
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    create_rp (datacenter, clusterName, rpname)
  File "test.py", line 70, in create_rp
    rootResourcePool  = cluster.resourcePool
AttributeError: 'NoneType' object has no attribute 'resourcePool'

**Comment by prziborowski** [comment]
> cluster = get_obj(content, [vim.ClusterComputeResource], cluster_name)
This line is reporting no clusters.
I don't know where cluster_name is set as the input to the function is:
> def create_rp(datacenter, clusterName, rpname):
So should it be clusterName? And I guess double check that cluster name exists in your environment.

**Comment by djcutch** [comment]
> > cluster = get_obj(content, [vim.ClusterComputeResource], cluster_name)
> > This line is reporting no clusters.
> > I don't know where cluster_name is set as the input to the function is:
> > def create_rp(datacenter, clusterName, rpname):
> > So should it be clusterName? And I guess double check that cluster name exists in your environment.

Woops Sorry i updated the cluster_name to clusterName but the results i have still returning the error above.

**Comment by prziborowski** [comment]
You might have to play around and see where things are going unexpected.

Such as:
```
clusters = get_obj(content, [vim.ClusterComputeResource])
print("clusters: %s" % clusters)
for cluster in clusters:
   print("%s: '%s'" % (cluster, cluster.name))
```
And see if it is properly getting your clusters, and if the name being passed in match what you expected.

**Comment by djcutch** [comment]
I am wondering if my get_obj is causing the problem as no values return

def get_obj(content, vimtype):
    obj = None
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    print(container.view)
    for managed_object_ref in container.view:
        if name:
            if managed_object_ref.name == name:
                obj = managed_object_ref
                break
        else:
            obj = managed_object_ref
            break
    return obj

**Comment by prziborowski** [comment]
I don't see a particular problem with that function (formatting on github got messed up a bit).
But it seems to imply that your vCenter has no clusters (at least that you have permissions to view with your user).

**Comment by djcutch** [comment]
Yeah idk what seem to be the issue I am pulling the dc object with out any issues.  But with the cluster it comes back as none and I am using administrator@vsphere.local

**Comment by djcutch** [comment]
I figure it out i can post the results if you like but i was trying to connect to the esxi host vs vcenter man these long days trying to learn python has been very painfull.

**Comment by kumahesh** [comment]
Hi @djcutch 
Did that issue got resolved? Can we close the issue?

**Comment by djcutch** [comment]
Pls close
