### ISSUE TITLE
Relocate vm disk datastore only, probably per disk.

### ISSUE THREAD

**Issue by welibekov** [vmware/pyvmomi#808]
Hi, does anyone know, how to relocate disk datastore only.
And how to do that per disk? If possible please share code snippet. Thanks!

**Comment by prziborowski** [comment]
In the [vim.vm.RelocateSpec](https://code.vmware.com/apis/358/vsphere#/doc/vim.vm.RelocateSpec.html)#[disk[]](https://code.vmware.com/apis/358/vsphere#/doc/vim.vm.RelocateSpec.DiskLocator.html), you can specify the diskId as well as datastore you wish to move that disk to.

You might have to play around with whether you need to set vim.vm.RelocateSpec#datastore to the current datastore or not. But to relocate the disks you need to make 1 entry per disk.

Example might be
```
rspec = vim.vm.RelocateSpec()
rspec.datastore = vm.datastore[0] # Not positive if this will be where the VM home is, so that is some homework.
for device in vm.config.hardware.device:
   if isinstance(device, vim.vm.device.VirtualDisk):
      rspec.disk.append(vim.vm.RelocateSpec.DiskLocator(diskId=device.key, datastore=dstDs))
task = vm.Relocate(rspec)
WaitForTask(task)
```

**Comment by welibekov** [comment]
prziborowski, you made my day! Thanks a lot.
