### ISSUE TITLE
How to clone vm as-is. No change disks datastores

### ISSUE THREAD

**Issue by welibekov** [vmware/pyvmomi#809]
I have vm with two disks, both from different datastores. After clone, vcenter move all two disks to "recommended" datastore.
Hi, does anyone know, how to clone vm without moving disks to recommended datastore?
Appreciate!

**Comment by kumahesh** [comment]
Please refer the community sample 'clone vm' where you have a choice parameter to set [datastore](https://github.com/vmware/pyvmomi-community-samples/blob/83c8bc362d3c3eaec665228618b62a958d0752a7/samples/clone_vm.py#L172)
The sample code use recommended datastore only if you provide the  choice parameter [datastore cluster](https://github.com/vmware/pyvmomi-community-samples/blob/83c8bc362d3c3eaec665228618b62a958d0752a7/samples/clone_vm.py#L201)

**Comment by welibekov** [comment]
Hi kumahesh,
Thank you for response. The problem is, that i have more than one disk.
And set "datastore" parameter will affect all disks i guess.

**Comment by kumahesh** [comment]
Yeah, you are correct. Set datastore parameter will move all disks to specified datastore. If you want to configure/keep the (same) datastore per disk, you can customize this [disklocater array](https://www.vmware.com/support/developer/converter-sdk/conv51_apireference/vim.vm.RelocateSpec.DiskLocator.html) to your need. Please refer this [ relocate_vm code sample](https://github.com/vmware/pyvmomi-community-samples/blob/83c8bc362d3c3eaec665228618b62a958d0752a7/samples/relocate_vm.py#L99) to see how to configure datastore per disk

**Comment by kumahesh** [comment]
@welibekov , Is that issue solved? can we close the issue?

**Comment by welibekov** [comment]
Yes, sorry for delayed response. Thank you very much!
You can close it.
