### ISSUE TITLE
Problem getting vm's tags on v6.7.1

### ISSUE THREAD

**Issue by yairshemla** [vmware/pyvmomi#811]
Hi, as @jeking3 posted on this thread:
https://github.com/vmware/pyvmomi/issues/733
Since v6.7.1 the vm's tags should be attached to the pyVmomi object.
For some reason I get an empty list: `(vim.Tag) []`
If I query directly the new API (`/rest/com/vmware/cis/tagging/tag-association?~action=list-attached-tags`) I'm getting the tag_id back: `urn:vmomi:InventoryServiceTag:8b7543da-564a-4ba7-8d24-1f6299aad359:GLOBAL`.

Am I missing something? Is it possible to get a specific vm's tags through pyVmomi?

Original comment:

There were some changes in v6.7.1 for tagging:
https://github.com/vmware/pyvmomi/commit/aace16b3257c6d2389554210906f0d63c94ea69e#diff-8fbd2be360383e3b0e54628cfce44c5dL240

Perhaps this fixed tagging, as now I see tags in the results through pyVmomi:
```
    "tag": [
        {
            "dynamicProperty": [], 
            "dynamicType": null, 
            "key": "SYSTEM/COM.VMWARE.VIM.VC"
        }
    ], 
```

_Originally posted by @jeking3 in https://github.com/vmware/pyvmomi/issues/733#issuecomment-434382049_

**Comment by pgbidkar** [comment]
Hi @yairshemla , tagging APIs are not part of pyVmomi. Please can you refer SDK repo https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/tagging for tagging API. Please raise issue in this repo if you find any issue

Thanks

**Comment by jeking3** [comment]
I was under the impression the tags can be read through pyVmomi as they show up as properties on each object, but you cannot modify them (or perhaps query based on them).  Not sure why tags are treated so differently from the rest of the object model.  It's an unfortunate design decision.

**Comment by pgbidkar** [comment]
Hi @jeking3 , tagging is the first REST API introduced with vSphere 6.0 release. SDK repo (vsphere-automation-python-sdk) all feature APIs are REST based.

**Comment by yairshemla** [comment]
@jeking3 As you said - I just need to view the tags and categories names associated to the VM, I don't need to edit them.
I think that pyVmomi's `tag` field is not working at all, and always return empty. @pgbidkar That's correct?

Thanks

**Comment by pgbidkar** [comment]
Hi @yairshemla , Please can you share your script? also please can you try the sample here https://github.com/vmware/vsphere-automation-sdk-python/tree/master/samples/vsphere/tagging?
Thanks

**Comment by kumahesh** [comment]
@yairshemla ,
Have you tried the above mentioned sample?

**Comment by yairshemla** [comment]
Hi, I used the new sdk package and it worked. Anyway I don't like the way
this API is handled by VMware. There's no good way to know if a tag is
changed or not...

Thanks for the help!
