### ISSUE TITLE
Importing SSL Certificates

### ISSUE THREAD

**Issue by TheNotary** [vmware/pyvmomi#813]
Can pyvmomi be used to import an ssl/ tls certificate?  Monthly certificate rotation is becoming a new technology trend so adding a sample of importing certs would be quite relevant.  

Edit: 
I came across this solution in the mean time which may explain why no one's submitted an example of dealing with certs through pyvmomi or a REST API.

```
# 1. Copy the certs to ESXi (6.5)
scp fullchain.pem example.com:/etc/vmware/ssl/rui.crt
scp privkey.pem example.com:/etc/vmware/ssl/rui.key

# 2. Restart the webserver
ssh example.com /etc/init.d/rhttpproxy restart
```

**Comment by kumahesh** [comment]
Hi @TheNotary , Since you said this task of importing certificate could be easily achieved by writing a script file, I could not convinced enough about the pyvmomi sample for that task. Could you please explain the necessity of sample?

**Comment by TheNotary** [comment]
I wouldn't use the word `necessity` since the workaround I shared exists, but you're right that there are downsides of using the workaround.  The workaround bypasses the ESXi middleware, and as it would seem, the UI doesn't seem to recognize the new cert (although the webserver is 100% using it).  Also, for people who configure their ESXi systems through pyvmomi, they may want to do 'all' configuration through that language instead of only doing parts of it.  

For the above reason, I would strongly recommend a pure pyvmomi solution be added to the samples if a PR for them were to arise.

**Comment by luckyinfil** [comment]
@TheNotary did you happen to find a solution for this? vRO has a notifyAffectedServices() method that applies the ESXi certs once it's on the host.

http://vroapi.com/Method/VC/6.5.0/VcHostCertificateManager/notifyAffectedServices

I can't find anything for pyvmomi though and the mob doesn't seem to have that method.

**Comment by luckyinfil** [comment]
@kumahesh is there a way to implement the above API using pyvmomi?

**Comment by TheNotary** [comment]
Hi @luckyinfil, I'm using the workaround in the OP still.  Looking back, I believe it's actually ideal that the solution be in bash commands since most other cert renewal processes are in bash commands (e.g. curl) and so the cert_install script can all be in a single file.

**Comment by luckyinfil** [comment]
@TheNotary can you expand on what you mean by the bash commands? Do you mean that you are refreshing the services by restarting the rhtppproxy service
