### ISSUE TITLE
Download from Datastore

### ISSUE THREAD

**Issue by Harish0596** [vmware/pyvmomi#814]
Hi 

Is there a python code to download a file from a specific datastore in vSphere using pyvmomi.
Kindly help me out on this.

**Comment by kumahesh** [comment]
Hi @Harish0596, 

Have you referred the [upload_file_to_datastore code sample](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/upload_file_to_datastore.py) of pyVmomi?

You want to do the opposite (downloading from the specific datastore). For that, replace the code segment starting at [line no. 124](https://github.com/vmware/pyvmomi-community-samples/blob/83c8bc362d3c3eaec665228618b62a958d0752a7/samples/upload_file_to_datastore.py#L124) with the following.
`        with open(args.local_file, "wb") as f:
            # Connect and upload the file
            response = requests.get(http_url,
                                   params=params,
                                   headers=headers,
                                   cookies=cookie,
                                   verify=verify_cert)
            f.write(response.content)`

For downloading files of large size, the above code should be modified in a way to write chunks of data from multiple consecutive server's responses.

**Comment by kumahesh** [comment]
Hi @Harish0596 ,
can we close the issue?

**Comment by dinis-cruz-gw** [comment]
perfect @kumahesh that helped

**Comment by ThakeeNathees** [comment]
@SarindraTherese I had the same issue, and if you remove the line `data=f` from you code it'll work since it was used for uploading the file
