### ISSUE TITLE
vmdk file mapping with windows drive letter

### ISSUE THREAD

**Issue by shital1313** [vmware/pyvmomi#815]
I need details of vmdk file mapping with windows drive letter. 
With the below methods, I able to get disk info:
_vm.guest.disk        =>  drive, freespace, capacity
vm.layoutEx.file    =>   all datastore items with size._

I was thinking to map drive with vmdk based on size, but the size information not matching with provisioned size in case of thin provisioning. vmdk size is not displaying provisioned size, it's actual vmdk size.

**Expected details:**
[datastorename] file3_volume.vmdk     =>      C- drive
[datastorename] file1_volume.vmdk     =>      D- drive
[datastorename] file2_volume.vmdk     =>      E- drive

**Comment by kumahesh** [comment]
@shital1313 
Is it same as this issue [816](https://github.com/vmware/pyvmomi/issues/816)?
Shall we close it?
