### ISSUE TITLE
How to get provisioned size for vmdk

### ISSUE THREAD

**Issue by shital1313** [vmware/pyvmomi#816]
With vm.layoutEx.file, we're able to get list of vmdk with size. But I was not able to get provisioned size. In Case of thin provisioning, I need information: size of vmdk and provisioned size for vmdk

**Comment by pgbidkar** [comment]
Hi @shital1313  Please can you share the Sample script?

Thanks

**Comment by shital1313** [comment]
**Hi @pgbidkar,
With Below Code able to get all the files inside datastore for the VM object:**

import atexit
import json
from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
service_instance = connect.SmartConnect('host', 'user','pwd')
atexit.register(connect.Disconnect, service_instance)
content = service_instance.RetrieveContent()
container = content.rootFolder
view_type = [vim.VirtualMachine]
recursive = True
container_view = content.viewManager.CreateContainerView(container, view_type, recursive)
vms=container_view.view
vms[0].layoutEx.file

**Comment by kumahesh** [comment]
Hi @shital1313 ,
I have added these two lines to your script. I was able to find the provisioned size from [summary](https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.device.VirtualDevice.html) field of the device(hard disk).

`for dev in vms[0].config.hardware.device:
    print(dev.deviceInfo)`

I hope it helps

**Comment by kumahesh** [comment]
Have you tried it? Can we close the issue?

**Comment by shital1313** [comment]
Yes, I was tried, and getting results as expected.
You can close this issue.
Thank you for assistance.
