### ISSUE TITLE
How can i remove custom values from a vm?

### ISSUE THREAD

**Issue by chalupaul** [vmware/pyvmomi#821]
Seems to be that there are only methods to create custom attributes and set them on managed objects, but the methods to delete them don't seem to be there. I tried setting the value to None, but it complains at me. Like, there's vm.setCustomValue(key=tag_name, value=tag_value), but how can I emulate a vm.removeCustomValue() method?

**Comment by kumahesh** [comment]
To my knowledge, we do not have api to create/delete custom attributes. Contact Vmware global support for feature request.

**Comment by lny005** [comment]
To remove the value (to $null) from a CustomAttribute on a specific VM:
get-vm $vm | Set-Annotation -CustomAttribute "ca-name" -Value ""

You can only remove a Custom Attribute globally in vCenter under /Tags & Custom Attributes, not on a specific VM or other instance.

Hope that helps.
