### ISSUE TITLE
What is the plan to support vSphere 7.0?

### ISSUE THREAD

**Issue by YeJianXin** [vmware/pyvmomi#829]
Hi Guys,

Anybody knows the plan to support the vSphere 7.0? thanks in advance!

Regards,
Jason Ye

**Comment by pgbidkar** [comment]
Hi @YeJianXin , Yes. 7.0 support is in pipeline.  

Thanks

**Comment by pgbidkar** [comment]
Closing the issue.
Please let me know if more details required

**Comment by YeJianXin** [comment]
Hi Pgbidkar, thanks for the reply! That will be great If you can let me know the release strategy, for example,  2 months after vSphere 7.0, Or 15 days after vSphere 7.0?
