### ISSUE TITLE
How to upload license file

### ISSUE THREAD

**Issue by schua1** [vmware/pyvmomi#838]
Hi all,

In older version pyVmomi SDK the instance of type LicenseAssignmentManager under path service_instance.content.licenseManager has a method named UploadLicenseFile then I just checked the reference and found this API is not avaiable any more.
My question is how I can upload license file with this method calling.

Thanks and best regards,
Flik

**Comment by kumahesh** [comment]
Can you mention the version number of the older pyVmomi? I could not find the method "UploadLicenseFile" in any of versions released in last one year. To get immediate resolution, contact Vmware support.

**Comment by schua1** [comment]
It looks like version 5.5. However I only have compiled version and there are more than 30 additional type definition files comparing to any published version of pyVmomi.
For example, the UploadLicenseFile is defined in attached package and class `vim.LicenseAssignmentManager`.
[ServerObjects.zip](https://github.com/vmware/pyvmomi/files/3710541/ServerObjects.zip)
