### ISSUE TITLE
 Support for VMware Update Manager

### ISSUE THREAD

**Issue by acpatric** [vmware/pyvmomi#840]
Hi all,
Are there plans to support APIs using VUM to update hosts/clusters?  Right now I'm unable to find any pyvmomi support for this.  If there is, can you point me to it?  There seems to only be support in PowerCLI on Windows.

Thanks, appreciate any insight you can give.

**Comment by kumahesh** [comment]
It is compelling use case for power cli to have VUM support because of its footprint among administrators. To my knowledge, Our scope is all about VMware vSphere API to manage ESX, ESXi, and vCenter.
