### ISSUE TITLE
Applying Advance Settings Issue

### ISSUE THREAD

**Issue by caseysalvador** [vmware/pyvmomi#853]
I'm having an issue trying to run update_esxi_advanced_settings.py
The issue I'm having is when I input the host information and credentials and try to authenticate the ESXi host, I'm receiving a Caught exception : 'NoneType' object has no attribute 'host'. To clarify, we do not have a cluster everything is being run locally. While looking over the script it appears that it's trying to query the host from the cluster information you parse in as -c for arguments. I don't parse the -c option since we don't have it in a cluster. Any way around this?

**Comment by kumahesh** [comment]
Hi @caseysalvador ,
The sample had been written with vcenter in mind.  I believe that same sample will cover your case with few modifications. 

Remove the code parts related to cluster.
Get the host object you are connecting to:
host = get_obj(content,[vim.HostSystem], args.host)
Call the same routine to update options over this 'host' instead of multiple hosts in a cluster.

**Comment by caseysalvador** [comment]
> Hi @caseysalvador ,
> The sample had been written with vcenter in mind. I believe that same sample will cover your case with few modifications.
> 
> Remove the code parts related to cluster.
> Get the host object you are connecting to:
> host = get_obj(content,[vim.HostSystem], args.host)
> Call the same routine to update options over this 'host' instead of multiple hosts in a cluster.

Hi @kumahesh so I commented out the cluster =get_obj portion and the parser.arguments portion of cluster. I then inserted host = get_obj(content,[vim.HostSystem], args.host) per your recommendation. I then inserted print statements to see what host = get_obj returns and its return type which I'm still getting None and <class 'NoneType'> See revision below and let me know if I'm doing something wrong here. Thank you so much for your help!
`host = get_obj(content,
                          [vim.HostSystem], args.host)
        print(host)
        print("-------------")
        print(type(host))
        print("=================")
        hosts = host.host
        for host in hosts:
            optionManager = host.configManager.advancedOption
            option = vim.option.OptionValue(key=args.key,
                                            value=long(args.value))
            print("Updating %s on ESXi host %s "
                  "with value of %s" % (args.key, host.name, args.value))
            optionManager.UpdateOptions(changedValue=[option])`

**Comment by caseysalvador** [comment]
@kumahesh I also tried to un-assign the variable hosts = host and commented it out and directed optionManager = host.configManager.advancedOption. When I run this code:
`host = get_obj(content,[vim.HostSystem], args.host)
        print(host)
        print("-------------")
        print(type(host))
        print("=================")
        #hosts = host.host

        #for host in hosts:
        optionManager = host.configManager.advancedOption
        option = vim.option.OptionValue(key=args.key,value=long(args.value))
        print("Updating %s on ESXi host %s "
                "with value of %s" % (args.key, host.name, args.value))
        optionManager.UpdateOptions(changedValue=[option])`

I'm receiving the following: Caught exception : 'NoneType' object has no attribute 'configManager'

**Comment by kumahesh** [comment]
Could you check the parameter 'args.host'? Is it vcenter name or Esxi host name?

**Comment by caseysalvador** [comment]
> Could you check the parameter 'args.host'? Is it vcenter name or Esxi host name?

@kumahesh so for `args.host` I assign it to the ESXi IP Address.
python3 python file.py -s ip address of ESXi -u username -p password -k advance settings option -v value
when I print out args.host, I'm getting the ESXi IP Address value that I passed through as -s or --host

This is the code for parser.args
`parser.add_argument('-s', '--host',
                        required=True,
                        action='store',
                        help='Remote host to connect to')`

**Comment by caseysalvador** [comment]
@kumahesh this is pretty much the script I'm just not sure why it's still returning NoneType when I run it and I'm passing in an IP address as the hostname for args.host
`
#!/usr/bin/env python

import argparse
import atexit
import getpass
import ssl

from pyVmomi import vim, vmodl
from pyVim import connect
from pyVim.connect import SmartConnectNoSSL


def get_args():
    parser = argparse.ArgumentParser(
        description='Process args for setting ESXi advanced settings')

    parser.add_argument('-s', '--host',
                        required=True,
                        action='store',
                        help='Remote host to connect to')

    parser.add_argument('-o', '--port',
                        type=int,
                        default=443,
                        action='store',
                        help='Port to connect on')

    parser.add_argument('-u', '--user',
                        required=True,
                        action='store',
                        help='User name to use when connecting to host')

    parser.add_argument('-p', '--password',
                        required=False,
                        action='store',
                        help='Password to use when connecting to host')

    parser.add_argument('-k', '--key',
                        required=True,
                        action='store',
                        help='Name of ESXi Advanced Setting to update')
    parser.add_argument('-v', '--value',
                        required=True,
                        action='store',
                        help='Value of the ESXi Advanced Setting to update')

    args = parser.parse_args()
    if not args.password:
        args. password = getpass.getpass(
            prompt='Enter password for host %s and user %s: ' %
                   (args.host, args.user))

    return args


def get_obj(content, vimtype, name):

    obj = None
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj = c
            break

    return obj


def main():


    args = get_args()
    try:
        service_instance = connect.SmartConnectNoSSL(host=args.host,user=args.user,pwd=args.password,port=int(args.port))

        if not service_instance:
            print("Could not connect to the specified host using specified "
                  "username and password")
            return -1

        atexit.register(connect.Disconnect, service_instance)
        print("Able to Authenticate into",args.host) #Checking Successful Authentication

        content = service_instance.RetrieveContent()
        print("Content:",content)

        host = get_obj(content,[vim.HostSystem], args.host)
        print("Args.Host:",args.host)
        print("Host:",host)

        optionManager = host.configManager.advancedOption
        option = vim.option.OptionValue(key=args.key,value=long(args.value))
        print("Updating %s on ESXi host %s "
                "with value of %s" % (args.key, host.name, args.value))
        optionManager.UpdateOptions(changedValue=[option])

    except vmodl.MethodFault as e:
        print("Caught vmodl fault : " + e.msg)
        return -1
    except Exception as e:
        print("Caught exception : " + str(e))
        return -1

    return 0

# Start program
if __name__ == "__main__":
    main()
`

I print out host of host=get_obj(content,[vim.HostSystem],args.host) and the return of host is None.

**Comment by caseysalvador** [comment]
@kumahesh Unfortunately it appears that we are unable to go this route after figuring out how to drill down our MOB of our ESXi host and tried to apply advanced options settings it doesn't seem to apply due to licensing of our ESXi host. Thank you for your help!
