### ISSUE TITLE
import DynamicTypeManagerHelper fail

### ISSUE THREAD

**Issue by zhgcao** [vmware/pyvmomi#854]
Test in python3.7:

Code:
>>> from pyVmomi import DynamicTypeManagerHelper

That will raise a error:
packages\pyVmomi\DynamicTypeManagerHelper.py", line 22, in <module>
    from Cache import Cache
ModuleNotFoundError: No module named 'Cache'

In DynamicTypeManagerHelper.py, Line 22:
from Cache import Cache
Maybe should be modify to:
from .Cache import Cache

**Comment by DanielDraganov** [comment]
DynamicTypeManagerHelper was removed in https://github.com/vmware/pyvmomi/commit/a90023fedfeda48cb1824200dc4530084215f99e
