### ISSUE TITLE
Can someone explain get_service_instance_from_managed_object?

### ISSUE THREAD

**Issue by blinkesto** [vmware/pyvmomi#861]
It looks like some operations use _get_si() to get a connection but others use the si from an existing object?  Is this correct?

**Comment by kumahesh** [comment]
Hi @blinkesto ,
Can elaborate your query with links to sample code you are referring?

From my understanding, 
Soapstub has connectionpool to store a list of connections. After use, connection is returned to the pool and stay in pool. if not reused for some time(connectionpooltimeout) will be cleaned up.

When making SmartConnect() call, soapstub will be created and attached to serviceinstance object.
The class Managedobject has method "_GetStub". All instances of Managedobject created while life of the program, has stub associated with it. ServiceInstance itself is an instance of managedobject and nothing special about it.

Instances of Managed objects are created on the client side from "Deserialize" call on soap response.
The soapstub associated with the "serviceinstance" will be copied to the subsequent managed objects. This is how single soapstub is preserved throughout the life of the program.

**Comment by kumahesh** [comment]
Hi @blinkesto , Does it help? can we close the issue?
