### ISSUE TITLE
How are you using pyvmomi?

### ISSUE THREAD

**Issue by kumahesh** [vmware/pyvmomi#864]
Hi guys,
How are you using pyVmomi? What is your favorite IDE for python?
1. pyCharm
2. Visual Studio code
3. Netbeans
4. Eclipse
5. python REPL
6. others, please specify

Please respond to this poll. It help us to build IDE specific customization around pyVmomi and usability around it.

**Comment by rodrigorras** [comment]
I usually utilize VSCode or even Jupyter notebook. It all depends.

Iterative python almost eliminates the necessity to Debug the code.

happy friday,
Kind regards,
Rodrigo Rios
H


Em sex., 22 de nov. de 2019 às 07:05, kumahesh <notifications@github.com>
escreveu:
