### ISSUE TITLE
How to vMotion from vSAN Datastore to Datastore

### ISSUE THREAD

**Issue by willervinNTS** [vmware/pyvmomi#867]
I opened an issue on this about a month ago (https://github.com/vmware/pyvmomi/issues/860) and got no response. The information I provided might have made the issue a little to complicated. Does anyone know how I vMotion VCSA from a vSAN Datastore to a Datastore that I have created on a new ESX host? This would be the equivalent of right-clicking a VCSA VM, clicking Migrate -> Change both compute resource and storage -> Selecting compute resource -> Selecting storage -> Selecting network -> Selecting vMotion priority

**Comment by prziborowski** [comment]
Your previous issue slipped past my radar. Sorry about that.
If you want to change the datastore of disks and VM home, you need to fill out the `datastore` parameter of [vim.vm.RelocateSpec()](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.RelocateSpec.html). If you only want to change disks then you fill out the `disk` parameter of vim.vm.RelocateSpec().
And changing the host usually requires filling out both `host` and `pool` parameters (unless both hosts were part of the same cluster).

From the relocate_vm.py sample, I think you need: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/relocate_vm.py#L156
If you have that specified to the destination you want and it is still not moving, it sounds like a bug outside of pyVmomi.

**Comment by willervinNTS** [comment]
Thank you for the reply. This solved my issue. I had been filling out the disk parameter of vim.vm.RelocateSpec() when I didn't need to. If you don't mind me asking, what's the use case for relocating only the disks? I can't think of a reason

**Comment by prziborowski** [comment]
> If you don't mind me asking, what's the use case for relocating only the disks? I can't think of a reason

I've heard of a couple reasons. I wouldn't be surprised if there are more.
1) Keep certain disks on faster backend storage if they need better I/O performance, while other disks can be on somewhat slower (but larger) storage.
2) Load-balancing when the VMs have very large vmdk and it might not be practical to move all the disks, especially at once.

**Comment by willervinNTS** [comment]
Thank you!
