### ISSUE TITLE
pyvmomi is not Python3 compatible

### ISSUE THREAD

**Issue by abhiraut** [vmware/pyvmomi#869]
The sso.py module has statements which are not compatible with python3. It is also possible that there are other modules within the code base which are not compatible.

**Comment by linuxdan** [comment]
This module needs an update.

**Comment by pgbidkar** [comment]
> The sso.py module has statements which are not compatible with python3. It is also possible that there are other modules within the code base which are not compatible.

Hi @abhiraut , Thanks for reporting this issue. 
sso.py is new module added for latest release. Changes are made to make it compatible with Python3.  Please can you point to exact statements not compatible with Python3? it would be really helpful if you can share any test code you have.

Thanks

**Comment by abhiraut** [comment]
thanks for your prompt reply. the issue was in the module calling sso.py. Closing this bug.
