### ISSUE TITLE
I'm looking for SRM API support with pyvmomi module.

### ISSUE THREAD

**Issue by ravic499** [vmware/pyvmomi#877]
I'm looking from SRM API support with pyvmomi module (Similar to what we have for SPBM APIs).
I tried searching but not able to find any, can someone help me with it

**Comment by jobingeo** [comment]
PyVmomi doesn't have Site Recovery Manager APIs. The SRM API wsdls/SDKs can be found at , https://code.vmware.com/group/sdk/8.2/site-recovery-manager

**Comment by ravic499** [comment]
Ok Thanks
