### ISSUE TITLE
deleting parent snapshot deletes all children

### ISSUE THREAD

**Issue by sonalfulkar** [vmware/pyvmomi#878]
Hi,
I am working on remove snapshot functionality. I understand that vmware has parent child relationship in all snapshot objects.
so, if i have snapshots like:
- snapshot A
     - snapshot B
           - snapshot C
If i run removeSnapshot_Task with "snapshot A"; my snapshot B and snapshot C are also removed.
how to avoid it?
I need to keep the child snapshots and only delete the parent.
Is that possible? can someone please point me to the related code / example?
Thanks,

**Comment by prziborowski** [comment]
What is the exact method and parameters you are using?
I presume you are using [vim.vm.Snapshot#remove](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.Snapshot.html#remove).
The first parameter is `removeChildren`. You'd want to make sure to specify False for that.
`consolidate` can be blank, or True so that you don't have extra disk links.

**Comment by sonalfulkar** [comment]
I am using this file; almost everything from there line to line; as I needed all those operations.
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/snapshot_operations.py

**Comment by prziborowski** [comment]
Ok, in that case, change https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/snapshot_operations.py#L154 from True to False.

**Comment by sonalfulkar** [comment]
Yep, did that. Thanks again!

**Comment by thiDucTran** [comment]
at the time of this comment. it is actually https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/snapshot_operations.py#L107 .. pasting the line for future reference

```python
WaitForTask(snap_obj.RemoveSnapshot_Task(True))
```
