### ISSUE TITLE
host.Capability.checkpointFtSupported missing 

### ISSUE THREAD

**Issue by goneri** [vmware/pyvmomi#893]
Hi @pgbidkar,

Since v7.0 `vim.host.Capability` does not expose the following attributes anymore:
- `checkpointFtSupported`
- `checkpointFtCompatibilityIssues`

Is this done on purpose?

**Comment by prziborowski** [comment]
Those features should not have been present before.
You should refer to `smpFtSupported` and `smpFtCompatibilityIssues` attributes.
