### ISSUE TITLE
How to disable vApp option ?

### ISSUE THREAD

**Issue by Muadiv** [vmware/pyvmomi#894]
Hi everyone, I'm deploying ASAv images on ESXi, and till there everything good, I'm able to do it (using the info in the example [deploy_ovf.py](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/deploy_ovf.py)).
But then, I notice that the image was not starting correctly, showing the next error: 

> OVF does not contain a ControllerType property. Please check your deployment source files.

Looking how to fix it I found that need to have the **"vApp option"** disabled. (here the [link](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjy5qHYkPfoAhVGjqQKHT0ABd0QFjAAegQIAhAB&url=https%3A%2F%2Fwww.cisco.com%2Fc%2Fen%2Fus%2Fsupport%2Fdocs%2Fsecurity%2Fadaptive-security-virtual-appliance-asav%2F211268-ASAv-Installation-Failure-on-vMware-ESXi.pdf&usg=AOvVaw2SYRBHpvunl5mD7xKXWOTA))  , and yes, after to this, is working, but I need to do deploy the image without that option need to be changed manually. 

Also I found [this ](https://communities.vmware.com/thread/333122) using powercli, but is not the kind of solution that I'm looking for. 

How I can disable it ? In the OVF ? or in the options when I'm deploying the image? 
Anybody knows? Thanks in advance ! :)

**Comment by Rakshith2294** [comment]
vsphereObj=Vsphere(vsphere_host, vsphere_username, vsphere_password, port=443, connect=True)
        vsphereObj.connect()
        vm_object = vsphere_object.find_vm(vm_name)
        disable_spec = vim.vm.ConfigSpec()
        disable_spec.vAppConfigRemoved = True
        vm_object.ReconfigVM_Task(disable_spec)
