### ISSUE TITLE
How to extract the "Certificate Valid To" field for esxi hosts 

### ISSUE THREAD

**Issue by CloudDevOpsItaly** [vmware/pyvmomi#899]
Hi everybody!
I'm new to this forum. 
I manage a cloud infrastructure with a large number of hosts and I need to extract the data appearing in  "the Certificate Valid To" GUI's field.
I browse the pyvmomi hosts' content structure and I found only "host".config.certificate branch, but here, there isn't the expiration date but probably the all certificate file divided in 2 numbers variables.
At the moment as a workaround I'm using the openssl module to ask directly to each host the certificate expiration date, but, as you can immagine, it's slow and I'd prefer to use pyvmomi.
Please, can somebody suggest me the best way to extract this information?
Thank you in advance!
Cheers!

**Comment by sky-joker** [comment]
Hi @CloudDevOpsItaly 

I think You use the following code can get a certificate expiration period from the ESXi host.
When the following code to execute, please use python3.

```python
#!/usr/bin/env python
from pyVim.connect import SmartConnect, Disconnect
from pyVmomi import vim, vmodl
import ssl
import atexit
from cryptography import x509
from cryptography.hazmat.backends import default_backend

host = 'change me to vCenter host name or ipaddress'
username = 'administrator@vsphere.local'
password = 'change me to username password'
esxi_hostname = 'change me to target esxi hostname'
mob = vim.HostSystem

if __name__ == "__main__":
    context = None
    if hasattr(ssl, '_create_unverified_context'):
        context = ssl._create_unverified_context()

    si = SmartConnect(host=host,
                      user=username,
                      pwd=password,
                      sslContext=context)

    atexit.register(Disconnect, si)

    content = si.content

    mob_list = content.viewManager.CreateContainerView(content.rootFolder,
                                                       [mob],
                                                       True)

    for mob in mob_list.view:
        if mob.name == esxi_hostname:
            pem = ''
            for byte in mob.config.certificate:
                pem = pem + chr(byte)
            cert = x509.load_pem_x509_certificate(pem.encode(), default_backend())
            print('Valid from ' + str(cert.not_valid_before) + ' to ' + str(cert.not_valid_after))
```

e.g.

```
# ./example.py
Valid from 2018-09-28 17:56:49 to 2023-09-28 17:56:49
```

**Comment by CloudDevOpsItaly** [comment]
Hi @sky-joker!
Thank you so much for your answer!
I tried your solution and it work as expected, the only problem is that looping on the 1024 elements' array to reconstruct PEM then decode it and extract the expiring date is really long and quadrupled my inventory scanning procedure execution time (from about 10 minutes to 40 minutes).
While using the openssl module to retrieve this information just added a couple of minutes to the total. 
I was hoping there was a place where this information was directly stored (as it appears on the GUI) but it seems is not like that.
Anyway you solution is valid an it work even if in a specific moment the host is not reachable via ssh.
Cheers!

**Comment by sky-joker** [comment]
Thank you @CloudDevOpsItaly for your reply.

> I tried your solution and it work as expected, the only problem is that looping on the 1024 elements' array to reconstruct PEM then decode it and extract the expiring date is really long and quadrupled my inventory scanning procedure execution time (from about 10 minutes to 40 minutes).

I see.  
So how about the following code?

```python
#!/usr/bin/env python
from pyVim.connect import SmartConnect, Disconnect
from pyVmomi import vim, vmodl
import ssl
import atexit

host = 'change me to vCenter host name or ipaddress'
username = 'administrator@vsphere.local'
password = 'change me to username password'
esxi_hostname = 'change me to target esxi hostname'
mob = vim.HostSystem

if __name__ == "__main__":
    context = None
    if hasattr(ssl, '_create_unverified_context'):
        context = ssl._create_unverified_context()

    si = SmartConnect(host=host,
                      user=username,
                      pwd=password,
                      sslContext=context)

    atexit.register(Disconnect, si)

    content = si.content

    mob_list = content.viewManager.CreateContainerView(content.rootFolder,
                                                       [mob],
                                                       True)

    for mob in mob_list.view:
        if mob.name == esxi_hostname:
            cert_info = mob.configManager.certificateManager.certificateInfo
            print('Valid from ' + str(cert_info.notBefore) + ' to ' + str(cert_info.notAfter))
```
