### ISSUE TITLE
Warning in py3 due to misuse of "is"

### ISSUE THREAD

**Issue by sinmaker** [vmware/pyvmomi#908]
The following warning is shown when trying to get pyvmomi version

.../eggs/pyvmomi-7.0-py3.8.egg/pyVmomi/Version.py:26: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if isLegacy or ns is "":

I have a fix for that but cannot push it due to CLA:
https://github.com/vmware/pyvmomi/pull/904

**Comment by DanielDraganov** [comment]
Fixed in https://github.com/vmware/pyvmomi/commit/7802b64a5efca695001fe55fb77e7cc849476885
