### ISSUE TITLE
Please include vSAN Management SDK for Python

### ISSUE THREAD

**Issue by mariolenz** [vmware/pyvmomi#909]
Please integrate the vSAN Management SDK in pyVmomi.

At the moment, doing advanced VSAN stuff with Python [is far from user-friendly](https://storagehub.vmware.com/t/vsan-api-cookbook-for-python/virtual-san-sdks/)... or, to put it less diplomatically: It's a pain in the ass.

**Comment by Absolutelight** [comment]
Do we have progress??

**Comment by mariolenz** [comment]
Any news on this?

**Comment by gone-for-coding** [comment]
Looks like it is finally there: https://github.com/vmware/pyvmomi/commit/29104169c65d8ce455a7d384a8a741801ea0c458 and already released: https://github.com/vmware/pyvmomi/releases/tag/v8.0.3.0.1

**Comment by mariolenz** [comment]
> Looks like it is finally there: [2910416](https://github.com/vmware/pyvmomi/commit/29104169c65d8ce455a7d384a8a741801ea0c458) and already released: https://github.com/vmware/pyvmomi/releases/tag/v8.0.3.0.1

Not to put too fine a point at this, but if it's really fixed it would be great if the ~VMware~ Broadcom people would close this issue as "fixed" :stuck_out_tongue_winking_eye: 

I think they could really improve their communication here on GitHub.

**Comment by mtsvetanov** [comment]
Fixed with[ 8.0 U3 release](https://github.com/vmware/pyvmomi/releases/tag/v8.0.3.0.0). 

Please use the following maintenance release -[ Maintenance Patch 1 for 8.0 U3](https://github.com/vmware/pyvmomi/releases/tag/v8.0.3.0.1).

Enjoy!
