### ISSUE TITLE
Retrieving files from datastore

### ISSUE THREAD

**Issue by sh1dow3r** [vmware/pyvmomi#913]
Using pyvmomi library, if the server has been snapshotted is it possible to retrieve files from datastore such as ".vmem" and "vmsn". 
In the script sample 'export_vm' I was able to retrive only 3 files, 'vmdk', 'iso' and 'nvram'
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/export_vm.py

**Comment by prziborowski** [comment]
The intention of the ExportVm API is for making an OVF. Typically an OVF package does not contain files that would not be portable for deploying as multiple instances.
You can download those files directly using an HTTP GET request.

I don't have a direct example reference, but in the opposite direction (upload/PUT request), William Lam has an article: https://www.virtuallyghetto.com/2014/06/how-to-efficiently-transfer-files-to-datastore-in-vcenter-using-the-vsphere-api.html and a perl script: https://github.com/lamw/vghetto-scripts/blob/master/perl/efficent-upload-files-to-datastore.pl

The concept would be quite similar. Use the pyVmomi APIs to request a generic ticket for the url (which you have to generate).
Use the ticket to connect directly to the host to download (faster than having it proxy via vCenter).

Let me know if you need more help / code snippets.

**Comment by sh1dow3r** [comment]
Thank you for your prompt response...

My implementation requires to be written in python and I'm not sure how would go about requesting a generic ticket using pyVmomi as most of what I found were written in Perl. 
If you have an article or code snippet I can start with, I would greatly appreciate it.

**Comment by prziborowski** [comment]
The resulting example is a bit larger than I want to post here, so I put it in a gist: [downloadfile.py](https://gist.github.com/prziborowski/8bbb9233b58246fd4abfc6f936da160c)
Some of the documentation I had to refer to is [SessionManager](https://code.vmware.com/apis/358/vsphere/doc/vim.SessionManager.html)#[acquireGenericServiceTicket](https://code.vmware.com/apis/358/vsphere/doc/vim.SessionManager.html#acquireGenericServiceTicket), the spec for its parameter [HttpServiceRequestSpec](https://code.vmware.com/apis/358/vsphere/doc/vim.SessionManager.HttpServiceRequestSpec.html), the result [SessionManagerGenericServiceTicket](https://code.vmware.com/apis/358/vsphere/doc/vim.SessionManager.GenericServiceTicket.html)

And the VM's [FileLayoutEx](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.FileLayoutEx.html) and [FileInfo](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.FileLayoutEx.FileInfo.html).

Other than that, it was just looking up how to use python modules (re.match, urlopen, Request).

Let me know if that helps.

**Comment by sh1dow3r** [comment]
That's all I needed. 
Thank you very much.
