### ISSUE TITLE
question: dose pyvmomi support to set advance options for das.includeFTcomplianceChecks

### ISSUE THREAD

**Issue by yixuan178** [vmware/pyvmomi#914]
hello all,
I want to set one option under vphsere HA -> advance options -> das.includeFTcomplianceChecks to false. 
But not sure whether it can be set through pyvmomi. 
if not, any suggestion to set it through other API? 
Thanks,
Eugene

**Comment by prziborowski** [comment]
Assuming you have a reference to your [cluster](https://code.vmware.com/apis/358/vsphere/doc/vim.ClusterComputeResource.html) object, you should be able to call [ReconfigureEx](https://code.vmware.com/apis/358/vsphere/doc/vim.ComputeResource.html#reconfigureEx) and pass a [spec](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vim.cluster.ConfigSpecEx.html) of the changes you want to make.
As you mention it is under advance options, I think you would change the option field and add that entry.

E.g.
```
from pyVim.task import WaitForTask
cls # this is your cluster object, lots of examples in https://github.com/vmware/pyvmomi-community-samples/tree/master/samples have a get_obj function where you can get the object by name
spec = vim.cluster.ConfigSpecEx()
spec.option = [vim.option.OptionValue(key='das.includeFTcomplianceChecks', value='false')]
task = cls.ReconfigureEx(spec=spec, modify=True)
WaitForTask(task)
```
