### ISSUE TITLE
Need SHA256 thumbprint verification support while connecting to vCenter.

### ISSUE THREAD

**Issue by nagavenkateshg** [vmware/pyvmomi#920]
**Feature Request.**
As of now, pyvmomi supports only SHA1 thumbprint verification while connecting to the vCenter along with username, password and certs. 
We would like to request the support for SHA256 thumbprint verification as well.

**Comment by DanielDraganov** [comment]
SHA256 and SHA512 thumbprint verification supported is added in https://github.com/vmware/pyvmomi/commit/a90023fedfeda48cb1824200dc4530084215f99e
