### ISSUE TITLE
should pywin32 be listed in requirements.txt as dependency?

### ISSUE THREAD

**Issue by suliuzh** [vmware/pyvmomi#932]
Hi
I am wondering if pywin32 should be listed in setup.py or requirements,txt?
As we can see, pywin32 is used in source codes as a must. But when I use "pip install pyvmomi", it seems that pywin32 will not be installed automatically. So should pywin32 be listed as dependency when the system is windows?
![image](https://user-images.githubusercontent.com/27858725/98790758-1e033b80-243f-11eb-854a-b9741926398d.png)

Solution
add pywin32;sys_platform == 'win32'  to requirements.txt

**Comment by Appsalar** [comment]
Yes, you are right. 
I have added pywin32 as an extra requirement for the sso module in 71e9b524d18037611fb093ee97e7d536b3e76579
