### ISSUE TITLE
run get_vm_names.py error

### ISSUE THREAD

**Issue by katafiy** [vmware/pyvmomi#945]
Hello, I got an error when I ran get_vm_names.py. I don't know where to type HOST and User

![image](https://user-images.githubusercontent.com/46115351/111323228-a2dbbb80-86a4-11eb-950f-f77532518a95.png)

**Comment by parvathic** [comment]
They're command-line arguments in this case. so the command would be: python2.7 get_vm_names.py -s "host_name" -u "username" -p "password"
