### ISSUE TITLE
How to get list VMs From 2 Datacenter

### ISSUE THREAD

**Issue by pipemsn1** [vmware/pyvmomi#949]
Hello , I've two datacenter , but i use pyvmomi it can get list VMs only one datacenter.
How to get list VMs from two datacenter , Thank you.

I already checked it's shown only one datacenter by this code:
https://gist.github.com/hartsock/513a27e0694e151fcea0

***vSphere Client version 6.5***

**Comment by prziborowski** [comment]
Something like https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/getallvms.py or https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/vminfo_quick.py isn't specific to the datacenter.
If you create a container view of VMs and start at the rootFolder, then it should include all datacenters.

If you need to narrow it down to just 2 datacenters, then you could either do 2 container views on each datacenter, or possibly something else fancy with property collectors (doesn't come to mind at the moment though).

**Comment by pipemsn1** [comment]
OK, I get it now / That’s clear, thank you.
