### ISSUE TITLE
How to show datastores in 1 VM

### ISSUE THREAD

**Issue by pipemsn** [vmware/pyvmomi#952]
How to show datastores in 1 VM , I can get datastores name only 1 but my VM have 2 datastore
I using vSphere Client version 6.7

Here this my code
`from pyVim.connect import SmartConnect
from pyVmomi import vim
import ssl
import time
import datetime
import pymongo

s = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
s.verify_mode = ssl.CERT_NONE
si = SmartConnect(host="xxxx", user="xxxx", pwd="xxxx", sslContext=s)
content = si.content
content_dc = si.RetrieveContent()

def get_all_objs(content, vimtype):
    obj = {}
    container = content.viewManager.CreateContainerView(content.rootFolder, vimtype, True)
    for managed_object_ref in container.view:
        obj.update({managed_object_ref: managed_object_ref.name})
    return obj
    

getAllVms = get_all_objs(content, [vim.VirtualMachine])
for vm in getAllVms:
    if(vm.config.template==False):
        vmdatastore = vm.datastore[0]
        ds = vmdatastore.name
        data = {"Datastore":ds}
        print(ds)
    
    else:
        print('no data')
#`

**Comment by m26126** [comment]
vm.datastore will give you the list  of datastore object .
