### ISSUE TITLE
The session is not authenticated after sleeping 30mins

### ISSUE THREAD

**Issue by 556u5ut** [vmware/pyvmomi#953]
from pyVim import connect
import time

def creat_si():
    service_instance = connect.SmartConnectNoSSL(
        host="xx.xx.xx.xx",
        user="xxx",
        pwd="xxx",
        connectionPoolTimeout=-1
    )
    si_content = service_instance.RetrieveContent()
    return service_instance, si_content

if __name__ == "__main__":
    si, content = creat_si()
    time_sleep = 1500
    increment = 300
    while True:
        try:
            print(si.CurrentTime())
        except Exception as ex:
            print(ex)
            connect.Disconnect(si)
            si, content = creat_si()
            print(si.CurrentTime())
            time_sleep = 1500

        print("sleep: {} seconds".format(time_sleep))
        time.sleep(time_sleep)
        time_sleep += increment

My python code is above. I get output below.

![image](https://user-images.githubusercontent.com/23205874/116638468-fb3af400-a998-11eb-8be4-9f31d3c4e07f.png)

Why every 30mins I get Exception (The session is not authenticated), but every 25mins not. The param connectionPoolTimeout = -1 doesn't work? 
![image](https://user-images.githubusercontent.com/23205874/116638650-5bca3100-a999-11eb-80c3-468de47e58b5.png)
It doesn't work. But the source code says it works? what's the matter?

**Comment by 556u5ut** [comment]
![image](https://user-images.githubusercontent.com/23205874/116638886-dc892d00-a999-11eb-8eb7-57a306996540.png)

**Comment by karaatanassov** [comment]
The default session expiration due to inactivity for the vCenter SOAP API is 30 minutes.
