### ISSUE TITLE
Add host to vcenter without cluster

### ISSUE THREAD

**Issue by Sc0th** [vmware/pyvmomi#955]
Apologies if I am missing something obvious but there appears to be no way for a host to join a vcenter without a cluster. I can only find cluster.Addhost is there an option to do something like datacenter.Addhost ?

**Comment by prziborowski** [comment]
There is a vim.Folder.[AddStandaloneHost](https://code.vmware.com/apis/358/vsphere/doc/vim.Folder.html#addStandaloneHost).
datacenter.hostFolder is where you can run that method.
