### ISSUE TITLE
How to get stdout and stderr or log when I created a VM.

### ISSUE THREAD

**Issue by billsteve** [vmware/pyvmomi#958]
Hot to get installing VM's stdout and stderr or log when I created a VM with pyvmomi.
I want to check if the VM install successfully and get the error when it's failed.

``` 
from pyVim.connect import Disconnect, SmartConnectNoSSL
from pyVmomi import vim, vmodl

vw.create_vm('vm_name', mac_address=mac_address, mem=2024, cpu=1, guest_id="rhel6_64Guest", version="vmx-11",
         ip="10.1.110.188")
vm = get_obj(vw.content, [vim.VirtualMachine], 'vm_name')
power(vm, "on")  # power on

# How to do??
stdout = "" 
stderr = ""
install_log = ""
````

**Comment by billsteve** [comment]
https://stackoverflow.com/questions/68066070/how-to-get-install-log-by-pyvmomi

**Comment by billsteve** [comment]
@DanielDraganov Could you help me?

**Comment by DanielDraganov** [comment]
You should use propertyCollector to get the tasks's status.
For convenience, there is a WaitForTask() method in pyVim/task.py
Ref: https://gitlab.eng.vmware.com/api-platform/pyvmomi-community-samples/-/blob/master/samples/create_vm.py
