### ISSUE TITLE
pyvmomi-6.5 with vcenter 7.0 - NIC creation - externalId not being set

### ISSUE THREAD

**Issue by niprabhu** [vmware/pyvmomi#960]
Hey folks, I'm trying to add a new nic to an existing vm, and trying to use the externalId field to set up a custom identifier to identify the nic. This worked when I tried with vcenter/vsphere 6.5 and 6.7, but with vcenter 7.0, it looks like the externalId is unset (snippet below). Has anyone seen this issue before? Is there a workaround?

   ```
resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      reservation = 0L,
      share = (vim.SharesInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         shares = 50,
         level = 'normal'
      },
      limit = -1L
   },
   externalId = <unset>,
   uptCompatibilityEnabled = true
```

**Comment by prziborowski** [comment]
That snippet is what you receive back when you are querying the nic, or that is something in the vpxd logs based on the reconfigure request?
I'm trying to determine if vcenter is ignoring your request, or the externalId field of the request is getting filtered out.

If it is the former, you could maybe increasing logging levels in vCenter and make a similar reconfigure in the UI and see what the ConfigSpec looks like in the vpxd log and how it differs from what you tried with pyvmomi.

If it is the latter, that would be more likely some version mismatch between vcenter and pyvmomi.

**Comment by niprabhu** [comment]
@prziborowski the snippet I shared is the response I received when querying the nic. The nic was created successfully -- it's just the externalId that was ignored. I will increase the logging levels and try it out through the UI like you suggested. Will post an update shortly.
