### ISSUE TITLE
Can this project worked without vCenter?

### ISSUE THREAD

**Issue by lazylazyboy** [vmware/pyvmomi#961]
Hi,

My vSphere only have ESXi and doesn't have vCenter, can I use this project to manage my ESXi? 
I ask it because I found vSphere automation API needs vCenter.
Hopes for your reply.
Thanks in advance.

**Comment by pgbidkar** [comment]
Yes! pyVmomi can be used to manage ESX.
Doc also says same "pyVmomi is the Python SDK for the VMware vSphere API that allows you to manage ESX, ESXi, and vCenter."

But, all APIs might not be compatible with ESXi. 
Thanks

**Comment by lazylazyboy** [comment]
Thanks a lot
