### ISSUE TITLE
Getting sharing attribute of VirtualDiskFlatVer2BackingInfo

### ISSUE THREAD

**Issue by jsbtgh** [vmware/pyvmomi#965]
I am trying to get details about the multi-writer flag and I am new to this library. 

As I understand it, I have to get the sharing attribute of the Data Object **VirtualDiskFlatVer2BackingInfo** which is **vim.vm.device.VirtualDisk.FlatVer2BackingInfo**

I know that can get the backingInfo of a virtual disk by iterating over the virtual devices of a VM.

If I iterate through my devices using _for device in vm.config.hardware.device_, does anyone know how I get the information (assuming I use **device.backing**)

**Comment by prziborowski** [comment]
```
for device in vm.config.hardware.device:
    if not isinstance(device, vim.vm.device.VirtualDevice):
        continue
    if not isinstance(device.backing, vim.vm.device.VirtualDisk.FlatVer2BackingInfo):
        continue
    if device.backing.sharing == vim.vm.device.VirtualDisk.Sharing.sharingMultiWriter:
        print("{} is set to multi-writer".format(device.backing.fileName))
```
