### ISSUE TITLE
Cross Vmotion for Host and Storage from One vcenter to another

### ISSUE THREAD

**Issue by sidrockzz** [vmware/pyvmomi#968]
I am trying to make a vmotion for host and storage of a VM from one vcenter to another vcenter. May I know how do I proceed with the Vmotion using Pyvmomi? Any clues, code would also suffice.

**Comment by prziborowski** [comment]
You will use the same [Relocate](https://code.vmware.com/apis/358/vsphere/doc/vim.VirtualMachine.html#relocate) method that is used for a single VC.
The [vim.vm.RelocateSpec](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.RelocateSpec.html) you provide as input needs to contain the [service](https://code.vmware.com/apis/358/vsphere/doc/vim.ServiceLocator.html) property filled out. This is details about the other VC. `credential` can be either user/password or a SAML token. `instanceUuid` you can gather from connecting to the other VC and it is in the ServiceInstanceContent (si.content)'s about.instanceUuid. `url` is the `https://{hostname}/sdk` for the other VC.
`sslThumbprint` is the thumbprint of the other VC's cert. Also if you have a connection to that VC, you can get the peer cert from https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.getpeercert kind of method. Like: https://github.com/vmware/pyvmomi/blob/master/pyVim/sso.py#L146

You will have to also provide inputs for other RelocateSpec inputs as the VM will be changing everything (folder, host, datastore, pool).

**Comment by sidrockzz** [comment]
Cool Thanks mate @prziborowski. It is done :)
