### ISSUE TITLE
whatever appears to be in pypi since 7.0.2 does not install on python2.7 / centos7 based box

### ISSUE THREAD

**Issue by marcfiu** [vmware/pyvmomi#972]
Starting with 7.0.2, doing python2 based install on CentOS 7 gets the following error:

`error in pyvmomi setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`

Oddly, it works fine when checking out the code from the pyvmomi git repo and manually building the wheel from the 7.0.2 (and 7.0.3) codebase.  Specifically, I built it using: `python2 setup.py bdist_wheel` and then pip installed the resulting whl. This works like a charm.

But whatever appears to be in pypi since 7.0.2 does not install, as shown below:
```
$ pip2 install pyvmomi==7.0.2
Collecting pyvmomi==7.0.2
  Downloading pyvmomi-7.0.2.tar.gz (589 kB)
     |████████████████████████████████| 589 kB 6.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dh1xVt/pyvmomi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dh1xVt/pyvmomi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-Zq5tUp
         cwd: /tmp/pip-install-dh1xVt/pyvmomi/
    Complete output (3 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in pyvmomi setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by optonc** [comment]
i got the same problem。have you find a solution？

**Comment by marcfiu** [comment]
Had to build it from the git repo.

git clone https://github.com/vmware/pyvmomi.git
cd pyvmomi
git checkout v7.0.3
python2 setup.py bdist_wheel

and then install the resulting .whl file using pip2.

Of course, it would be nice if the pip2 repo was updated to a working setup.

**Comment by DanielDraganov** [comment]
As of Dec 15, 2022 Python 2.7 is no longer supported. Ref. https://github.com/vmware/pyvmomi/commit/6234051f13627f006edeae753b42e729a3a3f657
This issue is outdated and therefore is closed.
