### ISSUE TITLE
Can't import stabeVersions from pyVmomi.VmomiSupport

### ISSUE THREAD

**Issue by mian4work** [vmware/pyvmomi#973]
We had a new release which uses pyVmomi on Nov. 4, 2021. Then our code stopped working with the following errors:

`
python vsanmgmtObjects.py 
Traceback (most recent call last):
  File "vsanmgmtObjects.py", line 1, in <module>
    from pyVmomi.VmomiSupport import CreateDataType, CreateManagedType, CreateEnumType, AddVersion, AddVersionParent, F_LINK, F_LINKABLE, F_OPTIONAL, F_SECRET, newestVersions, stableVersions, publicVersions
ImportError: cannot import name 'stableVersions' from 'pyVmomi.VmomiSupport' (/usr/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py)
`

The import has been there for long time. Not sure why it started throwing exceptions now.

**Comment by mian4work** [comment]
The stableVersions alias has been removed.

**Comment by dipanshu231099** [comment]
@mian4work can you suggest the alrernative as well, in case this alias is now removed
