### ISSUE TITLE
Not able to build python egg with python2.7

### ISSUE THREAD

**Issue by gdpak-xi** [vmware/pyvmomi#977]
### Describe the bug

When I try to build with python 2.7, I get following error
error in pyvmomi setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
I needed to remove following option from setup.py to build it with python 2.7

```
diff --git a/setup.py b/setup.py
index 6265ae2..fe50726 100644
--- a/setup.py
+++ b/setup.py
@@ -68,12 +68,5 @@ setup(
     python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*',
     test_suite='tests',
     tests_require=required_for_tests,
-    extras_require={
-        'sso': [
-            'pyOpenSSL',
-            'lxml',
-            'pywin32; sys_platform == "win32"'
-        ]
-    },
     zip_safe=True
 )

```

### Reproduction steps

```bash
1. python2.7 setup.py build
```

### Expected behavior

It should build with python2.7 as it say supported version.

**Comment by DanielDraganov** [comment]
As of Dec 15, 2022 Python 2.7 is no longer supported. Ref. https://github.com/vmware/pyvmomi/commit/6234051f13627f006edeae753b42e729a3a3f657
This issue is outdated and therefore is closed.
