### ISSUE TITLE
Can't install on latest Ubuntu 20.04 or 22.04

### ISSUE THREAD

**Issue by denlun** [vmware/pyvmomi#983]
### Describe the bug

Tried fresh install of both Ubuntu 20.04 and 22.04.
Running python 3.8.10 out of the box.
Running pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
Ran sudo pip3 install pytest... it works.

:~$ sudo pip3 install pyvomi
ERROR: Could not find a version that satisfies the requirement pyvomi (from versions: none)
ERROR: No matching distribution found for pyvomi

Any ideas anyone?

### Reproduction steps

```bash
1. Do fresh install of Ubuntu Server
2. sudo apt update
3. sudo apt upgrade
4. sudo apt install python3-pip
5. sudo pip3 install pyvomi
```

### Expected behavior

pip shoud have installed pyvomi.

**Comment by prziborowski** [comment]
I think you have a typo. It should be under `pyvmomi` and not `pyvomi`.

**Comment by denlun** [comment]
🤦
