### ISSUE TITLE
pyVim.sso is using base64.encodestring method, causing attribute error in python 3.10

### ISSUE THREAD

**Issue by 2ez4szliu** [vmware/pyvmomi#985]
### Describe the bug

base64.encodestring method is removed since python 3.9, however in [pyVim.sso._load_private_key](https://github.com/vmware/pyvmomi/blob/master/pyVim/sso.py#L953) it's still using encodestring method, if running with python 3.10 it will cause attribute error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pyVim/sso.py", line 953, in _load_private_key
    base64.encodestring(der_key).decode(UTF_8) +
AttributeError: module 'base64' has no attribute 'encodestring'

### Reproduction steps

```bash
1. Set an environment with python 3.10
2. pip install pyvmomi
3. from pyVim import sso
4. try to call the sso._load_private_key function
5. Get attribute error module 'base64' has no attribute 'encodestring'
```

### Expected behavior

The attribute error should not happen.

### Additional context

Maybe we can replace the encodestring function with encodebytes

**Comment by DanielDraganov** [comment]
Fixed in https://github.com/vmware/pyvmomi/commit/a90023fedfeda48cb1824200dc4530084215f99e
