### ISSUE TITLE
Attachment of shared SCSI disk failed

### ISSUE THREAD

**Issue by Christop1964** [vmware/pyvmomi#988]
### Describe the bug

We are maintain VMware using pyVmomi to creating VM's.
That means cloning vm, attaching disks, setup network, and so on. 

But we are fighting with attaching of shared disks (multi-writer disks) to multiple VM's using pyVmomi.
May someone have an idea or example, how we can attach shared disks !
So far we have added a SCSI controller to an existing VM using pyVmomi. The controller has the "bus sharing = virtual" set. 
The disk that should be added to the SCSI controller is created before attaching (see code below) but the task failed with
the following message. 

msg = "Incompatible device backing specified for device '0'.",

Does anyone has an idea how we can add multi-writer disks ?

Here some lines of code about the disk attachment :

```
    disk_spec = vim.vm.device.VirtualDeviceSpec()
    disk_spec.fileOperation = "create"
    disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add

    disk_spec.device = vim.vm.device.VirtualDisk()
    disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()
    disk_spec.device.backing.diskMode = "persistent"
    disk_spec.device.backing.thinProvisioned = False
    disk_spec.device.backing.sharing = "sharingMultiWriter"
    disk_spec.device.capacityInKB = disk_capacity
    disk_spec.device.controllerKey = controller.key
    disk_spec.device.unitNumber = unit_number

    disk_device = []
    disk_device.append(disk_spec)

    vm_spec = vim.vm.ConfigSpec()
    vm_spec.deviceChange = disk_device
    task = vm_obj.ReconfigVM_Task (spec=vm_spec )
    WaitForTask(task, si)

```

When we creating the shared disk via the vCenter with the parameter "Disk Type = Thick Provision Eager Zeroed", the attachment to  the VM works.  The disc is visible at the  VM.

Our problem is , how do we can attach shared disk to VM's using pyVmomi. 

### Reproduction steps

1. Add a SCSI controller to a VM that has the parameter / option set to sharedBus = 'virtualSharing' (with pyVmomi)
    If you add the SCSI controller to the VM via the vCenter, you need to set the parameter "SCSI Bus Sharing to virtual".
2. Create the disk that should be attached to the SCSI controller. To attach shared disc you need to set some backing information:

        disk_spec.device.backing.diskMode = "persistent"
        disk_spec.device.backing.thinProvisioned = False
        disk_spec.device.backing.sharing = "sharingMultiWriter"

3.
4.
...

### Expected behavior

Our expectation is, that the shared disk get attached to the VM using pyVmomi. 

### Additional context

We get the following error message, when running the above code !

```
pyVmomi.VmomiSupport.InvalidDeviceBacking: (vim.fault.InvalidDeviceBacking) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = "Incompatible device backing specified for device '0'.",
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   property = 'backing.sharing',
   deviceIndex = 0
}
```

**Comment by jimkleine** [comment]
@Christop1964 I believe this may be a typo in your configuration, specifically an excess period here:

From: `disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()`
To: `disk_spec.device.backing = vim.vm.device.VirtualDiskFlatVer2BackingInfo()`

[Per vmware docs](https://vdc-download.vmware.com/vmwb-repository/dcr-public/98d63b35-d822-47fe-a87a-ddefd469df06/2e3c7b58-f2bd-486e-8bb1-a75eb0640bee/doc/vim.vm.device.VirtualDisk.FlatVer2BackingInfo.html)

**Comment by Christop1964** [comment]
Hi Jim, 
thanks for your resaponce but this is no typo. 
We got the problem solved to attach shared disk to different vm's. 
We hat to add just one more line to the code 

        `disk_spec.device.backing.eagerlyScrub = True`

The complete code to attach shared disks to other VM's looks like the follow.

```
        # Create disk specification
        disk_spec = vim.vm.device.VirtualDeviceSpec()
        disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add

        disk_spec.device = vim.vm.device.VirtualDisk()
        disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()
        disk_spec.device.backing.diskMode = "persistent"
        disk_spec.device.backing.thinProvisioned = False
        disk_spec.device.backing.eagerlyScrub = True
        disk_spec.device.backing.sharing = "sharingMultiWriter"
        disk_spec.device.backing.fileName = filename
        disk_spec.device.controllerKey = controller_obj.key
        disk_spec.device.unitNumber = unit_number

        disk_device = []
        disk_device.append(disk_spec)

        vm_spec = vim.vm.ConfigSpec()
        vm_spec.deviceChange = disk_device

        task = vm_obj.ReconfigVM_Task(spec=vm_spec)
        WaitForTask(task, si)

```

**Comment by Christop1964** [comment]
The problem is fixed. 
See solution above !
