### ISSUE TITLE
WaitForTask broken on version >8.0.0

### ISSUE THREAD

**Issue by wouterdb** [vmware/pyvmomi#993]
### Describe the bug

When executing a (previously working) power down, the following happens 

```
12:44:57      WaitForTask(managed_object.PowerOffVM_Task())
12:44:57    File "/home/jenkins/workspace/modules_vcenter_issue_pyvmomi-8/env/lib64/python3.9/site-packages/pyVim/task.py", line 126, in WaitForTask
12:44:57      filter = CreateFilter(pc, task)
12:44:57    File "/home/jenkins/workspace/modules_vcenter_issue_pyvmomi-8/env/lib64/python3.9/site-packages/pyVim/task.py", line 266, in CreateFilter
12:44:57      return CreateTasksFilter(pc, [task])
12:44:57    File "/home/jenkins/workspace/modules_vcenter_issue_pyvmomi-8/env/lib64/python3.9/site-packages/pyVim/task.py", line 275, in CreateTasksFilter
12:44:57      objspecs = [
12:44:57    File "/home/jenkins/workspace/modules_vcenter_issue_pyvmomi-8/env/lib64/python3.9/site-packages/pyVim/task.py", line 276, in <listcomp>
12:44:57      vmodl.Query.PropertyCollector.ObjectSpec(obj=task) for task in tasks
12:44:57    File "/home/jenkins/workspace/modules_vcenter_issue_pyvmomi-8/env/lib64/python3.9/site-packages/pyVmomi/VmomiSupport.py", line 249, in __getattr__
12:44:57      raise AttributeError(attr)
12:44:57  AttributeError: Query
``` 

### Reproduction steps

Create a VM and try to power it off, by using 

`WaitForTask(managed_object.PowerOffVM_Task())`

### Expected behavior

This doesn't fail.

**Comment by hmn** [comment]
I have the same errors in my WaitForTask calls

**Comment by david-leroux** [comment]
I am experiencing the same issue.
`Name: pyvmomi
Version: 8.0.0.1
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.
Author-email: jhu@vmware.com
License: License :: OSI Approved :: Apache Software License
Location: /usr/local/lib/python3.9/dist-packages
Requires: six
Required-by:`

`20221128 09:42:57.529 - DEBUG - Traceback (most recent call last):
  File "/usr/local/bin/Voss4UC.py", line 295, in VM_Add_Disk
    WaitForTask(vm.ReconfigVM_Task(spec=spec))
  File "/usr/local/lib/python3.9/dist-packages/pyVim/task.py", line 126, in WaitForTask
    filter = CreateFilter(pc, task)
  File "/usr/local/lib/python3.9/dist-packages/pyVim/task.py", line 266, in CreateFilter
    return CreateTasksFilter(pc, [task])
  File "/usr/local/lib/python3.9/dist-packages/pyVim/task.py", line 275, in CreateTasksFilter
    objspecs = [
  File "/usr/local/lib/python3.9/dist-packages/pyVim/task.py", line 276, in <listcomp>
    vmodl.Query.PropertyCollector.ObjectSpec(obj=task) for task in tasks
  File "/usr/local/lib/python3.9/dist-packages/pyVmomi/VmomiSupport.py", line 249, in __getattr__
    raise AttributeError(attr)
AttributeError: Query`

I have removed the WaitForTask statement to allow the code to continue working. But I would rather have it working as before.

**Comment by wferi** [comment]
Many thanks for the quick fix! Can we expect a bugfix release coming soon?

**Comment by LyuboGit** [comment]
> Many thanks for the quick fix! Can we expect a bugfix release coming soon?
Hi wferi,
Yes, we're working on it. We should release it sometime this week (12/11/2022)

**Comment by DanielDraganov** [comment]
> Many thanks for the quick fix! Can we expect a bugfix release coming soon?

[Maintenance Patch 1 for 8.0](https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1.1) has just been released.
